function figures = plot_phase2_3_run(runFile, options)
%PLOT_PHASE2_3_RUN Plot one saved Phase 2.3 simulation run.

arguments
    runFile (1,1) string
    options.SaveFigures (1,1) logical = true
    options.ShowFigures (1,1) logical = true
end

assert(isfile(runFile), ...
    "Phase 2.3 run file does not exist: %s", runFile);

stored = load(runFile, "runArtifact");
assert(isfield(stored, "runArtifact"), ...
    "Run file does not contain runArtifact.");

artifact = stored.runArtifact;
figures = plot_phase2_3_results( ...
    artifact.results, ...
    artifact.reference, ...
    artifact.taskData, ...
    artifact.scenarioName, ...
    artifact.environmentName, ...
    artifact.loadCase);

if options.SaveFigures
    projectRoot = string(matlab.project.currentProject().RootFolder);
    figureFolder = fullfile( ...
        projectRoot, "phase2", "figures", "phase2_3", ...
        artifact.scenarioName, ...
        artifact.environmentName, ...
        artifact.loadCase);

    sdv.io.exportFigure( ...
        figures.control, figureFolder, "control_performance");
    sdv.io.exportFigure( ...
        figures.scheduler, figureFolder, "scheduler_timing");
end

if ~options.ShowFigures
    close(figures.control);
    close(figures.scheduler);
end

end
