function figureHandle = plot_phase2_4_response_histogram( ...
    scenarioName, ...
    environmentName, ...
    loadExecutionTime_ms, ...
    options)
%PLOT_PHASE2_4_RESPONSE_HISTOGRAM Plot one saved response-time distribution.

arguments
    scenarioName (1,1) string
    environmentName (1,1) string
    loadExecutionTime_ms (1,1) double {mustBeNonnegative}
    options.SaveFigure (1,1) logical = true
end

projectRoot = string(matlab.project.currentProject().RootFolder);
caseFolder = phase2_4_case_folder( ...
    projectRoot, ...
    scenarioName, ...
    environmentName, ...
    loadExecutionTime_ms);

runFile = fullfile(caseFolder, "run_data.mat");
assert(isfile(runFile), "Phase 2.4 run was not found:\n%s", runFile);

savedRun = load(runFile, "runArtifact");
runArtifact = savedRun.runArtifact;
responseTime_ms = 1e3*runArtifact.controlResponseTime_s(:);

figureHandle = figure( ...
    Name="Phase 2.4 response-time histogram", ...
    Color="white");

histogram(responseTime_ms, Normalization="probability");
hold on;
xline( ...
    1e3*runArtifact.controlTaskPeriod_s, ...
    "r--", ...
    "Control deadline", ...
    LineWidth=1.3);
hold off;

grid on;
xlabel("Control-task response time (ms)");
ylabel("Probability");
title(sprintf( ...
    "%s | %s | load %.3f ms | U %.3f", ...
    strrep(scenarioName, "_", " "), ...
    strrep(environmentName, "_", " "), ...
    loadExecutionTime_ms, ...
    runArtifact.nominalUtilization));

if options.SaveFigure
    exportgraphics( ...
        figureHandle, ...
        fullfile(caseFolder, "control_response_histogram.png"), ...
        Resolution=200);
end

end
