function [figureHandle] = ...
    plot_phase2_tool_spike( ...
        positionSignal, ...
        velocitySignal, ...
        controlSignal, ...
        timingTable, ...
        controlPeriod_s, ...
        nominalExecutionTime_s, ...
        outputFile)
%PLOT_PHASE2_TOOL_SPIKE Plot Phase 2.1 scheduler tool-spike results.

loadedFromFile = ...
    nargin == 1 && (isstring(positionSignal) || ischar(positionSignal));

if loadedFromFile
    resultsFile = string(positionSignal);
    assert(isfile(resultsFile), ...
        "Phase 2.1 result file does not exist: %s", resultsFile);

    stored = load(resultsFile, "results", "timingTable");
    assert(isfield(stored, "results") && ...
        isfield(stored, "timingTable"), ...
        "Result file must contain results and timingTable.");

    positionSignal = stored.results.position;
    velocitySignal = stored.results.velocity;
    controlSignal = stored.results.control_output;
    timingTable = stored.timingTable;
    controlPeriod_s = stored.results.control_period_s;
    nominalExecutionTime_s = ...
        stored.results.nominal_execution_time_s;

    projectRoot = string(matlab.project.currentProject().RootFolder);
    outputFile = fullfile( ...
        projectRoot, "phase2", "figures", ...
        "phase2_1_scheduler_tool_spike.png");
end

if ~loadedFromFile && (nargin < 5 || isempty(controlPeriod_s))
    controlPeriod_s = 0.01;
end

if ~loadedFromFile && ...
        (nargin < 6 || isempty(nominalExecutionTime_s))
    nominalExecutionTime_s = 0.003;
end

if ~loadedFromFile && nargin < 7
    outputFile = "";
end

assert(isa(positionSignal, "timeseries"), ...
    "positionSignal must be a timeseries.");

assert(isa(velocitySignal, "timeseries"), ...
    "velocitySignal must be a timeseries.");

assert(isa(controlSignal, "timeseries"), ...
    "controlSignal must be a timeseries.");

assert(istable(timingTable), ...
    "timingTable must be a table.");

requiredTimingVariables = [ ...
    "CompletionTime_s", ...
    "ExecutionTime_ms", ...
    "ResponseTime_ms"];

assert(all(ismember( ...
    requiredTimingVariables, ...
    string(timingTable.Properties.VariableNames))), ...
    "timingTable is missing required timing variables.");

%% Extract signals

positionTime_s = positionSignal.Time(:);
position_m = squeeze(positionSignal.Data);
position_m = position_m(:);

velocityTime_s = velocitySignal.Time(:);
velocity_mps = squeeze(velocitySignal.Data);
velocity_mps = velocity_mps(:);

controlTime_s = controlSignal.Time(:);
controlCommand = squeeze(controlSignal.Data);
controlCommand = controlCommand(:);

fprintf("\nPhase 2.1 tool-spike timing summary\n");
fprintf("Control period:          %.3f ms\n", ...
    1000*controlPeriod_s);
fprintf("Nominal execution time:  %.3f ms\n", ...
    1000*nominalExecutionTime_s);

meanResponseTime_ms = ...
    mean(timingTable.ResponseTime_ms, "omitnan");

maximumResponseTime_ms = ...
    max(timingTable.ResponseTime_ms, [], "omitnan");

%% Plot

figureHandle = figure( ...
    Name="Phase 2.1 scheduler tool spike", ...
    Color="white");

layout = tiledlayout( ...
    figureHandle, ...
    2, ...
    2, ...
    TileSpacing="compact", ...
    Padding="compact");

title(layout, ...
    "Phase 2.1 Scheduler-in-the-Loop Tool Spike");

% Position
nexttile;
stairs( ...
    positionTime_s, ...
    position_m, ...
    LineWidth=1.4);
grid on;
xlabel("Time (s)");
ylabel("Position (m)");
title("Toy-Plant Position");

% Velocity
nexttile;
stairs( ...
    velocityTime_s, ...
    velocity_mps, ...
    LineWidth=1.4);
grid on;
xlabel("Time (s)");
ylabel("Velocity (m/s)");
title("Toy-Plant Velocity");

% Control command
nexttile;
stairs( ...
    controlTime_s, ...
    controlCommand, ...
    LineWidth=1.4);
grid on;
xlabel("Time (s)");
ylabel("Control command");
title("Scheduler-Delayed and Held Control Command");

% Control-task timing
nexttile;

stem( ...
    timingTable.CompletionTime_s, ...
    timingTable.ResponseTime_ms, ...
    Marker="none", ...
    LineWidth=1.1, ...
    DisplayName="Response time");

hold on;

plot( ...
    timingTable.CompletionTime_s, ...
    timingTable.ExecutionTime_ms, ...
    "--", ...
    LineWidth=1.2, ...
    DisplayName="Execution time");

yline( ...
    1000*nominalExecutionTime_s, ...
    "--", ...
    "Nominal execution time", ...
    LineWidth=1.2, ...
    HandleVisibility="off");

yline( ...
    1000*controlPeriod_s, ...
    ":", ...
    "10 ms deadline", ...
    LineWidth=1.2, ...
    HandleVisibility="off");

hold off;
grid on;
xlabel("Task completion time (s)");
ylabel("Response time (ms)");
legend(Location="best");
title(sprintf( ...
    "Control-Task Response Time: Mean %.3f ms, Max %.3f ms", ...
    meanResponseTime_ms, ...
    maximumResponseTime_ms));

%% Save figure

if strlength(string(outputFile)) > 0

    outputFile = string(outputFile);
    outputFolder = fileparts(outputFile);

    if strlength(outputFolder) > 0 && ~isfolder(outputFolder)
        mkdir(outputFolder);
    end

    exportgraphics( ...
        figureHandle, ...
        outputFile, ...
        Resolution=300);
end
end
