function figures = plot_phase4_performance_map_errors( ...
        performanceMapTable, options)
%PLOT_PHASE4_PERFORMANCE_MAP_ERRORS Compare errors for each sampling mode.

arguments
    performanceMapTable table
    options.TimeWindow_s (1,2) double = [NaN, NaN]
    options.Visible (1,1) string ...
        {mustBeMember(options.Visible, ["on", "off"])} = "on"
    options.LineWidth (1,1) double {mustBePositive} = 1.5
end

requiredVariables = [ ...
    "Scenario"
    "Environment"
    "CandidateSampleTime_s"
    "SourceTime_s"
    "AbsLateralError_m"
    "AbsHeadingError_rad"
    "LateralRms_m"
    "HeadingRms_rad"
    ];

missingVariables = setdiff( ...
    requiredVariables, ...
    string(performanceMapTable.Properties.VariableNames));

assert(isempty(missingVariables), ...
    "Performance-map table is missing: %s", ...
    strjoin(missingVariables, ", "));

plotTable = performanceMapTable;

if all(isfinite(options.TimeWindow_s))
    assert(options.TimeWindow_s(2) > options.TimeWindow_s(1), ...
        "TimeWindow_s must be increasing.");

    plotTable = plotTable( ...
        plotTable.SourceTime_s >= options.TimeWindow_s(1) ...
        & plotTable.SourceTime_s <= options.TimeWindow_s(2), :);
elseif ~all(isnan(options.TimeWindow_s))
    error("TimeWindow_s must be [start, end] or [NaN, NaN].");
end

assert(~isempty(plotTable), ...
    "No performance-map rows are inside the selected time window.");

scenarioNames = unique(string(plotTable.Scenario));
environmentNames = unique(string(plotTable.Environment));

assert(isscalar(scenarioNames) && isscalar(environmentNames), ...
    "The input table must contain one scenario/environment pair.");

scenarioLabel = strrep(scenarioNames, "_", " ");
environmentLabel = strrep(environmentNames, "_", " ");

sampleTimes_s = sort(unique( ...
    double(plotTable.CandidateSampleTime_s(:))));

expectedSampleTimes_s = [0.010; 0.020; 0.050];
missingSampleTimes_s = setdiff( ...
    expectedSampleTimes_s, sampleTimes_s);

if ~isempty(missingSampleTimes_s)
    warning( ...
        "Phase4:MissingSamplingModes", ...
        "No map rows exist for sampling periods: %s ms.", ...
        strjoin(string(1e3*missingSampleTimes_s), ", "));
end

colors = lines(numel(sampleTimes_s));
figureTitlePrefix = ...
    scenarioLabel + " | " + environmentLabel;

figures = struct();

figures.InstantaneousErrors = createComparisonFigure( ...
    plotTable, ...
    sampleTimes_s, ...
    colors, ...
    "AbsLateralError_m", ...
    "AbsHeadingError_rad", ...
    "Absolute lateral error (m)", ...
    "Absolute heading error (rad)", ...
    "Instantaneous Lateral and Heading Errors", ...
    figureTitlePrefix, ...
    options.Visible, ...
    options.LineWidth, ...
    options.TimeWindow_s);

figures.WindowRmsErrors = createComparisonFigure( ...
    plotTable, ...
    sampleTimes_s, ...
    colors, ...
    "LateralRms_m", ...
    "HeadingRms_rad", ...
    "Future-window lateral RMS (m)", ...
    "Future-window heading RMS (rad)", ...
    "One-Second Future-Window RMS Errors", ...
    figureTitlePrefix, ...
    options.Visible, ...
    options.LineWidth, ...
    options.TimeWindow_s);

figures.WindowRmsErrors = createComparisonFigure( ...
    plotTable, ...
    sampleTimes_s, ...
    colors, ...
    "LateralPeak_m", ...
    "HeadingPeak_rad", ...
    "Lateral Peak (m)", ...
    "Heading Peak (rad)", ...
    "Lateral and Heading Peak", ...
    figureTitlePrefix, ...
    options.Visible, ...
    options.LineWidth, ...
    options.TimeWindow_s);

end


function figureHandle = createComparisonFigure( ...
        data, sampleTimes_s, colors, ...
        upperVariable, lowerVariable, ...
        upperLabel, lowerLabel, figureName, ...
        titlePrefix, visibility, lineWidth, timeWindow_s)

figureHandle = figure( ...
    Name=figureName, ...
    Color="white", ...
    Visible=visibility);

layout = tiledlayout( ...
    figureHandle, 2, 1, ...
    TileSpacing="compact", ...
    Padding="compact");

upperAxes = nexttile(layout);
hold(upperAxes, "on");
grid(upperAxes, "on");

lowerAxes = nexttile(layout);
hold(lowerAxes, "on");
grid(lowerAxes, "on");

legendHandles = gobjects(numel(sampleTimes_s), 1);
legendLabels = strings(numel(sampleTimes_s), 1);

for sampleIndex = 1:numel(sampleTimes_s)
    sampleTime_s = sampleTimes_s(sampleIndex);
    modeRows = abs( ...
        double(data.CandidateSampleTime_s) ...
        - sampleTime_s) < 1e-12;

    modeData = sortrows(data(modeRows, :), "SourceTime_s");
    time_s = double(modeData.SourceTime_s);

    legendLabels(sampleIndex) = sprintf( ...
        "%.0f ms", 1e3*sampleTime_s);

    legendHandles(sampleIndex) = plot( ...
        upperAxes, ...
        time_s, ...
        double(modeData.(upperVariable)), ...
        Color=colors(sampleIndex, :), ...
        LineWidth=lineWidth, ...
        DisplayName=legendLabels(sampleIndex));

    plot( ...
        lowerAxes, ...
        time_s, ...
        double(modeData.(lowerVariable)), ...
        Color=colors(sampleIndex, :), ...
        LineWidth=lineWidth, ...
        HandleVisibility="off");
end

ylabel(upperAxes, upperLabel);
ylabel(lowerAxes, lowerLabel);
xlabel(lowerAxes, "Source time (s)");

title(upperAxes, upperLabel);
title(lowerAxes, lowerLabel);
title(layout, titlePrefix + " | " + figureName, ...
    Interpreter="none", FontWeight="bold");

linkaxes([upperAxes, lowerAxes], "x");

if all(isfinite(timeWindow_s))
    xlim(upperAxes, timeWindow_s);
end

legendHandle = legend( ...
    upperAxes, legendHandles, legendLabels, ...
    Interpreter="none");
legendHandle.Layout.Tile = "east";

end
