function [figureHandle, costTable] = ...
    plot_phase4_candidate_cost_comparison( ...
        candidateCost, options)
%PLOT_PHASE4_CANDIDATE_COST_COMPARISON Compare costs for all controller modes.

arguments
    candidateCost (1,1) struct
    options.SelectedMode (1,1) struct = struct()
    options.TimeWindow_s (1,2) double = [NaN, NaN]
    options.Title (1,1) string = "Phase 4 Candidate-Mode Cost Comparison"
    options.Visible (1,1) string ...
        {mustBeMember(options.Visible, ["on", "off"])} = "on"
    options.LineWidth (1,1) double {mustBePositive} = 1.4
    options.SaveFile (1,1) string = ""
end

requiredFields = [ ...
    "Time_s"
    "Data"
    "CandidateSampleTimes_s"
    ];

assert(all(isfield(candidateCost, requiredFields)), ...
    "candidateCost must contain Time_s, Data and CandidateSampleTimes_s.");

time_s = double(candidateCost.Time_s(:));
costData = double(candidateCost.Data);
sampleTimes_s = double( ...
    candidateCost.CandidateSampleTimes_s(:));

assert(~isempty(time_s), "Candidate-cost data is empty.");
assert(size(costData, 1) == numel(time_s), ...
    "Candidate-cost rows must match the number of time samples.");
assert(size(costData, 2) == numel(sampleTimes_s), ...
    "Candidate-cost columns must match CandidateSampleTimes_s.");

if all(isfinite(options.TimeWindow_s))
    assert(options.TimeWindow_s(2) > options.TimeWindow_s(1), ...
        "TimeWindow_s must be increasing.");
    keepRows = time_s >= options.TimeWindow_s(1) ...
        & time_s <= options.TimeWindow_s(2);
elseif all(isnan(options.TimeWindow_s))
    keepRows = true(size(time_s));
else
    error("TimeWindow_s must be [start, end] or [NaN, NaN].");
end

time_s = time_s(keepRows);
costData = costData(keepRows, :);

assert(~isempty(time_s), ...
    "No candidate-cost samples are inside the selected time window.");

comparisonData = costData;
comparisonData(isnan(comparisonData)) = inf;

[minimumCost, minimumMode] = min(comparisonData, [], 2);
noFiniteCandidate = all(~isfinite(comparisonData), 2);
minimumCost(noFiniteCandidate) = NaN;
minimumMode = double(minimumMode);
minimumMode(noFiniteCandidate) = NaN;

activeMode = nan(size(time_s));
hasSelectedMode = all(isfield( ...
    options.SelectedMode, ["Time_s", "Data"]));

if hasSelectedMode
    modeTime_s = double(options.SelectedMode.Time_s(:));
    modeData = double(options.SelectedMode.Data(:));

    validModeRows = isfinite(modeTime_s) & isfinite(modeData);
    modeTime_s = modeTime_s(validModeRows);
    modeData = modeData(validModeRows);

    if ~isempty(modeTime_s)
        [modeTime_s, uniqueRows] = unique( ...
            modeTime_s, "last");
        modeData = modeData(uniqueRows);

        activeMode = interp1( ...
            modeTime_s, modeData, time_s, ...
            "previous", "extrap");
    end
end

modeColors = [ ...
    0.00, 0.45, 0.74
    0.93, 0.69, 0.13
    0.85, 0.20, 0.20
    ];

if numel(sampleTimes_s) ~= size(modeColors, 1)
    modeColors = lines(numel(sampleTimes_s));
end

figureHandle = figure( ...
    Name="Phase 4 candidate-mode costs", ...
    Color="white", ...
    Visible=options.Visible);

layout = tiledlayout( ...
    figureHandle, 2, 1, ...
    TileSpacing="compact", ...
    Padding="compact");

costAxes = nexttile(layout);
hold(costAxes, "on");
grid(costAxes, "on");

for modeIndex = 1:numel(sampleTimes_s)
    stairs( ...
        costAxes, ...
        time_s, ...
        costData(:, modeIndex), ...
        Color=modeColors(modeIndex, :), ...
        LineWidth=options.LineWidth, ...
        DisplayName=sprintf( ...
            "%.0f ms candidate", ...
            1e3*sampleTimes_s(modeIndex)));
end

ylabel(costAxes, "Total candidate cost");
title(costAxes, options.Title, Interpreter="none");

legend( ...
    costAxes, ...
    Location="eastoutside", ...
    Interpreter="none");

modeAxes = nexttile(layout);
hold(modeAxes, "on");
grid(modeAxes, "on");

stairs( ...
    modeAxes, ...
    time_s, ...
    minimumMode, ...
    "--", ...
    Color=[0.15, 0.15, 0.15], ...
    LineWidth=1.4, ...
    DisplayName="Minimum-cost mode");

if any(isfinite(activeMode))
    stairs( ...
        modeAxes, ...
        time_s, ...
        activeMode, ...
        Color=[0.49, 0.18, 0.56], ...
        LineWidth=1.2, ...
        DisplayName="Active mode");
end

yticks(modeAxes, 1:numel(sampleTimes_s));
yticklabels(modeAxes, compose( ...
    "%.0f ms", 1e3*sampleTimes_s));
ylim(modeAxes, [0.75, numel(sampleTimes_s) + 0.25]);

xlabel(modeAxes, "Time (s)");
ylabel(modeAxes, "Controller mode");

legend( ...
    modeAxes, ...
    Location="eastoutside", ...
    Interpreter="none");

linkaxes([costAxes, modeAxes], "x");
xlim(modeAxes, time_s([1, end]));

costTable = array2table( ...
    costData, ...
    VariableNames=matlab.lang.makeUniqueStrings( ...
        "Cost_" + string(round(1e3*sampleTimes_s)) + "ms"));

costTable = addvars( ...
    costTable, ...
    time_s, ...
    minimumCost, ...
    minimumMode, ...
    activeMode, ...
    Before=1, ...
    NewVariableNames=[ ...
        "Time_s"
        "MinimumCost"
        "MinimumCostMode"
        "ActiveMode"
        ]);

if strlength(options.SaveFile) > 0
    outputFolder = fileparts(options.SaveFile);
    if strlength(outputFolder) > 0 && ~isfolder(outputFolder)
        mkdir(outputFolder);
    end

    exportgraphics( ...
        figureHandle, ...
        options.SaveFile, ...
        Resolution=300);
end

end
