%% Collect fixed-mode data for Phase 4 performance maps

clearvars;
clc;

startup_project;

collectionSummary = collect_phase4_performance_data( ...
    ScenarioNames=[ ...
        % "urban_profile"
        % "highway_cruise"
        "aggressive_maneuver"], ...
    EnvironmentNames=[ ...
        "dry_road"
        % "low_friction_road" ...
        ], ...
    SampleTimes_s=[0.05, 0.02, 0.010], ...
    LoadTaskDuration_s=0.020, ...
    BaseRandomSeed=4000, ...
    Overwrite=false);

disp(collectionSummary);
