%% Build Phase 4 KNN performance maps from fixed-mode runs

clearvars;
clc;

startup_project;

mapSummary = build_phase4_performance_maps( ...
    ScenarioNames=[ ...
        % "urban_profile"
        % "highway_cruise"
        "aggressive_maneuver"], ...
    EnvironmentNames=[ ...
        "dry_road"
        % "low_friction_road" ...
        ], ...
    PredictionHorizon_s=1.0, ...
    RowStride_s=0.050);

disp(mapSummary);
