clearvars;
close all;
clc;

startup_project;

scenarioNames = [ ...
    sdv.enum.ScenarioName.urban_profile
    sdv.enum.ScenarioName.highway_cruise
    sdv.enum.ScenarioName.aggressive_maneuver
    ];

environmentNames = [ ...
    sdv.enum.EnvironmentName.dry_road
    sdv.enum.EnvironmentName.low_friction_road
    ];

loadCases = [ ...
    "off"
    "maximum"
    ];

randomSeed = 1001;
modelName = "phase2_scheduler_testbed";

numberOfRuns = ...
    numel(scenarioNames) ...
    * numel(environmentNames) ...
    * numel(loadCases);

runNumber = 0;

for scenarioName = scenarioNames.'
    for environmentName = environmentNames.'
        for loadCase = loadCases.'

            runNumber = runNumber + 1;

            fprintf( ...
                "\n[%d/%d] Running %s | %s | %s\n", ...
                runNumber, ...
                numberOfRuns, ...
                scenarioName, ...
                environmentName, ...
                loadCase);

%% Build the normal Phase 0 configuration

configuration = ...
    build_phase0_configuration(scenarioName);

vehicleParams = configuration.vehicle;
controllerParams = configuration.controller;
simulationParams = configuration.simulation;
adaptiveModelParams = configuration.adaptiveModel;


initialControllerMeasurement = [
    simulationParams.initial_speed_mps
    0
    0
    simulationParams.initial_x_m
    simulationParams.initial_y_m
    simulationParams.initial_yaw_rad
    ];

check_runtime_requirements(controllerParams);

%% Variables required by the existing plant and controller

UT = legacy_plant_parameters( ...
    vehicleParams, ...
    simulationParams);

acadosSettings = ...
    acados_ocp_parameters(controllerParams);

acados_nominal_input = reshape( ...
    acadosSettings.nominal_input, ...
    2, ...
    1);

track_ref_table = ...
    configuration.scenario.lookup_table;

scenario_stop_table = ...
    configuration.scenario.stop_event_table;

stopTime_s = configuration.scenario.simulation_stop_time_s;
% stopTime_s = 2;
final_track_index = ...
    size(track_ref_table,1);

environment = load_env_profile( ...
    lower(environmentName), ...
    stopTime_s, ...
    FrictionDropTime_s=10);

roadFrictionProfile = ...
    environment.road_friction_profile;

%% Load empirical MPC execution times: solveTimeTelemetry
durationData = ...
    load_control_task_durations( ...
        scenarioName, ...
        environmentName);

% resample solveTimeTelemetry
controlTaskDuration = ...
    create_control_task_duration_signal( ...
        durationData.samples_s, ...
        stopTime_s, ...
        randomSeed);

%% CPU load
% off -> only control task, maximum -> perception & communication
% included
loadTaskPeriod_s = 0.050;

switch loadCase
    case "off"
        loadTaskDuration_s = 1e-6;

    case "maximum"
        loadTaskDuration_s = 0.030;  % 10-45 ms

    otherwise
        error("Unknown load case: %s", loadCase);
end

loadReleaseTime_s = (0:0.05:stopTime_s).';

loadTaskDuration = timeseries( ...
    repmat(loadTaskDuration_s, ...
           numel(loadReleaseTime_s), 1), ...
    loadReleaseTime_s);

loadTaskDuration = setinterpmethod( ...
    loadTaskDuration, ...
    "zoh");

fprintf( ...
    "Control timing source: %s\n", ...
    durationData.source_file);

fprintf( ...
    "Mean execution time: %.3f ms\n", ...
    1e3*durationData.mean_s);

fprintf( ...
    "Maximum execution time: %.3f ms\n", ...
    1e3*durationData.maximum_s);

%% Build the simulation input

simulationInput = ...
    Simulink.SimulationInput(modelName);

simulationInput = simulationInput.setVariable( ...
    "vehicleParams",vehicleParams);

simulationInput = simulationInput.setVariable( ...
    "controllerParams",controllerParams);

simulationInput = simulationInput.setVariable( ...
    "simulationParams",simulationParams);

simulationInput = simulationInput.setVariable( ...
    "adaptiveModelParams",adaptiveModelParams);

simulationInput = simulationInput.setVariable( ...
    "UT",UT);

simulationInput = simulationInput.setVariable( ...
    "acados_nominal_input",acados_nominal_input);

simulationInput = simulationInput.setVariable( ...
    "track_ref_table",track_ref_table);

simulationInput = simulationInput.setVariable( ...
    "scenario_stop_table",scenario_stop_table);

simulationInput = simulationInput.setVariable( ...
    "final_track_index",final_track_index);

simulationInput = simulationInput.setVariable( ...
    "roadFrictionProfile",roadFrictionProfile);

simulationInput = simulationInput.setVariable( ...
    "controlTaskDuration",controlTaskDuration);

simulationInput = simulationInput.setVariable( ...
    "loadTaskDuration", ...
    loadTaskDuration);

simulationInput = simulationInput.setVariable( ...
    "initialControllerMeasurement", ...
    initialControllerMeasurement);

simulationInput = simulationInput.setModelParameter( ...
    StopTime=string(stopTime_s), ...
    ReturnWorkspaceOutputs="on", ...
    SignalLogging="on", ...
    SignalLoggingName="logsout", ...
    SignalInfNanChecking="error");

%% Simulation log

fprintf("\nRunning Phase 2.3 simulation ...\n");

simulationOutput = sim(simulationInput);

fprintf("Phase 2.3 simulation completed.\n");

logs = simulationOutput.logsout;

disp("Logged signals:");
disp(string(logs.getElementNames));

%% extract simulation results
availableSignals = string(logs.getElementNames);

solveTimeAvailable = ...
    ismember("solve_time", availableSignals);

results = sdv.results.extractBaseline( ...
    logs, ...
    solveTimeAvailable, ...
    IrregularControllerTiming=true);

%% Extract scheduler timing results

runIds = Simulink.sdi.getAllRunIDs;
latestRun = Simulink.sdi.getRun(runIds(end));

taskData = socTaskTimes( ...
    modelName, ...
    latestRun.Name, ...
    "SuppressPlot");
disp(taskData)
numberOfTasks = numel(taskData);

taskName = strings(numberOfTasks,1);

meanExecution_ms = nan(numberOfTasks,1);
maximumExecution_ms = nan(numberOfTasks,1);
meanResponse_ms = nan(numberOfTasks,1);
maximumResponse_ms = nan(numberOfTasks,1);

numberOfOverruns = zeros(numberOfTasks,1);
overrunPercent = zeros(numberOfTasks,1);
numberOfDroppedJobs = zeros(numberOfTasks,1);

for taskIndex = 1:numberOfTasks

    currentTask = taskData(taskIndex);

    taskName(taskIndex) = string(currentTask.Name);

    meanExecution_ms(taskIndex) = ...
        1e3*scalarOrDefault(currentTask.Mean, NaN);

    maximumExecution_ms(taskIndex) = ...
        1e3*scalarOrDefault(currentTask.MaxDuration, NaN);

    meanResponse_ms(taskIndex) = ...
        1e3*scalarOrDefault(currentTask.MeanTurnaround, NaN);

    maximumResponse_ms(taskIndex) = ...
        1e3*scalarOrDefault(currentTask.MaxTurnaround, NaN);

    numberOfOverruns(taskIndex) = ...
        scalarOrDefault(currentTask.NumOverran, 0);

    overrunPercent(taskIndex) = ...
        scalarOrDefault(currentTask.PercentOverran, 0);

    numberOfDroppedJobs(taskIndex) = ...
        scalarOrDefault(currentTask.NumDropped, 0);
end

taskSummary = table( ...
    taskName, ...
    meanExecution_ms, ...
    maximumExecution_ms, ...
    meanResponse_ms, ...
    maximumResponse_ms, ...
    numberOfOverruns, ...
    overrunPercent, ...
    numberOfDroppedJobs, ...
    VariableNames=[ ...
        "Task", ...
        "MeanExecution_ms", ...
        "MaximumExecution_ms", ...
        "MeanResponse_ms", ...
        "MaximumResponse_ms", ...
        "Overruns", ...
        "OverrunPercent", ...
        "DroppedJobs"]);

disp(taskSummary);


%% Save Phase 2.3 scheduler results

projectRoot = string( ...
    matlab.project.currentProject().RootFolder);

resultsFolder = fullfile( ...
    projectRoot, ...
    "phase2", ...
    "results", ...
    "phase2_3", ...
    scenarioName, ...
    environmentName, ...
    loadCase);

if ~isfolder(resultsFolder)
    mkdir(resultsFolder);
end

save( ...
    fullfile(resultsFolder, "scheduler_results.mat"), ...
    "taskData", ...
    "taskSummary", ...
    "scenarioName", ...
    "environmentName", ...
    "loadCase", ...
    "loadTaskDuration_s");

writetable( ...
    taskSummary, ...
    fullfile(resultsFolder, "scheduler_summary.csv"));


%% saving simulation results

runArtifact = struct();

runArtifact.schema_version = 1;
runArtifact.results = results;
runArtifact.reference = track_ref_table;
runArtifact.taskData = taskData;

runArtifact.scenarioName = string(scenarioName);
runArtifact.environmentName = string(environmentName);
runArtifact.loadCase = string(loadCase);

runFile = fullfile(resultsFolder,"run_data.mat");

% Save before plotting so plotting errors do not lose simulation results.
save(runFile,"runArtifact","-v7.3");

fprintf("Phase 2.3 run saved to:\n%s\n",runFile);

figures = plot_phase2_3_results( ...
    results, ...
    track_ref_table, ...
    taskData, ...
    scenarioName, ...
    environmentName, ...
    loadCase ...
    );

figureFolder = fullfile( ...
    projectRoot, ...
    "phase2", ...
    "figures", ...
    "phase2_3", ...
    scenarioName, ...
    environmentName, ...
    loadCase);

sdv.io.exportFigure( ...
    figures.control, ...
    figureFolder, ...
    "control_performance");

sdv.io.exportFigure( ...
    figures.scheduler, ...
    figureFolder, ...
    "scheduler_timing");

close(figures.control);
close(figures.scheduler);

        end
    end
end

fprintf("\nPhase 2.3 batch completed: %d runs.\n",numberOfRuns);

function value = scalarOrDefault(inputValue, defaultValue)

if isempty(inputValue)
    value = defaultValue;
else
    value = double(inputValue(1));
end

end
