function figureHandle = samplingJitterProfile( ...
    eventTable, ...
    executionLog, ...
    nominalSampleTime_s, ...
    jitterBound_ms, ...
    scenarioName)
%SAMPLINGJITTERPROFILE Plot requested and realized controller timing.
%
% Inputs:
%   eventTable            Trigger schedule produced by the jitter generator
%   executionLog          One row per observed controller execution
%   nominalSampleTime_s   Nominal controller period, seconds
%   jitterBound_ms        Requested symmetric jitter bound, milliseconds
%   scenarioName          Scenario name used in the figure title

arguments
    eventTable table
    executionLog table
    nominalSampleTime_s (1,1) double {mustBePositive}
    jitterBound_ms (1,1) double {mustBeNonnegative}
    scenarioName (1,1) string
end

%% Align scheduled and observed executions

numberOfExecutions = min( ...
    height(eventTable), ...
    height(executionLog));

% eventTable = ...
%     eventTable(1:numberOfExecutions, :);

executionLog = ...
    executionLog(1:numberOfExecutions, :);

executionTime_s = ...
    executionLog.ActualTime_s;

%% Convert timing quantities to milliseconds

% scheduledJitter_ms = ...
%     1e3 * eventTable.AppliedJitter_s;

actualJitter_ms = ...
    1e3 * executionLog.ActualJitter_s;

% scheduledInterval_ms = ...
%     1e3 * eventTable.AppliedInterval_s;

actualInterval_ms = ...
    1e3 * executionLog.ActualInterval_s;

% schedulingError_ms = ...
%     1e3 * executionLog.SchedulingError_s; % error = actual_time - applied_time

nominalSampleTime_ms = ...
    1e3 * nominalSampleTime_s;

rawStatus = ...
    executionLog.SolverStatus;

%% Create figure

figureHandle = figure( ...
    Name="Sampling jitter profile: " + scenarioName, ...
    Color="w");

layout = tiledlayout( ...
    figureHandle, ...
    3, ...
    1, ...
    TileSpacing="compact", ...
    Padding="compact");

title( ...
    layout, ...
    "Sampling-Jitter Execution Profile: " + ...
    replace(scenarioName, "_", " "));

%% Requested, scheduled and actual jitter

nexttile;
plot( ...
    executionTime_s, ...
    actualJitter_ms, ...
    LineWidth=1.0, ...
    DisplayName="Observed execution jitter");

yline( ...
    jitterBound_ms, ...
    "r--", ...
    DisplayName="+Jitter bound");

yline( ...
    -jitterBound_ms, ...
    "r--", ...
    HandleVisibility="off");

grid on;
ylabel("Jitter (ms)");
legend(Location="best");

%% Controller execution intervals

nexttile;

plot( ...
    executionTime_s, ...
    actualInterval_ms, ...
    ".", ...
    MarkerSize=6, ...
    DisplayName="Observed interval");

hold on;

yline( ...
    nominalSampleTime_ms, ...
    "k--", ...
    LineWidth=1.2, ...
    DisplayName="Nominal period");

grid on;
ylabel("Interval (ms)");
legend(Location="best");

%% Raw acados status

nexttile;

stairs( ...
    executionTime_s, ...
    rawStatus, ...
    LineWidth=1.0, ...
    DisplayName="Raw acados controller status");

hold on;

yline( ...
    0, ...
    "g--", ...
    DisplayName="ACADOS\_SUCCESS");

hold off;

grid on;
xlabel("Simulation time (s)");
ylabel("Raw status");
legend(Location="best");

end