function figures = standardRunFigures(results, config)
%STANDARDRUNFIGURES Create the standard figures for one saved run.

arguments
    results (1,1) struct
    config (1,1) struct
end

assert(isfield(config, "run"), ...
    "Saved configuration does not contain config.run.");

runConfig = config.run;
figures = struct();

figures.closed_loop = sdv.plot.closedLoop( ...
    results, ...
    config.scenario, ...
    runConfig.environment_name, ...
    runConfig.actuation_delay_s);

figures.tracking_errors = sdv.plot.trackingErrors( ...
    results, ...
    config.scenario, ...
    runConfig.environment_name, ...
    config.controller, ...
    runConfig.actuation_delay_s);

if runConfig.phase_name == "phase1_trigger"
    figures.sampling_jitter_profile = ...
        sdv.plot.samplingJitterProfile( ...
            results.jitter_event_table, ...
            results.controller_execution_log, ...
            config.controller.Ts_s, ...
            runConfig.jitter.bound_ms, ...
            runConfig.scenario_name);
end

solveTimeAvailable = ...
    config.controller.controller_backend == ...
    config.controller.BACKEND_ACADOS;

if solveTimeAvailable
    figures.solve_time_histogram = sdv.plot.solveTimeHistogram( ...
        results, ...
        config.scenario, ...
        runConfig.environment_name, ...
        config.simulation.Ts_s, ...
        runConfig.actuation_delay_s);

    figures.solve_time_telemetry = sdv.plot.solveTimeTelemetry( ...
        results, ...
        string(config.scenario.name), ...
        runConfig.environment_name, ...
        config.simulation.Ts_s, ...
        runConfig.actuation_delay_s);
end

end
