function figureHandle = trackingErrorOverlay( ...
    timeSeries_s, lateralErrorSeries_m, headingErrorSeries, ...
    legendLabels, options)
%TRACKINGERROROVERLAY Plot multiple prepared tracking-error histories.
%
% All phase-specific loading and preprocessing must be completed before
% calling this function. Each cell contains one run and may have a
% different time-vector length.

arguments
    timeSeries_s cell
    lateralErrorSeries_m cell
    headingErrorSeries cell
    legendLabels string
    options.FigureTitle (1,1) string = "Tracking-error comparison"
    options.HeadingUnit (1,1) string ...
        {mustBeMember(options.HeadingUnit, ["deg", "rad"])} = "deg"
    options.Colors (:,3) double = zeros(0,3)
    options.LineStyles string = strings(0,1)
    options.LineWidth (1,1) double {mustBePositive} = 1.2
    options.LateralLimits_m (1,2) double = [NaN, NaN]
    options.HeadingLimits (1,2) double = [NaN, NaN]
    options.HighlightViolations (1,1) logical = true
    options.LegendColumns (1,1) double ...
        {mustBeInteger, mustBeNonnegative} = 0
    options.XLimits_s (1,2) double = [NaN, NaN]
    options.Visible (1,1) string ...
        {mustBeMember(options.Visible, ["on", "off"])} = "on"
    options.ShowMarkers (1,1) logical = true
    options.Marker (1,1) string = "."
    options.MarkerSize (1, 1) double = 5.0
end

timeSeries_s = timeSeries_s(:);
lateralErrorSeries_m = lateralErrorSeries_m(:);
headingErrorSeries = headingErrorSeries(:);
legendLabels = legendLabels(:);

numberOfSeries = numel(timeSeries_s);
lateralLimitsEnabled = validateLimits( ...
    options.LateralLimits_m, "LateralLimits_m");
headingLimitsEnabled = validateLimits( ...
    options.HeadingLimits, "HeadingLimits");

assert(numberOfSeries > 0, ...
    "At least one tracking-error series is required.");
assert(numel(lateralErrorSeries_m) == numberOfSeries && ...
    numel(headingErrorSeries) == numberOfSeries && ...
    numel(legendLabels) == numberOfSeries, ...
    "Time, lateral error, heading error, and labels must have equal counts.");

if isempty(options.Colors)
    colors = turbo(numberOfSeries);
else
    assert(size(options.Colors, 1) == numberOfSeries, ...
        "Colors must contain one RGB row per series.");
    colors = options.Colors;
end

if isempty(options.LineStyles)
    lineStyles = "-";
else
    lineStyles = options.LineStyles(:);
end

figureHandle = figure( ...
    Name=options.FigureTitle, ...
    Color="white", ...
    Visible=options.Visible);

layout = tiledlayout( ...
    figureHandle, 2, 1, ...
    TileSpacing="compact", ...
    Padding="compact");

lateralAxes = nexttile(layout);
hold(lateralAxes, "on");

headingAxes = nexttile(layout);
hold(headingAxes, "on");

legendHandles = gobjects(numberOfSeries, 1);
hasViolation = false;
violationColor = [0.90, 0.50, 0.36];

markerStyle = "none";

if options.ShowMarkers
    markerStyle = options.Marker;
end

for seriesIndex = 1:numberOfSeries
    time_s = double(timeSeries_s{seriesIndex}(:));
    lateralError_m = double(lateralErrorSeries_m{seriesIndex}(:));
    headingError = double(headingErrorSeries{seriesIndex}(:));

    assert(numel(time_s) == numel(lateralError_m) && ...
        numel(time_s) == numel(headingError), ...
        "Series %d has inconsistent time and error lengths.", ...
        seriesIndex);
    assert(all(isfinite(time_s)) && ...
        all(isfinite(lateralError_m)) && ...
        all(isfinite(headingError)), ...
        "Series %d contains NaN or Inf values.", seriesIndex);

    lineStyleIndex = mod( ...
        seriesIndex - 1, numel(lineStyles)) + 1;

    legendHandles(seriesIndex) = plot( ...
        lateralAxes, time_s, lateralError_m, ...
        LineStyle=lineStyles(lineStyleIndex), ...
        Color=colors(seriesIndex, :), ...
        LineWidth=options.LineWidth, ...
        DisplayName=legendLabels(seriesIndex));

    plot( ...
        headingAxes, time_s, headingError, ...
        LineStyle=lineStyles(lineStyleIndex), ...
        Color=colors(seriesIndex, :), ...
        LineWidth=options.LineWidth, ...
        HandleVisibility="off");

    if options.HighlightViolations && lateralLimitsEnabled
        lateralViolation = ...
            lateralError_m < options.LateralLimits_m(1) | ...
            lateralError_m > options.LateralLimits_m(2);
        hasViolation = hasViolation || any(lateralViolation);

        plot( ...
            lateralAxes, ...
            time_s(lateralViolation), ...
            lateralError_m(lateralViolation), ...
            ".", ...
            LineStyle="none", ...
            Marker = markerStyle, ...
            MarkerSize= options.MarkerSize, ...
            MarkerFaceColor=violationColor, ...
            MarkerEdgeColor=violationColor, ...
            HandleVisibility="off");
    end

    if options.HighlightViolations && headingLimitsEnabled
        headingViolation = ...
            headingError < options.HeadingLimits(1) | ...
            headingError > options.HeadingLimits(2);
        hasViolation = hasViolation || any(headingViolation);

        plot( ...
            headingAxes, ...
            time_s(headingViolation), ...
            headingError(headingViolation), ...
            "o", ...
            LineStyle="none", ...
            Marker = markerStyle, ...
            MarkerSize=options.MarkerSize, ...
            MarkerFaceColor=violationColor, ...
            MarkerEdgeColor=violationColor, ...
            HandleVisibility="off");
    end
end

yline(lateralAxes, 0, "k-", HandleVisibility="off");
yline(headingAxes, 0, "k-", HandleVisibility="off");

if lateralLimitsEnabled
    yline( ...
        lateralAxes, options.LateralLimits_m(1), "k--", ...
        HandleVisibility="off");
    yline( ...
        lateralAxes, options.LateralLimits_m(2), "k--", ...
        HandleVisibility="off");
end

if headingLimitsEnabled
    yline( ...
        headingAxes, options.HeadingLimits(1), "k--", ...
        HandleVisibility="off");
    yline( ...
        headingAxes, options.HeadingLimits(2), "k--", ...
        HandleVisibility="off");
end

ylabel(lateralAxes, "Lateral error, e_y (m)");
ylabel(headingAxes, ...
    "Heading error, e_\psi (" + options.HeadingUnit + ")");
xlabel(headingAxes, "Time (s)");

title(lateralAxes, "Lateral tracking error");
title(headingAxes, "Heading tracking error");
title(layout, options.FigureTitle, FontWeight="bold");

grid(lateralAxes, "on");
grid(headingAxes, "on");
linkaxes([lateralAxes, headingAxes], "x");

if all(isfinite(options.XLimits_s))
    assert(options.XLimits_s(2) > options.XLimits_s(1), ...
        "XLimits_s must be increasing.");
    xlim(lateralAxes, options.XLimits_s);
end

legendColumns = options.LegendColumns;
if legendColumns == 0
    legendColumns = max(1, ceil(numberOfSeries / 24));
end

allLegendHandles = legendHandles;
allLegendLabels = legendLabels;

if lateralLimitsEnabled || headingLimitsEnabled
    constraintLegendHandle = plot( ...
        lateralAxes, NaN, NaN, "k--", LineWidth=1.0);
    allLegendHandles(end+1,1) = constraintLegendHandle;
    allLegendLabels(end+1,1) = "Constraint limits";
end

if hasViolation
    violationLegendHandle = plot( ...
        lateralAxes, NaN, NaN, "o", ...
        LineStyle="none", ...
        MarkerSize=4, ...
        MarkerFaceColor=violationColor, ...
        MarkerEdgeColor=violationColor);
    allLegendHandles(end+1,1) = violationLegendHandle;
    allLegendLabels(end+1,1) = "Constraint violation";
end

[allLegendLabels, uniqueLegendIndex] = unique( ...
    allLegendLabels, "stable");
allLegendHandles = allLegendHandles(uniqueLegendIndex);

legendHandle = legend( ...
    lateralAxes, allLegendHandles, allLegendLabels, ...
    Interpreter="none", ...
    NumColumns=legendColumns);
legendHandle.Layout.Tile = "east";

end

function enabled = validateLimits(limits, optionName)
finiteLimits = all(isfinite(limits));
disabledLimits = all(isnan(limits));

assert(finiteLimits || disabledLimits, ...
    "%s must contain two finite limits or [NaN, NaN].", optionName);

if finiteLimits
    assert(limits(2) > limits(1), ...
        "%s must be [lower, upper].", optionName);
end

enabled = finiteLimits;
end
