clearvars;
clc;

startup_project;

scenarioName = "aggressive_maneuver";
environmentName = "dry_road";

projectRoot = string( ...
    matlab.project.currentProject().RootFolder);

baseFolder = fullfile( ...
    projectRoot, ...
    "phase2", ...
    "results", ...
    "phase2_3", ...
    scenarioName, ...
    environmentName);

offSummary = readtable( ...
    fullfile(baseFolder, "off", "scheduler_summary.csv"), ...
    TextType="string");

maximumSummary = readtable( ...
    fullfile(baseFolder, "maximum", "scheduler_summary.csv"), ...
    TextType="string");

offSummary.Properties.VariableNames(2:end) = ...
    "Off_" + string( ...
    offSummary.Properties.VariableNames(2:end));

maximumSummary.Properties.VariableNames(2:end) = ...
    "Maximum_" + string( ...
    maximumSummary.Properties.VariableNames(2:end));

comparisonTable = innerjoin( ...
    offSummary, ...
    maximumSummary, ...
    Keys="Task");

comparisonTable.MeanResponseIncrease_ms = ...
    comparisonTable.Maximum_MeanResponse_ms ...
    - comparisonTable.Off_MeanResponse_ms;

comparisonTable.MaximumResponseIncrease_ms = ...
    comparisonTable.Maximum_MaximumResponse_ms ...
    - comparisonTable.Off_MaximumResponse_ms;

comparisonTable.AdditionalOverruns = ...
    comparisonTable.Maximum_Overruns ...
    - comparisonTable.Off_Overruns;

disp(comparisonTable);

writetable( ...
    comparisonTable, ...
    fullfile(baseFolder, "scheduler_case_comparison.csv"));