
scenarioName = "aggressive_maneuver";
environmentName = "dry_road";
randomSeed = 1001;

durationData = ...
    load_control_task_durations( ...
    scenarioName, ...
    environmentName);

% stopTime_s = durationData.stop_time_s;
stopTime_s = 1;
controlTaskDuration = ...
    create_control_task_duration_signal( ...
    durationData.samples_s, ...
    stopTime_s, ...
    randomSeed);

fprintf( ...
    "Control-task timing source: %s\n", ...
    durationData.source_file);

fprintf( ...
    "Measured mean: %.3f ms\n", ...
    1e3*durationData.mean_s);

fprintf( ...
    "Measured maximum: %.3f ms\n", ...
    1e3*durationData.maximum_s);


[results, timingTable] = ...
    run_phase2_tool_spike(stopTime_s, controlTaskDuration);