function [results, timingTable] = run_phase2_tool_spike()
%RUN_PHASE2_TOOL_SPIKE Run and document the Phase 2.1 tool spike.

startup_project;

%% Paths

project = matlab.project.currentProject;
projectRoot = string(project.RootFolder);

modelName = "phase2_soc_tool_spike";

resultsFolder = fullfile( ...
    projectRoot, ...
    "phase2", ...
    "results");

figuresFolder = fullfile( ...
    projectRoot, ...
    "phase2", ...
    "figures");

if ~isfolder(resultsFolder)
    mkdir(resultsFolder);
end

if ~isfolder(figuresFolder)
    mkdir(figuresFolder);
end

%% Experiment configuration

stopTime_s = 0.15;

controlPeriod_s = 0.01;
nominalControlExecutionTime_s = 0.003;

%% Load and validate model

load_system(modelName);

set_param( ...
    modelName, ...
    "FastRestart", ...
    "off");

set_param( ...
    modelName, ...
    "SignalLogging", ...
    "on");

%% Run simulation

simulationInput = ...
    Simulink.SimulationInput(modelName);

simulationInput = ...
    simulationInput.setModelParameter( ...
        StopTime=string(stopTime_s), ...
        SignalLogging="on", ...
        SignalLoggingName="logsout");

fprintf("\nRunning Phase 2.1 scheduler tool spike...\n");

simulationOutput = sim(simulationInput);

runIds = Simulink.sdi.getAllRunIDs;
assert(~isempty(runIds), ...
    "No Simulation Data Inspector run was found.");

latestRun = Simulink.sdi.getRun(runIds(end));
runName = string(latestRun.Name);

fprintf("Using SDI run: %s\n", runName);

taskData = socTaskTimes( ...
    modelName, ...
    runName, ...
    "SuppressPlot");

taskNames = string({taskData.Name});

controlIndex = ...
    find(taskNames == "ControlTask", 1);

assert( ...
    ~isempty(controlIndex), ...
    "ControlTask was not found in SDI task telemetry.");

controlTaskData = taskData(controlIndex);

executionTime_s = ...
    controlTaskData.Duration(:);

startTime_s = ...
    controlTaskData.StartTime(:);

completionTime_s = ...
    controlTaskData.EndTime(:);

responseTime_s = ...
    controlTaskData.Turnaround(:);

releaseTime_s = ...
    completionTime_s - responseTime_s;

waitingAndPreemptionTime_s = ...
    responseTime_s - executionTime_s;

timingTable = table( ...
    releaseTime_s, ...
    startTime_s, ...
    completionTime_s, ...
    1000*executionTime_s, ...
    1000*responseTime_s, ...
    1000*waitingAndPreemptionTime_s, ...
    VariableNames=[ ...
        "ReleaseTime_s", ...
        "StartTime_s", ...
        "CompletionTime_s", ...
        "ExecutionTime_ms", ...
        "ResponseTime_ms", ...
        "WaitingAndPreemptionTime_ms"]);

assert( ...
    isprop(simulationOutput, "logsout") || ...
    any(strcmp(simulationOutput.who, "logsout")), ...
    "The simulation did not produce logsout.");

logs = simulationOutput.logsout;

assert( ...
    isa(logs, "Simulink.SimulationData.Dataset"), ...
    "logsout is not a Simulink logging Dataset.");

%% Extract required signals

requiredSignalNames = [
    "position"
    "velocity"
    "control_output"
    ];

availableSignalNames = ...
    string(logs.getElementNames);

missingSignalNames = ...
    setdiff( ...
        requiredSignalNames, ...
        availableSignalNames);

assert( ...
    isempty(missingSignalNames), ...
    "Missing logged signals: %s", ...
    strjoin(missingSignalNames, ", "));

positionSignal = ...
    logs.getElement("position").Values;

velocitySignal = ...
    logs.getElement("velocity").Values;

controlSignal = ...
    logs.getElement("control_output").Values;

%% Store extracted results

results = struct();

results.scenario = "phase2_1_tool_spike";
results.stop_time_s = stopTime_s;
results.control_period_s = controlPeriod_s;
results.nominal_execution_time_s = ...
    nominalControlExecutionTime_s;

results.position = positionSignal;
results.velocity = velocitySignal;
results.control_output = controlSignal;

results.time_s = positionSignal.Time(:);
results.position_m = ...
    reshape(positionSignal.Data, [], 1);

results.velocity_mps = ...
    reshape(velocitySignal.Data, [], 1);

results.control_time_s = ...
    controlSignal.Time(:);

results.control_command = ...
    reshape(controlSignal.Data, [], 1);

%% Plot and calculate response-time telemetry

figureFile = fullfile( ...
    figuresFolder, ...
    "phase2_1_scheduler_tool_spike.png");

[figureHandle] = ...
    plot_phase2_tool_spike( ...
        positionSignal, ...
        velocitySignal, ...
        controlSignal, ...
        timingTable, ...
        controlPeriod_s, ...
        nominalControlExecutionTime_s, ...
        figureFile);

results.response_time = timingTable;

%% Save results

matFile = fullfile( ...
    resultsFolder, ...
    "phase2_1_tool_spike_results.mat");

save( ...
    matFile, ...
    "results", ...
    "timingTable");

csvFile = fullfile( ...
    resultsFolder, ...
    "phase2_1_response_time.csv");

writetable( ...
    timingTable, ...
    csvFile);

fprintf("\nPhase 2.1 simulation completed.\n");
fprintf("Results: %s\n", matFile);
fprintf("Timing table: %s\n", csvFile);
fprintf("Figure: %s\n", figureFile);

if isempty(timingTable)
    warning( ...
        "No control-output transitions were detected.");
else
    fprintf( ...
        "Mean response time: %.3f ms\n", ...
        mean(timingTable.ResponseTime_ms));

    fprintf( ...
        "Maximum response time: %.3f ms\n", ...
        max(timingTable.ResponseTime_ms));
end

figure(figureHandle);
end
