function [summaryTable, figures, loadTaskSummaryTable] = ...
    run_phase2_4_utilization_sweep(options)
%RUN_PHASE2_4_UTILIZATION_SWEEP Sweep load-task execution time.
%
% Each simulation is saved immediately. The aggregate MAT and CSV files
% are also updated after every attempted point, so an interrupted sweep can
% be resumed without losing completed cases.

arguments
    options.ScenarioNames (1,:) string = [ ...
        "urban_profile", ...
        "highway_cruise", ...
        "aggressive_maneuver"]
    options.EnvironmentNames (1,:) string = [ ...
        "dry_road", ...
        "low_friction_road"]
    options.LoadExecutionTime_ms (1,:) double {mustBeNonnegative} = ...
        0:5:40
    options.RandomSeed (1,1) double = 1001
    options.Resume (1,1) logical = true
    options.ShowFigure (1,1) logical = true
end

startup_project;

projectRoot = string(matlab.project.currentProject().RootFolder);
aggregateFolder = fullfile( ...
    projectRoot, ...
    "phase2", ...
    "results", ...
    "phase2_4");

if ~isfolder(aggregateFolder)
    mkdir(aggregateFolder);
end

summaryFile = fullfile(aggregateFolder, "phase2_4_summary.mat");
summaryCsv = fullfile(aggregateFolder, "phase2_4_summary.csv");
loadSummaryFile = fullfile( ...
    aggregateFolder, ...
    "phase2_4_load_task_summary.mat");
loadSummaryCsv = fullfile( ...
    aggregateFolder, ...
    "phase2_4_load_task_summary.csv");

summaryTable = emptySummaryTable();
loadTaskSummaryTable = emptyLoadTaskSummaryTable();

if options.Resume && isfile(summaryFile)
    savedSummary = load(summaryFile, "summaryTable");
    if isfield(savedSummary, "summaryTable")
        summaryTable = savedSummary.summaryTable;
    end
end

if options.Resume && isfile(loadSummaryFile)
    savedLoadSummary = load(loadSummaryFile, "loadTaskSummaryTable");
    if isfield(savedLoadSummary, "loadTaskSummaryTable")
        loadTaskSummaryTable = savedLoadSummary.loadTaskSummaryTable;
    end
end

loadTaskSummaryTable = backfillLoadTaskSummary( ...
    summaryTable, ...
    loadTaskSummaryTable);

if ~isempty(loadTaskSummaryTable)
    save(loadSummaryFile, "loadTaskSummaryTable");
    writetable(loadTaskSummaryTable, loadSummaryCsv);
end

numberOfCases = ...
    numel(options.ScenarioNames) ...
    * numel(options.EnvironmentNames) ...
    * numel(options.LoadExecutionTime_ms);

caseNumber = 0;

for scenarioName = options.ScenarioNames
    for environmentName = options.EnvironmentNames
        for loadExecutionTime_ms = options.LoadExecutionTime_ms

            caseNumber = caseNumber + 1;

            controllerCaseComplete = isCompleted( ...
                    summaryTable, ...
                    scenarioName, ...
                    environmentName, ...
                    loadExecutionTime_ms);

            loadCaseComplete = isCompleted( ...
                    loadTaskSummaryTable, ...
                    scenarioName, ...
                    environmentName, ...
                    loadExecutionTime_ms);

            if options.Resume && controllerCaseComplete && loadCaseComplete
                fprintf( ...
                    "[%d/%d] Skipping completed case: %s | %s | %.3f ms\n", ...
                    caseNumber, ...
                    numberOfCases, ...
                    scenarioName, ...
                    environmentName, ...
                    loadExecutionTime_ms);
                continue;
            end

            fprintf( ...
                "\n[%d/%d] %s | %s | load %.3f ms\n", ...
                caseNumber, ...
                numberOfCases, ...
                scenarioName, ...
                environmentName, ...
                loadExecutionTime_ms);

            try
                [~, newRow, newLoadRow] = run_phase2_4_case( ...
                    scenarioName, ...
                    environmentName, ...
                    loadExecutionTime_ms, ...
                    RandomSeed=options.RandomSeed, ...
                    SaveResults=true);
            catch exception
                warning( ...
                    "SDV:Phase2_4CaseFailed", ...
                    "Phase 2.4 case failed: %s", ...
                    exception.message);

                newRow = failureRow( ...
                    scenarioName, ...
                    environmentName, ...
                    loadExecutionTime_ms, ...
                    options.RandomSeed, ...
                    exception);

                newLoadRow = loadFailureRow( ...
                    scenarioName, ...
                    environmentName, ...
                    loadExecutionTime_ms, ...
                    options.RandomSeed, ...
                    exception);
            end

            summaryTable = removeExistingCase( ...
                summaryTable, ...
                scenarioName, ...
                environmentName, ...
                loadExecutionTime_ms);

            summaryTable = [summaryTable; newRow]; %#ok<AGROW>
            summaryTable = sortrows( ...
                summaryTable, ...
                ["Scenario", "Environment", "LoadExecution_ms"]);

            loadTaskSummaryTable = removeExistingCase( ...
                loadTaskSummaryTable, ...
                scenarioName, ...
                environmentName, ...
                loadExecutionTime_ms);

            loadTaskSummaryTable = [ ...
                loadTaskSummaryTable; newLoadRow]; %#ok<AGROW>
            loadTaskSummaryTable = sortrows( ...
                loadTaskSummaryTable, ...
                ["Scenario", "Environment", "LoadExecution_ms"]);

            save(summaryFile, "summaryTable");
            writetable(summaryTable, summaryCsv);
            save(loadSummaryFile, "loadTaskSummaryTable");
            writetable(loadTaskSummaryTable, loadSummaryCsv);

            fprintf("Checkpoint saved: %s\n", summaryFile);
        end
    end
end

if options.ShowFigure
    figures = plot_phase2_4_utilization_sweep(summaryTable);
    figures.loadTask = ...
        plot_phase2_4_load_task_sweep(loadTaskSummaryTable);
else
    figures = struct();
end

end


function summaryTable = emptySummaryTable()

summaryTable = table( ...
    strings(0,1), ...
    strings(0,1), ...
    zeros(0,1), ...
    zeros(0,1), ...
    zeros(0,1), ...
    zeros(0,1), ...
    zeros(0,1), ...
    zeros(0,1), ...
    zeros(0,1), ...
    zeros(0,1), ...
    zeros(0,1), ...
    zeros(0,1), ...
    zeros(0,1), ...
    zeros(0,1), ...
    zeros(0,1), ...
    strings(0,1), ...
    strings(0,1), ...
    strings(0,1), ...
    strings(0,1), ...
    VariableNames=[ ...
        "Scenario", ...
        "Environment", ...
        "LoadExecution_ms", ... %important
        "NominalUtilization", ... %important
        "SpeedRMS_mps", ...
        "LateralRMS_m", ... %important
        "HeadingRMS_deg", ... %important
        "ControlMeanResponse_ms", ...
        "ControlP95Response_ms", ... %important
        "ControlMaximumResponse_ms", ...
        "DeadlineMissCount", ...
        "DeadlineMissPercent", ...
        "ControlOverrunCount", ... %imp
        "ControlDroppedJobs", ... %imp
        "RandomSeed", ...
        "Status", ...
        "ErrorIdentifier", ...
        "ErrorMessage", ...
        "RunFile"]);

end


function tableData = emptyLoadTaskSummaryTable()

tableData = table( ...
    strings(0,1), strings(0,1), ...
    zeros(0,1), zeros(0,1), zeros(0,1), ...
    zeros(0,1), zeros(0,1), ...
    zeros(0,1), zeros(0,1), zeros(0,1), ...
    zeros(0,1), zeros(0,1), ...
    zeros(0,1), zeros(0,1), zeros(0,1), ...
    strings(0,1), strings(0,1), strings(0,1), strings(0,1), ...
    VariableNames=[ ...
        "Scenario", "Environment", ...
        "LoadExecution_ms", "NominalUtilization", "LoadUtilization", ...
        "MeanExecution_ms", "MaximumExecution_ms", ...
        "MeanResponse_ms", "P95Response_ms", "MaximumResponse_ms", ...
        "DeadlineMissCount", "DeadlineMissPercent", ...
        "OverrunCount", "DroppedJobs", "RandomSeed", ...
        "Status", "ErrorIdentifier", "ErrorMessage", "RunFile"]);

end


function tf = isCompleted(tableData, scenario, environment, load_ms)

if isempty(tableData)
    tf = false;
    return;
end

matching = ...
    tableData.Scenario == scenario ...
    & tableData.Environment == environment ...
    & abs(tableData.LoadExecution_ms - load_ms) < 1e-9 ...
    & tableData.Status == "completed";

tf = any(matching);

end


function tableData = removeExistingCase( ...
    tableData, ...
    scenario, ...
    environment, ...
    load_ms)

if isempty(tableData)
    return;
end

matching = ...
    tableData.Scenario == scenario ...
    & tableData.Environment == environment ...
    & abs(tableData.LoadExecution_ms - load_ms) < 1e-9;

tableData(matching,:) = [];

end


function row = failureRow( ...
    scenario, ...
    environment, ...
    load_ms, ...
    randomSeed, ...
    exception)

message = string(exception.message);
message = replace(message, newline, " ");

row = table( ...
    scenario, ...
    environment, ...
    load_ms, ...
    NaN, ...
    NaN, ...
    NaN, ...
    NaN, ...
    NaN, ...
    NaN, ...
    NaN, ...
    NaN, ...
    NaN, ...
    NaN, ...
    NaN, ...
    randomSeed, ...
    "failed", ...
    string(exception.identifier), ...
    message, ...
    "", ...
    VariableNames=emptySummaryTable().Properties.VariableNames);

end


function loadTable = backfillLoadTaskSummary(controllerTable, loadTable)

for rowIndex = 1:height(controllerTable)
    controllerRow = controllerTable(rowIndex,:);

    if controllerRow.Status ~= "completed" || ...
            isCompleted( ...
                loadTable, ...
                controllerRow.Scenario, ...
                controllerRow.Environment, ...
                controllerRow.LoadExecution_ms)
        continue;
    end

    runFile = string(controllerRow.RunFile);
    if strlength(runFile) == 0 || ~isfile(runFile)
        continue;
    end

    savedRun = load(runFile, "runArtifact");
    if ~isfield(savedRun, "runArtifact")
        continue;
    end

    newRow = create_phase2_4_load_task_row(savedRun.runArtifact);
    newRow.RunFile = runFile;
    loadTable = [loadTable; newRow]; %#ok<AGROW>
end

if ~isempty(loadTable)
    loadTable = sortrows( ...
        loadTable, ...
        ["Scenario", "Environment", "LoadExecution_ms"]);
end

end


function row = loadFailureRow( ...
    scenario, ...
    environment, ...
    load_ms, ...
    randomSeed, ...
    exception)

message = replace(string(exception.message), newline, " ");

row = table( ...
    scenario, environment, load_ms, ...
    NaN, NaN, NaN, NaN, NaN, NaN, NaN, ...
    NaN, NaN, NaN, NaN, ...
    randomSeed, ...
    "failed", string(exception.identifier), message, "", ...
    VariableNames=emptyLoadTaskSummaryTable().Properties.VariableNames);

end
