function [summaryTable, figures] = ...
    run_phase2_4_utilization_sweep(options)
%RUN_PHASE2_4_UTILIZATION_SWEEP Sweep load-task execution time.
%
% Each simulation is saved immediately. The aggregate MAT and CSV files
% are also updated after every attempted point, so an interrupted sweep can
% be resumed without losing completed cases.

arguments
    options.ScenarioNames (1,:) string = [ ...
        "urban_profile", ...
        "aggressive_maneuver"]
    options.EnvironmentNames (1,:) string = [ ...
        "dry_road", ...
        "low_friction_road"]
    options.LoadExecutionTime_ms (1,:) double {mustBeNonnegative} = ...
        0:5:40
    options.RandomSeed (1,1) double = 1001
    options.Resume (1,1) logical = true
    options.ShowFigure (1,1) logical = true
end

startup_project;

projectRoot = string(matlab.project.currentProject().RootFolder);
aggregateFolder = fullfile( ...
    projectRoot, ...
    "phase2", ...
    "results", ...
    "phase2_4");

if ~isfolder(aggregateFolder)
    mkdir(aggregateFolder);
end

summaryFile = fullfile(aggregateFolder, "phase2_4_summary.mat");
summaryCsv = fullfile(aggregateFolder, "phase2_4_summary.csv");

summaryTable = emptySummaryTable();

if options.Resume && isfile(summaryFile)
    savedSummary = load(summaryFile, "summaryTable");
    if isfield(savedSummary, "summaryTable")
        summaryTable = savedSummary.summaryTable;
    end
end

numberOfCases = ...
    numel(options.ScenarioNames) ...
    * numel(options.EnvironmentNames) ...
    * numel(options.LoadExecutionTime_ms);

caseNumber = 0;

for scenarioName = options.ScenarioNames
    for environmentName = options.EnvironmentNames
        for loadExecutionTime_ms = options.LoadExecutionTime_ms

            caseNumber = caseNumber + 1;

            if options.Resume && isCompleted( ...
                    summaryTable, ...
                    scenarioName, ...
                    environmentName, ...
                    loadExecutionTime_ms)
                fprintf( ...
                    "[%d/%d] Skipping completed case: %s | %s | %.3f ms\n", ...
                    caseNumber, ...
                    numberOfCases, ...
                    scenarioName, ...
                    environmentName, ...
                    loadExecutionTime_ms);
                continue;
            end

            fprintf( ...
                "\n[%d/%d] %s | %s | load %.3f ms\n", ...
                caseNumber, ...
                numberOfCases, ...
                scenarioName, ...
                environmentName, ...
                loadExecutionTime_ms);

            try
                [~, newRow] = run_phase2_4_case( ...
                    scenarioName, ...
                    environmentName, ...
                    loadExecutionTime_ms, ...
                    RandomSeed=options.RandomSeed, ...
                    SaveResults=true);
            catch exception
                warning( ...
                    "SDV:Phase2_4CaseFailed", ...
                    "Phase 2.4 case failed: %s", ...
                    exception.message);

                newRow = failureRow( ...
                    scenarioName, ...
                    environmentName, ...
                    loadExecutionTime_ms, ...
                    options.RandomSeed, ...
                    exception);
            end

            summaryTable = removeExistingCase( ...
                summaryTable, ...
                scenarioName, ...
                environmentName, ...
                loadExecutionTime_ms);

            summaryTable = [summaryTable; newRow]; %#ok<AGROW>
            summaryTable = sortrows( ...
                summaryTable, ...
                ["Scenario", "Environment", "LoadExecution_ms"]);

            save(summaryFile, "summaryTable");
            writetable(summaryTable, summaryCsv);

            fprintf("Checkpoint saved: %s\n", summaryFile);
        end
    end
end

if options.ShowFigure
    figures = plot_phase2_4_utilization_sweep(summaryTable);
else
    figures = struct();
end

end


function summaryTable = emptySummaryTable()

summaryTable = table( ...
    strings(0,1), ...
    strings(0,1), ...
    zeros(0,1), ...
    zeros(0,1), ...
    zeros(0,1), ...
    zeros(0,1), ...
    zeros(0,1), ...
    zeros(0,1), ...
    zeros(0,1), ...
    zeros(0,1), ...
    zeros(0,1), ...
    zeros(0,1), ...
    zeros(0,1), ...
    zeros(0,1), ...
    zeros(0,1), ...
    strings(0,1), ...
    strings(0,1), ...
    strings(0,1), ...
    strings(0,1), ...
    VariableNames=[ ...
        "Scenario", ...
        "Environment", ...
        "LoadExecution_ms", ...
        "NominalUtilization", ...
        "SpeedRMS_mps", ...
        "LateralRMS_m", ...
        "HeadingRMS_deg", ...
        "ControlMeanResponse_ms", ...
        "ControlP95Response_ms", ...
        "ControlMaximumResponse_ms", ...
        "DeadlineMissCount", ...
        "DeadlineMissPercent", ...
        "ControlOverrunCount", ...
        "ControlDroppedJobs", ...
        "RandomSeed", ...
        "Status", ...
        "ErrorIdentifier", ...
        "ErrorMessage", ...
        "RunFile"]);

end


function tf = isCompleted(tableData, scenario, environment, load_ms)

if isempty(tableData)
    tf = false;
    return;
end

matching = ...
    tableData.Scenario == scenario ...
    & tableData.Environment == environment ...
    & abs(tableData.LoadExecution_ms - load_ms) < 1e-9 ...
    & tableData.Status == "completed";

tf = any(matching);

end


function tableData = removeExistingCase( ...
    tableData, ...
    scenario, ...
    environment, ...
    load_ms)

if isempty(tableData)
    return;
end

matching = ...
    tableData.Scenario == scenario ...
    & tableData.Environment == environment ...
    & abs(tableData.LoadExecution_ms - load_ms) < 1e-9;

tableData(matching,:) = [];

end


function row = failureRow( ...
    scenario, ...
    environment, ...
    load_ms, ...
    randomSeed, ...
    exception)

message = string(exception.message);
message = replace(message, newline, " ");

row = table( ...
    scenario, ...
    environment, ...
    load_ms, ...
    NaN, ...
    NaN, ...
    NaN, ...
    NaN, ...
    NaN, ...
    NaN, ...
    NaN, ...
    NaN, ...
    NaN, ...
    NaN, ...
    NaN, ...
    randomSeed, ...
    "failed", ...
    string(exception.identifier), ...
    message, ...
    "", ...
    VariableNames=emptySummaryTable().Properties.VariableNames);

end
