scenarios = [
    % sdv.enum.ScenarioName.urban_profile
    sdv.enum.ScenarioName.highway_cruise
    % sdv.enum.ScenarioName.aggressive_maneuver
    ];
environments = [
    sdv.enum.EnvironmentName.dry_road 
    % sdv.enum.EnvironmentName.low_friction_road
    ];
loads = [
    "off" 
    "maximum"
    ];

project = matlab.project.currentProject();
projectRoot = string(project.RootFolder);

figuresFolder = fullfile( ...
    projectRoot, ...
    "phase2", ...
    "figures", ...
    "phase2_3");

if ~isfolder(figuresFolder)
    mkdir(figuresFolder);
end

for i = 1:numel(scenarios)
    scenario = scenarios(i);
    for e = 1:numel(environments)
        environment = environments(e);
        for j = 1:numel(loads)
            loadCase = loads(j);
            [probeFigure, ~] = ...
                run_phase2_3_probe_fun( ...
                scenario, ...
                environment, ...
                loadCase, ...
                [5 40]);
            % 
            % sdv.io.exportFigure( ...
            %     probeFigure, ...
            %     figuresFolder, ...
            %     scenario + "_" + environment + "_" + loadCase);
            % close(probeFigure);

            [probeFigure, ~] = ...
                run_phase2_3_probe_fun( ...
                scenario, ...
                environment, ...
                loadCase, ...
                [39 40]);

            % sdv.io.exportFigure( ...
            %     probeFigure, ...
            %     figuresFolder, ...
            %     scenario + "_" + environment + "_" + loadCase + "39to40");

            % [probeFigure, probeData] = ...
            %     run_phase2_3_probe_fun( ...
            %     scenario, ...
            %     environment, ...
            %     loadCase, ...
            %     [10 15]);
            % 
            % sdv.io.exportFigure( ...
            %     probeFigure, ...
            %     figuresFolder, ...
            %     scenario + "_" + environment + "_" + loadCase + "10to15");
            % close(probeFigure);

            fprintf("Processing scenario: %s, load: %s\n", scenario, loadCase);
            % ----------------------------------------------------------------
        end
    end
    %% break, if you want only one scenario
end





function [figureHandle, probeData] = ...
    run_phase2_3_probe_fun( ...
    scenarioName, ...
    environmentName, ...
    loadCase, ...
    window_s)

arguments
    scenarioName (1,1) string
    environmentName (1,1) string
    loadCase (1,1) string
    window_s (1,2) double
end

assert(window_s(1) < window_s(2), ...
    "window_s must be [startTime endTime].");

project = matlab.project.currentProject();
projectRoot = string(project.RootFolder);

runFile = fullfile( ...
    projectRoot, ...
    "phase2", ...
    "results", ...
    "phase2_3", ...
    scenarioName, ...
    environmentName, ...
    loadCase, ...
    "run_data.mat");

assert(isfile(runFile), ...
    "Saved Phase 2.3 run was not found:\n%s", ...
    runFile);

savedRun = load(runFile,"runArtifact");
assert(isfield(savedRun,"runArtifact"), ...
    "Saved file does not contain runArtifact: %s", ...
    runFile);

runArtifact = savedRun.runArtifact;

requiredArtifactFields = [ ...
    "results", ...
    "reference", ...
    "taskData", ...
    "scenarioName", ...
    "environmentName", ...
    "loadCase"];

assert(all(isfield(runArtifact,requiredArtifactFields)), ...
    "runArtifact does not satisfy the Phase 2.3 probe schema.");

availableWindow_s = [ ...
    min(runArtifact.results.time_s), ...
    max(runArtifact.results.time_s)];

assert( ...
    window_s(1) >= availableWindow_s(1) && ...
    window_s(2) <= availableWindow_s(2), ...
    "Requested window [%.6f, %.6f] s is outside the saved " + ...
    "interval [%.6f, %.6f] s.", ...
    window_s(1), ...
    window_s(2), ...
    availableWindow_s(1), ...
    availableWindow_s(2));

fprintf( ...
    "Probing saved Phase 2.3 run between %.6f and %.6f seconds.\n", ...
    window_s(1), ...
    window_s(2));

[figureHandle, probeData] = ...
    plot_phase2_3_probe( ...
    runArtifact.results, ...
    runArtifact.reference, ...
    runArtifact.taskData, ...
    window_s, ...
    runArtifact.scenarioName, ...
    runArtifact.environmentName, ...
    runArtifact.loadCase);

end
