%% Rebuild sampling-jitter sweep summary

startup_project;

projectRoot = string( ...
    matlab.project.currentProject().RootFolder);

sourceRoot = fullfile( ...
    projectRoot, ...
    "phase1", ...
    "results", ...
    "ACADOS_MPC", ...
    "sampling_jitter");

outputFolder = fullfile( ...
    projectRoot, ...
    "analysis", ...
    "phase1", ...
    "jitter");

if ~isfolder(outputFolder)
    mkdir(outputFolder);
end

%% Find all scenario result files

resultFiles = dir(fullfile( ...
    sourceRoot, ...
    "jitter_bound_*_ms", ...
    "seed_*", ...
    "*", ...
    "*", ...
    "*_results.mat"));

assert(~isempty(resultFiles), ...
    "No scenario result files were found.");

sweepSummary = table();

%% Process each saved simulation

for fileIndex = 1:numel(resultFiles)

    filePath = fullfile( ...
        resultFiles(fileIndex).folder, ...
        resultFiles(fileIndex).name);

    savedData = load(filePath, "results");

    assert(isfield(savedData, "results"), ...
        "Missing results struct in: %s", filePath);

    results = savedData.results;

    tracking = results.tracking_metrics;
    constraints = results.constraint_metrics;
    validation = results.jitter_validation;
    executionLog = results.controller_execution_log;
    metadata = results.metadata;

    %% Raw acados status

    rawStatus = executionLog.SolverStatus(:);

    rawStatus0Count = nnz(rawStatus == 0);
    rawStatus2Count = nnz(rawStatus == 2);
    rawStatus4Count = nnz(rawStatus == 4);

    otherStatusCount = ...
        nnz(~ismember(rawStatus, [0 2 4]));

    %% Solve-time 95th percentile

    solveTime_ms = sort( ...
        1e3 * executionLog.SolveTime_s(:));

    percentileIndex = max( ...
        1, ...
        ceil(0.95 * numel(solveTime_ms)));

    solveTimeP95_ms = ...
        solveTime_ms(percentileIndex);

    %% Build one summary row

    newRow = table( ...
        string(metadata.scenario_name), ...
        string(metadata.environment_name), ...
        metadata.jitter_bound_ms, ...
        metadata.jitter_random_seed, ...
        metadata.simulation_step_s, ...
        validation.execution_count, ...
        tracking.speed_rmse_mps, ...
        tracking.lateral_rmse_m, ...
        tracking.heading_rmse_rad, ...
        validation.deadline_miss_count, ...
        true, ...
        tracking.speed_peak_mps, ...
        tracking.lateral_peak_m, ...
        tracking.heading_rmse_deg, ...
        tracking.heading_peak_deg, ...
        constraints.any_sample_count, ...
        constraints.event_count, ...
        constraints.duration_s, ...
        rawStatus0Count, ...
        rawStatus2Count, ...
        rawStatus4Count, ...
        otherStatusCount, ...
        solveTimeP95_ms, ...
        1e3 * validation.maximum_abs_actual_jitter_s, ...
        "", ...
        VariableNames=[ ...
            "ScenarioName", ...
            "EnvironmentName", ...
            "JitterBound_ms", ...
            "RandomSeed", ...
            "SimulationStep_s", ...
            "ExecutionCount", ...
            "SpeedRmse_mps", ...
            "LateralRmse_m", ...
            "HeadingRmse_rad", ...
            "DeadlineMissCount", ...
            "Completed", ...
            "SpeedPeak_mps", ...
            "LateralPeak_m", ...
            "HeadingRmse_deg", ...
            "HeadingPeak_deg", ...
            "ConstraintViolationSamples", ...
            "ConstraintEventCount", ...
            "ConstraintDuration_s", ...
            "RawStatus0Count", ...
            "RawStatus2Count", ...
            "RawStatus4Count", ...
            "OtherStatusCount", ...
            "SolveTimeP95_ms", ...
            "MaximumActualJitter_ms", ...
            "ErrorMessage"]);

    sweepSummary = [sweepSummary; newRow]; %#ok<AGROW>
end

%% Sort summary

sweepSummary = sortrows( ...
    sweepSummary, ...
    ["EnvironmentName", ...
     "ScenarioName", ...
     "JitterBound_ms", ...
     "RandomSeed"]);

%% Save MAT and CSV

matFile = fullfile( ...
    outputFolder, ...
    "sweep_summary.mat");

csvFile = fullfile( ...
    outputFolder, ...
    "sweep_summary.csv");

save(matFile, "sweepSummary");
writetable(sweepSummary, csvFile);

fprintf("\nRebuilt %d sampling-jitter rows.\n", ...
    height(sweepSummary));

fprintf("MAT file: %s\n", matFile);
fprintf("CSV file: %s\n", csvFile);