clear;
clc;

projectRoot = string( ...
    matlab.project.currentProject().RootFolder);

legacyResultsRoot = string( ...
    getenv("SDV_LEGACY_RESULTS_ROOT"));

if strlength(legacyResultsRoot) == 0
    legacyResultsRoot = fullfile( ...
        fileparts(projectRoot), ...
        "SDV_SIM_RESULTS");
end

tablePath1 = ...
    fullfile( ...
        legacyResultsRoot, ...
        "NEW_SIMULATION", ...
        "PHASE1", ...
        "RESULTS", ...
        "random_delay_sweep", ...
        "random_delay_summary.mat");

tablePath2 = ...
    fullfile( ...
        projectRoot, ...
        "phase1", ...
        "results", ...
        "ACADOS_MPC", ...
        "random_delay_sweep", ...
        "random_delay_summary.mat");

outputPath = ...
    fullfile( ...
        projectRoot, ...
        "analysis", ...
        "phase1", ...
        "random_delay_all_scenarios.mat");

randomDelayTable = joinTable( ...
    tablePath1, ...
    tablePath2, ...
    outputPath);
