clear;
clc;

tablePath1 = ...
    "C:\Users\rayyu\OneDrive\Desktop\UTD\SDV_SIM_RESULTS\NEW_SIMULATION\PHASE1\RESULTS\random_delay_sweep\random_delay_summary.mat";

tablePath2 = ...
    "C:\Users\rayyu\OneDrive\Desktop\UTD\SDV\phase1\results\ACADOS_MPC\random_delay_sweep\random_delay_summary.mat";

outputPath = ...
    "analysis/phase1/random_delay_all_scenarios.mat";

randomDelayTable = joinTable( ...
    tablePath1, ...
    tablePath2, ...
    outputPath);