data = load( ...
    "analysis/phase1/jitter/sweep_summary.mat");

sweepSummary = data.sweepSummary;

% [figureHandle, statistics] = ...
%     plotSamplingJitterSummary(sweepSummary);
% 

% [figureHandle, statistics] = ...
%     plotSamplingJitterSummary( ...
%     sweepSummary, ...
%     Panels=[ ...
%     "lateral_rmse", ...
%     "heading_rmse", ...
%     "solve_time_p95", ...
%     "actual_jitter"]);

[figureHandle, statistics] = ...
    plotSamplingJitterSummary( ...
    sweepSummary, ...
    IncludeScenarios=("highway_cruise"), ...
    Panels = ["actual_jitter","solve_time_p95"] ...
    );