function [figureHandle, probe] = plot_phase2_3_probe( ...
    results, reference, taskData, window_s, ...
    scenarioTitle, environmentTitle, loadCase)
%PLOT_PHASE2_3_PROBE Inspect scheduler events and control effects offline.

startup_project;

assert(window_s(1) < window_s(2), ...
    "window_s must be [startTime endTime].");

requiredResultFields = [ ...
    "time_s", ...
    "vx_mps", ...
    "vx_ref_mps", ...
    "ev_mps", ...
    "ey_m", ...
    "epsi_rad", ...
    "x_pos_m", ...
    "y_pos_m", ...
    "torque_Nm", ...
    "steering_angle_rad", ...
    "torque_applied_time_s", ...
    "torque_applied_Nm", ...
    "steering_applied_time_s", ...
    "steering_applied_angle_deg"];

missing = setdiff(requiredResultFields, string(fieldnames(results)));
disp('Missing fields: '); disp(missing);

assert(all(isfield(results,cellstr(requiredResultFields))), ...
    "Saved results do not satisfy the Phase 2.3 probe schema.");

time_s = toColumn(results.time_s);
controlMask = ...
    time_s >= window_s(1) & ...
    time_s <= window_s(2);

assert(any(controlMask), ...
    "No controller data exists inside the requested window.");

%% Extract only the requested interval

probe = struct();
probe.window_s = window_s;
probe.time_s = time_s(controlMask);
probe.vx_mps = toColumn(results.vx_mps(controlMask));
probe.vx_ref_mps = toColumn(results.vx_ref_mps(controlMask));
probe.ev_mps = toColumn(results.ev_mps(controlMask));
probe.ey_m = toColumn(results.ey_m(controlMask));
probe.epsi_rad = toColumn(results.epsi_rad(controlMask));
probe.x_pos_m = toColumn(results.x_pos_m(controlMask));
probe.y_pos_m = toColumn(results.y_pos_m(controlMask));
probe.torque_Nm = toColumn(results.torque_Nm(controlMask));
probe.steering_angle_rad = ...
    toColumn(results.steering_angle_rad(controlMask));

%% get only fraction of input data: for selected timeframe
[probe.torque_applied_time_s, probe.torque_applied_Nm] = ...
    selectWindow( ...
        results.torque_applied_time_s, ...
        results.torque_applied_Nm, ...
        window_s);

[probe.steering_applied_time_s, ...
    probe.steering_applied_angle_deg] = ...
    selectWindow( ...
        results.steering_applied_time_s, ...
        results.steering_applied_angle_deg, ...
        window_s);

%% ControlTask timing and stale-command exposure windows

taskNames = strings(numel(taskData),1);
for taskIndex = 1:numel(taskData)
    taskNames(taskIndex) = string(taskData(taskIndex).Name);
end

controlTaskIndex = find(taskNames == "ControlTask",1);
assert(~isempty(controlTaskIndex), ...
    "ControlTask was not found in taskData.");

controlTask = taskData(controlTaskIndex);
controlCompletionTime_s = sort(toColumn(controlTask.EndTime));

probe.eventWindows = buildExposureWindows( ...
    controlTask, ...
    window_s);

probe.command_hold_age_s = commandHoldAge( ...
    probe.time_s, ...
    controlCompletionTime_s, ...
    time_s(1));

%% Figure layout

scenarioLabel = replace(string(scenarioTitle),"_"," ");
environmentLabel = replace(string(environmentTitle),"_"," ");

figureHandle = figure( ...
    Name="Phase 2.3 scheduler-effect probe", ...
    Color="w", ...
    Position=[70 35 1500 1050]);

layout = tiledlayout(figureHandle,5,2);
layout.TileSpacing = "compact";
layout.Padding = "compact";

timeAxes = gobjects(7,1);

%% Command age and ControlTask events

schedulerAxes = nexttile(layout,[1 2]);
timeAxes(1) = schedulerAxes;

hold(schedulerAxes,"on");

plot( ...
    schedulerAxes, ...
    probe.time_s, ...
    1e3*probe.command_hold_age_s, ... % in ms
    LineWidth=1.3, ...
    DisplayName="Command hold age");

yline( ...
    schedulerAxes, ...
    10, ... % sampling period (fixed)
    "--", ...
    Color=[0.35 0.35 0.35], ...
    LineWidth=1.0, ...
    DisplayName="Control period");

completionInWindow_s = controlCompletionTime_s( ...
    controlCompletionTime_s >= window_s(1) & ...
    controlCompletionTime_s <= window_s(2));

plot( ...
    schedulerAxes, ...
    completionInWindow_s, ...
    zeros(size(completionInWindow_s)), ...
    LineStyle="none", ...
    Marker="|", ...
    MarkerSize=10, ...
    Color=[0.20 0.60 0.30], ...
    DisplayName="Control completion");

%% get drop time and overrun time: for selected time frame
overrunTime_s = windowEvents(controlTask.OverrunTime,window_s);
dropTime_s = windowEvents(controlTask.DropTime,window_s);

%check any infinite value
finiteAge_ms = 1e3*probe.command_hold_age_s( ...
    isfinite(probe.command_hold_age_s));

if isempty(finiteAge_ms)
    eventMarkerHeight_ms = 11;
else
    eventMarkerHeight_ms = 1.08*max([10; finiteAge_ms]);
end

scatter( ...
    schedulerAxes, ...
    overrunTime_s, ...
    eventMarkerHeight_ms*ones(size(overrunTime_s)), ...
    45, ...
    "^", ...
    MarkerEdgeColor=[0.85 0.52 0.05], ...
    LineWidth=1.2, ...
    DisplayName="Control overrun");

scatter( ...
    schedulerAxes, ...
    dropTime_s, ...
    eventMarkerHeight_ms*ones(size(dropTime_s)), ...
    55, ...
    "x", ...
    MarkerEdgeColor=[0.82 0.12 0.12], ...
    LineWidth=1.5, ...
    DisplayName="Control drop");

hold(schedulerAxes,"off");
grid(schedulerAxes,"on");
xlim(schedulerAxes,window_s);
ylim(schedulerAxes,[0 1.16*max(1,eventMarkerHeight_ms)]);
xlabel(schedulerAxes,"Time (s)");
ylabel(schedulerAxes,"Age (ms)");
title(schedulerAxes,"Command hold age and Control Task events");
legend(schedulerAxes,Location="bestoutside");

shadeExposureWindows(schedulerAxes,probe.eventWindows);

%% Computed and plant-applied torque

torqueAxes = nexttile(layout);
timeAxes(2) = torqueAxes;

stairs( ...
    torqueAxes, ...
    probe.time_s, ...
    probe.torque_Nm * 0.5, ... %% since 0.5 is gain applied for plant
    "--", ...
    LineWidth=1.1, ...
    DisplayName="Controller-computed");

hold(torqueAxes,"on");

stairs( ...
    torqueAxes, ...
    probe.torque_applied_time_s, ...
    probe.torque_applied_Nm, ...
    LineWidth=1.5, ...
    DisplayName="Plant-applied");

hold(torqueAxes,"off");
grid(torqueAxes,"on");
xlim(torqueAxes,window_s);
xlabel(torqueAxes,"Time (s)");
ylabel(torqueAxes,"Torque (N·m)");
title(torqueAxes,"Torque publication and hold");
legend(torqueAxes,Location="best");

shadeExposureWindows(torqueAxes,probe.eventWindows);

%% Computed and plant-applied steering

steeringAxes = nexttile(layout);
timeAxes(3) = steeringAxes;

stairs( ...
    steeringAxes, ...
    probe.time_s, ...
    rad2deg(probe.steering_angle_rad), ...
    "--", ...
    LineWidth=1.1, ...
    DisplayName="Controller-computed");

hold(steeringAxes,"on");

stairs( ...
    steeringAxes, ...
    probe.steering_applied_time_s, ...
    (probe.steering_applied_angle_deg)/24, ...
    LineWidth=1.5, ...
    DisplayName="Steering-applied");

hold(steeringAxes,"off");
grid(steeringAxes,"on");
xlim(steeringAxes,window_s);
xlabel(steeringAxes,"Time (s)");
ylabel(steeringAxes,"Steering angle (deg)");
title(steeringAxes,"Steering publication and hold");
legend(steeringAxes,Location="bestoutside");

shadeExposureWindows(steeringAxes,probe.eventWindows);

%% Longitudinal state and tracking error

longitudinalAxes = nexttile(layout);
timeAxes(4) = longitudinalAxes;

yyaxis(longitudinalAxes,"left");

plot( ...
    longitudinalAxes, ...
    probe.time_s, ...
    probe.vx_mps, ...
    LineWidth=1.2, ...
    DisplayName="Measured speed");

hold(longitudinalAxes,"on");

plot( ...
    longitudinalAxes, ...
    probe.time_s, ...
    probe.vx_ref_mps, ...
    "--", ...
    LineWidth=1.1, ...
    DisplayName="Reference speed");

ylabel(longitudinalAxes,"Speed (m/s)");

yyaxis(longitudinalAxes,"right");

plot( ...
    longitudinalAxes, ...
    probe.time_s, ...
    probe.ev_mps, ...
    LineWidth=1.1, ...
    DisplayName="Speed error");

yline(longitudinalAxes,0,":",HandleVisibility="off");
ylabel(longitudinalAxes,"e_v (m/s)");

hold(longitudinalAxes,"off");
grid(longitudinalAxes,"on");
xlim(longitudinalAxes,window_s);
xlabel(longitudinalAxes,"Time (s)");
title(longitudinalAxes,"Longitudinal response");
legend(longitudinalAxes,Location="best");

yyaxis(longitudinalAxes,"left");
shadeExposureWindows(longitudinalAxes,probe.eventWindows);

%% Lateral and heading tracking errors

lateralAxes = nexttile(layout);
timeAxes(5) = lateralAxes;

yyaxis(lateralAxes,"left");

plot( ...
    lateralAxes, ...
    probe.time_s, ...
    probe.ey_m, ...
    LineWidth=1.2, ...
    DisplayName="Lateral error");

yline(lateralAxes,0,":",HandleVisibility="off");
ylabel(lateralAxes,"e_y (m)");

hold(lateralAxes,"on");
yyaxis(lateralAxes,"right");

plot( ...
    lateralAxes, ...
    probe.time_s, ...
    rad2deg(probe.epsi_rad), ...
    LineWidth=1.2, ...
    DisplayName="Heading error");

yline(lateralAxes,0,":",HandleVisibility="off");
ylabel(lateralAxes,"e_ψ (deg)");

hold(lateralAxes,"off");
grid(lateralAxes,"on");
xlim(lateralAxes,window_s);
xlabel(lateralAxes,"Time (s)");
title(lateralAxes,"Lateral tracking response");
legend(lateralAxes,Location="bestoutside");

yyaxis(lateralAxes,"left");
shadeExposureWindows(lateralAxes,probe.eventWindows);

%% Completed-job response times

responseAxes = nexttile(layout);
timeAxes(6) = responseAxes;

hold(responseAxes,"on");
taskColors = lines(numel(taskData));
hasResponseData = false;

for taskIndex = 1:numel(taskData)

    completionTime_s = toColumn(taskData(taskIndex).EndTime);
    responseTime_ms = 1e3*toColumn(taskData(taskIndex).Turnaround);

    sampleCount = min( ...
        numel(completionTime_s), ...
        numel(responseTime_ms));

    completionTime_s = completionTime_s(1:sampleCount);
    responseTime_ms = responseTime_ms(1:sampleCount);

    mask = ...
        completionTime_s >= window_s(1) & ...
        completionTime_s <= window_s(2);

    if any(mask)
        hasResponseData = true;

        plot( ...
            responseAxes, ...
            completionTime_s(mask), ...
            responseTime_ms(mask), ...
            ".-", ...
            Color=taskColors(taskIndex,:), ...
            LineWidth=1.0, ...
            MarkerSize=10, ...
            DisplayName=taskNames(taskIndex));
    end
end

hold(responseAxes,"off");
grid(responseAxes,"on");
xlim(responseAxes,window_s);
xlabel(responseAxes,"Completion time (s)");
ylabel(responseAxes,"Response time (ms)");
title(responseAxes,"Completed-job response time");

if hasResponseData
    legend(responseAxes,Location="best");
end

shadeExposureWindows(responseAxes,probe.eventWindows);

%% Dropped and overrun releases for all tasks

eventAxes = nexttile(layout);
timeAxes(7) = eventAxes;

hold(eventAxes,"on");

dropLegend = scatter( ...
    eventAxes,nan,nan,55,"x", ...
    MarkerEdgeColor=[0.82 0.12 0.12], ...
    LineWidth=1.5, ...
    DisplayName="Dropped");

overrunLegend = scatter( ...
    eventAxes,nan,nan,45,"^", ...
    MarkerEdgeColor=[0.85 0.52 0.05], ...
    LineWidth=1.2, ...
    DisplayName="Overrun");

for taskIndex = 1:numel(taskData)

    droppedTime_s = windowEvents( ...
        taskData(taskIndex).DropTime,window_s);

    taskOverrunTime_s = windowEvents( ...
        taskData(taskIndex).OverrunTime,window_s);

    scatter( ...
        eventAxes, ...
        droppedTime_s, ...
        taskIndex*ones(size(droppedTime_s)), ...
        55,"x", ...
        MarkerEdgeColor=[0.82 0.12 0.12], ...
        LineWidth=1.5, ...
        HandleVisibility="off");

    scatter( ...
        eventAxes, ...
        taskOverrunTime_s, ...
        taskIndex*ones(size(taskOverrunTime_s)), ...
        45,"^", ...
        MarkerEdgeColor=[0.85 0.52 0.05], ...
        LineWidth=1.2, ...
        HandleVisibility="off");
end

hold(eventAxes,"off");
grid(eventAxes,"on");
xlim(eventAxes,window_s);
ylim(eventAxes,[0.5 numel(taskData)+0.5]);
yticks(eventAxes,1:numel(taskData));
yticklabels(eventAxes,taskNames);
xlabel(eventAxes,"Time (s)");
ylabel(eventAxes,"Task");
title(eventAxes,"Scheduler events for all tasks");
legend(eventAxes,[dropLegend overrunLegend],Location="bestoutside");

shadeExposureWindows(eventAxes,probe.eventWindows);

%% Local trajectory colored by ControlTask exposure

trajectoryAxes = nexttile(layout,[1 2]);

referenceMask = localReferenceMask( ...
    reference, ...
    probe.x_pos_m, ...
    probe.y_pos_m);

plot( ...
    trajectoryAxes, ...
    reference(referenceMask,2), ...
    reference(referenceMask,3), ...
    "--", ...
    Color=[0.35 0.35 0.35], ...
    LineWidth=1.1, ...
    DisplayName="Reference path");

hold(trajectoryAxes,"on");

plotTrajectoryByExposure( ...
    trajectoryAxes, ...
    probe, ...
    probe.eventWindows);

hold(trajectoryAxes,"off");
axis(trajectoryAxes,"equal");
grid(trajectoryAxes,"on");
xlabel(trajectoryAxes,"X (m)");
ylabel(trajectoryAxes,"Y (m)");
title(trajectoryAxes,"Local trajectory by scheduler exposure");
legend(trajectoryAxes,Location="bestoutside");

%% Align all time-domain views

linkaxes(timeAxes,"x");
xlim(timeAxes(1),window_s);

title( ...
    layout, ...
    sprintf( ...
        "Phase 2.3 Probe: %.4f–%.4f s — %s — %s — %s", ...
        window_s(1), ...
        window_s(2), ...
        scenarioLabel, ...
        environmentLabel, ...
        string(loadCase)));

end

%% for input command: get fraction of data from results for analysis
function [selectedTime_s, selectedData] = ...
    selectWindow(time_s,data,window_s)

time_s = toColumn(time_s);
data = toColumn(data);

sampleCount = min(numel(time_s),numel(data));
time_s = time_s(1:sampleCount);
data = data(1:sampleCount);

mask = ...
    time_s >= window_s(1) & ...
    time_s <= window_s(2);

selectedTime_s = time_s(mask);
selectedData = data(mask);

end

function values = toColumn(values)

values = reshape(squeeze(double(values)),[],1);

end

function eventTime_s = windowEvents(eventTime_s,window_s)

eventTime_s = toColumn(eventTime_s);
eventTime_s = eventTime_s( ...
    eventTime_s >= window_s(1) & ...
    eventTime_s <= window_s(2));

end

function eventWindows = ...
    buildExposureWindows(controlTask,window_s)

completionTime_s = sort(toColumn(controlTask.EndTime));
overrunTime_s = toColumn(controlTask.OverrunTime);
dropTime_s = toColumn(controlTask.DropTime);

eventTime_s = [overrunTime_s; dropTime_s];
eventType = [ ...
    repmat("Overrun",numel(overrunTime_s),1); ...
    repmat("Drop",numel(dropTime_s),1)];

startTime_s = zeros(0,1);
endTime_s = zeros(0,1);
windowType = strings(0,1);

for eventIndex = 1:numel(eventTime_s)

    eventTime = eventTime_s(eventIndex);

    if eventTime > window_s(2)
        continue;
    end

    nextCompletionIndex = find( ...
        completionTime_s > eventTime,1,"first");

    if isempty(nextCompletionIndex)
        recoveryTime = window_s(2);
    else
        recoveryTime = completionTime_s(nextCompletionIndex);
    end

    clippedStart = max(eventTime,window_s(1));
    clippedEnd = min(recoveryTime,window_s(2));

    if clippedEnd > clippedStart
        startTime_s(end+1,1) = clippedStart; %#ok<AGROW>
        endTime_s(end+1,1) = clippedEnd; %#ok<AGROW>
        windowType(end+1,1) = eventType(eventIndex); %#ok<AGROW>
    end
end

eventWindows = table( ...
    startTime_s, ...
    endTime_s, ...
    windowType, ...
    VariableNames=["StartTime_s","EndTime_s","Type"]);

eventWindows = mergeExposureWindows(eventWindows);

end

function mergedWindows = mergeExposureWindows(eventWindows)

mergedWindows = table( ...
    zeros(0,1), ...
    zeros(0,1), ...
    strings(0,1), ...
    VariableNames=["StartTime_s","EndTime_s","Type"]);

for eventType = ["Overrun","Drop"]

    rows = eventWindows(eventWindows.Type == eventType,:);

    if isempty(rows)
        continue;
    end

    rows = sortrows(rows,"StartTime_s");
    mergedStart = rows.StartTime_s(1);
    mergedEnd = rows.EndTime_s(1);

    for rowIndex = 2:height(rows)

        if rows.StartTime_s(rowIndex) <= mergedEnd
            mergedEnd = max(mergedEnd,rows.EndTime_s(rowIndex));
        else
            mergedWindows(end+1,:) = { ...
                mergedStart,mergedEnd,eventType}; %#ok<AGROW>

            mergedStart = rows.StartTime_s(rowIndex);
            mergedEnd = rows.EndTime_s(rowIndex);
        end
    end

    mergedWindows(end+1,:) = { ...
        mergedStart,mergedEnd,eventType}; %#ok<AGROW>
end

if ~isempty(mergedWindows)
    mergedWindows = sortrows(mergedWindows,"StartTime_s");
end

end

function commandAge_s = ...
    commandHoldAge(sampleTime_s,completionTime_s,initialTime_s)

publicationTime_s = unique([ ...
    initialTime_s; ...
    toColumn(completionTime_s)]);

commandAge_s = nan(size(sampleTime_s));

for sampleIndex = 1:numel(sampleTime_s)

    previousPublicationIndex = find( ...
        publicationTime_s <= sampleTime_s(sampleIndex), ...
        1,"last");

    if ~isempty(previousPublicationIndex)
        commandAge_s(sampleIndex) = ...
            sampleTime_s(sampleIndex) - ...
            publicationTime_s(previousPublicationIndex);
    end
end

end

function shadeExposureWindows(axesHandle,eventWindows)

if isempty(eventWindows)
    return;
end

originalHoldState = ishold(axesHandle);
hold(axesHandle,"on");

for eventType = ["Overrun","Drop"]

    rows = eventWindows(eventWindows.Type == eventType,:);

    if eventType == "Overrun"
        regionColor = [1.00 0.72 0.15];
        regionAlpha = 0.10;
    else
        regionColor = [0.92 0.20 0.20];
        regionAlpha = 0.12;
    end

    for rowIndex = 1:height(rows)

        x1 = rows.StartTime_s(rowIndex);
        x2 = rows.EndTime_s(rowIndex);

        region = xregion( ...
            axesHandle, ...
            x1, ...
            x2, ...
            FaceColor=regionColor, ...
            FaceAlpha=regionAlpha, ...
            EdgeAlpha=0, ...
            LineStyle="none");

        region.HandleVisibility = "off";
    end
end

if ~originalHoldState
    hold(axesHandle,"off");
end

end

function referenceMask = ...
    localReferenceMask(reference,xPosition_m,yPosition_m)

assert(isnumeric(reference) && size(reference,2) >= 3, ...
    "reference must contain at least station, X, and Y columns.");

xMinimum = min(xPosition_m);
xMaximum = max(xPosition_m);
yMinimum = min(yPosition_m);
yMaximum = max(yPosition_m);

margin_m = max(5,0.25*max( ...
    xMaximum-xMinimum, ...
    yMaximum-yMinimum));

referenceMask = ...
    reference(:,2) >= xMinimum-margin_m & ...
    reference(:,2) <= xMaximum+margin_m & ...
    reference(:,3) >= yMinimum-margin_m & ...
    reference(:,3) <= yMaximum+margin_m;

if ~any(referenceMask)
    referenceMask = true(size(reference,1),1);
end

end

function plotTrajectoryByExposure(axesHandle,probe,eventWindows)

statusCode = ones(numel(probe.time_s),1);

for rowIndex = 1:height(eventWindows)

    mask = ...
        probe.time_s >= eventWindows.StartTime_s(rowIndex) & ...
        probe.time_s <= eventWindows.EndTime_s(rowIndex);

    if eventWindows.Type(rowIndex) == "Overrun"
        statusCode(mask) = max(statusCode(mask),2);
    else
        statusCode(mask) = 3;
    end
end

statusNames = ["Normal","Overrun exposure","Drop exposure"];
statusColors = [ ...
    0.00 0.45 0.74; ...
    0.85 0.52 0.05; ...
    0.82 0.12 0.12];

for statusIndex = 1:3
    plot( ...
        axesHandle,nan,nan, ...
        Color=statusColors(statusIndex,:), ...
        LineWidth=2.0, ...
        DisplayName=statusNames(statusIndex));
end

segmentStart = [ ...
    1; ...
    find(diff(statusCode) ~= 0)+1];

segmentEnd = [ ...
    segmentStart(2:end)-1; ...
    numel(statusCode)];

for segmentIndex = 1:numel(segmentStart)

    firstIndex = segmentStart(segmentIndex);
    lastIndex = segmentEnd(segmentIndex);

    if firstIndex > 1
        firstIndex = firstIndex-1;
    end

    segmentStatus = statusCode(segmentStart(segmentIndex));

    plot( ...
        axesHandle, ...
        probe.x_pos_m(firstIndex:lastIndex), ...
        probe.y_pos_m(firstIndex:lastIndex), ...
        Color=statusColors(segmentStatus,:), ...
        LineWidth=2.0, ...
        HandleVisibility="off");
end

end
