function [figureHandle, probeData] = ...
    run_phase2_4_probe( ...
    scenarioName, ...
    environmentName, ...
    loadExecutionTime_ms, ...
    window_s)

%% example usage
% [probeFigure, probeData] = ...
%     run_phase2_4_probe( ...
%     "urban_profile", ...
%     "dry_road", ...
%     25, ...
%     [20 25]);

arguments
    scenarioName (1,1) string
    environmentName (1,1) string
    loadExecutionTime_ms (1,1) double ...
        {mustBeNonnegative}
    window_s (1,2) double
end

assert(window_s(1) < window_s(2), ...
    "window_s must be [startTime endTime].");

projectRoot = string( ...
    matlab.project.currentProject().RootFolder);

caseFolder = phase2_4_case_folder( ...
    projectRoot, ...
    scenarioName, ...
    environmentName, ...
    loadExecutionTime_ms);

runFile = fullfile( ...
    caseFolder, ...
    "run_data.mat");

assert(isfile(runFile), ...
    "Saved Phase 2.4 run was not found:\n%s", ...
    runFile);

savedRun = load( ...
    runFile, ...
    "runArtifact");

assert(isfield(savedRun, "runArtifact"), ...
    "File does not contain runArtifact:\n%s", ...
    runFile);

runArtifact = savedRun.runArtifact;

availableWindow_s = [
    min(runArtifact.results.time_s)
    max(runArtifact.results.time_s)
    ].';

assert( ...
    window_s(1) >= availableWindow_s(1) ...
    && window_s(2) <= availableWindow_s(2), ...
    "Requested window is outside [%.6f, %.6f] s.", ...
    availableWindow_s(1), ...
    availableWindow_s(2));

loadLabel = sprintf( ...
    "load %.3f ms", ...
    loadExecutionTime_ms);

[figureHandle, probeData] = ...
    plot_phase2_3_probe( ...
    runArtifact.results, ...
    runArtifact.reference, ...
    runArtifact.taskData, ...
    window_s, ...
    runArtifact.scenarioName, ...
    runArtifact.environmentName, ...
    string(loadLabel));

end