function metrics = computeDelayResidual( ...
    commandTime_s, commandData, ...
    appliedTime_s, appliedData, ...
    delayTime_s, delayData_s, options)
%COMPUTEDELAYRESIDUAL Validate y(t) = u(t - delay(t)).

arguments
    commandTime_s (:,1) double
    commandData (:,1) double
    appliedTime_s (:,1) double
    appliedData (:,1) double
    delayTime_s (:,1) double
    delayData_s (:,1) double
    options.AbsoluteTolerance (1,1) double ...
        {mustBeNonnegative} = 1e-8
    options.RelativeTolerance (1,1) double ...
        {mustBeNonnegative} = 1e-6
end

assert(numel(commandTime_s) == numel(commandData), ...
    "Command time and data must have equal lengths.");
assert(numel(appliedTime_s) == numel(appliedData), ...
    "Applied time and data must have equal lengths.");
assert(numel(delayTime_s) == numel(delayData_s), ...
    "Delay time and data must have equal lengths.");

assert(~isempty(commandTime_s) && ~isempty(appliedTime_s), ...
    "Command and applied signals cannot be empty.");
assert(~isempty(delayTime_s), ...
    "Delay profile cannot be empty.");

assert(all(isfinite([ ...
    commandTime_s; commandData; ...
    appliedTime_s; appliedData; ...
    delayTime_s; delayData_s])), ...
    "Delay-validation inputs contain NaN or Inf values.");
assert(all(diff(commandTime_s) > 0), ...
    "Command times must be strictly increasing.");
assert(all(diff(appliedTime_s) > 0), ...
    "Applied times must be strictly increasing.");
assert(all(diff(delayTime_s) > 0), ...
    "Delay-profile times must be strictly increasing.");
assert(all(delayData_s >= 0), ...
    "Delay values must be nonnegative.");

delayAtAppliedTime_s = interp1( ...
    delayTime_s, delayData_s, appliedTime_s, ...
    "previous", "extrap");

commandQueryTime_s = ...
    appliedTime_s - delayAtAppliedTime_s;

validSamples = ...
    commandQueryTime_s >= commandTime_s(1) & ...
    commandQueryTime_s <= commandTime_s(end);

assert(any(validSamples), ...
    "No samples remain after excluding the initial delay interval.");

expectedData = interp1( ...
    commandTime_s, commandData, ...
    commandQueryTime_s(validSamples), ...
    "previous");

residual = ...
    appliedData(validSamples) - expectedData;

signalScale = max(1, max(abs(expectedData)));
tolerance = ...
    options.AbsoluteTolerance + ...
    options.RelativeTolerance * signalScale;

metrics = struct();
metrics.available = true;
metrics.valid_sample_count = nnz(validSamples);
metrics.excluded_sample_count = nnz(~validSamples);
metrics.rmse = sqrt(mean(residual.^2));
metrics.mean_absolute = mean(abs(residual));
metrics.maximum_absolute = max(abs(residual));
metrics.signal_scale = signalScale;
metrics.normalized_rmse = metrics.rmse / signalScale;
metrics.tolerance = tolerance;
metrics.within_tolerance = ...
    metrics.maximum_absolute <= tolerance;
metrics.delay_minimum_s = min(delayAtAppliedTime_s(validSamples));
metrics.delay_mean_s = mean(delayAtAppliedTime_s(validSamples));
metrics.delay_maximum_s = max(delayAtAppliedTime_s(validSamples));

end
