function validation = validateActuationDelay( ...
    results, runConfig, controllerParams)
%VALIDATEACTUATIONDELAY Check commanded-to-applied signal timing.

validation = struct();
validation.available = false;
validation.passed = false;

if runConfig.phase_name ~= "phase1"
    return;
end

requiredFields = [ ...
    "torque_command_time_s"
    "torque_command_Nm"
    "torque_applied_time_s"
    "torque_applied_Nm"
    "steering_command_time_s"
    "steering_command_angle_rad"
    "steering_applied_time_s"
    "steering_applied_angle_rad"
    ];

missingFields = setdiff( ...
    requiredFields, string(fieldnames(results)));

assert(isempty(missingFields), ...
    "Missing delay-validation result fields: %s", ...
    strjoin(missingFields, ", "));

[delayTime_s, delayData_s, modeName] = ...
    resolveDelayProfile(runConfig, controllerParams, results);

validation.available = true;
validation.mode = modeName;

validation.torque = sdv.timing.computeDelayResidual( ...
    results.torque_command_time_s, ...
    results.torque_command_Nm, ...
    results.torque_applied_time_s, ...
    results.torque_applied_Nm, ...
    delayTime_s, delayData_s);

validation.steering = sdv.timing.computeDelayResidual( ...
    results.steering_command_time_s, ...
    results.steering_command_angle_rad, ...
    results.steering_applied_time_s, ...
    results.steering_applied_angle_rad, ...
    delayTime_s, delayData_s);

validation.passed = ...
    validation.torque.within_tolerance && ...
    validation.steering.within_tolerance;

end

function [delayTime_s, delayData_s, modeName] = ...
    resolveDelayProfile(runConfig, controllerParams, results)
%RESOLVEDELAYPROFILE Convert either delay mode to one ZOH profile.

if runConfig.delay_mode == ...
        controllerParams.DELAY_MODE_RANDOM

    delayProfile = runConfig.random_delay_profile;

    assert(isa(delayProfile, "timeseries"), ...
        "Random-delay validation requires a timeseries profile.");

    delayTime_s = reshape( ...
        squeeze(double(delayProfile.Time)), [], 1);
    delayData_s = reshape( ...
        squeeze(double(delayProfile.Data)), [], 1);
    modeName = "random";

elseif runConfig.delay_mode == ...
        controllerParams.DELAY_MODE_CONSTANT

    finalTime_s = max([ ...
        results.torque_applied_time_s(end), ...
        results.steering_applied_time_s(end)]);

    delayTime_s = [0; max(finalTime_s, eps)];
    delayData_s = ...
        runConfig.actuation_delay_s * ones(2, 1);
    modeName = "constant";

else
    error( ...
        "SDV:UnknownDelayMode", ...
        "Unsupported delay mode ID: %g", ...
        runConfig.delay_mode);
end

end
