projectRoot = string( ...
    matlab.project.currentProject().RootFolder);

outputFile = fullfile( ...
    projectRoot, ...
    "phase0", ...
    "results", ...
    "ACADOS_MPC", ...
    "solve_time_boxplot_ts_10ms.png");

[solveTimeFigure, solveTimeSummary] = ...
    plot_solve_time_box_plot( ...
    Deadline_ms=10, ...
    SaveFile=outputFile, ...
    ShowFigure=true);

disp(solveTimeSummary);