function figureHandle = ...
    plot_critical_delay_mode(delayStability)
%PLOT_CRITICAL_DELAY_MODE Show only the stability-critical mode.

data = delayStability.table;

delay_ms = data.Delay_ms;
spectralRadius = data.SpectralRadius;

dominantEigenvalue = complex( ...
    data.DominantEigenvalueReal, ...
    data.DominantEigenvalueImag);

stabilityMargin = ...
    1 - spectralRadius;

figureHandle = figure( ...
    Name="Critical delayed closed-loop mode", ...
    Color="white");

layout = tiledlayout(2,1);
layout.TileSpacing = "compact";
layout.Padding = "compact";

%% Spectral radius

nexttile;

plot( ...
    delay_ms, ...
    spectralRadius, ...
    "o-", ...
    LineWidth=1.4, ...
    MarkerSize=5);

hold on;

yline( ...
    1, ...
    "r--", ...
    "Stability boundary", ...
    LineWidth=1.3);

hold off;
grid on;

xlabel("Delay (ms)");
ylabel("Spectral radius");
title("Dominant Closed-Loop Pole Magnitude");

%% Stability margin

nexttile;

plot( ...
    delay_ms, ...
    stabilityMargin, ...
    "o-", ...
    LineWidth=1.4, ...
    MarkerSize=5);

hold on;

yline( ...
    0, ...
    "r--", ...
    "Loss of stability", ...
    LineWidth=1.3);

hold off;
grid on;

xlabel("Delay (ms)");
ylabel("Stability margin, 1-\rho");
title("Closed-Loop Stability Margin");

end