function [runSummary, figureHandle] = ...
    plot_sampling_jitter_errors( ...
        scenarioName, ...
        environmentName, ...
        jitterBounds_ms, ...
        seeds)
%PLOT_SAMPLING_JITTER_ERRORS Plot e_y and e_psi for jitter runs.
%
% Example:
  % [summary, fig] = plot_sampling_jitter_errors( ...
  %     "highway_cruise", ...
  %     "dry_road", ...
  %     1:8, ...
  %     1:20);

arguments
    scenarioName (1,1) string = "highway_cruise"
    environmentName (1,1) string = "dry_road"
    jitterBounds_ms (1,:) double = 1:8
    seeds (1,:) double = 1:20
end

%% Results location

projectRoot = string( ...
    matlab.project.currentProject().RootFolder);

resultsRoot = fullfile( ...
    projectRoot, ...
    "phase1", ...
    "results", ...
    "ACADOS_MPC", ...
    "sampling_jitter");

%% Storage

runs = struct( ...
    'time_s', {}, ...
    'ey_m', {}, ...
    'epsi_rad', {}, ...
    'jitterBound_ms', {}, ...
    'seed', {}, ...
    'lateralViolation', {}, ...
    'headingViolation', {}, ...
    'anyViolation', {});

jitterColumn = [];
seedColumn = [];
lateralViolationColumn = [];
headingViolationColumn = [];
anyViolationColumn = [];
maximumEyColumn = [];
maximumEpsiColumn = [];
resultFileColumn = strings(0,1);

lateralLimit_m = [];
headingLimit_rad = [];

runCount = 0;
missingCount = 0;

%% Load all requested runs

for jitterBound_ms = jitterBounds_ms

    jitterFolder = sprintf( ...
        "jitter_bound_%g_ms", ...
        jitterBound_ms);

    for seed = seeds

        seedFolder = sprintf("seed_%d", seed);

        resultFile = fullfile( ...
            resultsRoot, ...
            jitterFolder, ...
            seedFolder, ...
            scenarioName, ...
            environmentName, ...
            scenarioName + "_results.mat");

        if ~isfile(resultFile)
            missingCount = missingCount + 1;
            continue;
        end

        savedData = load( ...
            resultFile, ...
            "results", ...
            "config");

        results = savedData.results;

        % Read constraint limits from the first available result.
        if isempty(lateralLimit_m)
            lateralLimit_m = ...
                savedData.config.controller.maximumLateralError_m;

            headingLimit_rad = ...
                savedData.config.controller.maximumHeadingError_rad;
        end

        time_s = results.time_s(:);
        ey_m = results.ey_m(:);
        epsi_rad = results.epsi_rad(:);

        % Protect against slightly different logged lengths.
        numberOfSamples = min([ ...
            numel(time_s), ...
            numel(ey_m), ...
            numel(epsi_rad)]);

        time_s = time_s(1:numberOfSamples);
        ey_m = ey_m(1:numberOfSamples);
        epsi_rad = epsi_rad(1:numberOfSamples);

        lateralViolation = ...
            any(abs(ey_m) > lateralLimit_m) || ...
            any(~isfinite(ey_m));

        headingViolation = ...
            any(abs(epsi_rad) > headingLimit_rad) || ...
            any(~isfinite(epsi_rad));

        anyViolation = ...
            lateralViolation || headingViolation;

        runCount = runCount + 1;

        runs(runCount).time_s = time_s;
        runs(runCount).ey_m = ey_m;
        runs(runCount).epsi_rad = epsi_rad;
        runs(runCount).jitterBound_ms = jitterBound_ms;
        runs(runCount).seed = seed;
        runs(runCount).lateralViolation = lateralViolation;
        runs(runCount).headingViolation = headingViolation;
        runs(runCount).anyViolation = anyViolation;

        jitterColumn(runCount,1) = jitterBound_ms;
        seedColumn(runCount,1) = seed;
        lateralViolationColumn(runCount,1) = lateralViolation;
        headingViolationColumn(runCount,1) = headingViolation;
        anyViolationColumn(runCount,1) = anyViolation;

        maximumEyColumn(runCount,1) = ...
            max(abs(ey_m), [], "omitnan");

        maximumEpsiColumn(runCount,1) = ...
            max(abs(rad2deg(epsi_rad)), [], "omitnan");

        resultFileColumn(runCount,1) = resultFile;
    end
end

assert(runCount > 0, ...
    "No sampling-jitter result files were found.");

%% Create a searchable summary table

runSummary = table( ...
    jitterColumn, ...
    seedColumn, ...
    lateralViolationColumn, ...
    headingViolationColumn, ...
    anyViolationColumn, ...
    maximumEyColumn, ...
    maximumEpsiColumn, ...
    resultFileColumn, ...
    'VariableNames', { ...
        'JitterBound_ms', ...
        'Seed', ...
        'LateralViolation', ...
        'HeadingViolation', ...
        'AnyViolation', ...
        'MaxAbsEy_m', ...
        'MaxAbsEpsi_deg', ...
        'ResultFile'});

%% Plot

figureHandle = figure( ...
    "Name", "Sampling-jitter tracking errors", ...
    "Color", "w");

layout = tiledlayout( ...
    figureHandle, ...
    2, 1, ...
    "TileSpacing", "compact", ...
    "Padding", "compact");

lateralAxes = nexttile(layout);

plotErrorPanel( ...
    lateralAxes, ...
    runs, ...
    'ey_m', ...
    'lateralViolation', ...
    1, ...
    lateralLimit_m, ...
    "Lateral error, e_y (m)", ...
    "Lateral-error trajectories");

headingAxes = nexttile(layout);

plotErrorPanel( ...
    headingAxes, ...
    runs, ...
    'epsi_rad', ...
    'headingViolation', ...
    180/pi, ...
    rad2deg(headingLimit_rad), ...
    "Heading error, e_\psi (deg)", ...
    "Heading-error trajectories");

titleText = sprintf( ...
    "%s — %s: %d loaded runs", ...
    strrep(scenarioName, "_", " "), ...
    strrep(environmentName, "_", " "), ...
    runCount);

title(layout, titleText, ...
    "Interpreter", "none", ...
    "Color", "k");

fprintf( ...
    "Loaded %d of %d requested runs.\n", ...
    runCount, ...
    numel(jitterBounds_ms)*numel(seeds));

fprintf( ...
    "Runs with any constraint violation: %d\n", ...
    nnz(anyViolationColumn));

if missingCount > 0
    warning( ...
        "%d requested result files were missing and skipped.", ...
        missingCount);
end

end


function plotErrorPanel( ...
    axesHandle, ...
    runs, ...
    signalField, ...
    violationField, ...
    scaleFactor, ...
    constraintLimit, ...
    yLabelText, ...
    titleText)
%PLOTERRORPANEL Plot normal runs first, then violating runs.

backgroundColor = [0.78 0.82 0.86];
violationColor = [0.85 0.10 0.10];

backgroundLineWidth = 0.6;
violationLineWidth = 1.4;

hold(axesHandle, "on");

%% Nonviolating trajectories in the background

for index = 1:numel(runs)

    if ~runs(index).(violationField)

        signal = ...
            scaleFactor*runs(index).(signalField);

        plot( ...
            axesHandle, ...
            runs(index).time_s, ...
            signal, ...
            "Color", backgroundColor, ...
            "LineWidth", backgroundLineWidth);
    end
end

%% Violating trajectories on top

for index = 1:numel(runs)

    if runs(index).(violationField)

        signal = ...
            scaleFactor*runs(index).(signalField);

        plot( ...
            axesHandle, ...
            runs(index).time_s, ...
            signal, ...
            "Color", violationColor, ...
            "LineWidth", violationLineWidth);
    end
end

%% Constraint limits

yline( ...
    axesHandle, ...
    constraintLimit, ...
    "k--", ...
    "LineWidth", 1.2);

yline( ...
    axesHandle, ...
    -constraintLimit, ...
    "k--", ...
    "LineWidth", 1.2);

yline(axesHandle, 0, ...
    "Color", [0.3 0.3 0.3], ...
    "LineWidth", 0.8);

violationCount = nnz([runs.(violationField)]);

grid(axesHandle, "on");
box(axesHandle, "on");

xlabel(axesHandle, "Time (s)");
ylabel(axesHandle, yLabelText);

title( ...
    axesHandle, ...
    sprintf( ...
        "%s: %d/%d runs violated the constraint", ...
        titleText, ...
        violationCount, ...
        numel(runs)));

set( ...
    axesHandle, ...
    "Color", "w", ...
    "XColor", "k", ...
    "YColor", "k", ...
    "Layer", "top");

hold(axesHandle, "off");

end