function figureHandle = ...
    plot_delay_eigenvalue_map(delayStability)
%PLOT_DELAY_EIGENVALUE_MAP Plot delayed closed-loop eigenvalues.

delayTable = delayStability.table;
eigenvalueHistory = delayStability.eigenvalues;

figureHandle = figure( ...
    Name="Closed-loop eigenvalues versus delay", ...
    Color="white");

hold on;

%% Unit circle

circleAngle = linspace(0, 2*pi, 500);

plot( ...
    cos(circleAngle), ...
    sin(circleAngle), ...
    "k--", ...
    LineWidth=1.4, ...
    DisplayName="Unit circle");

%% Eigenvalues for every delay

for caseIndex = 1:height(delayTable)

    eigenvalues = ...
        eigenvalueHistory{caseIndex};

    delayColor = ...
        delayTable.Delay_ms(caseIndex) ...
        * ones(size(eigenvalues));

    scatter( ...
        real(eigenvalues), ...
        imag(eigenvalues), ...
        25, ...
        delayColor, ...
        "filled", ...
        MarkerFaceAlpha=0.65, ...
        HandleVisibility="off");
end

%% Highlight zero-delay poles

zeroDelayEigenvalues = ...
    eigenvalueHistory{1};

scatter( ...
    real(zeroDelayEigenvalues), ...
    imag(zeroDelayEigenvalues), ...
    70, ...
    "g", ...
    "o", ...
    LineWidth=1.5, ...
    DisplayName="Zero-delay poles");

%% Highlight first unstable poles

firstUnstableIndex = find( ...
    delayTable.SpectralRadius >= 1, ...
    1, ...
    "first");

if ~isempty(firstUnstableIndex)

    unstableEigenvalues = ...
        eigenvalueHistory{firstUnstableIndex};

    scatter( ...
        real(unstableEigenvalues), ...
        imag(unstableEigenvalues), ...
        80, ...
        "r", ...
        "x", ...
        LineWidth=1.8, ...
        DisplayName="First unstable-delay poles");
end

hold off;

axis equal;
grid on;
box on;

xlabel("Real part");
ylabel("Imaginary part");
title("Closed-Loop Eigenvalue Migration with Delay");

colorBar = colorbar;
colorBar.Label.String = "Delay (ms)";

colormap(turbo);
legend(Location="best");

end