function [figureHandle, diagnostic] = ...
    plot_sampling_jitter_violation_timeframe( ...
        scenarioName, ...
        environmentName, ...
        jitterBound_ms, ...
        seed, ...
        timeWindow_s, ...
        controllerParams)
%PLOT_SAMPLING_JITTER_VIOLATION_CASE Inspect one jitter realization.
%
% Example using a selected time window:
%
%   plot_sampling_jitter_violation_timeframe( ...
%       "highway_cruise", "dry_road", 8, 17, [20 35]);
%
% Automatically select a window around the first violation:
%
%   plot_sampling_jitter_violation_timeframe( ...
%       "highway_cruise", "dry_road", 8, 17, []);

arguments
    scenarioName (1,1) string
    environmentName (1,1) string
    jitterBound_ms (1,1) double
    seed (1,1) double
    timeWindow_s = []
    controllerParams (1,1) struct = struct()
end

%% Locate and load the saved simulation

startupFile = which("startup_project");

assert(~isempty(startupFile), ...
    "startup_project.m is not on the MATLAB path.");

projectRoot = string(fileparts(startupFile));

resultFile = fullfile( ...
    projectRoot, ...
    "phase1", ...
    "results", ...
    "ACADOS_MPC", ...
    "sampling_jitter", ...
    sprintf("jitter_bound_%g_ms", jitterBound_ms), ...
    sprintf("seed_%d", seed), ...
    scenarioName, ...
    environmentName, ...
    scenarioName + "_results.mat");

assert(isfile(resultFile), ...
    "Result file does not exist:\n%s", ...
    resultFile);

savedData = load( ...
    resultFile, ...
    "results");

results = savedData.results;
performanceMonitor = ...
    results.performance_monitor;

%% Extract plant-rate signals

plantTime_s = results.time_s(:);
xPosition_m = results.x_pos_m(:);
yPosition_m = results.y_pos_m(:);
lateralError_m = results.ey_m(:);
headingError_rad = results.epsi_rad(:);

sampleCount = min([ ...
    numel(plantTime_s), ...
    numel(xPosition_m), ...
    numel(yPosition_m), ...
    numel(lateralError_m), ...
    numel(headingError_rad)]);

plantTime_s = plantTime_s(1:sampleCount);
xPosition_m = xPosition_m(1:sampleCount);
yPosition_m = yPosition_m(1:sampleCount);
lateralError_m = lateralError_m(1:sampleCount);
headingError_rad = headingError_rad(1:sampleCount);

%% Extract configured constraints


lateralLimit_m = ...
    controllerParams.maximumLateralError_m;

headingLimit_rad = ...
    controllerParams.maximumHeadingError_rad;

controllerPeriod_ms = ...
    1000*controllerParams.Ts_s;

%% Find the first constraint violation

lateralViolation = ...
    abs(lateralError_m) > lateralLimit_m;

headingViolation = ...
    abs(headingError_rad) > headingLimit_rad;

violationMask = ...
    lateralViolation | headingViolation;

firstViolationIndex = find( ...
    violationMask, ...
    1, ...
    "first");

if isempty(firstViolationIndex)

    firstViolationTime_s = NaN;

    if isempty(timeWindow_s)
        timeWindow_s = [ ...
            plantTime_s(1), ...
            plantTime_s(end)];
    end

    warning( ...
        "This run does not contain a tracking-constraint violation.");

else

    firstViolationTime_s = ...
        plantTime_s(firstViolationIndex);

    if isempty(timeWindow_s)
        timeWindow_s = [ ...
            max(plantTime_s(1), firstViolationTime_s - 3), ...
            min(plantTime_s(end), firstViolationTime_s + 5)];
    end
end

assert(numel(timeWindow_s) == 2, ...
    "timeWindow_s must be [startTime endTime].");

timeWindow_s = sort(timeWindow_s);

%% Select plant data within the requested window

plantSelection = ...
    plantTime_s >= timeWindow_s(1) & ...
    plantTime_s <= timeWindow_s(2);

assert(any(plantSelection), ...
    "No plant data exists in the selected time window.");

normalizedLateralError = ...
    lateralError_m/lateralLimit_m;

normalizedHeadingError = ...
    headingError_rad/headingLimit_rad;

%% Extract controller-execution telemetry

executionLog = results.controller_execution_log;

executionTime_s = ...
    getExecutionTime(executionLog);

actualJitter_ms = ...
    1000*executionLog.ActualJitter_s(:);

solveTime_ms = ...
    1000*executionLog.SolveTime_s(:);

% Keep the exact raw acados value.
rawStatus = ...
    double(executionLog.SolverStatus(:));

controllerSelection = ...
    executionTime_s >= timeWindow_s(1) & ...
    executionTime_s <= timeWindow_s(2);

assert(any(controllerSelection), ...
    "No controller executions exist in the selected time window.");

%% Reference trajectory

referenceX_m = ...
    performanceMonitor.reference_x_m(:);

referenceY_m = ...
    performanceMonitor.reference_y_m(:);

%% Create the figure

figureHandle = figure( ...
    "Name", "Sampling-jitter violation diagnostic", ...
    "Color", "w", ...
    "Position", [100 80 1500 850]);

layout = tiledlayout( ...
    figureHandle, ...
    2, 2, ...
    "TileSpacing", "compact", ...
    "Padding", "compact");

%% 1. Spatial trajectory

trajectoryAxes = nexttile(layout, 1);

plot( ...
    trajectoryAxes, ...
    referenceX_m, ...
    referenceY_m, ...
    "k--", ...
    "LineWidth", 1.3, ...
    "DisplayName", "Reference");

hold(trajectoryAxes, "on");

plot( ...
    trajectoryAxes, ...
    xPosition_m, ...
    yPosition_m, ...
    "Color", [0.75 0.80 0.88], ...
    "LineWidth", 0.8, ...
    "DisplayName", "Complete trajectory");

plot( ...
    trajectoryAxes, ...
    xPosition_m(plantSelection), ...
    yPosition_m(plantSelection), ...
    "b-", ...
    "LineWidth", 2, ...
    "DisplayName", "Selected window");

if ~isnan(firstViolationTime_s)

    plot( ...
        trajectoryAxes, ...
        xPosition_m(firstViolationIndex), ...
        yPosition_m(firstViolationIndex), ...
        "ro", ...
        "MarkerFaceColor", "r", ...
        "MarkerSize", 7, ...
        "DisplayName", "First violation");
end

axis(trajectoryAxes, "equal");
grid(trajectoryAxes, "on");
xlabel(trajectoryAxes, "X position (m)");
ylabel(trajectoryAxes, "Y position (m)");
title(trajectoryAxes, "Trajectory in selected time window");
legend(trajectoryAxes, "Location", "best");

hold(trajectoryAxes, "off");

%% 2. Normalized tracking errors

errorAxes = nexttile(layout, 2);

plot( ...
    errorAxes, ...
    plantTime_s(plantSelection), ...
    normalizedLateralError(plantSelection), ...
    "LineWidth", 1.3, ...
    "DisplayName", "e_y / e_{y,max}");

hold(errorAxes, "on");

plot( ...
    errorAxes, ...
    plantTime_s(plantSelection), ...
    normalizedHeadingError(plantSelection), ...
    "LineWidth", 1.3, ...
    "DisplayName", "e_\psi / e_{\psi,max}");

yline(errorAxes, 1, "r--", "DisplayName", "Upper constraint");
yline(errorAxes, -1, "r--", "DisplayName", "Lower constraint");
yline(errorAxes, 0, "k-", "DisplayName", "Reference");

grid(errorAxes, "on");
xlabel(errorAxes, "Time (s)");
ylabel(errorAxes, "Normalized error");
title(errorAxes, "Normalized tracking errors");
legend(errorAxes, "Location", "best");

hold(errorAxes, "off");

%% 3. Applied sampling jitter

jitterAxes = nexttile(layout, 3);

scatter( ...
    jitterAxes, ...
    executionTime_s(controllerSelection), ...
    actualJitter_ms(controllerSelection), ...
    10, ...
    [0.10 0.40 0.85], ...
    "filled");

hold(jitterAxes, "on");

yline(jitterAxes, 0, "k-");

yline( ...
    jitterAxes, ...
    jitterBound_ms, ...
    "r--", ...
    "+J bound");

yline( ...
    jitterAxes, ...
    -jitterBound_ms, ...
    "r--", ...
    "-J bound");

grid(jitterAxes, "on");
xlabel(jitterAxes, "Controller execution time (s)");
ylabel(jitterAxes, "Actual jitter (ms)");
title(jitterAxes, "Applied sampling jitter");

hold(jitterAxes, "off");

%% 4. Solve time colored by raw acados status

solveTimeAxes = nexttile(layout, 4);

selectedTime_s = ...
    executionTime_s(controllerSelection);

selectedSolveTime_ms = ...
    solveTime_ms(controllerSelection);

selectedRawStatus = ...
    rawStatus(controllerSelection);

plot( ...
    solveTimeAxes, ...
    selectedTime_s, ...
    selectedSolveTime_ms, ...
    "-", ...
    "Color", [0.72 0.72 0.72], ...
    "LineWidth", 0.7);

hold(solveTimeAxes, "on");

scatter( ...
    solveTimeAxes, ...
    selectedTime_s, ...
    selectedSolveTime_ms, ...
    16, ...
    selectedRawStatus, ...
    "filled");

yline( ...
    solveTimeAxes, ...
    controllerPeriod_ms, ...
    "r--", ...
    sprintf("Deadline = %.1f ms", controllerPeriod_ms));

grid(solveTimeAxes, "on");
xlabel(solveTimeAxes, "Controller execution time (s)");
ylabel(solveTimeAxes, "Solve time (ms)");
title(solveTimeAxes, "Solve time and raw acados status");

statusValues = unique( ...
    selectedRawStatus(isfinite(selectedRawStatus)));

if isempty(statusValues)
    statusValues = 0;
end

statusLimits = [ ...
    min(statusValues) - 0.5, ...
    max(statusValues) + 0.5];

clim(solveTimeAxes, statusLimits);
colormap(solveTimeAxes, turbo(256));

statusColorbar = colorbar(solveTimeAxes);
statusColorbar.Label.String = ...
    "Raw acados status";

statusColorbar.Ticks = statusValues;

hold(solveTimeAxes, "off");

%% Mark first violation on time plots

timeAxes = [errorAxes, jitterAxes, solveTimeAxes];

if ~isnan(firstViolationTime_s) && ...
        firstViolationTime_s >= timeWindow_s(1) && ...
        firstViolationTime_s <= timeWindow_s(2)

    for axesHandle = timeAxes

        xline( ...
            axesHandle, ...
            firstViolationTime_s, ...
            "m--", ...
            "First violation", ...
            "LineWidth", 1.2, ...
            DisplayName= "1st Violation");
    end
end

linkaxes(timeAxes, "x");
xlim(timeAxes, timeWindow_s);

%% White figure appearance

allAxes = [ ...
    trajectoryAxes, ...
    errorAxes, ...
    jitterAxes, ...
    solveTimeAxes];

set( ...
    allAxes, ...
    "Color", "w", ...
    "XColor", "k", ...
    "YColor", "k", ...
    "Layer", "top");

title( ...
    layout, ...
    sprintf( ...
        "%s — %s, J = %g ms, seed = %d", ...
        strrep(scenarioName, "_", " "), ...
        strrep(environmentName, "_", " "), ...
        jitterBound_ms, ...
        seed), ...
    "Interpreter", "none", ...
    "Color", "k");

%% Return diagnostic information

diagnostic = struct();

diagnostic.result_file = resultFile;
diagnostic.time_window_s = timeWindow_s;
diagnostic.first_violation_time_s = firstViolationTime_s;

diagnostic.lateral_violation = ...
    any(lateralViolation);

diagnostic.heading_violation = ...
    any(headingViolation);

diagnostic.maximum_absolute_ey_m = ...
    max(abs(lateralError_m), [], "omitnan");

diagnostic.maximum_absolute_epsi_deg = ...
    max(abs(rad2deg(headingError_rad)), [], "omitnan");

diagnostic.raw_status_values = ...
    unique(rawStatus);

end


function executionTime_s = getExecutionTime(executionLog)
%GETEXECUTIONTIME Locate the actual controller execution-time column.

availableNames = string( ...
    executionLog.Properties.VariableNames);

candidateNames = [ ...
    "ExecutionTime_s"
    "ActualExecutionTime_s"
    "ObservedTime_s"
    "ActualTime_s"
    "Time_s"
    ];

selectedName = "";

for candidate = candidateNames.'

    if any(availableNames == candidate)
        selectedName = candidate;
        break;
    end
end

assert(strlength(selectedName) > 0, ...
    "Could not find the execution-time column. Available columns: %s", ...
    strjoin(availableNames, ", "));

executionTime_s = ...
    executionLog.(selectedName)(:);

end