function controlTaskDuration = ...
    create_phase3_control_task_duration( ...
        demandModeSignal, ...
        durationBank, ...
        stopTime_s, ...
        randomSeed, ...
        options)

arguments
    demandModeSignal (1,1) timeseries
    durationBank (1,1) struct
    stopTime_s (1,1) double {mustBePositive}
    randomSeed (1,1) double
    options.SupervisorSampleTime_s (1,1) double = 0.010
end

supervisorTime_s = ...
    (0:options.SupervisorSampleTime_s:stopTime_s).';

demandMode = interp1( ...
    double(demandModeSignal.Time), ...
    double(demandModeSignal.Data), ...
    supervisorTime_s, ...
    "previous", ...
    "extrap");

lowSamples_s = ...
    double(durationBank.LOW.samples_s(:));

mediumSamples_s = ...
    double(durationBank.MEDIUM.samples_s(:));

highSamples_s = ...
    double(durationBank.HIGH.samples_s(:));

assert(~isempty(lowSamples_s), ...
    "The LOW-duration bank is empty.");

assert(~isempty(mediumSamples_s), ...
    "The MEDIUM-duration bank is empty.");

assert(~isempty(highSamples_s), ...
    "The HIGH-duration bank is empty.");

assert(all(lowSamples_s >= 0), ...
    "LOW-duration samples contain negative values.");

assert(all(mediumSamples_s >= 0), ...
    "MEDIUM-duration samples contain negative values.");

assert(all(highSamples_s >= 0), ...
    "HIGH-duration samples contain negative values.");

randomStream = RandStream( ...
    "mt19937ar", ...
    "Seed", ...
    randomSeed);

duration_s = zeros( ...
    size(supervisorTime_s));

for sampleIndex = 1:numel(supervisorTime_s)

    switch uint8(demandMode(sampleIndex))

        case 1  % LOW, 50 ms
            sourceSamples_s = lowSamples_s;

        case 2  % MEDIUM, 20 ms
            sourceSamples_s = mediumSamples_s;

        case 3  % HIGH, 10 ms
            sourceSamples_s = highSamples_s;

        otherwise
            error( ...
                "Invalid demand mode %g at %.6f s.", ...
                demandMode(sampleIndex), ...
                supervisorTime_s(sampleIndex));
    end

    selectedIndex = randi( ...
        randomStream, ...
        numel(sourceSamples_s));

    duration_s(sampleIndex) = ...
        sourceSamples_s(selectedIndex);
end

controlTaskDuration = timeseries( ...
    duration_s, ...
    supervisorTime_s);

controlTaskDuration.Name = ...
    "phase3_control_task_duration";

controlTaskDuration = setinterpmethod( ...
    controlTaskDuration, ...
    "zoh");

end