function dependency = acados_dependency()
%ACADOS_DEPENDENCY Defines the acados version required by this project.

dependency.name = "acados";
dependency.version = "v0.5.4";

dependency.commit = ...
    "d9d0ba2e8f127855119d38874af8a9570df1d8e5";

dependency.repository = ...
    "https://github.com/acados/acados.git";

if ispc
    dependency.root = fullfile( ...
        getenv("LOCALAPPDATA"), ...
        "SDV", ...
        "dependencies", ...
        "acados", ...
        dependency.version);
else
    dependency.root = fullfile( ...
        getenv("HOME"), ...
        ".cache", ...
        "SDV", ...
        "dependencies", ...
        "acados", ...
        dependency.version);
end

end