function xdot = dynamic_model(x,u,kappa,p)

vx   = x(1);
vy   = x(2);
r    = x(3);
% ey   = x(4); 
epsi = x(5);

Tlong = u(1);
delta = u(2);

vxSafe = max(vx,p.minimum_speed_mps);

alphaF = ...
    atan2(vy + p.lf_m*r,vxSafe) - delta;

alphaR = ...
    atan2(vy - p.lr_m*r,vxSafe);

Fyf = -p.Cf_Nprad*alphaF;
Fyr = -p.Cr_Nprad*alphaR;

% Tlong is total front-axle torque.
Fdrive = ...
    p.drivetrain_efficiency ...
    * Tlong ...
    / p.wheel_radius_m;

Fresistance = ...
    p.rolling_resistance_coefficient ...
    * p.mass_kg ...
    * p.gravity_mps2 ...
    * tanh(vx/p.rolling_resistance_smoothing_speed_mps) ...
    + 0.5 ...
    * p.air_density_kgpm3 ...
    * p.drag_coefficient ...
    * p.frontal_area_m2 ...
    * vx ...
    * abs(vx);

vxDot = ...
    vy*r ...
    + (Fdrive*cos(delta) ...
    - Fyf*sin(delta) ...
    - Fresistance) ...
    / p.mass_kg;

vyDot = ...
    -vx*r ...
    + (Fyf*cos(delta) ...
    + Fyr ...
    + Fdrive*sin(delta)) ...
    / p.mass_kg;

rDot = ...
    (p.lf_m*Fyf*cos(delta) ...
    - p.lr_m*Fyr ...
    + p.lf_m*Fdrive*sin(delta)) ...
    / p.yaw_inertia_kgm2;

eyDot = vy + vx*epsi;
epsiDot = r - vx*kappa;

xdot = [
    vxDot
    vyDot
    rDot
    eyDot
    epsiDot
    ];


end
