function mapSummary = build_phase4_performance_maps(options)
%BUILD_PHASE4_PERFORMANCE_MAPS Build all selected scenario/environment maps.

arguments
    options.ScenarioNames (:,1) string = [
        "urban_profile"
        "highway_cruise"
        "aggressive_maneuver"
        ]
    options.EnvironmentNames (:,1) string = [
        "dry_road"
        "low_friction_road"
        ]
    options.PredictionHorizon_s (1,1) double ...
        {mustBePositive} = 1.0
    options.RowStride_s (1,1) double ...
        {mustBePositive} = 0.050
end

startup_project;

mapSummary = table();

for scenarioIndex = 1:numel(options.ScenarioNames)
    scenarioName = options.ScenarioNames(scenarioIndex);

    for environmentIndex = 1:numel(options.EnvironmentNames)
        environmentName = ...
            options.EnvironmentNames(environmentIndex);

        [~, mapTable, mapFile] = ...
            build_phase4_performance_map( ...
                scenarioName, ...
                environmentName, ...
                PredictionHorizon_s= ...
                    options.PredictionHorizon_s, ...
                RowStride_s=options.RowStride_s);

        newRow = table( ...
            scenarioName, ...
            environmentName, ...
            height(mapTable), ...
            string(mapFile), ...
            VariableNames=[ ...
                "Scenario", ...
                "Environment", ...
                "NumberOfRows", ...
                "MapFile"]);

        mapSummary = [mapSummary; newRow]; %#ok<AGROW>
    end
end

projectRoot = string( ...
    matlab.project.currentProject().RootFolder);

summaryFolder = fullfile( ...
    projectRoot, "phase4", "data", "performance_maps");

save(fullfile(summaryFolder, "map_summary.mat"), "mapSummary");
writetable(mapSummary, fullfile(summaryFolder, "map_summary.csv"));

disp(mapSummary);

fprintf( ...
    "\nPerformance-map construction finished.\n" + ...
    "Runtime entry point: %s\n", ...
    fullfile(projectRoot, "phase4", "main.m"));

end
