function collectionSummary = ...
    collect_phase4_performance_data(options)
%COLLECT_PHASE4_PERFORMANCE_DATA Run all fixed-mode map experiments.

arguments
    options.ScenarioNames (:,1) string = [
        "urban_profile"
        "highway_cruise"
        "aggressive_maneuver"
        ]
    options.EnvironmentNames (:,1) string = [
        "dry_road"
        "low_friction_road"
        ]
    options.SampleTimes_s (:,1) double = [
        0.050
        0.020
        0.010
        ]
    options.LoadTaskDuration_s (1,1) double ...
        {mustBeNonnegative} = 0.020
    options.LoadTaskPeriod_s (1,1) double ...
        {mustBePositive} = 0.050
    options.BaseRandomSeed (1,1) double = 4000
    options.Overwrite (1,1) logical = false
end

startup_project;

projectRoot = string( ...
    matlab.project.currentProject().RootFolder);

resultsRoot = fullfile( ...
    projectRoot, "phase4", "results", ...
    "performance_map_runs");

if ~isfolder(resultsRoot)
    mkdir(resultsRoot);
end

summaryFile = fullfile( ...
    resultsRoot, "collection_summary.mat");

summaryCsv = fullfile( ...
    resultsRoot, "collection_summary.csv");

collectionSummary = table();
caseNumber = 0;

for scenarioIndex = 1:numel(options.ScenarioNames)
    scenarioName = options.ScenarioNames(scenarioIndex);

    for environmentIndex = 1:numel(options.EnvironmentNames)
        environmentName = ...
            options.EnvironmentNames(environmentIndex);

        for periodIndex = 1:numel(options.SampleTimes_s)
            sampleTime_s = options.SampleTimes_s(periodIndex);
            caseNumber = caseNumber + 1;

            randomSeed = ...
                options.BaseRandomSeed ...
                + 100*scenarioIndex ...
                + 10*environmentIndex ...
                + periodIndex;

            runTimer = tic;

            try
                [~, resultsFile] = ...
                    run_phase4_fixed_mode_case( ...
                        scenarioName, ...
                        environmentName, ...
                        sampleTime_s, ...
                        LoadTaskDuration_s= ...
                            options.LoadTaskDuration_s, ...
                        LoadTaskPeriod_s= ...
                            options.LoadTaskPeriod_s, ...
                        RandomSeed=randomSeed, ...
                        ResultsRoot=resultsRoot, ...
                        Overwrite=options.Overwrite);

                status = "completed";
                errorMessage = "";

            catch simulationError
                resultsFile = "";
                status = "failed";
                errorMessage = string(getReport( ...
                    simulationError, ...
                    "extended", ...
                    "hyperlinks", ...
                    "off"));

                warning( ...
                    "Phase4:MapRunFailed", ...
                    "%s | %s | %.0f ms failed:\n%s", ...
                    scenarioName, ...
                    environmentName, ...
                    1e3*sampleTime_s, ...
                    errorMessage);
            end

            newRow = table( ...
                caseNumber, ...
                scenarioName, ...
                environmentName, ...
                sampleTime_s, ...
                status, ...
                string(resultsFile), ...
                toc(runTimer), ...
                errorMessage, ...
                VariableNames=[ ...
                    "CaseNumber", ...
                    "Scenario", ...
                    "Environment", ...
                    "SampleTime_s", ...
                    "Status", ...
                    "ResultsFile", ...
                    "ElapsedTime_s", ...
                    "ErrorMessage"]);

            collectionSummary = [
                collectionSummary
                newRow
                ]; %#ok<AGROW>

            save(summaryFile, "collectionSummary");
            writetable(collectionSummary, summaryCsv);
        end
    end
end

disp(collectionSummary(:, [ ...
    "Scenario", "Environment", ...
    "SampleTime_s", "Status"]));

fprintf( ...
    "\nFixed-mode data collection finished.\n" + ...
    "Next file: %s\n", ...
    fullfile(projectRoot, "phase4", "scripts", ...
        "build_phase4_performance_maps.m"));

end
