function durationSignal = ...
    create_control_task_duration_signal( ...
    solveTimeSamples_s, ...
    stopTime_s, ...
    randomSeed)

arguments
    solveTimeSamples_s (:,1) double
    stopTime_s (1,1) double {mustBePositive}
    randomSeed (1,1) double {mustBeInteger} = 1
end

controlPeriod_s = 0.010;

numberOfReleases = ...
    floor(stopTime_s/controlPeriod_s) + 1;

stream = RandStream( ...
    "Threefry", ...
    Seed=randomSeed);

sampleIndices = randi( ...
    stream, ...
    numel(solveTimeSamples_s), ...
    numberOfReleases, ...
    1);

executionDuration_s = ...
    solveTimeSamples_s(sampleIndices);

releaseTime_s = ...
    (0:numberOfReleases-1).' * controlPeriod_s;

durationSignal = timeseries( ...
    executionDuration_s, ...
    releaseTime_s);

durationSignal = setinterpmethod( ...
    durationSignal, ...
    "zoh");

durationSignal.Name = ...
    "control_task_duration_s";

end