function caseFolder = phase2_4_case_folder( ...
    projectRoot, ...
    scenarioName, ...
    environmentName, ...
    loadExecutionTime_ms)
%PHASE2_4_CASE_FOLDER Return the canonical folder for one sweep point.

arguments
    projectRoot (1,1) string
    scenarioName (1,1) string
    environmentName (1,1) string
    loadExecutionTime_ms (1,1) double {mustBeNonnegative}
end

loadLabel = string(sprintf("load_%07.3f_ms", loadExecutionTime_ms));
loadLabel = replace(loadLabel, ".", "p");

caseFolder = fullfile( ...
    projectRoot, ...
    "phase2", ...
    "results", ...
    "phase2_4", ...
    scenarioName, ...
    environmentName, ...
    loadLabel);

end
