function [solver, metadata] = create_acados_solver(config)
%CREATE_ACADOS_SOLVER Build and initialize the Phase 0 acados solver.

[ocp, metadata] = build_acados_ocp( ...
    config.adaptiveModel, ...
    config.controller);

solver = AcadosOcpSolver(ocp);

initialState = config.controller.initial_state;
nominalInput = metadata.settings.nominal_input;

solver.set( ...
    'init_x', ...
    repmat(initialState, 1, metadata.N + 1));

solver.set( ...
    'init_u', ...
    repmat(nominalInput, 1, metadata.N));

solver.set( ...
    'init_pi', ...
    zeros(metadata.nx, metadata.N));

end