function [ ...
    lowerInitialState, ...
    upperInitialState, ...
    curvatureTrajectory, ...
    pathReference, ...
    terminalReference] = ...
    format_acados_inputs( ...
    measuredVehicleState, ...
    appliedCommand, ...
    stateReference, ...
    curvatureReference, ...
    numberOfIntervals)
%FORMAT_ACADOS_INPUTS Format signals for the generated S-function.

measuredVehicleState = measuredVehicleState(:);
appliedCommand = appliedCommand(:);
stateReference = stateReference(:);

assert(numel(measuredVehicleState) == 5);
assert(numel(appliedCommand) == 2);
assert(numel(stateReference) == 5);
assert(numberOfIntervals >= 2);

% Equal lower and upper bounds fix the initial predicted state to the
% measured vehicle state and the current physical actuator commands.
augmentedInitialState = [
    measuredVehicleState
    appliedCommand
    ];

lowerInitialState = augmentedInitialState;
upperInitialState = augmentedInitialState;

% One curvature parameter for every state node, including the terminal node.
curvatureTrajectory = repmat( ...
    curvatureReference, ...
    numberOfIntervals + 1, ...
    1);

% Intermediate-stage reference:
% [five vehicle states; two physical commands; two command rates].
singleStageReference = [
    stateReference
    zeros(2,1)
    zeros(2,1)
    ];

pathReference = repmat( ...
    singleStageReference, ...
    numberOfIntervals - 1, ...
    1);

terminalReference = stateReference;

end
