function [ ...
    lowerInitialState, ...
    upperInitialState, ...
    curvatureTrajectory, ...
    pathReference, ...
    terminalReference] = ...
    format_acados_inputs( ...
    measuredState, ...
    stateReference, ...
    curvatureReference, ...
    nominalInput, ...
    numberOfIntervals)
%FORMAT_ACADOS_INPUTS Format signals for the generated S-function.

measuredState = measuredState(:);
stateReference = stateReference(:);
nominalInput = nominalInput(:);

assert(numel(measuredState) == 5);
assert(numel(stateReference) == 5);
assert(numel(nominalInput) == 2);
assert(numberOfIntervals >= 2);

% Equal lower and upper bounds fix the initial predicted state to the
% currently measured controller state.
lowerInitialState = measuredState;
upperInitialState = measuredState;

% One curvature parameter for every state node, including the terminal node.
curvatureTrajectory = repmat( ...
    curvatureReference, ...
    numberOfIntervals + 1, ...
    1);

% Intermediate-stage reference:
% [five states; torque reference; steering reference].
singleStageReference = [
    stateReference
    nominalInput
    ];

pathReference = repmat( ...
    singleStageReference, ...
    numberOfIntervals - 1, ...
    1);

terminalReference = stateReference;

end