function solverFile = s_fun_generation_acados()
%S_FUN_GENERATION_ACADOS Generate the acados Simulink S-function.

bdclose("all");
clear mex;

startup_project;
activate_acados(true);

configuration = ...
    build_phase0_configuration("highway_cruise");

[ocp, metadata] = build_acados_ocp( ...
    configuration.adaptiveModel, ...
    configuration.controller, ...
    true);

solver = AcadosOcpSolver(ocp);

originalDirectory = pwd;
directoryCleanup = ...
    onCleanup(@() cd(originalDirectory)); %#ok<NASGU>

generatedDirectory = metadata.generated_directory;
cd(generatedDirectory);

run("make_sfun.m");

solverFile = fullfile( ...
    generatedDirectory, ...
    "acados_solver_sfunction_sdv_dynamic_bicycle." ...
    + string(mexext));

assert( ...
    isfile(solverFile), ...
    "acados S-function generation did not create:\n%s", ...
    solverFile);

fprintf( ...
    "Generated acados S-function:\n%s\n", ...
    solverFile);

end
