function solverFile = s_fun_generation_acados()
%S_FUN_GENERATION_ACADOS Generate the acados Simulink S-function.

bdclose("all");
clear mex;

startup_project; % add necessary folders path
activate_acados(true); % check acados installation

configuration = ...
    build_phase0_configuration("highway_cruise"); % all the parameters required for simulation and building ocp model

[ocp, metadata] = build_acados_ocp( ...
    configuration.adaptiveModel, ...
    configuration.controller, ...
    true);

solver = AcadosOcpSolver(ocp);

solverSourceName = ...
    "acados_solver_sfunction_" + ...
    string(metadata.model_name) + ".c";

patch_acados_model_reference_rule( ...
    metadata.generated_directory, ...
    solverSourceName);

originalDirectory = pwd;
directoryCleanup = ...
    onCleanup(@() cd(originalDirectory));

generatedDirectory = metadata.generated_directory;
cd(generatedDirectory);

run("make_sfun.m");

solverFile = fullfile( ...
    generatedDirectory, ...
    "acados_solver_sfunction_sdv_dynamic_bicycle." ...
    + string(mexext));

assert( ...
    isfile(solverFile), ...
    "acados S-function generation did not create:\n%s", ...
    solverFile);

fprintf( ...
    "Generated acados S-function:\n%s\n", ...
    solverFile);

end
