function files = saveDelaySweepSummary( ...
    summaryTable, ...
    controllerName, ...
    environmentName)
%SAVEDELAYSWEEPSUMMARY Checkpoint the Phase 1 sweep table.

arguments
    summaryTable table
    controllerName (1,1) string
    environmentName (1,1) string
end

projectRoot = string( ...
    matlab.project.currentProject().RootFolder);

resultsFolder = fullfile( ...
    projectRoot, ...
    "phase1", ...
    "results", ...
    controllerName, ...
    "constant_delay_sweep", ...
    environmentName);

if ~isfolder(resultsFolder)
    mkdir(resultsFolder);
end

files = struct();

files.mat = fullfile( ...
    resultsFolder, ...
    "constant_delay_summary.mat");

files.csv = fullfile( ...
    resultsFolder, ...
    "constant_delay_summary.csv");

save(files.mat, "summaryTable");
writetable(summaryTable, files.csv);

end