function [figureHandle, metrics] = ...
    plot_phase0_solve_time( ...
        results, scenario, environmentName, controlSampleTime_s)
%PLOT_PHASE0_SOLVE_TIME Plot solve-time histogram and calculate metrics.
%
% Raw solve time is stored in seconds. The figure and report table use
% milliseconds for readability.

solveTime_s = results.solve_time_s;

assert(~isempty(solveTime_s), ...
    "No solve-time samples were logged.");

assert(all(isfinite(solveTime_s)), ...
    "Solve-time telemetry contains NaN or Inf values.");

assert(all(solveTime_s >= 0), ...
    "Solve-time telemetry contains negative values.");

sampleCount = numel(solveTime_s);
sortedSolveTime_s = sort(solveTime_s);

% Nearest-rank 95th percentile. This avoids requiring an additional
% Statistics and Machine Learning Toolbox dependency.
percentile95Index = max( ...
    1, ceil(0.95 * sampleCount));

metrics = struct();

metrics.sample_count = sampleCount;
metrics.mean_s = mean(solveTime_s);
metrics.percentile95_s = ...
    sortedSolveTime_s(percentile95Index);
metrics.max_s = max(solveTime_s);

metrics.control_deadline_s = controlSampleTime_s;
metrics.deadline_miss_count = ...
    nnz(solveTime_s > controlSampleTime_s);
metrics.deadline_miss_percent = ...
    100 * metrics.deadline_miss_count / sampleCount;

metrics.summary_table = table( ...
    string(scenario.name), ...
    metrics.mean_s * 1e3, ...
    metrics.percentile95_s * 1e3, ...
    metrics.max_s * 1e3, ...
    metrics.deadline_miss_count, ...
    metrics.deadline_miss_percent, ...
    VariableNames=[ ...
        "Scenario"
        "Mean_ms"
        "Percentile95_ms"
        "Maximum_ms"
        "DeadlineMisses"
        "DeadlineMissPercent"
    ]);

%% Histogram

solveTime_ms = solveTime_s * 1e3;

numberOfBins = max( ...
    10, min(50, ceil(sqrt(sampleCount))));

figureHandle = figure( ...
    Name="MPC solve-time telemetry", ...
    Color="w", ...
    Position=[150 100 900 600]);

histogram( ...
    solveTime_ms, ...
    numberOfBins, ...
    FaceColor=[0.20 0.45 0.75], ...
    EdgeColor="w");

hold on;

xline( ...
    metrics.mean_s * 1e3, ...
    "-", ...
    sprintf("Mean: %.3f ms", metrics.mean_s * 1e3), ...
    LineWidth=1.5, ...
    LabelVerticalAlignment="middle");

xline( ...
    metrics.percentile95_s * 1e3, ...
    "--", ...
    sprintf( ...
        "95th: %.3f ms", ...
        metrics.percentile95_s * 1e3), ...
    LineWidth=1.5, ...
    LabelVerticalAlignment="bottom");

xline( ...
    metrics.max_s * 1e3, ...
    ":", ...
    sprintf("Max: %.3f ms", metrics.max_s * 1e3), ...
    LineWidth=1.5, ...
    LabelVerticalAlignment="top");

hold off;
grid on;

xlabel("MPC solve time (ms)");
ylabel("Number of control steps");

scenarioTitle = replace( ...
    string(scenario.name), "_", " ");
environmentName = replace(string(environmentName), "_", " ");

title( ...
    "MPC Solve-Time Distribution: " + scenarioTitle +", " + environmentName);

end