function [figureHandle, metrics] = ...
    plot_solve_time_telemetry( ...
        results, ...
        scenarioName, ...
        environmentName, ...
        Ts_s, ...
        actuationDelay_s)
arguments
    results (1,1) struct
    scenarioName (1,1) string
    environmentName (1,1) string
    Ts_s (1,1) double {mustBePositive}
    actuationDelay_s (1,1) double = NaN
end

%% Validate inputs

assert(isfield(results,"time_s"), ...
    "results.time_s is missing.");

assert(isfield(results,"solve_time_s"), ...
    "results.solve_time_s is missing.");

%% Extract and clean data

if isfield(results, "solve_time_time_s") && ...
        ~isempty(results.solve_time_time_s)
    time_s = results.solve_time_time_s(:);
else
    time_s = results.time_s(:);
end
solveTime_ms = 1e3 * results.solve_time_s(:);

numberOfSamples = min( ...
    numel(time_s), ...
    numel(solveTime_ms));

time_s = time_s(1:numberOfSamples);
solveTime_ms = solveTime_ms(1:numberOfSamples);

validSamples = ...
    isfinite(time_s) & ...
    isfinite(solveTime_ms) & ...
    solveTime_ms >= 0;

time_s = time_s(validSamples);
solveTime_ms = solveTime_ms(validSamples);

assert(~isempty(solveTime_ms), ...
    "No valid solver-time samples were found.");

%% Calculate statistics

sampleDeadline_ms = ...
    1e3 * Ts_s;

metrics.mean_ms = mean(solveTime_ms);
metrics.median_ms = median(solveTime_ms);
metrics.p95_ms = samplePercentile(solveTime_ms,0.95);
metrics.p99_ms = samplePercentile(solveTime_ms,0.99);
metrics.maximum_ms = max(solveTime_ms);

deadlineMiss = ...
    solveTime_ms > sampleDeadline_ms;

metrics.deadline_ms = sampleDeadline_ms;
metrics.deadline_miss_count = sum(deadlineMiss);
metrics.valid_sample_count = numel(solveTime_ms);

metrics.deadline_miss_percentage = ...
    100 ...
    * metrics.deadline_miss_count ...
    / metrics.valid_sample_count;

%% Create figure

figureHandle = figure( ...
    Name="Solve-time telemetry: " + scenarioName, ...
    Theme="light");

axesHandle = axes(figureHandle);

plot( ...
    axesHandle, ...
    time_s, ...
    solveTime_ms, ...
    Color=[0 0.4470 0.7410], ...
    LineWidth=1.0, ...
    DisplayName="acados solve time");

hold(axesHandle,"on");

yline( ...
    axesHandle, ...
    metrics.mean_ms, ...
    "k--", ...
    sprintf("Mean = %.3f ms",metrics.mean_ms), ...
    LineWidth=1.1, ...
    DisplayName="Mean");

yline( ...
    axesHandle, ...
    metrics.p95_ms, ...
    "m-.", ...
    sprintf("95th percentile = %.3f ms",metrics.p95_ms), ...
    LineWidth=1.1, ...
    DisplayName="95th percentile");

yline( ...
    axesHandle, ...
    sampleDeadline_ms, ...
    "r--", ...
    sprintf("Deadline = %.3f ms",sampleDeadline_ms), ...
    LineWidth=1.5, ...
    DisplayName="Sampling deadline");

if any(deadlineMiss)
    scatter( ...
        axesHandle, ...
        time_s(deadlineMiss), ...
        solveTime_ms(deadlineMiss), ...
        40, ...
        "r", ...
        "filled", ...
        DisplayName="Deadline miss");
end

hold(axesHandle,"off");

grid(axesHandle,"on");
xlabel(axesHandle,"Simulation time (s)");
ylabel(axesHandle,"Solver execution time (ms)");

baseTitle = "acados Solve-Time Telemetry: " + replace(scenarioName,"_"," ") + " — " + ...
            replace(environmentName, "_", " ");

if ~isnan(actuationDelay_s)
    delay_ms = actuationDelay_s * 1e3;
    titleText = baseTitle + " (delay = " + num2str(delay_ms,'%.1f') + " ms)";
else
    titleText = baseTitle;
end

title(axesHandle, titleText);

subtitle( ...
    axesHandle, ...
    sprintf( ...
        "Median %.3f ms | P95 %.3f ms | P99 %.3f ms | Max %.3f ms", ...
        metrics.median_ms, ...
        metrics.p95_ms, ...
        metrics.p99_ms, ...
        metrics.maximum_ms));

legend(axesHandle,Location="best");

%% Print summary

fprintf("\nSolve-time telemetry: %s\n",scenarioName);
fprintf("Mean:             %.4f ms\n",metrics.mean_ms);
fprintf("Median:           %.4f ms\n",metrics.median_ms);
fprintf("95th percentile:  %.4f ms\n",metrics.p95_ms);
fprintf("99th percentile:  %.4f ms\n",metrics.p99_ms);
fprintf("Maximum:          %.4f ms\n",metrics.maximum_ms);
fprintf("Deadline:         %.4f ms\n",metrics.deadline_ms);
fprintf( ...
    "Deadline misses: %d/%d (%.4f%%)\n", ...
    metrics.deadline_miss_count, ...
    metrics.valid_sample_count, ...
    metrics.deadline_miss_percentage);

end

function value = samplePercentile(data,probability)
%SAMPLEPERCENTILE Linear-interpolated percentile without extra toolboxes.

sortedData = sort(data(:));
numberOfValues = numel(sortedData);

position = 1 + ...
    (numberOfValues - 1) * probability;

lowerIndex = floor(position);
upperIndex = ceil(position);

if lowerIndex == upperIndex
    value = sortedData(lowerIndex);
else
    interpolationFraction = ...
        position - lowerIndex;

    value = ...
        sortedData(lowerIndex) ...
        + interpolationFraction ...
        * ( ...
            sortedData(upperIndex) ...
            - sortedData(lowerIndex));
end

end
