function [figureHandle, metrics] = ...
    plot_phase0_tracking_errors( ...
        results, scenario, environmentName, controller, actuationDelay_s)
%PLOT_PHASE0_TRACKING_ERRORS Plot e_v, e_y, and e_psi with metrics.

arguments
    results
    scenario
    environmentName
    controller
    actuationDelay_s (1,1) double = NaN
end

time = results.time_s;
speedError = results.ev_mps;
lateralError = results.ey_m;
headingError = results.epsi_rad;
slackTime = results.slack_time_s;

firstEySlack = ...
    results.first_predicted_ey_slack_m;

maxEySlack = ...
    results.max_predicted_ey_slack_m;

firstEpsiSlack_deg = rad2deg( ...
    results.first_predicted_epsi_slack_rad);

maxEpsiSlack_deg = rad2deg( ...
    results.max_predicted_epsi_slack_rad);


assert(all(isfinite( ...
    [time; speedError; lateralError; headingError])), ...
    "Tracking-error results contain NaN or Inf values.");

metrics = sdv.metrics.computeTracking(results);
metrics.maximum_predicted_ey_slack_m = ...
    max(maxEySlack);

metrics.maximum_predicted_epsi_slack_deg = ...
    max(maxEpsiSlack_deg);

scenarioTitle = replace(string(scenario.name), "_", " ");
environmentName = replace(string(environmentName), "_", " ");


figureHandle = figure( ...
    Name="Phase 0 tracking errors: " + scenarioTitle, ...
    Color="w", ...
    Position=[150 40 1150 1100]);

layout = tiledlayout(figureHandle, 5, 1);
layout.TileSpacing = "compact";
layout.Padding = "compact";

%% Longitudinal-speed tracking error

nexttile(layout);
plot( ...
    time, speedError, ...
    LineWidth=1.3, ...
    DisplayName="Tracking error");
addErrorReferenceLines( ...
    metrics.speed_rmse_mps, ...
    metrics.speed_peak_mps, ...
    "m/s");
grid on;
xlabel("Time (s)");
ylabel("e_v (m/s)");
title(sprintf( ...
    "Speed error: RMS %.3f m/s, peak %.3f m/s", ...
    metrics.speed_rmse_mps, metrics.speed_peak_mps));

%% Lateral path-tracking error

nexttile(layout);
plot( ...
    time, lateralError, ...
    LineWidth=1.3, ...
    DisplayName="Tracking error");
addErrorReferenceLines( ...
    metrics.lateral_rmse_m, ...
    metrics.lateral_peak_m, ...
    "m");
lateralLimit_m = controller.maximumLateralError_m;

yline( ...
    lateralLimit_m, "b--", ...
    LineWidth=1.3, ...
    DisplayName=sprintf( ...
    "Configured limit = \\pm%.2f m", lateralLimit_m));

yline( ...
    -lateralLimit_m, "b--", ...
    LineWidth=1.3, ...
    HandleVisibility="off");
grid on;
xlabel("Time (s)");
ylabel("e_y (m)");
title(sprintf( ...
    "Lateral error: RMS %.3f m, peak %.3f m", ...
    metrics.lateral_rmse_m, metrics.lateral_peak_m));
legend(Location="best");

%% Heading tracking error

nexttile(layout);
plot( ...
    time, rad2deg(headingError), ...
    LineWidth=1.3, ...
    DisplayName="Tracking error");
addErrorReferenceLines( ...
    metrics.heading_rmse_deg, ...
    metrics.heading_peak_deg, ...
    "deg");
headingLimit_deg = ...
    rad2deg(controller.maximumHeadingError_rad);

yline( ...
    headingLimit_deg, "b--", ...
    LineWidth=1.3, ...
    DisplayName=sprintf( ...
    "Configured limit = \\pm%.1f deg", headingLimit_deg));

yline( ...
    -headingLimit_deg, "b--", ...
    LineWidth=1.3, ...
    HandleVisibility="off");
grid on;
xlabel("Time (s)");
ylabel("e_\psi (deg)");
title(sprintf( ...
    "Heading error: RMS %.3f deg, peak %.3f deg", ...
    metrics.heading_rmse_deg, metrics.heading_peak_deg));
legend(Location="best");

%% Lateral-error constraint slack

nexttile(layout);

plot( ...
    slackTime, ...
    firstEySlack, ...
    LineWidth=1.2, ...
    DisplayName="First predicted stage");

hold on;

plot( ...
    slackTime, ...
    maxEySlack, ...
    LineWidth=1.3, ...
    DisplayName="Maximum over horizon");

yline( ...
    0, "k-", ...
    HandleVisibility="off");

hold off;
grid on;

xlabel("Time (s)");
ylabel("e_y slack (m)");

title(sprintf( ...
    "Lateral-error slack: maximum predicted %.4f m", ...
    metrics.maximum_predicted_ey_slack_m));

legend(Location="best");

%% Heading-error constraint slack

nexttile(layout);

plot( ...
    slackTime, ...
    firstEpsiSlack_deg, ...
    LineWidth=1.2, ...
    DisplayName="First predicted stage");

hold on;

plot( ...
    slackTime, ...
    maxEpsiSlack_deg, ...
    LineWidth=1.3, ...
    DisplayName="Maximum over horizon");

yline( ...
    0, "k-", ...
    HandleVisibility="off");

hold off;
grid on;

xlabel("Time (s)");
ylabel("e_\psi slack (deg)");

title(sprintf( ...
    "Heading-error slack: maximum predicted %.4f deg", ...
    metrics.maximum_predicted_epsi_slack_deg));

legend(Location="best");

if ~isnan(actuationDelay_s)
    delay_ms = actuationDelay_s * 1e3;
    titleText = "Tracking Errors: " + scenarioTitle + " — " + environmentName + ...
                " (delay = " + num2str(delay_ms, '%.1f') + " ms)";
else
    titleText = "Tracking Errors: " + scenarioTitle + " — " + environmentName;
end

title(layout, titleText);

end

function addErrorReferenceLines(rmsValue, peakValue, units)
%ADDERRORREFERENCELINES Show symmetric RMS and peak error magnitudes.

yline( ...
    0, "k-", ...
    DisplayName="Zero error");

yline( ...
    rmsValue, "r:", ...
    LineWidth=1.4, ...
    DisplayName=sprintf( ...
        "\\pmRMS = %.3f %s", rmsValue, units));

yline( ...
    -rmsValue, "r:", ...
    LineWidth=1.4, ...
    HandleVisibility="off");

yline( ...
    peakValue, "m--", ...
    LineWidth=1.2, ...
    DisplayName=sprintf( ...
        "\\pmPeak = %.3f %s", peakValue, units));

yline( ...
    -peakValue, "m--", ...
    LineWidth=1.2, ...
    HandleVisibility="off");
end
