function [figureHandle, metrics] = ...
    plot_phase0_tracking_errors( ...
        results, scenario, environmentName, controller)
%PLOT_PHASE0_TRACKING_ERRORS Plot e_v, e_y, and e_psi with metrics.

time = results.time_s;
speedError = results.ev_mps;
lateralError = results.ey_m;
headingError = results.epsi_rad;

assert(all(isfinite( ...
    [time; speedError; lateralError; headingError])), ...
    "Tracking-error results contain NaN or Inf values.");

metrics = sdv.metrics.computeTracking(results);

scenarioTitle = replace(string(scenario.name), "_", " ");
environmentName = replace(string(environmentName), "_", " ");


figureHandle = figure( ...
    Name="Phase 0 tracking errors: " + scenarioTitle, ...
    Color="w", ...
    Position=[150 80 1150 850]);

layout = tiledlayout(figureHandle, 3, 1);
layout.TileSpacing = "compact";
layout.Padding = "compact";

%% Longitudinal-speed tracking error

nexttile(layout);
plot( ...
    time, speedError, ...
    LineWidth=1.3, ...
    DisplayName="Tracking error");
addErrorReferenceLines( ...
    metrics.speed_rmse_mps, ...
    metrics.speed_peak_mps, ...
    "m/s");
grid on;
xlabel("Time (s)");
ylabel("e_v (m/s)");
title(sprintf( ...
    "Speed error: RMS %.3f m/s, peak %.3f m/s", ...
    metrics.speed_rmse_mps, metrics.speed_peak_mps));

%% Lateral path-tracking error

nexttile(layout);
plot( ...
    time, lateralError, ...
    LineWidth=1.3, ...
    DisplayName="Tracking error");
addErrorReferenceLines( ...
    metrics.lateral_rmse_m, ...
    metrics.lateral_peak_m, ...
    "m");
lateralLimit_m = controller.maximumLateralError_m;

yline( ...
    lateralLimit_m, "b--", ...
    LineWidth=1.3, ...
    DisplayName=sprintf( ...
    "Configured limit = \\pm%.2f m", lateralLimit_m));

yline( ...
    -lateralLimit_m, "b--", ...
    LineWidth=1.3, ...
    HandleVisibility="off");
grid on;
xlabel("Time (s)");
ylabel("e_y (m)");
title(sprintf( ...
    "Lateral error: RMS %.3f m, peak %.3f m", ...
    metrics.lateral_rmse_m, metrics.lateral_peak_m));
legend(Location="best");

%% Heading tracking error

nexttile(layout);
plot( ...
    time, rad2deg(headingError), ...
    LineWidth=1.3, ...
    DisplayName="Tracking error");
addErrorReferenceLines( ...
    metrics.heading_rmse_deg, ...
    metrics.heading_peak_deg, ...
    "deg");
headingLimit_deg = ...
    rad2deg(controller.maximumHeadingError_rad);

yline( ...
    headingLimit_deg, "b--", ...
    LineWidth=1.3, ...
    DisplayName=sprintf( ...
    "Configured limit = \\pm%.1f deg", headingLimit_deg));

yline( ...
    -headingLimit_deg, "b--", ...
    LineWidth=1.3, ...
    HandleVisibility="off");
grid on;
xlabel("Time (s)");
ylabel("e_\psi (deg)");
title(sprintf( ...
    "Heading error: RMS %.3f deg, peak %.3f deg", ...
    metrics.heading_rmse_deg, metrics.heading_peak_deg));
legend(Location="best");

title(layout, "Tracking Errors: " + scenarioTitle + " — " + environmentName);

end

function addErrorReferenceLines(rmsValue, peakValue, units)
%ADDERRORREFERENCELINES Show symmetric RMS and peak error magnitudes.

yline( ...
    0, "k-", ...
    DisplayName="Zero error");

yline( ...
    rmsValue, "r:", ...
    LineWidth=1.4, ...
    DisplayName=sprintf( ...
        "\\pmRMS = %.3f %s", rmsValue, units));

yline( ...
    -rmsValue, "r:", ...
    LineWidth=1.4, ...
    HandleVisibility="off");

yline( ...
    peakValue, "m--", ...
    LineWidth=1.2, ...
    DisplayName=sprintf( ...
        "\\pmPeak = %.3f %s", peakValue, units));

yline( ...
    -peakValue, "m--", ...
    LineWidth=1.2, ...
    HandleVisibility="off");
end
