function track = save_phase0_scenario(track, outputFolder, writeText)
%SAVE_PHASE0_SCENARIO Validate and save a Phase 0 spatial scenario.

arguments
    track (1,1) struct
    outputFolder (1,1) string
    writeText (1,1) logical = true
end

if ~isfolder(outputFolder)
    mkdir(outputFolder);
end

track.schema_version = "phase0-scenario-v1";
track.yaw_rate_ref_radps = ...
    track.vx_ref_mps .* track.curvature_1pm;
track.mpc_reference = [ ...
    track.vx_ref_mps, ...
    zeros(numel(track.station_m),1), ...
    track.yaw_rate_ref_radps, ...
    zeros(numel(track.station_m),1), ...
    zeros(numel(track.station_m),1)];

validate_phase0_scenario(track);

matFile = fullfile(outputFolder, track.name + ".mat");
save(matFile, "track");

if writeText
    inspectionTable = table( ...
        track.station_m, track.X_ref_m, track.Y_ref_m, ...
        track.psi_ref_rad, track.curvature_1pm, ...
        track.local_speed_limit_mps, track.vx_ref_mps, ...
        track.yaw_rate_ref_radps, ...
        VariableNames=["station_m","X_ref_m","Y_ref_m","psi_ref_rad", ...
    "curvature_1pm","local_speed_limit_mps","vx_ref_mps","yaw_rate_ref_radps"]);
    writetable(inspectionTable, ...
        fullfile(outputFolder, track.name + ".txt"), ...
        Delimiter="\t");
end
end
