function [vxFinal, vxSteady, vxForward, traversalTime] = ...
    three_pass_speed_profile( ...
        station, ...
        curvature, ...
        localSpeedLimit, ...
        parameters)
%THREEPASSSPEEDPROFILE Generate a physically feasible speed reference.

numberOfPoints = numel(station);

mass = parameters.mass_kg;
gravity = parameters.gravity_mps2;
mu = parameters.road_friction_mu;

maximumTireForce = ...
    mu * mass * gravity;

%% Pass 1: curvature/lateral-acceleration limit

lateralAccelerationLimit = min( ...
    parameters.maximum_lateral_acceleration_mps2, ...
    mu * gravity);

curvatureFloor = 1e-8;

vxCurvature = sqrt( ...
    lateralAccelerationLimit ./ ...
    max(abs(curvature), curvatureFloor));

vxSteady = min( ...
    vxCurvature, ...
    localSpeedLimit);

%% Pass 2: forward acceleration limit

vxForward = zeros(numberOfPoints, 1);

vxForward(1) = min( ...
    parameters.initial_speed_mps, ...
    vxSteady(1));

for index = 2:numberOfPoints

    ds = station(index) - station(index - 1);
    currentSpeed = vxForward(index - 1);

    lateralForce = ...
        mass * currentSpeed^2 * ...
        abs(curvature(index - 1));

    longitudinalTireForce = sqrt(max( ...
        maximumTireForce^2 - lateralForce^2, ...
        0));

    availableDriveForce = min( ...
        parameters.maximum_drive_force_N, ...
        longitudinalTireForce);

    rollingResistance = ...
        parameters.rolling_resistance_coefficient * ...
        mass * gravity * ...
        smooth_speed_sign(currentSpeed, parameters);

    aerodynamicDrag = ...
        0.5 * ...
        parameters.air_density_kgpm3 * ...
        parameters.drag_coefficient * ...
        parameters.frontal_area_m2 * ...
        currentSpeed^2;

    longitudinalAcceleration = ( ...
        availableDriveForce - ...
        rollingResistance - ...
        aerodynamicDrag) / mass;

    candidateSpeedSquared = ...
        currentSpeed^2 + ...
        2 * longitudinalAcceleration * ds;

    candidateSpeed = sqrt(max( ...
        candidateSpeedSquared, ...
        0));

    vxForward(index) = min([ ...
        candidateSpeed, ...
        vxSteady(index), ...
        localSpeedLimit(index)]);
end

%% Pass 3: backward braking limit

vxFinal = zeros(numberOfPoints, 1);
vxFinal(end) = vxForward(end);

for index = numberOfPoints-1:-1:1

    ds = station(index + 1) - station(index);
    nextSpeed = vxFinal(index + 1);

    lateralForce = ...
        mass * nextSpeed^2 * ...
        abs(curvature(index + 1));

    longitudinalTireForce = sqrt(max( ...
        maximumTireForce^2 - lateralForce^2, ...
        0));

    availableBrakingForce = min( ...
        parameters.maximum_braking_force_N, ...
        longitudinalTireForce);

    rollingResistance = ...
        parameters.rolling_resistance_coefficient * ...
        mass * gravity * ...
        smooth_speed_sign(nextSpeed, parameters);

    aerodynamicDrag = ...
        0.5 * ...
        parameters.air_density_kgpm3 * ...
        parameters.drag_coefficient * ...
        parameters.frontal_area_m2 * ...
        nextSpeed^2;

    availableDeceleration = ( ...
        availableBrakingForce + ...
        rollingResistance + ...
        aerodynamicDrag) / mass;

    allowableSpeed = sqrt(max( ...
        nextSpeed^2 + ...
        2 * availableDeceleration * ds, ...
        0));

    vxFinal(index) = min([ ...
        allowableSpeed, ...
        vxForward(index), ...
        vxSteady(index)]);
end

%% Traversal-time estimate

averageSpeed = 0.5 * ( ...
    vxFinal(1:end-1) + ...
    vxFinal(2:end));

averageSpeed = max( ...
    averageSpeed, ...
    parameters.minimum_speed_for_time_mps);

timeStep = diff(station) ./ averageSpeed;
traversalTime = sum(timeStep);

end

function value = smooth_speed_sign(speed_mps, parameters)
% Rolling resistance must vanish at zero speed so a stop is an equilibrium.

if isfield(parameters, "rolling_resistance_smoothing_speed_mps")
    smoothingSpeed_mps = ...
        parameters.rolling_resistance_smoothing_speed_mps;
else
    smoothingSpeed_mps = 0.10;
end

value = tanh(speed_mps/max(smoothingSpeed_mps, eps));
end
