function validation = validate_phase0_scenario(track)
%VALIDATE_PHASE0_SCENARIO Enforce the common Phase 0 scenario schema.

requiredFields = [ ...
    "schema_version","name","description","source", ...
    "station_m","X_ref_m","Y_ref_m","psi_ref_rad", ...
    "curvature_1pm","local_speed_limit_mps","vx_ref_mps", ...
    "yaw_rate_ref_radps","initial_speed_mps", ...
    "traversal_time_s","simulation_stop_time_s", ...
    "road_friction_mu","slope_rad","stop_event_table"];

for fieldName = requiredFields
    assert(isfield(track, fieldName), ...
        "Scenario is missing required field '%s'.", fieldName);
end

signals = { ...
    track.station_m, track.X_ref_m, track.Y_ref_m, ...
    track.psi_ref_rad, track.curvature_1pm, ...
    track.local_speed_limit_mps, track.vx_ref_mps, ...
    track.yaw_rate_ref_radps};
signalLengths = cellfun(@numel, signals);

assert(all(signalLengths == signalLengths(1)), ...
    "All spatial scenario arrays must have equal length.");
assert(all(cellfun(@(value) all(isfinite(value(:))), signals)), ...
    "Scenario arrays must contain only finite values.");
assert(all(diff(track.station_m) > 0), ...
    "Scenario station must be strictly increasing.");
assert(all(track.vx_ref_mps >= 0), ...
    "Reference speed must be nonnegative.");
assert(isequal(size(track.stop_event_table), [2 5]), ...
    "stop_event_table must be a fixed 2-by-5 matrix.");

ds_m = diff(track.station_m);
derivedCurvature_1pm = diff(unwrap(track.psi_ref_rad)) ./ ds_m;
curvatureAgreement = max(abs( ...
    derivedCurvature_1pm - ...
    0.5*(track.curvature_1pm(1:end-1) + ...
         track.curvature_1pm(2:end))));

allowedCurvatureError_1pm = max(5e-4, ...
    0.05*max(abs(track.curvature_1pm)));
assert(curvatureAgreement <= allowedCurvatureError_1pm, ...
    "Yaw derivative and curvature disagree (max error %.4g 1/m).", ...
    curvatureAgreement);

lateralAcceleration_mps2 = ...
    track.vx_ref_mps.^2 .* abs(track.curvature_1pm);
assert(max(lateralAcceleration_mps2) <= ...
    track.maximum_lateral_acceleration_mps2 + 1e-6, ...
    "Scenario exceeds its lateral-acceleration envelope.");

activeStops = track.stop_event_table(:,1) > 0.5;
for stopStation_m = track.stop_event_table(activeStops,2)'
    [~, stopIndex] = min(abs(track.station_m - stopStation_m));
    assert(track.vx_ref_mps(stopIndex) == 0, ...
        "Every active stop must contain an exact zero-speed sample.");
end

validation = struct();
validation.number_of_points = signalLengths(1);
validation.maximum_curvature_error_1pm = curvatureAgreement;
validation.maximum_lateral_acceleration_mps2 = ...
    max(lateralAcceleration_mps2);
validation.passed = true;
end
