%% Phase 3 batch experiment

startup_project;

projectRoot = string( ...
    matlab.project.currentProject().RootFolder);

modelName = "phase3_scheduler_testbed";

scenarioNames = [
    sdv.enum.ScenarioName.highway_cruise
    sdv.enum.ScenarioName.aggressive_maneuver
    sdv.enum.ScenarioName.urban_profile
    ];

environmentNames = [
    sdv.enum.EnvironmentName.dry_road
    sdv.enum.EnvironmentName.low_friction_road
    ];

loadCases = [
    "off"
    "maximum"
    ];
loadIndex = 2;

baseRandomSeed = 1111;
loadTaskPeriod_s = 0.050;

resultsRoot = fullfile( ...
    projectRoot, ...
    "phase3", ...
    "results", ...
    "aligned_scheduler_runs");

if ~isfolder(resultsRoot)
    mkdir(resultsRoot);
end

load_system(modelName);

runtimeChecked = false;
phase3Summary = table();
runSummary = table( ...
    strings(0,1), ...
    strings(0,1), ...
    strings(0,1), ...
    strings(0,1), ...
    strings(0,1), ...
    zeros(0,1), ...
    'VariableNames', { ...
    'Scenario', ...
    'Environment', ...
    'LoadCase', ...
    'Status', ...
    'ResultsFile', ...
    'ElapsedTime_s'});

%% Scenario loop

for scenarioIndex = 1:numel(scenarioNames)

    scenarioName = scenarioNames(scenarioIndex);
    scenarioLabel = string(scenarioName);

    fprintf( ...
        "\n========================================\n" + ...
        "Scenario: %s\n" + ...
        "========================================\n", ...
        scenarioLabel);

    %% Scenario-dependent configuration

    configuration = ...
        build_phase0_configuration(scenarioName);

    vehicleParams = configuration.vehicle;
    controllerParams = configuration.controller;
    simulationParams = configuration.simulation;
    adaptiveModelParams = configuration.adaptiveModel;

    if ~runtimeChecked
        check_runtime_requirements(controllerParams);
        runtimeChecked = true;
    end

    initialControllerMeasurement = [
        simulationParams.initial_speed_mps
        0
        0
        simulationParams.initial_x_m
        simulationParams.initial_y_m
        simulationParams.initial_yaw_rad
        ];

    UT = legacy_plant_parameters( ...
        vehicleParams, ...
        simulationParams);

    acadosSettings = ...
        acados_ocp_parameters(controllerParams);

    acados_nominal_input = reshape( ...
        acadosSettings.nominal_input, ...
        2, ...
        1);

    track_ref_table = ...
        configuration.scenario.lookup_table;

    scenario_stop_table = ...
        configuration.scenario.stop_event_table;

    stopTime_s = ...
        configuration.scenario.simulation_stop_time_s;

    final_track_index = ...
        size(track_ref_table, 1);

    %% Load this scenario's demand tags once

    demandTagsFile = fullfile( ...
        projectRoot, ...
        "phase3", ...
        "results", ...
        "aligned_demand_tags", ...
        scenarioLabel + "_aligned_tags.mat");

    assert( ...
        isfile(demandTagsFile), ...
        "Demand-tag file not found: %s", ...
        demandTagsFile);

    demandTagsData = load(demandTagsFile, "alignedTags");

    assert( ...
        isfield(demandTagsData, "alignedTags"), ...
        "Variable 'alignedTags' is missing from %s.", ...
        demandTagsFile);

    assert( ...
        isfield( ...
            demandTagsData.alignedTags, ...
            "timing_table"), ...
        "Field alignedTags.timing_table is missing.");

    demandTagsTable = ...
        demandTagsData.alignedTags.timing_table;

    tableVariableNames = string( ...
        demandTagsTable.Properties.VariableNames);

    assert( ...
        all(ismember( ...
            ["time_s", "activeMode", "activePeriod_s"], ...
            tableVariableNames)), ...
        "Aligned tags require time_s, activeMode, and activePeriod_s.");

    % The permitted mode, not the pending request, drives the model.
    demandMode = double(demandTagsTable.activeMode(:));

    tagTime_s = double( ...
        demandTagsTable.time_s(:));

    assert( ...
        numel(tagTime_s) == numel(demandMode), ...
        "Demand-tag time and mode lengths do not match.");

    assert( ...
        ~isempty(tagTime_s) && tagTime_s(1) == 0 ...
            && all(isfinite(tagTime_s)) && all(diff(tagTime_s) > 0), ...
        "Demand-tag time must start at zero and increase strictly.");

    assert( ...
        all(ismember(demandMode, [1 2 3])), ...
        "Demand modes must be LOW=1, MEDIUM=2, or HIGH=3.");

    correspondingActivePeriod_s = ...
        double(demandTagsTable.activePeriod_s(:));
    periodLookup_s = [0.050; 0.020; 0.010];

    assert( ...
        all(isfinite(correspondingActivePeriod_s)) ...
            && all(abs(correspondingActivePeriod_s ...
                - periodLookup_s(demandMode)) < 1e-9), ...
        "Aligned periods must match the model's 50/20/10 ms modes.");

    activePeriodSignal = struct( ...
        Time_s=tagTime_s, ...
        Data=correspondingActivePeriod_s);
    demandMode = uint8(demandMode);

    phase3_demand_mode_ts = timeseries( ...
        demandMode, ...
        tagTime_s);

    phase3_demand_mode_ts.Name = ...
        "phase3_demand_mode";

    phase3_demand_mode_ts = setinterpmethod( ...
        phase3_demand_mode_ts, ...
        "zoh");

    %% Environment loop

    for environmentIndex = 1:numel(environmentNames)
        
        environmentName = ...
            environmentNames(environmentIndex);

        environmentLabel = ...
            string(environmentName);

        durationBank = struct;

        durationBank.LOW = ...
            load_control_task_durations( ...
            scenarioLabel, ...
            environmentLabel, ...
            "phase3_50ms");

        durationBank.MEDIUM = ...
            load_control_task_durations( ...
            scenarioLabel, ...
            environmentLabel, ...
            "phase3_20ms");

        durationBank.HIGH = ...
            load_control_task_durations( ...
            scenarioLabel, ...
            environmentLabel, ...
            "phase0");

        fprintf( ...
            "\nEnvironment: %s\n", ...
            environmentLabel);

        environment = load_env_profile( ...
            lower(environmentLabel), ...
            stopTime_s, ...
            FrictionDropTime_s=10);

        roadFrictionProfile = ...
            environment.road_friction_profile;

        durationData = ...
            load_control_task_durations( ...
                scenarioLabel, ...
                environmentLabel);

        % Keep the same controller-duration realization for every
        % load case within this scenario/environment combination.
        randomSeed = ...
            baseRandomSeed ...
            + 100*scenarioIndex ...
            + 10*environmentIndex;

        controlTaskDuration = ...
            create_phase3_control_task_duration( ...
                phase3_demand_mode_ts, ...
                durationBank, ...
                stopTime_s, ...
                randomSeed, ...
                SupervisorSampleTime_s=0.010); %% always check but default is 10ms which is controller minimum sampling rate

        %% Load-case loop

        for load_duration_s = 0.020:0.005:0.045

            loadCase = loadCases(loadIndex);

            fprintf( ...
                "  Load case: %s\n", ...
                loadCase);

            switch loadCase

                case "off"
                    loadTaskDuration_s = 1e-6;

                case "maximum"
                    loadTaskDuration_s = load_duration_s;

                otherwise
                    error( ...
                        "Unknown load case: %s", ...
                        loadCase);
            end

            loadReleaseTime_s = ...
                (0:loadTaskPeriod_s:stopTime_s).';

            loadTaskDuration = timeseries( ...
                repmat( ...
                    loadTaskDuration_s, ...
                    numel(loadReleaseTime_s), ...
                    1), ...
                loadReleaseTime_s);

            loadTaskDuration = setinterpmethod( ...
                loadTaskDuration, ...
                "zoh");

            %% Create an isolated simulation input

            simulationInput = ...
                Simulink.SimulationInput(modelName);

            simulationVariables = struct( ...
                phase3_demand_mode_ts=phase3_demand_mode_ts, ...
                roadFrictionProfile=roadFrictionProfile, ...
                controlTaskDuration=controlTaskDuration, ...
                loadTaskDuration=loadTaskDuration, ...
                vehicleParams=vehicleParams, ...
                controllerParams=controllerParams, ...
                simulationParams=simulationParams, ...
                adaptiveModelParams=adaptiveModelParams, ...
                initialControllerMeasurement= ...
                    initialControllerMeasurement, ...
                UT=UT, ...
                acados_nominal_input= ...
                    acados_nominal_input, ...
                track_ref_table=track_ref_table, ...
                scenario_stop_table=scenario_stop_table, ...
                final_track_index=final_track_index ...
            );

            simulationVariableNames = ...
                fieldnames(simulationVariables);

            for variableIndex = ...
                    1:numel(simulationVariableNames)

                variableName = ...
                    simulationVariableNames{variableIndex};

                simulationInput = ...
                    simulationInput.setVariable( ...
                        variableName, ...
                        simulationVariables.(variableName));
            end

            simulationInput = ...
                simulationInput.setModelParameter( ...
                    StopTime=string(stopTime_s), ...
                    ReturnWorkspaceOutputs="on", ...
                    SignalLogging="on", ...
                    SignalLoggingName="logsout", ...
                    SignalInfNanChecking="error");

            %% Combination-specific results folder

            resultsFolder = fullfile( ...
                resultsRoot, ...
                scenarioLabel, ...
                environmentLabel, ...
                "load_" + loadTaskDuration_s);

            if ~isfolder(resultsFolder)
                mkdir(resultsFolder);
            end

            resultsFile = fullfile( ...
                resultsFolder, ...
                "simulation_output.mat");

            runMetadata = struct( ...
                scenario=scenarioLabel, ...
                environment=environmentLabel, ...
                load_case=loadCase, ...
                random_seed=randomSeed, ...
                stop_time_s=stopTime_s, ...
                load_task_period_s=loadTaskPeriod_s, ...
                load_task_duration_s=loadTaskDuration_s, ...
                demand_tags_file=demandTagsFile);

            %% Run and save immediately
            runIdsBefore = Simulink.sdi.getAllRunIDs;
            runTimer = tic;

            try
                simulationOutput = sim(simulationInput);
                
                elapsedTime_s = toc(runTimer);

                save( ...
                    resultsFile, ...
                    "simulationOutput", ...
                    "configuration", ...
                    "demandTagsTable", ...
                    "phase3_demand_mode_ts", ...
                    "controlTaskDuration", ...
                    "loadTaskDuration", ...
                    "runMetadata", ...
                    "-v7.3");

                runStatus = "completed";

                fprintf( ...
                    "  Completed in %.2f s\n", ...
                    elapsedTime_s);

            catch simulationError

                elapsedTime_s = toc(runTimer);
                runStatus = "failed";

                failureReport = string(getReport( ...
                    simulationError, ...
                    "extended", ...
                    "hyperlinks", ...
                    "off"));

                failureFile = fullfile( ...
                    resultsFolder, ...
                    "failure.mat");

                save( ...
                    failureFile, ...
                    "failureReport", ...
                    "runMetadata");

                resultsFile = failureFile;

                warning( ...
                    "Phase3:SimulationFailed", ...
                    "%s / %s / %s failed:\n%s", ...
                    scenarioLabel, ...
                    environmentLabel, ...
                    loadCase, ...
                    simulationError.message);
            end
            
            if loadCase == "off"
                reportedLoadExecution_ms = 0;
            else
                reportedLoadExecution_ms = ...
                    1e3*loadTaskDuration_s;
            end

            metadata = struct( ...
                Policy="variable_rate", ...
                Scenario=scenarioLabel, ...
                Environment=environmentLabel, ...
                LoadCase=loadCase, ...
                LoadExecutionTime_ms=reportedLoadExecution_ms, ...
                LoadTaskExecutionTime_s=loadTaskDuration_s, ...
                LoadTaskPeriod_s=loadTaskPeriod_s, ...
                ActivePeriodSignal=activePeriodSignal, ...
                RandomSeed=randomSeed, ...
                StopTime_s=stopTime_s);

            [runArtifact, newSummaryRow] = ...
                collect_phase3_results( ...
                simulationOutput, ...
                modelName, ...
                runIdsBefore, ...
                track_ref_table, ...
                metadata);

            runArtifact.runFile = string(resultsFile);
            newSummaryRow.RunFile = string(resultsFile);

            save( ...
                resultsFile, ...
                "runArtifact", ...
                "-append");

            phase3Summary = [
                phase3Summary
                newSummaryRow
                ];

            runSummary(end+1,:) = { ...
                scenarioLabel, ...
                environmentLabel, ...
                loadCase, ...
                runStatus, ...
                string(resultsFile), ...
                elapsedTime_s ...
                };
        end
    end
end

phase3SummaryFile = fullfile( ...
    resultsRoot, ...
    "phase3_summary.mat");

phase3SummaryCsv = fullfile( ...
    resultsRoot, ...
    "phase3_summary.csv");

save( ...
    phase3SummaryFile, ...
    "phase3Summary");

writetable( ...
    phase3Summary, ...
    phase3SummaryCsv);
%% Save batch summary

summaryMatFile = fullfile( ...
    resultsRoot, ...
    "batch_summary.mat");

summaryCsvFile = fullfile( ...
    resultsRoot, ...
    "batch_summary.csv");

save( ...
    summaryMatFile, ...
    "runSummary");

writetable( ...
    runSummary, ...
    summaryCsvFile);

disp(runSummary);

fprintf("Relevant plot files:\n%s\n%s\n%s\n", ...
    fullfile(projectRoot, "phase3", "plot", ...
        "plot_phase3_comparison.m"), ...
    fullfile(projectRoot, "phase3", "plot", ...
        "plot_phase3_demo.m"), ...
    fullfile(projectRoot, "phase3", "plot", ...
        "plot_phase3_load_task_sweep.m"));
