function taggedScenario = ...
    tag_phase3_scenario_file( ...
    scenarioFile, ...
    parameters)

arguments
    scenarioFile (1,1) string
    parameters (1,1) struct = ...
        phase3_supervisor_parameters()
end

assert(isfile(scenarioFile), ...
    "Scenario file was not found:\n%s", ...
    scenarioFile);

[~, scenarioName] = ...
    fileparts(scenarioFile);

% This directly loads the track variable from the specified .mat file
% and constructs the seven-column lookup table required by the tagger.
reference = generate_ref(scenarioFile);

taggedScenario = tag_phase3_scenario( ...
    string(scenarioName), ...
    reference.lookup_table, ...
    parameters);

% Preserve source/reference information for reproducibility.
taggedScenario.source_file = scenarioFile;
taggedScenario.reference = reference;

end