function result = estimate_local_mpc_gain(config)
%ESTIMATE_LOCAL_MPC_GAIN Estimate u-uStar = -K(x-xStar).
%
% State order:
%   [vx; vy; yawRate; lateralError; headingError]
%
% Input order:
%   [frontAxleTorque; roadWheelAngle]

controller = config.controller;

xStar = controller.nominal_state(:);
stateReference = xStar;
curvatureReference = 0;

% Initial perturbation sizes in each state's physical unit.
baseStep = [
    0.05              % vx, m/s
    0.01              % vy, m/s
    0.002             % yaw rate, rad/s
    0.01              % lateral error, m
    deg2rad(0.1)      % heading error, rad
    ];

% Multiple sizes check whether the identified gain is genuinely local.
stepMultipliers = [0.5, 1, 2];

[solver, metadata] = create_acados_analysis_solver(config);

%% Nominal control action

[uStar, nominalDiagnostics] = evaluatePolicy( ...
    solver, ...
    metadata, ...
    xStar, ...
    stateReference, ...
    curvatureReference, ...
    xStar);

assert(nominalDiagnostics.raw_status == 0, ...
    "Nominal acados solution did not converge.");

nx = metadata.nx;
nu = numel(uStar);
numberOfScales = numel(stepMultipliers);

KByScale = zeros(nu, nx, numberOfScales);

% Samples used for a least-squares fit.
statePerturbations = zeros( ...
    nx, ...
    2*nx*numberOfScales);

inputPerturbations = zeros( ...
    nu, ...
    2*nx*numberOfScales);

sampleIndex = 0;

%% Symmetric state perturbations

for scaleIndex = 1:numberOfScales

    step = ...
        stepMultipliers(scaleIndex)*baseStep;

    for stateIndex = 1:nx

        direction = zeros(nx,1);
        direction(stateIndex) = 1;

        xPlus = ...
            xStar + step(stateIndex)*direction;

        xMinus = ...
            xStar - step(stateIndex)*direction;

        [uPlus, plusDiagnostics] = evaluatePolicy( ...
            solver, metadata, xPlus, ...
            stateReference, curvatureReference, xPlus);

        [uMinus, minusDiagnostics] = evaluatePolicy( ...
            solver, metadata, xMinus, ...
            stateReference, curvatureReference, xMinus);

        if plusDiagnostics.raw_status ~= 0
            solver.print("stat");
        
            error( ...
                "Positive perturbation of state %d failed; " + ...
                "raw acados status = %d.", ...
                stateIndex, ...
                plusDiagnostics.raw_status);
        end

        if minusDiagnostics.raw_status ~= 0
            solver.print("stat");
        
            error( ...
                "Negative perturbation of state %d failed; " + ...
                "raw acados status = %d.", ...
                stateIndex, ...
                minusDiagnostics.raw_status);
        end
        % Because u-uStar = -K(x-xStar).
        KByScale(:,stateIndex,scaleIndex) = ...
            -(uPlus-uMinus)/(2*step(stateIndex));

        sampleIndex = sampleIndex + 1;
        statePerturbations(:,sampleIndex) = ...
            xPlus-xStar;
        inputPerturbations(:,sampleIndex) = ...
            uPlus-uStar;

        sampleIndex = sampleIndex + 1;
        statePerturbations(:,sampleIndex) = ...
            xMinus-xStar;
        inputPerturbations(:,sampleIndex) = ...
            uMinus-uStar;
    end
end

%% Fit one gain using all perturbations

% inputPerturbations ≈ J*statePerturbations
policyJacobian = ...
    inputPerturbations*pinv(statePerturbations);

K = -policyJacobian;

predictedInputPerturbations = ...
    -K*statePerturbations;

relativeFitError = ...
    norm( ...
        inputPerturbations-predictedInputPerturbations, ...
        "fro") ...
    / max(norm(inputPerturbations,"fro"), eps);

%% Check sensitivity to perturbation size

gainVariation = zeros(numberOfScales,1);

for scaleIndex = 1:numberOfScales
    gainVariation(scaleIndex) = ...
        norm( ...
            KByScale(:,:,scaleIndex)-K, ...
            "fro") ...
        / max(norm(K,"fro"), eps);
end

%% Return results

result = struct();

result.K = K;
result.policy_jacobian = policyJacobian;
result.x_star = xStar;
result.u_star = uStar;
result.base_step = baseStep;
result.K_by_scale = KByScale;
result.relative_fit_error = relativeFitError;
result.relative_gain_variation = gainVariation;
result.nominal_diagnostics = nominalDiagnostics;

fprintf("\nEstimated local MPC gain K:\n");
disp(array2table( ...
    K, ...
    VariableNames=cellstr(controller.state_names), ...
    RowNames=cellstr(controller.input_names)));

fprintf( ...
    "Relative local-fit error: %.4f %%\n", ...
    100*relativeFitError);

fprintf( ...
    "Gain variation for [0.5, 1, 2] perturbation scales: " + ...
    "%.2f%%, %.2f%%, %.2f%%\n", ...
    100*gainVariation(1), ...
    100*gainVariation(2), ...
    100*gainVariation(3));

end


function [u0, diagnostics] = evaluatePolicy( ...
    solver, metadata, measuredState, ...
    stateReference, curvatureReference, xGuess)
%EVALUATEPOLICY Solve from a consistent initial guess.

solver.set( ...
    'init_x', ...
    repmat(xGuess, 1, metadata.N + 1));

solver.set( ...
    'init_u', ...
    repmat( ...
        metadata.settings.nominal_input, ...
        1, metadata.N));

solver.set( ...
    'init_pi', ...
    zeros(metadata.nx, metadata.N));

[~, ~, ~, diagnostics] = solve_acados_step( ...
    solver, ...
    metadata, ...
    measuredState, ...
    stateReference, ...
    curvatureReference);

% Use the raw first optimized input. Do not use the fallback command.
u0 = diagnostics.predicted_input(:,1);

end