startup_project;

config = ...
    build_phase0_configuration("highway_cruise");

% Phase 1.4 requires the unconstrained local MPC law.
config.controller.enableIntermediateStateConstraints = false;
config.controller.enableTerminalStateConstraints = false;

gainResult = ...
    estimate_local_mpc_gain(config);

K = gainResult.K;
%% Linearize the nonlinear prediction model

curvatureStar = 0;

linearModel = ...
    build_local_linear_model( ...
    config, ...
    gainResult, ...
    curvatureStar);

Ac = linearModel.Ac;
Bc = linearModel.Bc;
Ad = linearModel.Ad;
Bd = linearModel.Bd;

% [~, dynamicsFunction] = ...
%     build_acados_prediction_model( ...
%     config.adaptiveModel);

stateDerivative = full( ...
    dynamicsFunction( ...
    gainResult.x_star, ...
    gainResult.u_star, ...
    0));

fprintf("Operating-point derivative:\n");
disp(stateDerivative);

fprintf( ...
    "Equilibrium residual norm: %.6e\n", ...
    norm(stateDerivative));

projectRoot = ...
    matlab.project.currentProject().RootFolder;

resultsFolder = fullfile( ...
    projectRoot, ...
    "phase1", ...
    "results", ...
    "analytical_cross_check");

if ~isfolder(resultsFolder)
    mkdir(resultsFolder);
end

save( ...
    fullfile( ...
    resultsFolder, ...
    "local_linear_model.mat"), ...
    "gainResult", ...
    "linearModel", ...
    "Ac", "Bc", "Ad", "Bd", "K");

%% Test augmented delayed closed-loop construction

zeroDelay = ...
    build_delayed_closed_loop_matrix( ...
    Ad, Bd, K, 0);

oneSampleDelay = ...
    build_delayed_closed_loop_matrix( ...
    Ad, Bd, K, 1);

fprintf( ...
    "Zero-delay spectral radius: %.6f\n", ...
    zeroDelay.spectral_radius);

fprintf( ...
    "One-sample-delay spectral radius: %.6f\n", ...
    oneSampleDelay.spectral_radius);

fprintf( ...
    "One sample corresponds to %.3f ms.\n", ...
    1000*config.controller.Ts_s);

%% Spectral-radius delay sweep

maximumAnalyticalDelay_ms = 100;

delayStability = ...
    sweep_delay_spectral_radius( ...
    Ad, ...
    Bd, ...
    K, ...
    config.controller.Ts_s, ...
    maximumAnalyticalDelay_ms);

disp(delayStability.table);

eigenvalueFigure = ...
    plot_delay_eigenvalue_map( ...
    delayStability);

criticalModeFigure = ...
    plot_critical_delay_mode( ...
    delayStability);

%% Validate delayed augmented model using direct simulation

simulationDuration_s = 5;
numberOfSteps = ...
    round(simulationDuration_s/config.controller.Ts_s);

initialPerturbation = [
    0                 % vx perturbation
    0                 % vy perturbation
    0                 % yaw-rate perturbation
    0.01              % lateral-error perturbation, m
    deg2rad(0.1)      % heading-error perturbation, rad
    ];

delayCases = [0, 1, 2];

figure( ...
    Name="Frozen-gain delayed-loop validation", ...
    Color="white");

hold on;

for delaySamples = delayCases

    delayedModel = ...
        build_delayed_closed_loop_matrix( ...
        Ad, Bd, K, delaySamples);

    augmentedState = zeros( ...
        size(delayedModel.augmented_A,1), ...
        numberOfSteps + 1);

    % Current and historical states receive the same initial perturbation.
    for historyIndex = 0:delaySamples

        indices = ...
            historyIndex*5 + (1:5);

        augmentedState(indices,1) = ...
            initialPerturbation;
    end

    for stepIndex = 1:numberOfSteps

        augmentedState(:,stepIndex+1) = ...
            delayedModel.augmented_A ...
            * augmentedState(:,stepIndex);
    end

    currentState = ...
        augmentedState(1:5,:);

    perturbationNorm = ...
        vecnorm(currentState,2,1);

    time_s = ...
        (0:numberOfSteps)*config.controller.Ts_s;

    semilogy( ...
        time_s, ...
        perturbationNorm, ...
        LineWidth=1.4, ...
        DisplayName=sprintf( ...
        "%d samples = %.0f ms", ...
        delaySamples, ...
        1000*delaySamples*config.controller.Ts_s));
end

hold off;
grid on;

xlabel("Time (s)");
ylabel("State-perturbation norm");
title("Frozen Linear Feedback under Delay");
legend(Location="best");