function result = sweep_delay_spectral_radius( ...
    Ad, Bd, K, sampleTime_s, maximumDelay_ms)
%SWEEP_DELAY_SPECTRAL_RADIUS Analyze stability versus integer delay.

arguments
    Ad (:,:) double
    Bd (:,:) double
    K  (:,:) double
    sampleTime_s (1,1) double {mustBePositive}
    maximumDelay_ms (1,1) double {mustBeNonnegative}
end

maximumDelaySamples = ...
    floor(maximumDelay_ms/(1000*sampleTime_s));

delaySamples = ...
    (0:maximumDelaySamples).';

delay_ms = ...
    1000*sampleTime_s*delaySamples;

numberOfCases = ...
    numel(delaySamples);

spectralRadius = ...
    zeros(numberOfCases,1);

dominantEigenvalue = ...
    complex(zeros(numberOfCases,1));

eigenvalueHistory = ...
    cell(numberOfCases,1);

for caseIndex = 1:numberOfCases

    delayedModel = ...
        build_delayed_closed_loop_matrix( ...
            Ad, ...
            Bd, ...
            K, ...
            delaySamples(caseIndex));

    spectralRadius(caseIndex) = ...
        delayedModel.spectral_radius;

    eigenvalues = ...
        delayedModel.eigenvalues;

    eigenvalueHistory{caseIndex} = ...
        eigenvalues;

    [~, dominantIndex] = ...
        max(abs(eigenvalues));

    dominantEigenvalue(caseIndex) = ...
        eigenvalues(dominantIndex);
end

%% Find first predicted unstable delay

firstUnstableIndex = ...
    find(spectralRadius >= 1, 1, "first");

if isempty(firstUnstableIndex)

    predictedDestabilizingDelay_ms = NaN;

    fprintf( ...
        "No unit-circle crossing found through %.1f ms.\n", ...
        maximumDelay_ms);

else

    predictedDestabilizingDelay_ms = ...
        delay_ms(firstUnstableIndex);

    fprintf( ...
        "First predicted destabilizing delay: %.1f ms\n", ...
        predictedDestabilizingDelay_ms);

    fprintf( ...
        "Spectral radius at crossing: %.6f\n", ...
        spectralRadius(firstUnstableIndex));
end

%% Return result

result = struct();

result.table = table( ...
    delaySamples, ...
    delay_ms, ...
    spectralRadius, ...
    real(dominantEigenvalue), ...
    imag(dominantEigenvalue), ...
    VariableNames=[ ...
        "DelaySamples", ...
        "Delay_ms", ...
        "SpectralRadius", ...
        "DominantEigenvalueReal", ...
        "DominantEigenvalueImag"]);
result.eigenvalues = eigenvalueHistory;
result.predicted_destabilizing_delay_ms = ...
    predictedDestabilizingDelay_ms;

%% Plot

result.figure = figure( ...
    Name="Analytical delay-stability cross-check", ...
    Color="white");

plot( ...
    delay_ms, ...
    spectralRadius, ...
    "o-", ...
    LineWidth=1.4, ...
    MarkerSize=5);

hold on;

yline( ...
    1, ...
    "r--", ...
    "Unit-circle boundary", ...
    LineWidth=1.3);

if ~isnan(predictedDestabilizingDelay_ms)
    xline( ...
        predictedDestabilizingDelay_ms, ...
        "m--", ...
        sprintf( ...
            "Predicted crossing: %.1f ms", ...
            predictedDestabilizingDelay_ms), ...
        LineWidth=1.3);
end

hold off;
grid on;

xlabel("Delay (ms)");
ylabel("Spectral radius, \rho(A_{aug})");
title("Analytical Closed-Loop Stability versus Delay");

end