function [ ...
    lookupInput, ...
    kappaPreview_1pm, ...
    kappaRms_1pm, ...
    kappaMaximum_1pm, ...
    featureValid] = ...
    formatLookupInput( ...
        measuredState, ...
        trackIndex, ...
        trackDistance_m, ...
        trackCurvature_1pm)
%FORMATLOOKUPINPUT Build runtime lookup-map features.
%
% measuredState:
%   1 = vx, m/s
%   2 = vy, m/s
%   3 = yaw rate, rad/s
%   4 = lateral error, m
%   5 = heading error, rad
%
% Preview:
%   common physical horizon = 1 second
%   preview step = 10 ms

numberOfPreviewPoints = 101;
previewStep_s = 0.01;

lookupInput = zeros(7, 1);
kappaPreview_1pm = zeros(numberOfPreviewPoints, 1);
kappaRms_1pm = 0;
kappaMaximum_1pm = 0;

numberOfTrackPoints = numel(trackDistance_m);

featureValid = ...
    all(isfinite(measuredState)) ...
    && isfinite(trackIndex) ...
    && numberOfTrackPoints >= 2 ...
    && numel(trackCurvature_1pm) ...
        == numberOfTrackPoints;

if ~featureValid
    return;
end

vx_mps = measuredState(1);
vy_mps = measuredState(2);
yawRate_radps = measuredState(3);
ey_m = measuredState(4);
epsi_rad = measuredState(5);

currentTrackIndex = round(trackIndex);

currentTrackIndex = min( ...
    max(currentTrackIndex, 1), ...
    numberOfTrackPoints);

currentTrackDistance_m = ...
    trackDistance_m(currentTrackIndex);

previewSpeed_mps = max(vx_mps, 0);

curvatureSquaredSum = 0;

for previewIndex = 1:numberOfPreviewPoints

    previewTime_s = ...
        (previewIndex - 1) * previewStep_s;

    queryDistance_m = ...
        currentTrackDistance_m ...
        + previewSpeed_mps * previewTime_s;

    % Prevent requesting points outside the track.
    queryDistance_m = min( ...
        max(queryDistance_m, trackDistance_m(1)), ...
        trackDistance_m(end));

    previewCurvature_1pm = interp1( ...
        trackDistance_m, ...
        trackCurvature_1pm, ...
        queryDistance_m, ...
        'linear');

    kappaPreview_1pm(previewIndex) = ...
        previewCurvature_1pm;

    curvatureSquaredSum = ...
        curvatureSquaredSum ...
        + previewCurvature_1pm^2;

    kappaMaximum_1pm = max( ...
        kappaMaximum_1pm, ...
        abs(previewCurvature_1pm));
end

kappaRms_1pm = sqrt( ...
    curvatureSquaredSum ...
    / numberOfPreviewPoints);

lookupInput = [
    abs(ey_m)
    abs(epsi_rad)
    vx_mps
    abs(vy_mps)
    abs(yawRate_radps)
    kappaRms_1pm
    kappaMaximum_1pm
    ];
end
