projectRoot = string( ...
    matlab.project.currentProject().RootFolder);

resultsRoots = [
    fullfile( ...
    projectRoot, ...
    "phase0", ...
    "results", ...
    "ACADOS_MPC")

    fullfile( ...
    projectRoot, ...
    "phase3_20ms", ...
    "results", ...
    "ACADOS_MPC")

    fullfile( ...
    projectRoot, ...
    "phase3_50ms", ...
    "results", ...
    "ACADOS_MPC")
    ];

samplingTimes_ms = [
    10
    20
    50
    ];

outputFolder = fullfile( ...
    projectRoot, ...
    "phase3", ...
    "results", ...
    "solve_time_comparison");

[solveTimeFigure, solveTimeSummary] = ...
    plot_solve_time_box_plot_comparison( ...
    resultsRoots.', ...
    samplingTimes_ms.', ...
    FigureFile=fullfile( ...
    outputFolder, ...
    "solve_time_sampling_comparison.png"), ...
    SummaryCsvFile=fullfile( ...
    outputFolder, ...
    "solve_time_sampling_summary.csv"), ...
    ShowDeadlineLines=true, ...
    ShowFigure=true);

disp(solveTimeSummary);