projectRoot = string( ...
    matlab.project.currentProject().RootFolder);

scenarioName = "aggressive_maneuver";

savedData = load(fullfile( ...
    projectRoot, "phase3", "results", "demand_tags", ...
    scenarioName + "_tags.mat"), ...
    "taggedScenario");

tags = savedData.taggedScenario.demand_table;

% Read the periods saved alongside these tags.

[figureHandle, timingTable] = plot_scheduler_cycle( ...
    tags.time_s, ...
    double(tags.dwellMode), ...
    BaseTick_ms=10, ...
    PlotStart_s=1, ...
    PlotDuration_s=1);