startup_project;

projectRoot = string( ...
    matlab.project.currentProject().RootFolder);

phase2SummaryFile = fullfile( ...
    projectRoot, ...
    "phase2", ...
    "results", ...
    "phase2_4", ...
    "phase2_4_summary.mat");

phase3SummaryFile = fullfile( ...
    projectRoot, ...
    "phase3", ...
    "results", ...
    "scheduler_runs", ...
    "phase3_summary.mat");

figures = ...
    plot_load_task_sweep_comparison( ...
    phase2SummaryFile, ...
    phase3SummaryFile, ...
    LoadExecution_ms=20:5:40, ...
    Deadline_ms=50, ...
    SaveFigure=true);