clearvars;
clc;

startup_project;

projectRoot = string( ...
    matlab.project.currentProject().RootFolder);

scenarioName = "aggressive_maneuver";
environmentName = "dry_road";
load_duration_s = 0.020;

fixedFile = fullfile( ...
    projectRoot, ...
    "phase3", ...
    "test", ...
    "results", ...
    "forced_high_10ms", ...
    scenarioName, ...
    environmentName, ...
    "load_" + load_duration_s, ...
    "simulation_output.mat");

supervisorFile = fullfile( ...
    projectRoot, ...
    "phase3", ...
    "results", ...
    "aligned_scheduler_runs", ...
    scenarioName, ...
    environmentName, ...
    "load_" + load_duration_s, ...
    "simulation_output.mat");

outputFile = fullfile( ...
    projectRoot, ...
    "phase3", ...
    "results", ...
    "demo", ...
    "phase3_demo_S0.png");

[demoFigure, demoMetrics] = plot_phase3_demo( ...
    fixedFile, ...
    supervisorFile, ...
    TrackingMetric="lateral", ...
    TimeWindow_s=[0, 600], ...
    Title="Fixed 10 ms vs. Naive Supervisor (Variable rate)", ...
    SaveFile=outputFile);

disp(demoMetrics);