%% Generate Phase 3 tags directly from scenario .mat files

startup_project;

projectRoot = string( ...
    matlab.project.currentProject().RootFolder);

scenarioDataFolder = fullfile( ...
    projectRoot, ...
    "phase0", ...
    "scenarios", ...
    "data");

scenarioNames = [
    "urban_profile"
    "highway_cruise"
    "aggressive_maneuver"
    ];

parameters = ...
    phase3_supervisor_parameters();

tagResultsFolder = fullfile( ...
    projectRoot, ...
    "phase3", ...
    "results", ...
    "demand_tags");

if ~isfolder(tagResultsFolder)
    mkdir(tagResultsFolder);
end

for scenarioName = scenarioNames.'

    scenarioFile = fullfile( ...
        scenarioDataFolder, ...
        scenarioName + ".mat");

    fprintf( ...
        "Generating demand tags from:\n%s\n", ...
        scenarioFile);

    taggedScenario = ...
        tag_phase3_scenario_file( ...
            scenarioFile, ...
            parameters);

    save( ...
        fullfile( ...
            tagResultsFolder, ...
            scenarioName + "_tags.mat"), ...
        "taggedScenario");

    writetable( ...
        taggedScenario.demand_table, ...
        fullfile( ...
            tagResultsFolder, ...
            scenarioName + "_tags.csv"));
end

fprintf("Relevant plot file:\n%s\n", fullfile( ...
    projectRoot, "phase3", "plot", ...
    "plot_phase3_scenario_tags.m"));
