%% Phase 1.2 random-delay Monte Carlo experiment

clearvars;
close all;
clc;

startup_project;

%% Controller and runtime requirements

configuration = ...
    build_phase0_configuration("highway_cruise");

controller = configuration.controller;

check_runtime_requirements( ...
    controller, ...
    false);

if controller.controller_backend == ...
        controller.BACKEND_ACADOS

    [acadosAvailable, ~] = ...
        activate_acados(false);

    projectRoot = string( ...
        matlab.project.currentProject().RootFolder);

    solverFile = fullfile( ...
        projectRoot, ...
        "build", ...
        "acados", ...
        "sdv_dynamic_bicycle", ...
        "acados_solver_sfunction_sdv_dynamic_bicycle." ...
        + string(mexext));

    solverAvailable = isfile(solverFile);

    if ~acadosAvailable || ~solverAvailable

        response = input( ...
            [ ...
            "The acados backend is not ready.\n" ...
            "Install acados and generate the S-function now? [y/N]: " ...
            ], ...
            "s");

        continueSetup = any(strcmpi( ...
            strtrim(response), ...
            ["y", "yes"]));

        if ~continueSetup
            error( ...
                "SDV:AcadosSetupDeclined", ...
                "acados setup was declined by the user.");
        end

        if ~acadosAvailable
            setup_acados_dependency;
        end

        if ~solverAvailable
            solverFile = ...
                s_fun_generation_acados();
        end

        startup_project;

        configuration = ...
            build_phase0_configuration( ...
                "highway_cruise");

        controller = configuration.controller;
    end
end

check_runtime_requirements(controller);

controllerName = ...
    sdv.config.controllerName(controller);

%% Monte Carlo configuration

scenarioNames = [ ...
    % "urban_profile", ...
    "aggressive_maneuver", ...
    "highway_cruise"];

environmentNames = [ ...
    "dry_road", ...
    "low_friction_road"];

maximumDelayValues_ms = [
    0, 50, 100, 150, 200, 225, 250, 275, 300
    ];

% maximumDelayValues_ms = [
%     50
%     ];

trialsPerLevel = 50;
baseSeed = 1000;

numberOfRuns = ...
    numel(scenarioNames) ...
    * numel(environmentNames) ...
    * numel(maximumDelayValues_ms) ...
    * trialsPerLevel;

maximumConfiguredDelay_ms = ...
    1e3 * controller.maximumRandomDelay_s;

assert( ...
    all(maximumDelayValues_ms <= ...
        maximumConfiguredDelay_ms), ...
    "Requested delay exceeds the configured maximum of %.1f ms.", ...
    maximumConfiguredDelay_ms);

%% Output folders

projectRoot = string( ...
    matlab.project.currentProject().RootFolder);

logFolder = fullfile( ...
    projectRoot, ...
    "phase1", ...
    "logs");

summaryFolder = fullfile( ...
    projectRoot, ...
    "phase1", ...
    "results", ...
    controllerName, ...
    "random_delay_sweep");

if ~isfolder(logFolder)
    mkdir(logFolder);
end

if ~isfolder(summaryFolder)
    mkdir(summaryFolder);
end

%% Start diary

runTimestamp = string(datetime( ...
    "now", ...
    Format="yyyyMMdd_HHmmss"));

logFile = fullfile( ...
    logFolder, ...
    "random_delay_sweep_" ...
    + runTimestamp ...
    + ".txt");

diary(logFile);
diary on;

% Guarantees diary closure if an error occurs.
diaryCleanup = onCleanup( ...
    @() diary("off"));

fprintf("\n========================================\n");
fprintf("Phase 1.2 random-delay Monte Carlo sweep\n");
fprintf("========================================\n");
fprintf("Started:          %s\n", string(datetime("now")));
fprintf("Controller:       %s\n", controllerName);
fprintf("Scenarios:        %s\n", ...
    strjoin(scenarioNames, ", "));
fprintf("Environments:     %s\n", ...
    strjoin(environmentNames, ", "));
fprintf("Maximum delays:   %s ms\n", ...
    join(string(maximumDelayValues_ms), ", "));
fprintf("Trials per level: %d\n", trialsPerLevel);
fprintf("Base seed:        %d\n", baseSeed);
fprintf("Total runs:       %d\n", numberOfRuns);
fprintf("Log file:         %s\n", logFile);
fprintf("========================================\n\n");

%% Run Monte Carlo sweep

summaryTable = table();
sweepFigure = gobjects(1);

try
    [summaryTable, sweepFigure] = ...
        run_random_delay_sweep( ...
            ScenarioNames=scenarioNames, ...
            EnvironmentNames=environmentNames, ...
            MaximumDelay_ms=maximumDelayValues_ms, ...
            TrialsPerLevel=trialsPerLevel, ...
            BaseSeed=baseSeed, ...
            SaveTrialResults=true, ...
            ShowFigure=true);

    %% Final summary files

    combinedMatFile = fullfile( ...
        summaryFolder, ...
        "random_delay_all_results.mat");

    combinedCsvFile = fullfile( ...
        summaryFolder, ...
        "random_delay_all_results.csv");

    save( ...
        combinedMatFile, ...
        "summaryTable", ...
        "scenarioNames", ...
        "environmentNames", ...
        "maximumDelayValues_ms", ...
        "trialsPerLevel", ...
        "baseSeed");

    writetable( ...
        summaryTable, ...
        combinedCsvFile);

    completedRuns = nnz( ...
        summaryTable.simulation_completed);

    failedRuns = ...
        height(summaryTable) - completedRuns;

    fprintf("\n========================================\n");
    fprintf("Phase 1.2 Monte Carlo sweep completed\n");
    fprintf("========================================\n");
    fprintf("Finished:        %s\n", string(datetime("now")));
    fprintf("Successful runs: %d\n", completedRuns);
    fprintf("Failed runs:     %d\n", failedRuns);
    fprintf("Expected runs:   %d\n", numberOfRuns);
    fprintf("Total rows:      %d\n", height(summaryTable));
    fprintf("MAT summary:     %s\n", combinedMatFile);
    fprintf("CSV summary:     %s\n", combinedCsvFile);
    fprintf("========================================\n");

    disp(summaryTable);

catch sweepError
    fprintf("\n========================================\n");
    fprintf("Random-delay sweep stopped unexpectedly\n");
    fprintf("========================================\n");
    fprintf("Stopped: %s\n", string(datetime("now")));
    fprintf("%s\n", ...
        getReport(sweepError, "extended"));

    % run_random_delay_sweep checkpoints its summary after every
    % completed or failed trial. Save the currently returned table
    % as an additional recovery file when available.
    if ~isempty(summaryTable)

        partialMatFile = fullfile( ...
            summaryFolder, ...
            "random_delay_partial_results.mat");

        partialCsvFile = fullfile( ...
            summaryFolder, ...
            "random_delay_partial_results.csv");

        save( ...
            partialMatFile, ...
            "summaryTable", ...
            "scenarioNames", ...
            "environmentNames", ...
            "maximumDelayValues_ms", ...
            "trialsPerLevel", ...
            "baseSeed");

        writetable( ...
            summaryTable, ...
            partialCsvFile);

        fprintf( ...
            "Partial MAT file: %s\n", ...
            partialMatFile);

        fprintf( ...
            "Partial CSV file: %s\n", ...
            partialCsvFile);
    end

    rethrow(sweepError);
end