%% Phase 1 single-case entry point

startup_project;

% Select one mode:
%   "constant_delay", "random_delay", or "sampling_jitter"
timingMode = "sampling_jitter";

scenarioName = sdv.enum.ScenarioName.aggressive_maneuver;
environmentName = sdv.enum.EnvironmentName.dry_road;
delay = 0;

prepare_phase1_runtime(scenarioName);

[runRows, sweepFigure] = run_constant_delay_sweep( ...
    Delay_ms=200, ...
    UpdateSummary=false, ...
    SaveRunResults=true, ...
    SaveRunFigures=false, ...
    ShowRunFigures=true);


% run_random_delay_sweep( ...
%     "EnvironmentNames", environmentName, ...
%     "MaximumDelay_ms", delay, ...
%     "TrialsPerLevel", 1 ...
%     );

% run_sampling_jitter_monte_carlo( ...
%     scenarioName, ...
%     environmentName ...
%     );

%% BATCH RUN
% run_constant_delay_sweep();
% run_random_delay_sweep();
% run_sampling_jitter_monte_carlo();
