%% Phase 1 single-case entry point

startup_project;

% Select one mode:
%   "constant_delay", "random_delay", or "sampling_jitter"
timingMode = "sampling_jitter";

scenarioName = "highway_cruise";
environmentName = "dry_road";
delay = 0;

prepare_phase1_runtime(scenarioName);

% % Single run
% run_constant_delay_sweep( ...
%     "Delay_ms", delay, ...
%     "EnvironmentNames", environmentName, ...
%     "ScenarioNames", scenarioName ...
%     )

% Batch run
% run_constant_delay_sweep();
 
% run_random_delay_sweep( ...
%     "EnvironmentNames", environmentName, ...
%     "MaximumDelay_ms", delay, ...
%     "TrialsPerLevel", 1 ...
%     );

run_sampling_jitter_monte_carlo( ...
    scenarioName, ...
    environmentName ...
    );
