function [sweepSummary, sweepStatistics, sweepFigure] = ...
    run_sampling_jitter_monte_carlo(scenarioNames, environmentNames, jitterBounds_ms)
%RUN_SAMPLING_JITTER_MONTE_CARLO  Sampling-jitter sweep (concise).
arguments
    scenarioNames (1,:) string = [ ...
        sdv.enum.ScenarioName.urban_profile, ...
        sdv.enum.ScenarioName.aggressive_maneuver, ...
        sdv.enum.ScenarioName.highway_cruise]

    environmentNames (1,:) string = [ ...
        sdv.enum.EnvironmentName.dry_road, ...
        sdv.enum.EnvironmentName.low_friction_road]

    jitterBounds_ms (1,:) double = [0 2 4 5 6 7 8]
end

randomSeeds = 1:50;
simulationStep_s = 0.0005;

numberOfRuns = ...
    numel(scenarioNames) * ...
    numel(environmentNames) * ...
    (1 + ...
    (numel(jitterBounds_ms) - 1) * numel(randomSeeds));

configuration = ...
    build_phase0_configuration("highway_cruise");

controllerName = ...
    sdv.config.controllerName(configuration.controller);

projectRoot = string( ...
    matlab.project.currentProject().RootFolder);

summaryFolder = fullfile( ...
    projectRoot, "phase1", "results", ...
    controllerName, "sampling_jitter", "sweep");

figureFolder = fullfile( ...
    projectRoot, "phase1", "figures", ...
    controllerName, "sampling_jitter", "sweep");

logFolder = fullfile( ...
    projectRoot, "phase1", "logs");

if ~isfolder(summaryFolder)
    mkdir(summaryFolder);
end

if ~isfolder(figureFolder)
    mkdir(figureFolder);
end

if ~isfolder(logFolder)
    mkdir(logFolder);
end

timestamp = string(datetime( ...
    "now", Format="yyyyMMdd_HHmmss"));

logFile = fullfile( ...
    logFolder, ...
    "sampling_jitter_sweep_" + timestamp + ".txt");

checkpointFile = fullfile( ...
    summaryFolder, "sweep_summary_checkpoint.mat");

csvFile = fullfile( ...
    summaryFolder, "sweep_summary.csv");

diary(logFile);
diary on;
diaryCleanup = onCleanup(@() diary("off"));

fprintf("\n========================================\n");
fprintf("Phase 1.3 sampling-jitter sweep\n");
fprintf("========================================\n");
fprintf("Scenarios: %s\n", strjoin(scenarioNames, ", "));
fprintf("Environments: %s\n", ...
    strjoin(environmentNames, ", "));
fprintf("Jitter bounds: %s ms\n", ...
    strjoin(string(jitterBounds_ms), ", "));
fprintf("Nonzero-jitter seeds: %d to %d\n", ...
    randomSeeds(1), randomSeeds(end));
fprintf("Simulation step: %.3f ms\n", ...
    1e3*simulationStep_s);
fprintf("Expected runs: %d\n", numberOfRuns);
fprintf("Log: %s\n", logFile);
fprintf("========================================\n\n");

sweepSummary = table();
runNumber = 0;


for environmentName = environmentNames

    for scenarioName = scenarioNames

        for jitterBound_ms = jitterBounds_ms

            if jitterBound_ms == 0
                seedsForBatch = 1;
            else
                seedsForBatch = randomSeeds;
            end

            for randomSeed = seedsForBatch

                runNumber = runNumber + 1;

                fprintf( ...
                    "\nRun %d/%d: %s, %s, J = %.1f ms, seed = %d\n", ...
                    runNumber, ...
                    numberOfRuns, ...
                    scenarioName, ...
                    environmentName, ...
                    jitterBound_ms, ...
                    randomSeed);
    
                try
                    [results, ~, ~, caseSummary] = ...
                        run_sampling_jitter_case( ...
                            scenarioName, ...
                            environmentName, ...
                            jitterBound_ms, ...
                            randomSeed, ...
                            simulationStep_s, ...
                            SaveResults=true, ...
                            SaveFigures=false, ...
                            ShowFigures=false);
    
                    tracking = results.tracking_metrics;
                    constraints = results.constraint_metrics;
                    validation = results.jitter_validation;
                    executionLog = results.controller_execution_log;
    
                    rawStatus = executionLog.SolverStatus(:);
                    solveTime_ms = ...
                        1e3*executionLog.SolveTime_s(:);
    
                    caseSummary.Completed = true;
                    caseSummary.SpeedPeak_mps = ...
                        tracking.speed_peak_mps;
                    caseSummary.LateralPeak_m = ...
                        tracking.lateral_peak_m;
                    caseSummary.HeadingRmse_deg = ...
                        tracking.heading_rmse_deg;
                    caseSummary.HeadingPeak_deg = ...
                        tracking.heading_peak_deg;
    
                    caseSummary.ConstraintViolationSamples = ...
                        constraints.any_sample_count;
                    caseSummary.ConstraintEventCount = ...
                        constraints.event_count;
                    caseSummary.ConstraintDuration_s = ...
                        constraints.duration_s;
    
                    % Preserve raw acados statuses without remapping.
                    caseSummary.RawStatus0Count = nnz(rawStatus == 0);
                    caseSummary.RawStatus2Count = nnz(rawStatus == 2);
                    caseSummary.RawStatus4Count = nnz(rawStatus == 4);
                    caseSummary.OtherStatusCount = ...
                        nnz(~ismember(rawStatus, [0 2 4]));
    
                    caseSummary.SolveTimeP95_ms = ...
                        samplePercentile(solveTime_ms, 0.95);
    
                    caseSummary.MaximumActualJitter_ms = ...
                        1e3*validation.maximum_abs_actual_jitter_s;
    
                    caseSummary.ErrorMessage = "";
    
                catch simulationError
    
                    warning( ...
                        "sweep run failed: %s", ...
                        simulationError.message);
    
                    caseSummary = createFailedRow( ...
                        scenarioName, ...
                        environmentName, ...
                        jitterBound_ms, ...
                        randomSeed, ...
                        simulationStep_s, ...
                        string(simulationError.message));
                end
    
                if isempty(sweepSummary)
                    sweepSummary = caseSummary;
                else
                    sweepSummary = [sweepSummary; caseSummary];
                end
    
                % Checkpoint after every simulation.
                save( ...
                    checkpointFile, ...
                    "sweepSummary", ...
                    "scenarioNames", ...
                    "environmentNames", ...
                    "jitterBounds_ms", ...
                    "randomSeeds", ...
                    "simulationStep_s");
    
                writetable(sweepSummary, csvFile);
    
                clear results caseSummary

            end
        end
    end
end

sweepSummary = sortrows( ...
    sweepSummary, ...
    [ ...
        "EnvironmentName", ...
        "ScenarioName", ...
        "JitterBound_ms", ...
        "RandomSeed" ...
    ]);

sweepStatistics = ...
    summarizeSamplingJitterSweep(sweepSummary);

statisticsCsvFile = fullfile( ...
    summaryFolder, ...
    "sweep_statistics.csv");

statisticsMatFile = fullfile( ...
    summaryFolder, ...
    "sweep_statistics.mat");

writetable( ...
    sweepStatistics, ...
    statisticsCsvFile);

save( ...
    statisticsMatFile, ...
    "sweepStatistics", ...
    "sweepSummary", ...
    "scenarioNames", ...
    "environmentNames", ...
    "jitterBounds_ms", ...
    "randomSeeds", ...
    "simulationStep_s");

save( ...
    checkpointFile, ...
    "sweepSummary", ...
    "scenarioNames", ...
    "environmentNames", ...
    "jitterBounds_ms", ...
    "randomSeeds", ...
    "simulationStep_s");
writetable(sweepSummary, csvFile);

sweepFigure = ...
    plotSweepStatistics(sweepStatistics);

exportgraphics( ...
    sweepFigure, ...
    fullfile(figureFolder, "sampling_jitter_sweep_summary.png"), ...
    Resolution=200);

savefig( ...
    sweepFigure, ...
    fullfile(figureFolder, "sampling_jitter_sweep_summary.fig"));

fprintf("\n========================================\n");
fprintf("sweep completed\n");
fprintf("Successful runs: %d/%d\n", ...
    nnz(sweepSummary.Completed), height(sweepSummary));
fprintf("Summary: %s\n", csvFile);
fprintf("========================================\n");

end


function row = createFailedRow( ...
    scenarioName, environmentName, jitterBound_ms, ...
    randomSeed, simulationStep_s, errorMessage)

nanValue = NaN;

row = table( ...
    scenarioName, environmentName, jitterBound_ms, ...
    randomSeed, simulationStep_s, ...
    nanValue, nanValue, nanValue, nanValue, nanValue, ...
    false, ...
    nanValue, nanValue, nanValue, nanValue, ...
    nanValue, nanValue, nanValue, ...
    nanValue, nanValue, nanValue, nanValue, ...
    nanValue, nanValue, errorMessage, ...
    VariableNames=[ ...
        "ScenarioName", ...
        "EnvironmentName", ...
        "JitterBound_ms", ...
        "RandomSeed", ...
        "SimulationStep_s", ...
        "ExecutionCount", ...
        "SpeedRmse_mps", ...
        "LateralRmse_m", ...
        "HeadingRmse_rad", ...
        "DeadlineMissCount", ...
        "Completed", ...
        "SpeedPeak_mps", ...
        "LateralPeak_m", ...
        "HeadingRmse_deg", ...
        "HeadingPeak_deg", ...
        "ConstraintViolationSamples", ...
        "ConstraintEventCount", ...
        "ConstraintDuration_s", ...
        "RawStatus0Count", ...
        "RawStatus2Count", ...
        "RawStatus4Count", ...
        "OtherStatusCount", ...
        "SolveTimeP95_ms", ...
        "MaximumActualJitter_ms", ...
        "ErrorMessage"]);
end


function figureHandle = ...
    plotSweepStatistics(statistics)
%PLOTSWEEPSTATISTICS Plot Monte Carlo mean with ±1σ uncertainty.

figureHandle = figure( ...
    Name="Phase 1.3 sampling-jitter sweep", ...
    Color="w");

layout = tiledlayout( ...
    figureHandle, ...
    2, ...
    2, ...
    TileSpacing="compact", ...
    Padding="compact");

title( ...
    layout, ...
    "Phase 1.3 Sampling Jitter: Mean \pm1\sigma");

seriesTable = unique( ...
    statistics(:, ...
    ["ScenarioName", "EnvironmentName"]), ...
    "rows", ...
    "stable");

colors = lines(height(seriesTable));

plotMetricStatistics( ...
    layout, statistics, seriesTable, colors, ...
    "LateralRmse_m", ...
    "Lateral RMSE (m)", ...
    "Lateral Tracking Error");

plotMetricStatistics( ...
    layout, statistics, seriesTable, colors, ...
    "HeadingRmse_deg", ...
    "Heading RMSE (deg)", ...
    "Heading Tracking Error");

plotConstraintStatistics( ...
    layout, statistics, seriesTable, colors);

plotMetricStatistics( ...
    layout, statistics, seriesTable, colors, ...
    "DeadlineMissCount", ...
    "Deadline-miss count", ...
    "Controller Deadline Misses");

xlabel(layout, "Jitter bound, J (ms)");

end


function plotMetricStatistics( ...
    layout, statistics, seriesTable, colors, ...
    metricName, yLabelText, titleText)
%PLOTMETRICSTATISTICS Plot one mean curve with a ±1σ band per series.

axesHandle = nexttile(layout);
hold(axesHandle, "on");

for seriesIndex = 1:height(seriesTable)

    selectedStatistics = selectSeries( ...
        statistics, seriesTable, seriesIndex);

    x = selectedStatistics.JitterBound_ms;
    meanValue = selectedStatistics.(metricName + "_Mean");
    sigmaValue = selectedStatistics.(metricName + "_Std");

    valid = ...
        isfinite(x) & ...
        isfinite(meanValue) & ...
        isfinite(sigmaValue);

    x = x(valid);
    meanValue = meanValue(valid);
    sigmaValue = sigmaValue(valid);

    if isempty(x)
        continue;
    end

    seriesColor = colors(seriesIndex, :);

    if numel(x) > 1
        fill( ...
            axesHandle, ...
            [x; flipud(x)], ...
            [meanValue - sigmaValue; ...
             flipud(meanValue + sigmaValue)], ...
            seriesColor, ...
            FaceAlpha=0.18, ...
            EdgeColor="none", ...
            HandleVisibility="off");
    end

    plot( ...
        axesHandle, ...
        x, ...
        meanValue, ...
        "-o", ...
        Color=seriesColor, ...
        MarkerFaceColor=seriesColor, ...
        LineWidth=1.5, ...
        MarkerSize=5, ...
        DisplayName=seriesDisplayName( ...
            seriesTable, seriesIndex));
end

hold(axesHandle, "off");
grid(axesHandle, "on");
ylabel(axesHandle, yLabelText);
title(axesHandle, titleText);
legend(axesHandle, Location="best");

end


function plotConstraintStatistics( ...
    layout, statistics, seriesTable, colors)
%PLOTCONSTRAINTSTATISTICS Plot sample and event counts together.

axesHandle = nexttile(layout);
yyaxis(axesHandle, "left");
hold(axesHandle, "on");
yyaxis(axesHandle, "right");
hold(axesHandle, "on");

for seriesIndex = 1:height(seriesTable)

    selectedStatistics = selectSeries( ...
        statistics, seriesTable, seriesIndex);

    x = selectedStatistics.JitterBound_ms;
    seriesColor = colors(seriesIndex, :);
    displayName = seriesDisplayName( ...
        seriesTable, seriesIndex);

    sampleMean = ...
        selectedStatistics.ConstraintViolationSamples_Mean;
    sampleStd = ...
        selectedStatistics.ConstraintViolationSamples_Std;
    sampleValid = ...
        isfinite(x) & isfinite(sampleMean) & isfinite(sampleStd);

    if any(sampleValid)
        yyaxis(axesHandle, "left");
        errorbar( ...
            axesHandle, ...
            x(sampleValid), ...
            sampleMean(sampleValid), ...
            sampleStd(sampleValid), ...
            "-o", ...
            Color=seriesColor, ...
            MarkerFaceColor=seriesColor, ...
            LineWidth=1.4, ...
            MarkerSize=5, ...
            DisplayName=displayName + " / samples");
    end

    eventMean = selectedStatistics.ConstraintEventCount_Mean;
    eventStd = selectedStatistics.ConstraintEventCount_Std;
    eventValid = ...
        isfinite(x) & isfinite(eventMean) & isfinite(eventStd);

    if any(eventValid)
        yyaxis(axesHandle, "right");
        errorbar( ...
            axesHandle, ...
            x(eventValid), ...
            eventMean(eventValid), ...
            eventStd(eventValid), ...
            "--s", ...
            Color=seriesColor, ...
            LineWidth=1.4, ...
            MarkerSize=5, ...
            DisplayName=displayName + " / events");
    end
end

yyaxis(axesHandle, "left");
hold(axesHandle, "off");
grid(axesHandle, "on");
ylabel(axesHandle, "Violating samples");
yyaxis(axesHandle, "right");
ylabel(axesHandle, "Violation events");
title(axesHandle, ...
    "Constraint-Violating Samples and Events");
legend(axesHandle, Location="best");

end


function selectedStatistics = ...
    selectSeries(statistics, seriesTable, seriesIndex)
%SELECTSERIES Select and order one scenario/environment series.

selected = ...
    statistics.ScenarioName == ...
        seriesTable.ScenarioName(seriesIndex) & ...
    statistics.EnvironmentName == ...
        seriesTable.EnvironmentName(seriesIndex);

selectedStatistics = sortrows( ...
    statistics(selected, :), ...
    "JitterBound_ms");

end


function displayName = ...
    seriesDisplayName(seriesTable, seriesIndex)
%SERIESDISPLAYNAME Create a readable legend label.

displayName = replace( ...
    seriesTable.ScenarioName(seriesIndex) + ...
    " / " + ...
    seriesTable.EnvironmentName(seriesIndex), ...
    "_", ...
    " ");

end


function value = samplePercentile(data, probability)

data = sort(data(isfinite(data)));

if isempty(data)
    value = NaN;
    return;
end

index = max(1, ceil(probability*numel(data)));
value = data(index);

end

function statistics = ...
    summarizeSamplingJitterSweep(summary)
%SUMMARIZESAMPLINGJITTERSWEEP
% Calculate statistics across random seeds for every scenario,
% environment, and jitter bound.

validRows = summary(summary.Completed, :);

assert(~isempty(validRows), ...
    "No completed sampling-jitter simulations are available.");

groupVariables = [
    "ScenarioName"
    "EnvironmentName"
    "JitterBound_ms"
    ];

statistics = unique( ...
    validRows(:, groupVariables), ...
    "rows", ...
    "stable");

metrics = [
    "SpeedRmse_mps"
    "SpeedPeak_mps"
    "LateralRmse_m"
    "LateralPeak_m"
    "HeadingRmse_deg"
    "HeadingPeak_deg"
    "ConstraintViolationSamples"
    "ConstraintEventCount"
    "ConstraintDuration_s"
    "RawStatus0Count"
    "RawStatus2Count"
    "RawStatus4Count"
    "OtherStatusCount"
    "DeadlineMissCount"
    "SolveTimeP95_ms"
    "MaximumActualJitter_ms"
    ];

numberOfGroups = height(statistics);

statistics.SampleCount = ...
    zeros(numberOfGroups, 1);

for groupIndex = 1:numberOfGroups

    selected = ...
        validRows.ScenarioName == ...
            statistics.ScenarioName(groupIndex) & ...
        validRows.EnvironmentName == ...
            statistics.EnvironmentName(groupIndex) & ...
        validRows.JitterBound_ms == ...
            statistics.JitterBound_ms(groupIndex);

    statistics.SampleCount(groupIndex) = nnz(selected);
end

for metricName = metrics.'

    meanValues = nan(numberOfGroups, 1);
    standardDeviationValues = nan(numberOfGroups, 1);
    medianValues = nan(numberOfGroups, 1);
    percentile95Values = nan(numberOfGroups, 1);

    for groupIndex = 1:numberOfGroups

        selected = ...
            validRows.ScenarioName == ...
                statistics.ScenarioName(groupIndex) & ...
            validRows.EnvironmentName == ...
                statistics.EnvironmentName(groupIndex) & ...
            validRows.JitterBound_ms == ...
                statistics.JitterBound_ms(groupIndex);

        values = ...
            validRows.(metricName)(selected);

        values = values(isfinite(values));

        if isempty(values)
            continue;
        end

        meanValues(groupIndex) = ...
            mean(values);

        standardDeviationValues(groupIndex) = ...
            std(values);

        medianValues(groupIndex) = ...
            median(values);

        percentile95Values(groupIndex) = ...
            samplePercentile(values, 0.95);
    end

    statistics.(metricName + "_Mean") = ...
        meanValues;

    statistics.(metricName + "_Std") = ...
        standardDeviationValues;

    statistics.(metricName + "_Median") = ...
        medianValues;

    statistics.(metricName + "_P95") = ...
        percentile95Values;
end

statistics = sortrows( ...
    statistics, ...
    [ ...
    "EnvironmentName", ...
    "ScenarioName", ...
    "JitterBound_ms" ...
    ]);

end
