function [pilotSummary, pilotFigure] = ...
    run_sampling_jitter_monte_carlo()
%RUN_SAMPLING_JITTER_PILOT Run the Phase 1.3 pilot Monte Carlo study.

startup_project;

scenarioNames = [
    "highway_cruise"
    "urban_profile"
    "aggressive_maneuver"
    ];

environmentName = "dry_road";
jitterBounds_ms = [0 3 5 7 8];
randomSeeds = 1:10;
simulationStep_s = 0.0005;

configuration = ...
    build_phase0_configuration("highway_cruise");

controllerName = ...
    sdv.config.controllerName(configuration.controller);

projectRoot = string( ...
    matlab.project.currentProject().RootFolder);

summaryFolder = fullfile( ...
    projectRoot, "phase1", "results", ...
    controllerName, "sampling_jitter", "pilot");

figureFolder = fullfile( ...
    projectRoot, "phase1", "figures", ...
    controllerName, "sampling_jitter", "pilot");

logFolder = fullfile( ...
    projectRoot, "phase1", "logs");

if ~isfolder(summaryFolder)
    mkdir(summaryFolder);
end

if ~isfolder(figureFolder)
    mkdir(figureFolder);
end

if ~isfolder(logFolder)
    mkdir(logFolder);
end

timestamp = string(datetime( ...
    "now", Format="yyyyMMdd_HHmmss"));

logFile = fullfile( ...
    logFolder, ...
    "sampling_jitter_pilot_" + timestamp + ".txt");

checkpointFile = fullfile( ...
    summaryFolder, "pilot_summary_checkpoint.mat");

csvFile = fullfile( ...
    summaryFolder, "pilot_summary.csv");

diary(logFile);
diary on;
diaryCleanup = onCleanup(@() diary("off"));

fprintf("\n========================================\n");
fprintf("Phase 1.3 sampling-jitter pilot\n");
fprintf("========================================\n");
fprintf("Scenarios: %s\n", strjoin(scenarioNames, ", "));
fprintf("Environment: %s\n", environmentName);
fprintf("Jitter bounds: %s ms\n", ...
    strjoin(string(jitterBounds_ms), ", "));
fprintf("Nonzero-jitter seeds: %d to %d\n", ...
    randomSeeds(1), randomSeeds(end));
fprintf("Simulation step: %.3f ms\n", ...
    1e3*simulationStep_s);
fprintf("Expected runs: 123\n");
fprintf("Log: %s\n", logFile);
fprintf("========================================\n\n");

pilotSummary = table();
runNumber = 0;

for scenarioName = scenarioNames.'

    for jitterBound_ms = jitterBounds_ms

        if jitterBound_ms == 0
            seedsForBatch = 1;
        else
            seedsForBatch = randomSeeds;
        end

        for randomSeed = seedsForBatch

            runNumber = runNumber + 1;

            fprintf( ...
                "\nRun %d/123: %s, J = %.1f ms, seed = %d\n", ...
                runNumber, scenarioName, ...
                jitterBound_ms, randomSeed);

            try
                [results, ~, ~, caseSummary] = ...
                    run_sampling_jitter_case( ...
                        scenarioName, ...
                        environmentName, ...
                        jitterBound_ms, ...
                        randomSeed, ...
                        simulationStep_s, ...
                        SaveResults=false, ...
                        SaveFigures=false, ...
                        ShowFigures=false);

                tracking = results.tracking_metrics;
                constraints = results.constraint_metrics;
                validation = results.jitter_validation;
                executionLog = results.controller_execution_log;

                rawStatus = executionLog.SolverStatus(:);
                solveTime_ms = ...
                    1e3*executionLog.SolveTime_s(:);

                caseSummary.Completed = true;
                caseSummary.SpeedPeak_mps = ...
                    tracking.speed_peak_mps;
                caseSummary.LateralPeak_m = ...
                    tracking.lateral_peak_m;
                caseSummary.HeadingRmse_deg = ...
                    tracking.heading_rmse_deg;
                caseSummary.HeadingPeak_deg = ...
                    tracking.heading_peak_deg;

                caseSummary.ConstraintEventCount = ...
                    constraints.event_count;
                caseSummary.ConstraintDuration_s = ...
                    constraints.duration_s;

                % Preserve raw acados statuses without remapping.
                caseSummary.RawStatus0Count = nnz(rawStatus == 0);
                caseSummary.RawStatus2Count = nnz(rawStatus == 2);
                caseSummary.RawStatus4Count = nnz(rawStatus == 4);
                caseSummary.OtherStatusCount = ...
                    nnz(~ismember(rawStatus, [0 2 4]));

                caseSummary.SolveTimeP95_ms = ...
                    samplePercentile(solveTime_ms, 0.95);

                caseSummary.MaximumActualJitter_ms = ...
                    1e3*validation.maximum_abs_actual_jitter_s;

                caseSummary.ErrorMessage = "";

            catch simulationError

                warning( ...
                    "Pilot run failed: %s", ...
                    simulationError.message);

                caseSummary = createFailedRow( ...
                    scenarioName, ...
                    environmentName, ...
                    jitterBound_ms, ...
                    randomSeed, ...
                    simulationStep_s, ...
                    string(simulationError.message));
            end

            if isempty(pilotSummary)
                pilotSummary = caseSummary;
            else
                pilotSummary = [pilotSummary; caseSummary];
            end

            % Checkpoint after every simulation.
            save( ...
                checkpointFile, ...
                "pilotSummary", ...
                "scenarioNames", ...
                "environmentName", ...
                "jitterBounds_ms", ...
                "randomSeeds", ...
                "simulationStep_s");

            writetable(pilotSummary, csvFile);

            clear results caseSummary
        end
    end
end

pilotSummary = sortrows( ...
    pilotSummary, ...
    ["ScenarioName", "JitterBound_ms", "RandomSeed"]);

save(checkpointFile, "pilotSummary");
writetable(pilotSummary, csvFile);

pilotFigure = plotPilotSummary(pilotSummary);

exportgraphics( ...
    pilotFigure, ...
    fullfile(figureFolder, "sampling_jitter_pilot_summary.png"), ...
    Resolution=200);

savefig( ...
    pilotFigure, ...
    fullfile(figureFolder, "sampling_jitter_pilot_summary.fig"));

fprintf("\n========================================\n");
fprintf("Pilot completed\n");
fprintf("Successful runs: %d/%d\n", ...
    nnz(pilotSummary.Completed), height(pilotSummary));
fprintf("Summary: %s\n", csvFile);
fprintf("========================================\n");

end


function row = createFailedRow( ...
    scenarioName, environmentName, jitterBound_ms, ...
    randomSeed, simulationStep_s, errorMessage)

nanValue = NaN;

row = table( ...
    scenarioName, environmentName, jitterBound_ms, ...
    randomSeed, simulationStep_s, ...
    nanValue, nanValue, nanValue, nanValue, nanValue, ...
    false, ...
    nanValue, nanValue, nanValue, nanValue, ...
    nanValue, nanValue, ...
    nanValue, nanValue, nanValue, nanValue, ...
    nanValue, nanValue, errorMessage, ...
    "VariableNames", { ...
        "ScenarioName", ...
        "EnvironmentName", ...
        "JitterBound_ms", ...
        "RandomSeed", ...
        "SimulationStep_s", ...
        "ExecutionCount", ...
        "SpeedRmse_mps", ...
        "LateralRmse_m", ...
        "HeadingRmse_rad", ...
        "DeadlineMissCount", ...
        "Completed", ...
        "SpeedPeak_mps", ...
        "LateralPeak_m", ...
        "HeadingRmse_deg", ...
        "HeadingPeak_deg", ...
        "ConstraintEventCount", ...
        "ConstraintDuration_s", ...
        "RawStatus0Count", ...
        "RawStatus2Count", ...
        "RawStatus4Count", ...
        "OtherStatusCount", ...
        "SolveTimeP95_ms", ...
        "MaximumActualJitter_ms", ...
        "ErrorMessage"});
end


function figureHandle = plotPilotSummary(summary)

validRows = summary(summary.Completed, :);

figureHandle = figure( ...
    Name="Phase 1.3 pilot summary", ...
    Color="w");

layout = tiledlayout( ...
    figureHandle, 3, 2, ...
    TileSpacing="compact", ...
    Padding="compact");

title(layout, ...
    "Phase 1.3 Sampling-Jitter Pilot: " + ...
    "solid = median, dashed = 95th percentile");

metricNames = [
    "SpeedRmse_mps"
    "LateralRmse_m"
    "HeadingRmse_deg"
    "ConstraintEventCount"
    "RawStatus4Count"
    "DeadlineMissCount"
    ];

metricLabels = [
    "Speed RMS error (m/s)"
    "Lateral RMS error (m)"
    "Heading RMS error (deg)"
    "Constraint-violation events"
    "Raw acados status-4 count"
    "Deadline-miss count"
    ];

scenarioNames = unique( ...
    validRows.ScenarioName, "stable");

colors = lines(numel(scenarioNames));

for metricIndex = 1:numel(metricNames)

    nexttile;
    hold on;

    for scenarioIndex = 1:numel(scenarioNames)

        scenarioName = scenarioNames(scenarioIndex);

        scenarioRows = validRows( ...
            validRows.ScenarioName == scenarioName, :);

        jitterValues = unique( ...
            scenarioRows.JitterBound_ms);

        medianValue = zeros(size(jitterValues));
        percentile95Value = zeros(size(jitterValues));

        for jitterIndex = 1:numel(jitterValues)

            selected = ...
                scenarioRows.JitterBound_ms == ...
                jitterValues(jitterIndex);

            values = scenarioRows.( ...
                metricNames(metricIndex))(selected);

            medianValue(jitterIndex) = ...
                median(values, "omitnan");

            percentile95Value(jitterIndex) = ...
                samplePercentile(values, 0.95);
        end

        plot( ...
            jitterValues, medianValue, ...
            "-o", ...
            Color=colors(scenarioIndex,:), ...
            LineWidth=1.4, ...
            DisplayName=replace(scenarioName, "_", " "));

        plot( ...
            jitterValues, percentile95Value, ...
            "--", ...
            Color=colors(scenarioIndex,:), ...
            LineWidth=1.0, ...
            HandleVisibility="off");
    end

    grid on;
    xlabel("Jitter bound, J (ms)");
    ylabel(metricLabels(metricIndex));
    legend(Location="best");
end

end


function value = samplePercentile(data, probability)

data = sort(data(isfinite(data)));

if isempty(data)
    value = NaN;
    return;
end

index = max(1, ceil(probability*numel(data)));
value = data(index);

end