%% Validate the Phase 1 actuation-delay block

startup_project;

modelName = "phase1_delay_test";

requestedDelay_s = 0.05;

simInput = Simulink.SimulationInput(modelName);

simInput = simInput.setVariable( ...
    "test_delay_s", ...
    requestedDelay_s);

simInput = simInput.setModelParameter( ...
    StopTime = "0.25");

simOut = sim(simInput);

commandBefore = simOut.get("command_before");
commandAfter  = simOut.get("command_after");

%% Find transition times

threshold = 0.5;

beforeIndex = find( ...
    commandBefore.Data >= threshold, ...
    1, ...
    "first");

afterIndex = find( ...
    commandAfter.Data >= threshold, ...
    1, ...
    "first");

assert(~isempty(beforeIndex), ...
    "Input transition was not detected.");

assert(~isempty(afterIndex), ...
    "Delayed transition was not detected.");

inputTransition_s = ...
    commandBefore.Time(beforeIndex);

outputTransition_s = ...
    commandAfter.Time(afterIndex);

measuredDelay_s = ...
    outputTransition_s - inputTransition_s;

%% Print results

fprintf( ...
    "Requested delay: %.3f ms\n", ...
    requestedDelay_s * 1000);

fprintf( ...
    "Measured delay:  %.3f ms\n", ...
    measuredDelay_s * 1000);

%% Validate within one simulation step

timeTolerance_s = 0.0011;

assert( ...
    abs(measuredDelay_s - requestedDelay_s) ...
    <= timeTolerance_s, ...
    "The measured delay does not match the requested delay.");

%% Plot

figure;

stairs( ...
    commandBefore.Time, ...
    commandBefore.Data, ...
    "LineWidth", 1.5, ...
    "DisplayName", "Command before delay");

hold on;

stairs( ...
    commandAfter.Time, ...
    commandAfter.Data, ...
    "--", ...
    "LineWidth", 1.5, ...
    "DisplayName", "Command after delay");

grid on;
xlabel("Time (s)");
ylabel("Command");
title("Actuation-delay validation");
legend("Location", "best");