function figures = ...
    plot_load_task_sweep_comparison( ...
        phase2SummaryFile, ...
        phase3SummaryFile, ...
        options)
%PLOT_PHASE2_4_PHASE3_LOAD_TASK_SWEEP
% Compare fixed-rate and variable-rate LoadTask scheduling results.
%
% The summary files identify each experiment. Raw response-time samples are
% loaded from the RunFile stored in each summary row.

arguments
    phase2SummaryFile (1,1) string
    phase3SummaryFile (1,1) string
    options.LoadExecution_ms (1,:) double = 20:5:40
    options.Deadline_ms (1,1) double {mustBePositive} = 50
    options.SaveFigure (1,1) logical = true
end

assert(isfile(phase2SummaryFile), ...
    "Phase 2.4 summary file not found: %s", ...
    phase2SummaryFile);

assert(isfile(phase3SummaryFile), ...
    "Phase 3 summary file not found: %s", ...
    phase3SummaryFile);

requiredVariables = [ ...
    "Scenario", ...
    "Environment", ...
    "LoadExecution_ms", ...
    "NominalUtilization", ...
    "LoadDeadlineMissPercent", ...
    "LoadDroppedJobs", ...
    "Status", ...
    "RunFile"];

phase2Table = loadSummaryTable( ...
    phase2SummaryFile, ...
    requiredVariables);

phase3Table = loadSummaryTable( ...
    phase3SummaryFile, ...
    requiredVariables);

phase2Table = normalizeSummaryTable( ...
    phase2Table, ...
    "Fixed rate 10ms", ...
    options.LoadExecution_ms);

phase3Table = normalizeSummaryTable( ...
    phase3Table, ...
    "Variable rate", ...
    options.LoadExecution_ms);

validateRunFiles( ...
    phase2Table, ...
    "Phase 2.4");

validateRunFiles( ...
    phase3Table, ...
    "Phase 3");

summaryTable = [
    phase2Table
    phase3Table
    ];

assert(~isempty(summaryTable), ...
    "No completed cases exist for the requested load levels.");

scenarioNames = unique( ...
    summaryTable.Scenario, ...
    "stable");

environmentNames = unique( ...
    summaryTable.Environment, ...
    "stable");

policyNames = unique( ...
    summaryTable.Policy, ...
    "stable");

environmentColors = ...
    lines(numel(environmentNames));

policyColors = [
    0.00 0.45 0.74
    0.85 0.33 0.10
    ];

assert(numel(policyNames) <= size(policyColors,1), ...
    "Add colors for additional controller policies.");

figures = struct();

figures.Response = plotResponseDistributions( ...
    summaryTable, ...
    scenarioNames, ...
    environmentNames, ...
    policyNames, ...
    policyColors, ...
    options.Deadline_ms);

figures.Scheduling = plotSchedulingMetrics( ...
    summaryTable, ...
    scenarioNames, ...
    environmentNames, ...
    policyNames, ...
    environmentColors);

if options.SaveFigure

    projectRoot = string( ...
        matlab.project.currentProject().RootFolder);

    figureFolder = fullfile( ...
        projectRoot, ...
        "phase3", ...
        "figures", ...
        "phase2_4_vs_phase3");

    if ~isfolder(figureFolder)
        mkdir(figureFolder);
    end

    exportgraphics( ...
        figures.Response, ...
        fullfile( ...
            figureFolder, ...
            "load_task_response_comparison.png"), ...
        Resolution=200);

    exportgraphics( ...
        figures.Scheduling, ...
        fullfile( ...
            figureFolder, ...
            "load_task_schedulability_comparison.png"), ...
        Resolution=200);
end

end


function figureHandle = plotResponseDistributions( ...
    summaryTable, ...
    scenarioNames, ...
    environmentNames, ...
    policyNames, ...
    policyColors, ...
    deadline_ms)

figureHandle = figure( ...
    Name="LoadTask response comparison", ...
    Color="white");

layout = tiledlayout( ...
    numel(environmentNames), ...
    numel(scenarioNames), ...
    TileSpacing="compact", ...
    Padding="compact");

title( ...
    layout, ...
    "LoadTask Response-Time Distributions");

for environmentIndex = 1:numel(environmentNames)

    for scenarioIndex = 1:numel(scenarioNames)

        axisHandle = nexttile(layout);

        scenarioName = ...
            scenarioNames(scenarioIndex);

        environmentName = ...
            environmentNames(environmentIndex);

        hold(axisHandle, "on");

        legendHandles = ...
            gobjects(numel(policyNames),1);

        for policyIndex = 1:numel(policyNames)

            policyName = ...
                policyNames(policyIndex);

            caseRows = selectRows( ...
                summaryTable, ...
                scenarioName, ...
                environmentName, ...
                policyName);

            [utilization, responseTime_ms] = ...
                loadResponseSamples(caseRows);

            if isempty(responseTime_ms)
                continue;
            end

            legendHandles(policyIndex) = boxchart( ...
                axisHandle, ...
                utilization, ...
                responseTime_ms, ...
                BoxFaceColor= ...
                    policyColors(policyIndex,:), ...
                BoxFaceAlpha=0.70, ...
                MarkerStyle=".", ...
                JitterOutliers="on", ...
                DisplayName=policyName);
        end

        deadlineLine = yline( ...
            axisHandle, ...
            deadline_ms, ...
            "r--", ...
            "LoadTask deadline", ...
            LabelHorizontalAlignment="left");

        deadlineLine.HandleVisibility = "off";

        utilizationLine = xline( ...
            axisHandle, ...
            1, ...
            "k:", ...
            "U = 1");

        utilizationLine.HandleVisibility = "off";

        hold(axisHandle, "off");
        grid(axisHandle, "on");

        xlabel( ...
            axisHandle, ...
            "Nominal task-set utilization, U");

        ylabel( ...
            axisHandle, ...
            "Response time (ms)");

        title( ...
            axisHandle, ...
            cleanLabel(scenarioName) ...
            + " | " ...
            + cleanLabel(environmentName));

        validHandles = ...
            isgraphics(legendHandles);

        if any(validHandles)
            legend( ...
                axisHandle, ...
                legendHandles(validHandles), ...
                Location="best");
        end
    end
end

end


function figureHandle = plotSchedulingMetrics( ...
    summaryTable, ...
    scenarioNames, ...
    environmentNames, ...
    policyNames, ...
    environmentColors)

figureHandle = figure( ...
    Name="LoadTask schedulability comparison", ...
    Color="white");

layout = tiledlayout( ...
    2, ...
    numel(scenarioNames), ...
    TileSpacing="compact", ...
    Padding="compact");

title( ...
    layout, ...
    "LoadTask Schedulability Across Processor Utilization");

for scenarioIndex = 1:numel(scenarioNames)

    scenarioName = ...
        scenarioNames(scenarioIndex);

    deadlineAxis = ...
        nexttile(layout, scenarioIndex);

    plotByEnvironmentAndPolicy( ...
        deadlineAxis, ...
        summaryTable, ...
        scenarioName, ...
        environmentNames, ...
        policyNames, ...
        environmentColors, ...
        "LoadDeadlineMissPercent", ...
        "Deadline misses (%)");

    droppedAxis = nexttile( ...
        layout, ...
        numel(scenarioNames) + scenarioIndex);

    plotByEnvironmentAndPolicy( ...
        droppedAxis, ...
        summaryTable, ...
        scenarioName, ...
        environmentNames, ...
        policyNames, ...
        environmentColors, ...
        "LoadDroppedJobs", ...
        "Dropped jobs");
end

end


function plotByEnvironmentAndPolicy( ...
    axisHandle, ...
    summaryTable, ...
    scenarioName, ...
    environmentNames, ...
    policyNames, ...
    environmentColors, ...
    variableName, ...
    yLabel)

lineStyles = [
    "-"
    "--"
    ];

markers = [
    "."
    "*"
    ];

assert(numel(policyNames) <= numel(lineStyles), ...
    "Add line styles for additional policies.");

hold(axisHandle, "on");

for environmentIndex = 1:numel(environmentNames)

    environmentName = ...
        environmentNames(environmentIndex);

    for policyIndex = 1:numel(policyNames)

        policyName = ...
            policyNames(policyIndex);

        rows = selectRows( ...
            summaryTable, ...
            scenarioName, ...
            environmentName, ...
            policyName);

        if isempty(rows)
            continue;
        end

        plot( ...
            axisHandle, ...
            rows.NominalUtilization, ...
            rows.(variableName), ...
            Color=environmentColors(environmentIndex,:), ...
            LineStyle=lineStyles(policyIndex), ...
            Marker=markers(policyIndex), ...
            LineWidth=1.2, ...
            MarkerSize=5, ...
            DisplayName= ...
                cleanLabel(environmentName) ...
                + " | " + ...
                policyName);
    end
end

utilizationLine = xline( ...
    axisHandle, ...
    1, ...
    "k:", ...
    "U = 1");

utilizationLine.HandleVisibility = "off";

hold(axisHandle, "off");
grid(axisHandle, "on");

xlabel( ...
    axisHandle, ...
    "Nominal task-set utilization, U");

ylabel( ...
    axisHandle, ...
    yLabel);

title( ...
    axisHandle, ...
    cleanLabel(scenarioName));

legend( ...
    axisHandle, ...
    Location="best");

end


function rows = selectRows( ...
    summaryTable, ...
    scenarioName, ...
    environmentName, ...
    policyName)

rows = summaryTable( ...
    summaryTable.Scenario == scenarioName ...
    & summaryTable.Environment == environmentName ...
    & summaryTable.Policy == policyName, ...
    :);

rows = sortrows( ...
    rows, ...
    "NominalUtilization");

end


function [utilization, responseTime_ms] = ...
    loadResponseSamples(caseRows)

utilization = zeros(0,1);
responseTime_ms = zeros(0,1);

for rowIndex = 1:height(caseRows)

    runFile = string( ...
        caseRows.RunFile(rowIndex));

    if strlength(runFile) == 0 || ...
            ~isfile(runFile)

        warning( ...
            "SDV:MissingComparisonRun", ...
            "Skipping missing run file: %s", ...
            runFile);

        continue;
    end

    savedData = load( ...
        runFile, ...
        "runArtifact");

    if ~isfield(savedData, "runArtifact")

        warning( ...
            "SDV:MissingRunArtifact", ...
            "Run file has no runArtifact: %s", ...
            runFile);

        continue;
    end

    runArtifact = ...
        savedData.runArtifact;

    if isfield( ...
            runArtifact, ...
            "loadResponseTime_s")

        % Phase 2.4 artifact.
        samples_s = double( ...
            runArtifact.loadResponseTime_s(:));

    elseif isfield(runArtifact, "loadJobs") ...
            && istable(runArtifact.loadJobs) ...
            && ismember( ...
                "ResponseTime_s", ...
                string( ...
                    runArtifact.loadJobs.Properties.VariableNames))

        % Phase 3 artifact.
        samples_s = double( ...
            runArtifact.loadJobs.ResponseTime_s(:));

    else
        warning( ...
            "SDV:MissingLoadResponse", ...
            "No LoadTask response samples in: %s", ...
            runFile);

        continue;
    end

    samples_ms = ...
        1e3*samples_s;

    samples_ms = samples_ms( ...
        isfinite(samples_ms) ...
        & samples_ms >= 0);

    responseTime_ms = [
        responseTime_ms
        samples_ms
        ]; %#ok<AGROW>

    utilization = [
        utilization
        repmat( ...
            caseRows.NominalUtilization(rowIndex), ...
            numel(samples_ms), ...
            1)
        ]; %#ok<AGROW>
end

end


function summaryTable = loadSummaryTable( ...
    summaryFile, ...
    requiredVariables)

[~, ~, extension] = ...
    fileparts(summaryFile);

if strcmpi(extension, ".csv")

    summaryTable = readtable( ...
        summaryFile, ...
        TextType="string");

else

    savedData = load(summaryFile);
    variableNames = fieldnames(savedData);

    summaryTable = table();

    for index = 1:numel(variableNames)

        candidate = ...
            savedData.(variableNames{index});

        if ~istable(candidate)
            continue;
        end

        candidateVariables = string( ...
            candidate.Properties.VariableNames);

        if all(ismember( ...
                requiredVariables, ...
                candidateVariables))

            summaryTable = candidate;
            break;
        end
    end
end

assert(~isempty(summaryTable), ...
    "No compatible summary table found in %s.", ...
    summaryFile);

missingVariables = setdiff( ...
    requiredVariables, ...
    string(summaryTable.Properties.VariableNames));

assert(isempty(missingVariables), ...
    "Summary table %s is missing: %s", ...
    summaryFile, ...
    strjoin(missingVariables, ", "));

end


function summaryTable = normalizeSummaryTable( ...
    summaryTable, ...
    policyName, ...
    requestedLoadExecution_ms)

summaryTable.Scenario = ...
    string(summaryTable.Scenario);

summaryTable.Environment = ...
    string(summaryTable.Environment);

summaryTable.Status = ...
    string(summaryTable.Status);

summaryTable.RunFile = ...
    string(summaryTable.RunFile);

completed = ...
    summaryTable.Status == "completed";

requestedLoad = false( ...
    height(summaryTable), ...
    1);

for loadIndex = 1:numel(requestedLoadExecution_ms)

    requestedLoad = requestedLoad ...
        | abs( ...
            summaryTable.LoadExecution_ms ...
            - requestedLoadExecution_ms(loadIndex)) ...
        < 1e-9;
end

summaryTable = summaryTable( ...
    completed & requestedLoad, ...
    :);

summaryTable.Policy = repmat( ...
    policyName, ...
    height(summaryTable), ...
    1);

variablesToKeep = [
    "Policy"
    "Scenario"
    "Environment"
    "LoadExecution_ms"
    "NominalUtilization"
    "LoadDeadlineMissPercent"
    "LoadDroppedJobs"
    "Status"
    "RunFile"
    ];

summaryTable = ...
    summaryTable(:, variablesToKeep);

end


function validateRunFiles( ...
    summaryTable, ...
    phaseLabel)

assert(~isempty(summaryTable), ...
    "No completed %s rows exist for the requested load levels.", ...
    phaseLabel);

runFiles = string( ...
    summaryTable.RunFile);

missingFile = ...
    strlength(runFiles) == 0 ...
    | ~isfile(runFiles);

assert(~any(missingFile), ...
    "%s has missing RunFile entries:\n%s", ...
    phaseLabel, ...
    strjoin(runFiles(missingFile), newline));

[uniqueFiles, ~, fileGroup] = ...
    unique(runFiles);

fileCounts = accumarray( ...
    fileGroup, ...
    1);

duplicatedFiles = ...
    uniqueFiles(fileCounts > 1);

assert(isempty(duplicatedFiles), ...
    "%s summary rows reuse the same RunFile. " + ...
    "True response-time box plots would repeat overwritten data:\n%s", ...
    phaseLabel, ...
    strjoin(duplicatedFiles, newline));

end


function label = cleanLabel(value)

label = replace( ...
    string(value), ...
    "_", ...
    " ");

end