function [figureHandle, summaryTable] = ...
    plot_solve_time_box_plot_comparison( ...
        resultsRoots, ...
        samplingTimes_ms, ...
        options)
%PLOT_SOLVE_TIME_SAMPLING_COMPARISON
% Compare solve-time distributions for multiple controller sampling rates.

arguments
    resultsRoots (1,:) string
    samplingTimes_ms (1,:) double
    options.ScenarioNames (1,:) string = [ ...
        "urban_profile", ...
        "highway_cruise", ...
        "aggressive_maneuver"]
    options.EnvironmentNames (1,:) string = [ ...
        "dry_road", ...
        "low_friction_road"]
    options.ShowDeadlineLines (1,1) logical = false
    options.ShowFigure (1,1) logical = true
    options.FigureFile (1,1) string = ""
    options.SummaryCsvFile (1,1) string = ""
end

assert( ...
    numel(resultsRoots) == numel(samplingTimes_ms), ...
    "Provide one sampling time for every results root.");

assert( ...
    all(isfolder(resultsRoots)), ...
    "One or more results roots do not exist.");

numberOfPeriods = numel(samplingTimes_ms);
numberOfScenarios = numel(options.ScenarioNames);
numberOfEnvironments = numel(options.EnvironmentNames);

numberOfGroups = ...
    numberOfScenarios*numberOfEnvironments;

numberOfResults = ...
    numberOfGroups*numberOfPeriods;

solveTimeGroups_ms = ...
    cell(numberOfGroups, numberOfPeriods);

groupLabels = ...
    strings(numberOfGroups, 1);

summaryRecords = repmat(struct( ...
    SamplingTime_ms=NaN, ...
    Scenario="", ...
    Environment="", ...
    Samples=0, ...
    Mean_ms=NaN, ...
    Median_ms=NaN, ...
    P95_ms=NaN, ...
    P99_ms=NaN, ...
    Maximum_ms=NaN, ...
    DeadlineMissPercent=NaN), ...
    numberOfResults, ...
    1);

%% Load results

groupIndex = 0;
recordIndex = 0;

for scenarioIndex = 1:numberOfScenarios

    scenarioName = ...
        options.ScenarioNames(scenarioIndex);

    for environmentIndex = 1:numberOfEnvironments

        environmentName = ...
            options.EnvironmentNames(environmentIndex);

        groupIndex = groupIndex + 1;

        groupLabels(groupIndex) = ...
            prettyName(scenarioName) ...
            + " / " ...
            + prettyName(environmentName);

        for periodIndex = 1:numberOfPeriods

            recordIndex = recordIndex + 1;

            resultsFile = fullfile( ...
                resultsRoots(periodIndex), ...
                scenarioName, ...
                environmentName, ...
                scenarioName + "_results.mat");

            assert(isfile(resultsFile), ...
                "Result file not found: %s", ...
                resultsFile);

            savedData = load(resultsFile);

            results = findResultsStructure( ...
                savedData, ...
                resultsFile);

            assert(isfield(results, "solve_time_s"), ...
                "solve_time_s is missing from %s.", ...
                resultsFile);

            solveTime_ms = ...
                1e3*double(results.solve_time_s(:));

            validSample = ...
                isfinite(solveTime_ms) ...
                & solveTime_ms > 0;

            solveTime_ms = ...
                solveTime_ms(validSample);

            assert(~isempty(solveTime_ms), ...
                "No valid solve-time data found in %s.", ...
                resultsFile);

            solveTimeGroups_ms{ ...
                groupIndex, ...
                periodIndex} = solveTime_ms;

            samplingTime_ms = ...
                samplingTimes_ms(periodIndex);

            summaryRecords(recordIndex).SamplingTime_ms = ...
                samplingTime_ms;

            summaryRecords(recordIndex).Scenario = ...
                scenarioName;

            summaryRecords(recordIndex).Environment = ...
                environmentName;

            summaryRecords(recordIndex).Samples = ...
                numel(solveTime_ms);

            summaryRecords(recordIndex).Mean_ms = ...
                mean(solveTime_ms);

            summaryRecords(recordIndex).Median_ms = ...
                median(solveTime_ms);

            summaryRecords(recordIndex).P95_ms = ...
                empiricalPercentile( ...
                    solveTime_ms, 95);

            summaryRecords(recordIndex).P99_ms = ...
                empiricalPercentile( ...
                    solveTime_ms, 99);

            summaryRecords(recordIndex).Maximum_ms = ...
                max(solveTime_ms);

            summaryRecords(recordIndex).DeadlineMissPercent = ...
                100*mean( ...
                    solveTime_ms > samplingTime_ms);
        end
    end
end

summaryTable = struct2table(summaryRecords);

%% Create figure

if options.ShowFigure
    visibility = "on";
else
    visibility = "off";
end

figureHandle = figure( ...
    "Color", "white", ...
    "Visible", visibility, ...
    "Name", "acados solve-time sampling comparison");

axesHandle = axes( ...
    figureHandle, ...
    "Color", "white");

hold(axesHandle, "on");
grid(axesHandle, "on");
box(axesHandle, "on");

periodColors = [
    0.00 0.45 0.74   % 10 ms
    0.85 0.33 0.10   % 20 ms
    0.47 0.67 0.19   % 50 ms
    ];

assert(numberOfPeriods <= size(periodColors, 1), ...
    "Add more colors for additional sampling periods.");

groupOffsets = linspace( ...
    -0.25, ...
    0.25, ...
    numberOfPeriods);

boxWidth = min( ...
    0.20, ...
    0.65/numberOfPeriods);

legendHandles = gobjects(numberOfPeriods, 1);

for groupIndex = 1:numberOfGroups

    for periodIndex = 1:numberOfPeriods

        solveTime_ms = ...
            solveTimeGroups_ms{ ...
                groupIndex, ...
                periodIndex};

        horizontalPosition = ...
            groupIndex ...
            + groupOffsets(periodIndex);

        boxHandle = boxchart( ...
            axesHandle, ...
            repmat( ...
                horizontalPosition, ...
                size(solveTime_ms)), ...
            solveTime_ms, ...
            "BoxFaceColor", ...
            periodColors(periodIndex,:), ...
            "BoxFaceAlpha", 0.70, ...
            "BoxWidth", boxWidth, ...
            "MarkerStyle", ".", ...
            "MarkerSize", 10, ...
            "JitterOutliers", "on", ...
            "DisplayName", ...
            sprintf( ...
                "%g ms controller", ...
                samplingTimes_ms(periodIndex)));

        if groupIndex == 1
            legendHandles(periodIndex) = ...
                boxHandle;
        else
            boxHandle.HandleVisibility = "off";
        end
    end
end

%% Optional deadline lines

if options.ShowDeadlineLines

    for periodIndex = 1:numberOfPeriods

        deadlineLine = yline( ...
            axesHandle, ...
            samplingTimes_ms(periodIndex), ...
            "--", ...
            sprintf( ...
                "%g ms deadline", ...
                samplingTimes_ms(periodIndex)), ...
            "Color", ...
            periodColors(periodIndex,:), ...
            "LineWidth", 1.2);

        deadlineLine.HandleVisibility = "off";
    end
end

% Separate the three scenario pairs.
for separatorPosition = ...
        (numberOfEnvironments + 0.5): ...
        numberOfEnvironments: ...
        (numberOfGroups - 0.5)

    separator = xline( ...
        axesHandle, ...
        separatorPosition, ...
        ":", ...
        "Color", [0.65 0.65 0.65]);

    separator.HandleVisibility = "off";
end

xlim(axesHandle, ...
    [0.5, numberOfGroups + 0.5]);

xticks(axesHandle, ...
    1:numberOfGroups);

xticklabels(axesHandle, ...
    groupLabels);

xtickangle(axesHandle, 25);

ylim(axesHandle, ...
    'tight');
ylabel(axesHandle, ...
    "acados solve time (ms)");

title(axesHandle, ...
    "acados Solve-Time Distribution by Controller Sampling Period");

subtitle(axesHandle, ...
    "Three adjacent boxes for each scenario/environment combination");

legend( ...
    axesHandle, ...
    legendHandles, ...
    "Location", "best");

%% Save outputs

if strlength(options.FigureFile) > 0

    createParentFolder(options.FigureFile);

    exportgraphics( ...
        figureHandle, ...
        options.FigureFile, ...
        "Resolution", 300);
end

if strlength(options.SummaryCsvFile) > 0

    createParentFolder(options.SummaryCsvFile);

    writetable( ...
        summaryTable, ...
        options.SummaryCsvFile);
end

end


function results = ...
    findResultsStructure(savedData, resultsFile)

if isfield(savedData, "results")
    results = savedData.results;
    return;
end

if isfield(savedData, "runArtifact") && ...
        isfield(savedData.runArtifact, "results")

    results = savedData.runArtifact.results;
    return;
end

variableNames = fieldnames(savedData);

for index = 1:numel(variableNames)

    candidate = ...
        savedData.(variableNames{index});

    if isstruct(candidate) && ...
            isfield(candidate, "solve_time_s")

        results = candidate;
        return;
    end
end

error( ...
    "No results structure containing solve_time_s found in %s.", ...
    resultsFile);

end


function value = ...
    empiricalPercentile(samples, percentile)

samples = sort(samples(:));

sampleIndex = max( ...
    1, ...
    ceil((percentile/100)*numel(samples)));

value = samples(sampleIndex);

end


function outputName = prettyName(inputName)

outputName = replace( ...
    inputName, ...
    "_", ...
    " ");

end


function createParentFolder(fileName)

parentFolder = fileparts(fileName);

if strlength(parentFolder) > 0 && ...
        ~isfolder(parentFolder)

    mkdir(parentFolder);
end

end