function [figureHandle, axesHandle] = ...
    plot_offline_n_simulated_tags(runArtifact, offlineTags)
%PLOT_PHASE3_MODE_ALIGNMENT Compare logged and scheduled active modes.

loggedTime_s = double(runArtifact.mode.Time_s(:));
loggedMode = double(runArtifact.mode.Data(:));

offlineTime_s = double( ...
    offlineTags.timing_table.time_s(:));

alignedMode = double( ...
    offlineTags.timing_table.activeMode(:));

assert( ...
    numel(loggedTime_s) == numel(loggedMode), ...
    "Logged mode time and data lengths do not match.");

assert( ...
    numel(offlineTime_s) == numel(alignedMode), ...
    "Aligned-tag time and mode lengths do not match.");

loggedColor = [0.00, 0.45, 0.74];
alignedColor = [0.85, 0.33, 0.10];

figureHandle = figure( ...
    Name="Phase 3 mode alignment", ...
    Color="white");

axesHandle = axes(figureHandle);
hold(axesHandle, "on");

stairs( ...
    axesHandle, ...
    loggedTime_s, ...
    loggedMode, ...
    "-", ...
    Color=loggedColor, ...
    LineWidth=2, ...
    DisplayName="Logged active mode");

stairs( ...
    axesHandle, ...
    offlineTime_s, ...
    alignedMode, ...
    "--", ...
    Color=alignedColor, ...
    LineWidth=1.7, ...
    DisplayName="Offline-tag active mode");

%% End-time markers

loggedEnd_s = loggedTime_s(end);
offlineEnd_s = offlineTime_s(end);

sameEndTime = ...
    abs(loggedEnd_s - offlineEnd_s) <= 1e-9;

if sameEndTime
    xline( ...
        axesHandle, ...
        loggedEnd_s, ...
        "k--", ...
        sprintf("Both end: %.3f s", loggedEnd_s), ...
        LineWidth=1.5, ...
        LabelVerticalAlignment="middle", ...
        HandleVisibility="off");
else
    xline( ...
        axesHandle, ...
        loggedEnd_s, ...
        "--", ...
        sprintf("Logged ends: %.3f s", loggedEnd_s), ...
        Color=loggedColor, ...
        LineWidth=1.5, ...
        LabelVerticalAlignment="middle", ...
        HandleVisibility="off");

    xline( ...
        axesHandle, ...
        offlineEnd_s, ...
        "--", ...
        sprintf("offline tag end: %.3f s", offlineEnd_s), ...
        Color=alignedColor, ...
        LineWidth=1.5, ...
        LabelVerticalAlignment="bottom", ...
        HandleVisibility="off");
end

%% Formatting

yticks(axesHandle, [1, 2, 3]);

yticklabels( ...
    axesHandle, ...
    ["Low: 50 ms", "Medium: 20 ms", "High: 10 ms"]);

ylim(axesHandle, [0.8, 3.2]);

xStart_s = min(loggedTime_s(1), offlineTime_s(1));
xEnd_s = max(loggedEnd_s, offlineEnd_s);

xlim(axesHandle, [xStart_s, xEnd_s]);

xlabel(axesHandle, "Time (s)");
ylabel(axesHandle, "Controller mode");

title( ...
    axesHandle, ...
    "Logged Controller Mode versus Aligned Demand Tags");

grid(axesHandle, "on");
box(axesHandle, "on");

legend( ...
    axesHandle, ...
    Location="best", ...
    Interpreter="none");

end