resultFile = fullfile( ...
    projectRoot, ...
    "phase3", ...
    "results", ...
    "aligned_scheduler_runs", ...
    "highway_cruise", ...
    "low_friction_road", ...
    "load_0.03", ...
    "simulation_output.mat");

[probeFigure, probeData, runArtifact] = ...
    sdv.analysis.probeSavedRun( ...
    resultFile, ...
    TimeWindow_s=[40, 42]);