function [runArtifact, resultsFile] = ...
    run_phase4_fixed_mode_case( ...
        scenarioName, environmentName, sampleTime_s, options)
%RUN_PHASE4_FIXED_MODE_CASE Run one fixed-period scheduler experiment.

arguments
    scenarioName (1,1) string
    environmentName (1,1) string
    sampleTime_s (1,1) double {mustBePositive}
    options.ModelName (1,1) string = "phase3_scheduler_testbed"
    options.LoadTaskDuration_s (1,1) double ...
        {mustBeNonnegative} = 0.020
    options.LoadTaskPeriod_s (1,1) double ...
        {mustBePositive} = 0.050
    options.RandomSeed (1,1) double = 4001
    options.ResultsRoot (1,1) string = ""
    options.Overwrite (1,1) logical = false
end

startup_project;

projectRoot = string( ...
    matlab.project.currentProject().RootFolder);

if strlength(options.ResultsRoot) == 0
    options.ResultsRoot = fullfile( ...
        projectRoot, "phase4", "results", ...
        "performance_map_runs");
end

[modeId, periodLabel] = ...
    sampleTimeToMode(sampleTime_s);

resultsFolder = fullfile( ...
    options.ResultsRoot, ...
    scenarioName, ...
    environmentName, ...
    periodLabel);

if ~isfolder(resultsFolder)
    mkdir(resultsFolder);
end

resultsFile = fullfile( ...
    resultsFolder, "fixed_mode_run.mat");

if isfile(resultsFile) && ~options.Overwrite
    savedData = load(resultsFile, "runArtifact");
    assert(isfield(savedData, "runArtifact"), ...
        "Existing run file does not contain runArtifact:\n%s", ...
        resultsFile);
    runArtifact = savedData.runArtifact;
    fprintf("Using existing fixed-mode run:\n%s\n", resultsFile);
    return;
end

configuration = ...
    build_phase0_configuration(scenarioName);

vehicleParams = configuration.vehicle;
controllerParams = configuration.controller;
simulationParams = configuration.simulation;
adaptiveModelParams = configuration.adaptiveModel;

check_runtime_requirements(controllerParams);

track_ref_table = ...
    configuration.scenario.lookup_table;

scenario_stop_table = ...
    configuration.scenario.stop_event_table;

stopTime_s = ...
    configuration.scenario.simulation_stop_time_s;

final_track_index = size(track_ref_table, 1);

initialControllerMeasurement = [
    simulationParams.initial_speed_mps
    0
    0
    simulationParams.initial_x_m
    simulationParams.initial_y_m
    simulationParams.initial_yaw_rad
    ];

UT = legacy_plant_parameters( ...
    vehicleParams, simulationParams);

acadosSettings = ...
    acados_ocp_parameters(controllerParams);

acados_nominal_input = reshape( ...
    acadosSettings.nominal_input, 2, 1);

environment = load_env_profile( ...
    lower(environmentName), ...
    stopTime_s, ...
    FrictionDropTime_s=10);

roadFrictionProfile = ...
    environment.road_friction_profile;

%% Force one controller mode for the complete run

supervisorSampleTime_s = 0.010;
supervisorTime_s = ...
    (0:supervisorSampleTime_s:stopTime_s).';

fixedMode = repmat( ...
    modeId, numel(supervisorTime_s), 1);

phase3_demand_mode_ts = timeseries( ...
    fixedMode, supervisorTime_s);


phase3_demand_mode_ts = setinterpmethod( ...
    phase3_demand_mode_ts, "zoh");

%% Controller execution-time realization for this fixed mode

durationBank = struct();

durationBank.LOW = load_control_task_durations( ...
    scenarioName, environmentName, "phase3_50ms");

durationBank.MEDIUM = load_control_task_durations( ...
    scenarioName, environmentName, "phase3_20ms");

durationBank.HIGH = load_control_task_durations( ...
    scenarioName, environmentName, "phase0");

controlTaskDuration = ...
    create_phase3_control_task_duration( ...
        phase3_demand_mode_ts, ...
        durationBank, ...
        stopTime_s, ...
        options.RandomSeed, ...
        SupervisorSampleTime_s=supervisorSampleTime_s);

loadReleaseTime_s = ...
    (0:options.LoadTaskPeriod_s:stopTime_s).';

loadTaskDuration = timeseries( ...
    repmat( ...
        options.LoadTaskDuration_s, ...
        numel(loadReleaseTime_s), 1), ...
    loadReleaseTime_s);

loadTaskDuration = setinterpmethod( ...
    loadTaskDuration, "zoh");

%% Simulation input

simulationInput = ...
    Simulink.SimulationInput(options.ModelName);

simulationVariables = struct( ...
    phase3_demand_mode_ts = phase3_demand_mode_ts, ...
    roadFrictionProfile=roadFrictionProfile, ...
    controlTaskDuration=controlTaskDuration, ...
    loadTaskDuration=loadTaskDuration, ...
    vehicleParams=vehicleParams, ...
    controllerParams=controllerParams, ...
    simulationParams=simulationParams, ...
    adaptiveModelParams=adaptiveModelParams, ...
    initialControllerMeasurement=initialControllerMeasurement, ...
    UT=UT, ...
    acados_nominal_input=acados_nominal_input, ...
    track_ref_table=track_ref_table, ...
    scenario_stop_table=scenario_stop_table, ...
    final_track_index=final_track_index);

variableNames = fieldnames(simulationVariables);

for variableIndex = 1:numel(variableNames)
    variableName = variableNames{variableIndex};
    simulationInput = simulationInput.setVariable( ...
        variableName, simulationVariables.(variableName));
end

simulationInput = simulationInput.setModelParameter( ...
    StopTime=string(stopTime_s), ...
    ReturnWorkspaceOutputs="on", ...
    SignalLogging="on", ...
    SignalLoggingName="logsout", ...
    SignalInfNanChecking="error");

load_system(options.ModelName);

runIdsBefore = Simulink.sdi.getAllRunIDs;

fprintf( ...
    "Running fixed mode: %s | %s | %.0f ms\n", ...
    scenarioName, environmentName, 1e3*sampleTime_s);

simulationOutput = sim(simulationInput);

metadata = struct( ...
    Policy="fixed_" + string(round(1e3*sampleTime_s)) + "ms", ...
    Scenario=scenarioName, ...
    Environment=environmentName, ...
    LoadCase="fixed", ...
    LoadExecutionTime_ms=1e3*options.LoadTaskDuration_s, ...
    LoadTaskExecutionTime_s=options.LoadTaskDuration_s, ...
    LoadTaskPeriod_s=options.LoadTaskPeriod_s, ...
    RandomSeed=options.RandomSeed, ...
    StopTime_s=stopTime_s);

[runArtifact, ~] = collect_phase3_results( ...
    simulationOutput, ...
    options.ModelName, ...
    runIdsBefore, ...
    track_ref_table, ...
    metadata);

runArtifact.fixedSampleTime_s = sampleTime_s;
runArtifact.fixedModeId = modeId;
runArtifact.controlInput = ...
    extractControlInput(simulationOutput);
runArtifact.runFile = string(resultsFile);

runMetadata = struct( ...
    scenario=scenarioName, ...
    environment=environmentName, ...
    fixed_sample_time_s=sampleTime_s, ...
    fixed_mode_id=modeId, ...
    random_seed=options.RandomSeed, ...
    load_task_duration_s=options.LoadTaskDuration_s, ...
    load_task_period_s=options.LoadTaskPeriod_s);

save( ...
    resultsFile, ...
    "runArtifact", ...
    "configuration", ...
    "runMetadata", ...
    "-v7.3");

fprintf("Saved fixed-mode run:\n%s\n", resultsFile);

end


function [modeId, periodLabel] = sampleTimeToMode(sampleTime_s)

candidateSampleTimes_s = [0.050; 0.020; 0.010];
[difference, modeIndex] = min(abs( ...
    candidateSampleTimes_s - sampleTime_s));

assert(difference < 1e-12, ...
    "Sample time must be 0.050, 0.020, or 0.010 seconds.");

modeId = uint8(modeIndex);
periodLabel = sprintf( ...
    "sample_time_%03d_ms", round(1e3*sampleTime_s));

end


function controlInput = extractControlInput(simulationOutput)

availableVariables = string(simulationOutput.who);

assert(ismember("control_input", availableVariables), ...
    "Simulation output does not contain control_input.");

controlInputSignal = ...
    simulationOutput.get("control_input");

controlInputData = ...
    squeeze(double(controlInputSignal.Data));

if size(controlInputData, 1) ~= ...
        numel(controlInputSignal.Time)
    controlInputData = controlInputData.';
end

assert(size(controlInputData, 2) >= 6, ...
    "control_input must contain [vx, vy, yaw rate, X, Y, yaw].");

controlInput = struct();
controlInput.Time_s = double(controlInputSignal.Time(:));
controlInput.Data = controlInputData(:, 1:6);

end
