function [simulationOutput, resultsFile] = ...
    run_phase4_lookup_supervisor( ...
        scenarioName, environmentName, options)
%RUN_PHASE4_LOOKUP_SUPERVISOR Run one Phase 4 lookup-map simulation.

arguments
    scenarioName (1,1) string
    environmentName (1,1) string
    options.ModelName (1,1) string = "phase4_scheduler_testbed"
    options.LoadTaskDuration_s (1,1) double ...
        {mustBeNonnegative} = 0.020
    options.LoadTaskPeriod_s (1,1) double ...
        {mustBePositive} = 0.050
    options.RandomSeed (1,1) double = 4001
    options.SupervisorExecutionTimeSamples_s (:,1) double = zeros(0,1)
end

startup_project;

projectRoot = string( ...
    matlab.project.currentProject().RootFolder);

parameters = phase4_performance_map_parameters();

[performanceMap, mapFile] = ...
    load_phase4_performance_map( ...
        scenarioName, environmentName);

configuration = ...
    build_phase0_configuration(scenarioName);

vehicleParams = configuration.vehicle;
controllerParams = configuration.controller;
simulationParams = configuration.simulation;
adaptiveModelParams = configuration.adaptiveModel;

check_runtime_requirements(controllerParams);

track_ref_table = ...
    configuration.scenario.lookup_table;

scenario_stop_table = ...
    configuration.scenario.stop_event_table;

stopTime_s = ...
    configuration.scenario.simulation_stop_time_s;

final_track_index = size(track_ref_table, 1);

initialControllerMeasurement = [
    simulationParams.initial_speed_mps
    0
    0
    simulationParams.initial_x_m
    simulationParams.initial_y_m
    simulationParams.initial_yaw_rad
    ];

UT = legacy_plant_parameters( ...
    vehicleParams, simulationParams);

acadosSettings = ...
    acados_ocp_parameters(controllerParams);

acados_nominal_input = reshape( ...
    acadosSettings.nominal_input, 2, 1);

environment = load_env_profile( ...
    lower(environmentName), ...
    stopTime_s, ...
    FrictionDropTime_s=10);

roadFrictionProfile = ...
    environment.road_friction_profile;

%% Runtime map variables used by the MATLAB Function blocks

MapX = performanceMap.mapX;
MapY = performanceMap.mapY;

assert(size(MapX, 2) == 7, ...
    "MapX must contain seven feature columns.");

assert(size(MapY, 2) == 6, ...
    "MapY must contain six outcome columns.");

MapSampleTimes_s = performanceMap.mapSampleTimes_s;
MapNormalizationMean = performanceMap.normalizationMean;
MapNormalizationScale = performanceMap.normalizationScale;
MapRawMinimum = performanceMap.rawMinimum;
MapRawMaximum = performanceMap.rawMaximum;
MapSafetyMargins = performanceMap.safetyMargins;
MapMaximumNearestDistance = ...
    performanceMap.maximumNearestDistance;

MaximumCpuUtilization = ...
    parameters.maximum_cpu_utilization;

supervisorTimingSamples_s = double( ...
    options.SupervisorExecutionTimeSamples_s(:));
supervisorTimingSamples_s = supervisorTimingSamples_s( ...
    isfinite(supervisorTimingSamples_s) ...
    & supervisorTimingSamples_s >= 0);

if isempty(supervisorTimingSamples_s)
    supervisorTimingSamples_s = ...
        parameters.supervisor_execution_time_s;
end

supervisorTimingStatistics = ...
    sdv.metrics.computeSampleStatistics( ...
        supervisorTimingSamples_s);

meanBackgroundCpuUtilization = ...
    options.LoadTaskDuration_s/options.LoadTaskPeriod_s ...
    + parameters.communication_execution_time_s ...
    / parameters.communication_period_s ...
    + supervisorTimingStatistics.Mean ...
    / parameters.supervisor_period_s;

p95BackgroundCpuUtilization = ...
    options.LoadTaskDuration_s/options.LoadTaskPeriod_s ...
    + parameters.communication_execution_time_s ...
    / parameters.communication_period_s ...
    + supervisorTimingStatistics.P95 ...
    / parameters.supervisor_period_s;

CandidateSampleTimes_s = ...
    performanceMap.candidateSampleTimes_s(:);

meanControlExecutionTime_s = ...
    performanceMap.meanControlExecutionTime_s(:);

p95ControlExecutionTime_s = ...
    performanceMap.p95ControlExecutionTime_s(:);

ModeMeanCpuUtilization = ...
    meanBackgroundCpuUtilization ...
    + meanControlExecutionTime_s ...
      ./ CandidateSampleTimes_s;

ModeP95CpuUtilization = ...
    p95BackgroundCpuUtilization ...
    + p95ControlExecutionTime_s ...
      ./ CandidateSampleTimes_s;

ModeCpuAdmissible = ...
    ModeP95CpuUtilization <= MaximumCpuUtilization;

MaximumLateralError_m = max(abs([ ...
    controllerParams.minimumState(4), ...
    controllerParams.maximumState(4)]));

MaximumHeadingError_rad = max(abs([ ...
    controllerParams.minimumState(5), ...
    controllerParams.maximumState(5)]));

CostWeights = parameters.cost_weights;

%% Task-duration inputs

supervisorTime_s = ...
    (0:parameters.supervisor_sample_time_s:stopTime_s).';

durationBank = struct();
durationBank.LOW = load_control_task_durations( ...
    scenarioName, environmentName, "phase3_50ms");
durationBank.MEDIUM = load_control_task_durations( ...
    scenarioName, environmentName, "phase3_20ms");
durationBank.HIGH = load_control_task_durations( ...
    scenarioName, environmentName, "phase0");

[controlTaskDurationByMode, supervisorTaskDuration, durationProfile] = ...
    create_phase4_task_duration_profiles( ...
        durationBank, ...
        stopTime_s, ...
        options.RandomSeed, ...
        SupervisorSampleTime_s=parameters.supervisor_sample_time_s, ...
        SupervisorExecutionTimeSamples_s= ...
            options.SupervisorExecutionTimeSamples_s, ...
        SupervisorExecutionTime_s= ...
            parameters.supervisor_execution_time_s);

loadReleaseTime_s = ...
    (0:options.LoadTaskPeriod_s:stopTime_s).';

loadTaskDuration = timeseries( ...
    repmat( ...
        options.LoadTaskDuration_s, ...
        numel(loadReleaseTime_s), 1), ...
    loadReleaseTime_s);

loadTaskDuration = setinterpmethod( ...
    loadTaskDuration, "zoh");

% The copied Phase 4 application still contains an unused Phase 3 From
% Workspace block. Keep a valid signal available until that block is
% removed from the model.
phase3_demand_mode_ts = timeseries( ...
    repmat(uint8(3), numel(supervisorTime_s), 1), ...
    supervisorTime_s);

phase3_demand_mode_ts = setinterpmethod( ...
    phase3_demand_mode_ts, "zoh");

%% Simulation

simulationInput = ...
    Simulink.SimulationInput(options.ModelName);

simulationVariables = struct( ...
    MapX=MapX, ...
    MapY=MapY, ...
    MapSampleTimes_s=MapSampleTimes_s, ...
    MapNormalizationMean=MapNormalizationMean, ...
    MapNormalizationScale=MapNormalizationScale, ...
    MapRawMinimum=MapRawMinimum, ...
    MapRawMaximum=MapRawMaximum, ...
    MapSafetyMargins=MapSafetyMargins, ...
    MapMaximumNearestDistance=MapMaximumNearestDistance, ...
    CandidateSampleTimes_s=CandidateSampleTimes_s, ...
    ModeMeanCpuUtilization=ModeMeanCpuUtilization, ...
    ModeP95CpuUtilization=ModeP95CpuUtilization, ...
    ModeCpuAdmissible=ModeCpuAdmissible, ...
    MaximumCpuUtilization=MaximumCpuUtilization, ...
    MaximumLateralError_m=MaximumLateralError_m, ...
    MaximumHeadingError_rad=MaximumHeadingError_rad, ...
    CostWeights=CostWeights, ...
    performanceMap=performanceMap, ...
    phase3_demand_mode_ts=phase3_demand_mode_ts, ...
    roadFrictionProfile=roadFrictionProfile, ...
    controlTaskDurationByMode=controlTaskDurationByMode, ...
    supervisorTaskDuration=supervisorTaskDuration, ...
    loadTaskDuration=loadTaskDuration, ...
    vehicleParams=vehicleParams, ...
    controllerParams=controllerParams, ...
    simulationParams=simulationParams, ...
    adaptiveModelParams=adaptiveModelParams, ...
    initialControllerMeasurement=initialControllerMeasurement, ...
    UT=UT, ...
    acados_nominal_input=acados_nominal_input, ...
    track_ref_table=track_ref_table, ...
    scenario_stop_table=scenario_stop_table, ...
    final_track_index=final_track_index);

variableNames = fieldnames(simulationVariables);

for variableIndex = 1:numel(variableNames)
    variableName = variableNames{variableIndex};
    simulationInput = simulationInput.setVariable( ...
        variableName, simulationVariables.(variableName));
end

simulationInput = simulationInput.setModelParameter( ...
    StopTime=string(stopTime_s), ...
    ReturnWorkspaceOutputs="on", ...
    SignalLogging="on", ...
    SignalLoggingName="logsout", ...
    SignalInfNanChecking="error");

fprintf( ...
    "Running Phase 4 lookup supervisor: %s | %s\n", ...
    scenarioName, environmentName);

runIdsBefore = Simulink.sdi.getAllRunIDs;

simulationOutput = sim(simulationInput);

resultsFolder = fullfile( ...
    projectRoot, ...
    "phase4", ...
    "results", ...
    "lookup_supervisor", ...
    scenarioName, ...
    environmentName);

if ~isfolder(resultsFolder)
    mkdir(resultsFolder);
end

resultsFile = fullfile( ...
    resultsFolder, "simulation_output.mat");

runMetadata = struct( ...
    scenario=scenarioName, ...
    environment=environmentName, ...
    performance_map_file=mapFile, ...
    load_task_duration_s=options.LoadTaskDuration_s, ...
    load_task_period_s=options.LoadTaskPeriod_s, ...
    random_seed=options.RandomSeed, ...
    control_duration_policy="empirical_mode_profiles", ...
    supervisor_duration_policy=durationProfile.SupervisorPolicy);

collectionMetadata = struct( ...
    Phase="4", ...
    Policy="lookup_supervisor", ...
    Scenario=scenarioName, ...
    Environment=environmentName, ...
    LoadCase="lookup_supervisor", ...
    LoadExecutionTime_ms=1e3*options.LoadTaskDuration_s, ...
    LoadTaskExecutionTime_s=options.LoadTaskDuration_s, ...
    LoadTaskPeriod_s=options.LoadTaskPeriod_s, ...
    CommunicationTaskExecutionTime_s= ...
        parameters.communication_execution_time_s, ...
    CommunicationTaskPeriod_s= ...
        parameters.communication_period_s, ...
    SupervisorTaskExecutionTime_s= ...
        supervisorTimingStatistics.Mean, ...
    SupervisorTaskPeriod_s= ...
        parameters.supervisor_period_s, ...
    SupervisorTaskDurationSignal=struct( ...
        Time_s=durationProfile.Time_s, ...
        Data=durationProfile.SupervisorDuration_s), ...
    RandomSeed=options.RandomSeed, ...
    StopTime_s=stopTime_s);

[runArtifact, ~] = collect_phase3_results( ...
    simulationOutput, ...
    options.ModelName, ...
    runIdsBefore, ...
    track_ref_table, ...
    collectionMetadata);

loggedSignalNames = string( ...
    simulationOutput.logsout.getElementNames);

if ismember("candidate_cost", loggedSignalNames)
    candidateCost = extract_phase4_candidate_cost( ...
        simulationOutput.logsout, ...
        "candidate_cost", ...
        CandidateSampleTimes_s);
else
    warning( ...
        "Phase4:CandidateCostNotLogged", ...
        ["The logged signal 'candidate_cost' was not found. " ...
         "The simulation result will be saved without cost data."]);

    candidateCost = struct( ...
        Time_s=zeros(0, 1), ...
        Data=zeros(0, numel(CandidateSampleTimes_s)), ...
        CandidateSampleTimes_s=CandidateSampleTimes_s(:));
end

runArtifact.performanceMapFile = string(mapFile);
runArtifact.runFile = string(resultsFile);
runArtifact.durationProfile = durationProfile;
runArtifact.candidateCost = candidateCost;
runArtifact.costWeights = CostWeights(:);

save( ...
    resultsFile, ...
    "runArtifact", ...
    "simulationOutput", ...
    "configuration", ...
    "performanceMap", ...
    "runMetadata", ...
    "-v7.3");

fprintf("Saved Phase 4 result:\n%s\n", resultsFile);
fprintf("Candidate-cost plot script:\n run_plot_phase4_candidate_cost_comparison\n");

end
