function addModelReferenceInheritanceRule( ...
    generatedDirectory)

sourceFile = fullfile( ...
    generatedDirectory, ...
    "acados_solver_sfunction_sdv_dynamic_bicycle.c");

sourceText = fileread(sourceFile);

inheritanceRule = ...
    "ssSetModelReferenceSampleTimeInheritanceRule(" + ...
    "S, USE_DEFAULT_FOR_DISCRETE_INHERITANCE);";

% Avoid adding the rule more than once.
if contains(sourceText, inheritanceRule)
    return;
end

pattern = ...
    "(static void mdlInitializeSizes\s*" + ...
    "\(SimStruct \*S\)\s*\{)";

replacement = ...
    "$1" + newline + ...
    "    " + inheritanceRule;

patchedText = regexprep( ...
    sourceText, ...
    pattern, ...
    replacement, ...
    "once");

assert( ...
    patchedText ~= sourceText, ...
    "Could not locate mdlInitializeSizes in generated S-function.");

fileID = fopen(sourceFile, "w");

assert( ...
    fileID ~= -1, ...
    "Could not open generated S-function source for writing.");

fileCleanup = onCleanup(@() fclose(fileID));

fprintf(fileID, "%s", patchedText);

disp( ...
    "Added the model-reference sample-time inheritance rule.");

end