function comparison = compare_sampling_jitter_baseline( ...
    periodicResults, triggeredResults, options)
%COMPARE_SAMPLING_JITTER_BASELINE Check J=0 triggered equivalence.

arguments
    periodicResults (1,1) struct
    triggeredResults (1,1) struct
    options.MaximumSpeedRmsDifference_mps (1,1) double ...
        {mustBeNonnegative} = 0.05
    options.MaximumPositionRmsDifference_m (1,1) double ...
        {mustBeNonnegative} = 0.25
    options.MaximumFinalPositionDifference_m (1,1) double ...
        {mustBeNonnegative} = 0.50
    options.AssertEquivalent (1,1) logical = true
end

periodicTime_s = periodicResults.time_s(:);
triggeredTime_s = triggeredResults.time_s(:);
commonEnd_s = min(periodicTime_s(end), triggeredTime_s(end));
commonTime_s = periodicTime_s(periodicTime_s <= commonEnd_s);

periodicVx = sampleSignal( ...
    periodicTime_s, periodicResults.vx_mps, commonTime_s);
triggeredVx = sampleSignal( ...
    triggeredTime_s, triggeredResults.vx_mps, commonTime_s);
periodicX = sampleSignal( ...
    periodicTime_s, periodicResults.x_pos_m, commonTime_s);
triggeredX = sampleSignal( ...
    triggeredTime_s, triggeredResults.x_pos_m, commonTime_s);
periodicY = sampleSignal( ...
    periodicTime_s, periodicResults.y_pos_m, commonTime_s);
triggeredY = sampleSignal( ...
    triggeredTime_s, triggeredResults.y_pos_m, commonTime_s);

speedDifference_mps = triggeredVx - periodicVx;
positionDifference_m = hypot( ...
    triggeredX - periodicX, triggeredY - periodicY);

comparison = struct();
comparison.common_end_time_s = commonEnd_s;
comparison.speed_rms_difference_mps = ...
    sqrt(mean(speedDifference_mps.^2));
comparison.speed_peak_difference_mps = ...
    max(abs(speedDifference_mps));
comparison.position_rms_difference_m = ...
    sqrt(mean(positionDifference_m.^2));
comparison.position_peak_difference_m = ...
    max(positionDifference_m);
comparison.final_position_difference_m = ...
    positionDifference_m(end);

comparison.passed = ...
    comparison.speed_rms_difference_mps <= ...
        options.MaximumSpeedRmsDifference_mps && ...
    comparison.position_rms_difference_m <= ...
        options.MaximumPositionRmsDifference_m && ...
    comparison.final_position_difference_m <= ...
        options.MaximumFinalPositionDifference_m;

fprintf("\nJ = 0 baseline-equivalence check:\n");
fprintf("Speed RMS difference:    %.6f m/s\n", ...
    comparison.speed_rms_difference_mps);
fprintf("Position RMS difference: %.6f m\n", ...
    comparison.position_rms_difference_m);
fprintf("Final position difference: %.6f m\n", ...
    comparison.final_position_difference_m);

if options.AssertEquivalent
    assert(comparison.passed, ...
        "J = 0 triggered execution is not equivalent to the periodic baseline.");
end

end

function sampledData = sampleSignal(sourceTime_s, sourceData, targetTime_s)
[sourceTime_s, uniqueIndex] = unique(sourceTime_s(:), "last");
sourceData = sourceData(:);
sourceData = sourceData(uniqueIndex);
sampledData = interp1( ...
    sourceTime_s, sourceData, targetTime_s, "linear");
end
