function executionLog = extract_controller_execution_log( ...
    logs, ...
    eventTable, ...
    executionValidation, ...
    nominalSampleTime_s)
%EXTRACT_CONTROLLER_EXECUTION_LOG
% Create one telemetry row for every actual controller execution.
%
% Inputs:
%   logs                  Simulink logsout dataset
%   eventTable            generated trigger schedule
%   executionValidation   Output from validate_controller_executions
%   nominalSampleTime_s   Nominal controller period, seconds
%
% Output:
%   executionLog          One table row per controller execution

arguments
    logs
    eventTable table
    executionValidation (1,1) struct
    nominalSampleTime_s (1,1) double {mustBePositive}
end

%% Validate execution information

requiredFields = [ ...
    "actual_count"
    "actual_execution_times_s"
    ];

missingFields = setdiff( ...
    requiredFields, ...
    string(fieldnames(executionValidation)));

assert(isempty(missingFields), ...
    "Missing execution-validation fields: %s", ...
    strjoin(missingFields, ", "));

%% Obtain actual execution times

actualTime_s = reshape( ...
    double(executionValidation.actual_execution_times_s), ...
    [], ...
    1);

numberOfExecutions = numel(actualTime_s);

assert(numberOfExecutions > 0, ...
    "No controller executions were detected.");

assert( ...
    numberOfExecutions == executionValidation.actual_count, ...
    "Execution-count data is inconsistent.");

assert(height(eventTable) >= numberOfExecutions, ...
    "The event table is shorter than the execution log.");

% The simulation may stop before the original trigger schedule ends.
% Keep only the schedule entries that actually occurred.
eventTable = eventTable(1:numberOfExecutions, :);

%% Compute realized execution timing

actualInterval_s = [ ...
    NaN
    diff(actualTime_s)
    ];

actualJitter_s = ...
    actualInterval_s - nominalSampleTime_s;

schedulingError_s = ...
    actualTime_s - eventTable.AppliedTime_s;

%% Sample controller outputs once per execution

solveTime_s = sampleHeldSignal( ...
    logs, ...
    "solve_time", ...
    actualTime_s);

solverStatus = sampleHeldSignal( ...
    logs, ...
    "solve_status", ...
    actualTime_s);

torque_Nm = sampleHeldSignal( ...
    logs, ...
    "torque_opt", ...
    actualTime_s);

steering_rad = sampleHeldSignal( ...
    logs, ...
    "steering_angle_opt", ...
    actualTime_s);

%% Construct the execution table

executionLog = table( ...
    eventTable.EventIndex, ...
    eventTable.RequestedTime_s, ...
    eventTable.AppliedTime_s, ...
    actualTime_s, ...
    schedulingError_s, ...
    actualInterval_s, ...
    actualJitter_s, ...
    solveTime_s, ...
    solverStatus, ...
    torque_Nm, ...
    steering_rad, ...
    VariableNames=[ ...
        "EventIndex", ...
        "RequestedTime_s", ...
        "ScheduledTime_s", ...
        "ActualTime_s", ...
        "SchedulingError_s", ...
        "ActualInterval_s", ...
        "ActualJitter_s", ...
        "SolveTime_s", ...
        "SolverStatus", ...
        "Torque_Nm", ...
        "Steering_rad"]);

assert( ...
    height(executionLog) == numberOfExecutions, ...
    "The execution log is not one row per execution.");

end


function sampledData = sampleHeldSignal( ...
    logs, ...
    signalName, ...
    targetTime_s)
%SAMPLEHELDSIGNAL Sample a logged scalar signal using zero-order hold.

availableSignals = string(logs.getElementNames);

assert(any(availableSignals == signalName), ...
    "Logged signal '%s' was not found.", ...
    signalName);

signal = logs.get(signalName).Values;

sourceTime_s = reshape( ...
    double(signal.Time), ...
    [], ...
    1);

sourceData = reshape( ...
    squeeze(double(signal.Data)), ...
    [], ...
    1);

assert(~isempty(sourceTime_s), ...
    "Logged signal '%s' is empty.", ...
    signalName);

assert(numel(sourceTime_s) == numel(sourceData), ...
    "Logged signal '%s' is not scalar.", ...
    signalName);

% If Simulink recorded several values at the same time, preserve the last
% value because it represents the completed controller execution.
[sourceTime_s, uniqueIndices] = unique( ...
    sourceTime_s, ...
    "last");

sourceData = sourceData(uniqueIndices);

if isscalar(sourceTime_s)

    sampledData = repmat( ...
        sourceData, ...
        numel(targetTime_s), ...
        1);

else

    sampledData = interp1( ...
        sourceTime_s, ...
        sourceData, ...
        targetTime_s, ...
        "previous", ...
        "extrap");
end

sampledData = reshape(sampledData, [], 1);

end