function [triggerSignal, eventTable] = ...
    generate_sampling_jitter_trigger( ...
        stopTime_s, ...
        nominalSampleTime_s, ...
        jitterBound_s, ...
        simulationStep_s, ...
        randomSeed)

arguments
    stopTime_s (1,1) double {mustBePositive}
    nominalSampleTime_s (1,1) double {mustBePositive}
    jitterBound_s (1,1) double {mustBeNonnegative}
    simulationStep_s (1,1) double {mustBePositive}
    randomSeed (1,1) double {mustBeInteger}
end

assert( ...
    jitterBound_s < nominalSampleTime_s, ...
    "Jitter bound must be smaller than the nominal sample time.");

assert( ...
    nominalSampleTime_s - jitterBound_s > simulationStep_s, ...
    "The minimum controller interval must exceed one simulation step.");

%% Generate the requested controller execution times

randomStream = RandStream( ...
    "mt19937ar", ...
    "Seed", randomSeed);

% The controller must execute once at simulation start. Jitter is applied
% only to the intervals that follow this initial execution.
requestedEventTimes_s = 0;
currentEventTime_s = 0;

while true

    jitter_s = jitterBound_s * ...
        (2*rand(randomStream) - 1);

    requestedInterval_s = ...
        nominalSampleTime_s + jitter_s;

    currentEventTime_s = ...
        currentEventTime_s + requestedInterval_s;

    if currentEventTime_s >= stopTime_s
        break;
    end

    requestedEventTimes_s(end+1,1) = ...
        currentEventTime_s;
end

%% Quantize events to the fixed simulation grid

appliedEventTimes_s = ...
    round(requestedEventTimes_s / simulationStep_s) ...
    * simulationStep_s;

assert(all(diff(appliedEventTimes_s) > 0), ...
    "Quantization produced duplicate or nonincreasing trigger events. " + ...
    "Reduce the simulation step.");

%% Construct one-step trigger pulses

simulationTime_s = ...
    (0:simulationStep_s:stopTime_s).';

triggerData = zeros(size(simulationTime_s));

eventIndices = ...
    round(appliedEventTimes_s / simulationStep_s) + 1;

eventIndices = eventIndices( ...
    eventIndices >= 1 & ...
    eventIndices <= numel(triggerData));

triggerData(eventIndices) = 1;

triggerSignal = timeseries( ...
    triggerData, ...
    simulationTime_s);

triggerSignal.Name = "controller_trigger";

%% Record requested and realized timing

requestedIntervals_s = [
    NaN
    diff(requestedEventTimes_s)
    ];

appliedIntervals_s = [
    NaN
    diff(appliedEventTimes_s)
    ];

requestedJitter_s = ...
    requestedIntervals_s - nominalSampleTime_s;
appliedJitter_s = ...
    appliedIntervals_s - nominalSampleTime_s;

eventTable = table( ...
    (1:numel(appliedEventTimes_s)).', ...
    requestedEventTimes_s, ...
    appliedEventTimes_s, ...
    requestedIntervals_s, ...
    appliedIntervals_s, ...
    requestedJitter_s, ...
    appliedJitter_s, ...
    appliedEventTimes_s - requestedEventTimes_s, ...
    VariableNames=[ ...
        "EventIndex", ...
        "RequestedTime_s", ...
        "AppliedTime_s", ...
        "RequestedInterval_s", ...
        "AppliedInterval_s", ...
        "RequestedJitter_s", ...
        "AppliedJitter_s", ...
        "QuantizationError_s"]);
end
