function validation = validate_controller_executions( ...
    logs, eventTable, simulationEnd_s, simulationStep_s)

signalName = "controller_execution_count";
availableSignals = string(logs.getElementNames);

assert(any(availableSignals == signalName), ...
    "Logged signal '%s' was not found.", signalName);

counterSignal = logs.get(signalName).Values;

counterTime_s = reshape(double(counterSignal.Time), [], 1);
counterValue = reshape(double(counterSignal.Data), [], 1);

assert(all(isfinite(counterValue)), ...
    "Execution counter contains NaN or Inf.");

roundedCounter = round(counterValue);

assert(all(abs(counterValue - roundedCounter) < 1e-9), ...
    "Execution counter must contain integer values.");

counterIncrement = [
    roundedCounter(1)
    diff(roundedCounter)
    ];

assert(all(counterIncrement == 0 | counterIncrement == 1), ...
    "Execution counter must increase by exactly one per execution.");

actualExecutionTimes_s = ...
    counterTime_s(counterIncrement == 1);

tolerance_s = simulationStep_s/2 + 1e-12;

expectedExecutionTimes_s = ...
    eventTable.AppliedTime_s;

expectedExecutionTimes_s = expectedExecutionTimes_s( ...
    expectedExecutionTimes_s <= simulationEnd_s + tolerance_s);

fprintf("\nController execution diagnostic:\n");
fprintf("Simulation end:        %.6f s\n", simulationEnd_s);
fprintf("Expected executions:   %d\n", numel(expectedExecutionTimes_s));
fprintf("Observed executions:   %d\n", numel(actualExecutionTimes_s));
fprintf("Final counter value:   %d\n", roundedCounter(end));
fprintf("Last expected event:   %.6f s\n", expectedExecutionTimes_s(end));
fprintf("Last observed event:   %.6f s\n", actualExecutionTimes_s(end));

commonCount = min( ...
    numel(expectedExecutionTimes_s), ...
    numel(actualExecutionTimes_s));

prefixError_s = ...
    actualExecutionTimes_s(1:commonCount) ...
    - expectedExecutionTimes_s(1:commonCount);

firstMismatch = find( ...
    abs(prefixError_s) > tolerance_s, ...
    1, ...
    "first");

if isempty(firstMismatch)
    fprintf( ...
        "All observed events match the beginning of the schedule.\n");
    fprintf( ...
        "Therefore, %d scheduled events are missing from the end.\n", ...
        numel(expectedExecutionTimes_s) ...
        - numel(actualExecutionTimes_s));
else
    fprintf("First timing mismatch at event %d:\n", firstMismatch);
    fprintf( ...
        "  Expected: %.6f s\n", ...
        expectedExecutionTimes_s(firstMismatch));
    fprintf( ...
        "  Observed: %.6f s\n", ...
        actualExecutionTimes_s(firstMismatch));
    fprintf( ...
        "  Difference: %.6f ms\n", ...
        1000*prefixError_s(firstMismatch));
end

assert( ...
    numel(actualExecutionTimes_s) == ...
    numel(expectedExecutionTimes_s), ...
    "Expected %d executions, but observed %d.", ...
    numel(expectedExecutionTimes_s), ...
    numel(actualExecutionTimes_s));

timingError_s = ...
    actualExecutionTimes_s - expectedExecutionTimes_s;

assert(all(abs(timingError_s) <= tolerance_s), ...
    "Controller execution times do not match scheduled trigger times.");

validation = struct();

validation.expected_count = ...
    numel(expectedExecutionTimes_s);

validation.actual_count = ...
    numel(actualExecutionTimes_s);

validation.actual_execution_times_s = ...
    actualExecutionTimes_s;

validation.expected_execution_times_s = ...
    expectedExecutionTimes_s;

validation.timing_error_s = timingError_s;

validation.maximum_timing_error_s = ...
    max(abs(timingError_s), [], "omitnan");

fprintf( ...
    "Step 5 passed: %d controller executions verified.\n", ...
    validation.actual_count);

fprintf( ...
    "Maximum trigger timing error: %.6f ms\n", ...
    1000*validation.maximum_timing_error_s);

end