%% Phase 3 batch experiment

startup_project;

projectRoot = string( ...
    matlab.project.currentProject().RootFolder);

modelName = "phase3_scheduler_testbed";

scenarioNames = [
    % sdv.enum.ScenarioName.urban_profile
    % sdv.enum.ScenarioName.highway_cruise
    sdv.enum.ScenarioName.aggressive_maneuver
    ];

environmentNames = [
    sdv.enum.EnvironmentName.dry_road
    sdv.enum.EnvironmentName.low_friction_road
    ];

loadCases = [
    "off"
    "maximum"
    ];

loadIndex = 2;

baseRandomSeed = 1001;
loadTaskPeriod_s = 0.050;

resultsRoot = fullfile( ...
    projectRoot, ...
    "phase3", ...
    "test", ...
    "results", ...
    "forced_high_10ms");

if ~isfolder(resultsRoot)
    mkdir(resultsRoot);
end

load_system(modelName);

runtimeChecked = false;
phase3Summary = table();
runSummary = table( ...
    strings(0,1), ...
    strings(0,1), ...
    strings(0,1), ...
    strings(0,1), ...
    strings(0,1), ...
    zeros(0,1), ...
    'VariableNames', { ...
    'Scenario', ...
    'Environment', ...
    'LoadCase', ...
    'Status', ...
    'ResultsFile', ...
    'ElapsedTime_s'});

%% Scenario loop

for scenarioIndex = 1:numel(scenarioNames)

    scenarioName = scenarioNames(scenarioIndex);
    scenarioLabel = string(scenarioName);

    fprintf( ...
        "\n========================================\n" + ...
        "Scenario: %s\n" + ...
        "========================================\n", ...
        scenarioLabel);

    %% Scenario-dependent configuration

    configuration = ...
        build_phase0_configuration(scenarioName);

    vehicleParams = configuration.vehicle;
    controllerParams = configuration.controller;
    simulationParams = configuration.simulation;
    adaptiveModelParams = configuration.adaptiveModel;

    if ~runtimeChecked
        check_runtime_requirements(controllerParams);
        runtimeChecked = true;
    end

    initialControllerMeasurement = [
        simulationParams.initial_speed_mps
        0
        0
        simulationParams.initial_x_m
        simulationParams.initial_y_m
        simulationParams.initial_yaw_rad
        ];

    UT = legacy_plant_parameters( ...
        vehicleParams, ...
        simulationParams);

    acadosSettings = ...
        acados_ocp_parameters(controllerParams);

    acados_nominal_input = reshape( ...
        acadosSettings.nominal_input, ...
        2, ...
        1);

    track_ref_table = ...
        configuration.scenario.lookup_table;

    scenario_stop_table = ...
        configuration.scenario.stop_event_table;

    stopTime_s = ...
        configuration.scenario.simulation_stop_time_s;

    final_track_index = ...
        size(track_ref_table, 1);

    %% Forced-HIGH equivalence test

    supervisorSampleTime_s = 0.010;

    tagTime_s = ...
        (0:supervisorSampleTime_s:stopTime_s).';

    demandMode = repmat( ...
        uint8(3), ...       % HIGH = fixed 10 ms controller
        numel(tagTime_s), ...
        1);

    demandTagsTable = table( ...
        tagTime_s, ...
        demandMode, ...
        VariableNames=["time_s", "dwellMode"]);

    demandTagsFile = "forced_HIGH_test";

    phase3_demand_mode_ts = timeseries( ...
        demandMode, ...
        tagTime_s);

    phase3_demand_mode_ts.Name = ...
        "phase3_demand_mode";

    phase3_demand_mode_ts = setinterpmethod( ...
        phase3_demand_mode_ts, ...
        "zoh");

    assert( ...
        all(phase3_demand_mode_ts.Data == uint8(3)), ...
        "Forced-HIGH test tag was not created correctly.");

    fprintf( ...
        "Forced demand mode: HIGH (10 ms) for %.2f s\n", ...
        stopTime_s);

    %% Environment loop

    for environmentIndex = 1:numel(environmentNames)
        
        environmentName = ...
            environmentNames(environmentIndex);

        environmentLabel = ...
            string(environmentName);

        durationBank = struct;

        durationBank.LOW = ...
            load_control_task_durations( ...
            scenarioLabel, ...
            environmentLabel, ...
            "phase3_50ms");

        durationBank.MEDIUM = ...
            load_control_task_durations( ...
            scenarioLabel, ...
            environmentLabel, ...
            "phase3_20ms");

        durationBank.HIGH = ...
            load_control_task_durations( ...
            scenarioLabel, ...
            environmentLabel, ...
            "phase0");

        fprintf( ...
            "\nEnvironment: %s\n", ...
            environmentLabel);

        environment = load_env_profile( ...
            lower(environmentLabel), ...
            stopTime_s, ...
            FrictionDropTime_s=10);

        roadFrictionProfile = ...
            environment.road_friction_profile;

        durationData = ...
            load_control_task_durations( ...
                scenarioLabel, ...
                environmentLabel);

        % Keep the same controller-duration realization for every
        % load case within this scenario/environment combination.
        randomSeed = ...
            baseRandomSeed ...
            + 100*scenarioIndex ...
            + 10*environmentIndex;

        controlTaskDuration = ...
            create_phase3_control_task_duration( ...
                phase3_demand_mode_ts, ...
                durationBank, ...
                stopTime_s, ...
                randomSeed, ...
                SupervisorSampleTime_s= ...
                    supervisorSampleTime_s);

        %% Load-case loop

        for load_duration_s = 0.030

            loadCase = loadCases(loadIndex);

            fprintf( ...
                "  Load case: %s\n", ...
                loadCase);

            switch loadCase

                case "off"
                    loadTaskDuration_s = 1e-6;

                case "maximum"
                    loadTaskDuration_s = load_duration_s;

                otherwise
                    error( ...
                        "Unknown load case: %s", ...
                        loadCase);
            end

            loadReleaseTime_s = ...
                (0:loadTaskPeriod_s:stopTime_s).';

            loadTaskDuration = timeseries( ...
                repmat( ...
                    loadTaskDuration_s, ...
                    numel(loadReleaseTime_s), ...
                    1), ...
                loadReleaseTime_s);

            loadTaskDuration = setinterpmethod( ...
                loadTaskDuration, ...
                "zoh");

            %% Create an isolated simulation input

            simulationInput = ...
                Simulink.SimulationInput(modelName);

            simulationVariables = struct( ...
                phase3_demand_mode_ts=phase3_demand_mode_ts, ...
                roadFrictionProfile=roadFrictionProfile, ...
                controlTaskDuration=controlTaskDuration, ...
                loadTaskDuration=loadTaskDuration, ...
                vehicleParams=vehicleParams, ...
                controllerParams=controllerParams, ...
                simulationParams=simulationParams, ...
                adaptiveModelParams=adaptiveModelParams, ...
                initialControllerMeasurement= ...
                    initialControllerMeasurement, ...
                UT=UT, ...
                acados_nominal_input= ...
                    acados_nominal_input, ...
                track_ref_table=track_ref_table, ...
                scenario_stop_table=scenario_stop_table, ...
                final_track_index=final_track_index ...
            );

            simulationVariableNames = ...
                fieldnames(simulationVariables);

            for variableIndex = ...
                    1:numel(simulationVariableNames)

                variableName = ...
                    simulationVariableNames{variableIndex};

                simulationInput = ...
                    simulationInput.setVariable( ...
                        variableName, ...
                        simulationVariables.(variableName));
            end

            simulationInput = ...
                simulationInput.setModelParameter( ...
                    StopTime=string(stopTime_s), ...
                    ReturnWorkspaceOutputs="on", ...
                    SignalLogging="on", ...
                    SignalLoggingName="logsout", ...
                    SignalInfNanChecking="error");

            %% Combination-specific results folder

            resultsFolder = fullfile( ...
                resultsRoot, ...
                scenarioLabel, ...
                environmentLabel, ...
                "load_" + loadTaskDuration_s);

            if ~isfolder(resultsFolder)
                mkdir(resultsFolder);
            end

            resultsFile = fullfile( ...
                resultsFolder, ...
                "simulation_output.mat");

            runMetadata = struct( ...
                scenario=scenarioLabel, ...
                environment=environmentLabel, ...
                load_case=loadCase, ...
                random_seed=randomSeed, ...
                stop_time_s=stopTime_s, ...
                load_task_period_s=loadTaskPeriod_s, ...
                load_task_duration_s=loadTaskDuration_s, ...
                demand_tags_file=demandTagsFile, ...
                demand_policy="forced_high_10ms");

            %% Run and save immediately
            runIdsBefore = Simulink.sdi.getAllRunIDs;
            runTimer = tic;

            try
                simulationOutput = sim(simulationInput);
                
                elapsedTime_s = toc(runTimer);

                save( ...
                    resultsFile, ...
                    "simulationOutput", ...
                    "configuration", ...
                    "demandTagsTable", ...
                    "phase3_demand_mode_ts", ...
                    "controlTaskDuration", ...
                    "loadTaskDuration", ...
                    "runMetadata", ...
                    "-v7.3");

                runStatus = "completed";

                fprintf( ...
                    "  Completed in %.2f s\n", ...
                    elapsedTime_s);

            catch simulationError

                elapsedTime_s = toc(runTimer);
                runStatus = "failed";

                failureReport = string(getReport( ...
                    simulationError, ...
                    "extended", ...
                    "hyperlinks", ...
                    "off"));

                failureFile = fullfile( ...
                    resultsFolder, ...
                    "failure.mat");

                save( ...
                    failureFile, ...
                    "failureReport", ...
                    "runMetadata");

                resultsFile = failureFile;

                warning( ...
                    "Phase3:SimulationFailed", ...
                    "%s / %s / %s failed:\n%s", ...
                    scenarioLabel, ...
                    environmentLabel, ...
                    loadCase, ...
                    simulationError.message);
            end
            
            if loadCase == "off"
                reportedLoadExecution_ms = 0;
            else
                reportedLoadExecution_ms = ...
                    1e3*loadTaskDuration_s;
            end

            metadata = struct( ...
                Policy="variable_rate", ...
                Scenario=scenarioLabel, ...
                Environment=environmentLabel, ...
                LoadCase=loadCase, ...
                LoadExecutionTime_ms=reportedLoadExecution_ms, ...
                RandomSeed=randomSeed, ...
                StopTime_s=stopTime_s);

            [runArtifact, newSummaryRow] = ...
                collect_phase3_results( ...
                simulationOutput, ...
                modelName, ...
                runIdsBefore, ...
                track_ref_table, ...
                metadata);

            runArtifact.runFile = string(resultsFile);
            newSummaryRow.RunFile = string(resultsFile);

            save( ...
                resultsFile, ...
                "runArtifact", ...
                "-append");

            phase3Summary = [
                phase3Summary
                newSummaryRow
                ];

            runSummary(end+1,:) = { ...
                scenarioLabel, ...
                environmentLabel, ...
                loadCase, ...
                runStatus, ...
                string(resultsFile), ...
                elapsedTime_s ...
                };
        end
    end
end

phase3SummaryFile = fullfile( ...
    resultsRoot, ...
    "phase3_summary.mat");

phase3SummaryCsv = fullfile( ...
    resultsRoot, ...
    "phase3_summary.csv");

save( ...
    phase3SummaryFile, ...
    "phase3Summary");

writetable( ...
    phase3Summary, ...
    phase3SummaryCsv);
%% Save batch summary

summaryMatFile = fullfile( ...
    resultsRoot, ...
    "batch_summary.mat");

summaryCsvFile = fullfile( ...
    resultsRoot, ...
    "batch_summary.csv");

save( ...
    summaryMatFile, ...
    "runSummary");

writetable( ...
    runSummary, ...
    summaryCsvFile);

disp(runSummary);
