function monitor = computePerformanceMonitor( ...
    results, ...
    scenario, ...
    initialYaw_rad)
%COMPUTEPERFORMANCEMONITOR
% Compute vehicle tracking errors independently of controller execution.
%
% The monitor operates on the fixed plant-output time grid. Therefore,
% controller jitter does not change the number or timing of performance
% samples.

arguments
    results (1,1) struct
    scenario (1,1) struct
    initialYaw_rad (1,1) double {mustBeFinite}
end

%% Validate result fields

requiredResultFields = [ ...
    "time_s"
    "x_pos_m"
    "y_pos_m"
    "vx_mps"
    "yaw_rate_radps"
    ];

missingResultFields = setdiff( ...
    requiredResultFields, ...
    string(fieldnames(results)));

assert(isempty(missingResultFields), ...
    "Missing result fields: %s", ...
    strjoin(missingResultFields, ", "));

%% Validate scenario fields

requiredScenarioFields = [ ...
    "station_m"
    "X_ref_m"
    "Y_ref_m"
    "psi_ref_rad"
    "vx_ref_mps"
    ];

missingScenarioFields = setdiff( ...
    requiredScenarioFields, ...
    string(fieldnames(scenario)));

assert(isempty(missingScenarioFields), ...
    "Missing scenario fields: %s", ...
    strjoin(missingScenarioFields, ", "));

%% Convert vehicle results into column vectors

time_s = toColumn(results.time_s);
vehicleX_m = toColumn(results.x_pos_m);
vehicleY_m = toColumn(results.y_pos_m);
vehicleSpeed_mps = toColumn(results.vx_mps);
yawRate_radps = toColumn(results.yaw_rate_radps);

numberOfSamples = numel(time_s);

assert( ...
    all([ ...
        numel(vehicleX_m), ...
        numel(vehicleY_m), ...
        numel(vehicleSpeed_mps), ...
        numel(yawRate_radps)] == numberOfSamples), ...
    "Plant telemetry signals must have equal lengths.");

assert(all(diff(time_s) > 0), ...
    "Plant telemetry time must be strictly increasing.");

assert(all(isfinite([ ...
        time_s
        vehicleX_m
        vehicleY_m
        vehicleSpeed_mps
        yawRate_radps])), ...
    "Plant telemetry contains NaN or Inf.");

%% Convert reference data into column vectors

station_m = toColumn(scenario.station_m);
referenceX_m = toColumn(scenario.X_ref_m);
referenceY_m = toColumn(scenario.Y_ref_m);
referenceYaw_rad = unwrap( ...
    toColumn(scenario.psi_ref_rad));
referenceSpeed_mps = toColumn(scenario.vx_ref_mps);

numberOfReferencePoints = numel(station_m);

assert(numberOfReferencePoints >= 2, ...
    "The reference path must contain at least two points.");

assert( ...
    all([ ...
        numel(referenceX_m), ...
        numel(referenceY_m), ...
        numel(referenceYaw_rad), ...
        numel(referenceSpeed_mps)] == ...
        numberOfReferencePoints), ...
    "Reference-path fields must have equal lengths.");

assert(all(diff(station_m) > 0), ...
    "Reference station must be strictly increasing.");

%% Reconstruct measured vehicle yaw

vehicleYaw_rad = ...
    initialYaw_rad + ...
    cumtrapz(time_s, yawRate_radps);

%% Allocate monitor outputs

referenceStation_m = zeros(numberOfSamples, 1);
projectedX_m = zeros(numberOfSamples, 1);
projectedY_m = zeros(numberOfSamples, 1);
projectedYaw_rad = zeros(numberOfSamples, 1);
projectedSpeed_mps = zeros(numberOfSamples, 1);
referenceSegmentIndex = zeros(numberOfSamples, 1);

lateralError_m = zeros(numberOfSamples, 1);
headingError_rad = zeros(numberOfSamples, 1);

%% Project every vehicle position onto the reference path

numberOfSegments = numberOfReferencePoints - 1;
previousSegment = 1;

% These bounds keep the path search computationally inexpensive while
% allowing limited movement backward and substantial movement forward.
searchBehind = 10;
searchAhead = 200;

for sampleIndex = 1:numberOfSamples

    firstSegment = max( ...
        1, ...
        previousSegment - searchBehind);

    lastSegment = min( ...
        numberOfSegments, ...
        previousSegment + searchAhead);

    candidateSegments = ...
        (firstSegment:lastSegment).';

    segmentX_m = ...
        referenceX_m(candidateSegments + 1) ...
        - referenceX_m(candidateSegments);

    segmentY_m = ...
        referenceY_m(candidateSegments + 1) ...
        - referenceY_m(candidateSegments);

    segmentLengthSquared_m2 = ...
        segmentX_m.^2 + segmentY_m.^2;

    segmentLengthSquared_m2 = max( ...
        segmentLengthSquared_m2, ...
        eps);

    relativeX_m = ...
        vehicleX_m(sampleIndex) ...
        - referenceX_m(candidateSegments);

    relativeY_m = ...
        vehicleY_m(sampleIndex) ...
        - referenceY_m(candidateSegments);

    projectionFraction = ...
        (relativeX_m .* segmentX_m ...
        + relativeY_m .* segmentY_m) ...
        ./ segmentLengthSquared_m2;

    projectionFraction = min( ...
        max(projectionFraction, 0), ...
        1);

    candidateX_m = ...
        referenceX_m(candidateSegments) ...
        + projectionFraction .* segmentX_m;

    candidateY_m = ...
        referenceY_m(candidateSegments) ...
        + projectionFraction .* segmentY_m;

    distanceSquared_m2 = ...
        (vehicleX_m(sampleIndex) - candidateX_m).^2 ...
        + (vehicleY_m(sampleIndex) - candidateY_m).^2;

    [~, localBestIndex] = min(distanceSquared_m2);

    selectedSegment = ...
        candidateSegments(localBestIndex);

    selectedFraction = ...
        projectionFraction(localBestIndex);

    previousSegment = selectedSegment;

    referenceSegmentIndex(sampleIndex) = ...
        selectedSegment;

    projectedX_m(sampleIndex) = ...
        referenceX_m(selectedSegment) ...
        + selectedFraction ...
        * (referenceX_m(selectedSegment + 1) ...
        - referenceX_m(selectedSegment));

    projectedY_m(sampleIndex) = ...
        referenceY_m(selectedSegment) ...
        + selectedFraction ...
        * (referenceY_m(selectedSegment + 1) ...
        - referenceY_m(selectedSegment));

    projectedYaw_rad(sampleIndex) = ...
        referenceYaw_rad(selectedSegment) ...
        + selectedFraction ...
        * (referenceYaw_rad(selectedSegment + 1) ...
        - referenceYaw_rad(selectedSegment));

    projectedSpeed_mps(sampleIndex) = ...
        referenceSpeed_mps(selectedSegment) ...
        + selectedFraction ...
        * (referenceSpeed_mps(selectedSegment + 1) ...
        - referenceSpeed_mps(selectedSegment));

    referenceStation_m(sampleIndex) = ...
        station_m(selectedSegment) ...
        + selectedFraction ...
        * (station_m(selectedSegment + 1) ...
        - station_m(selectedSegment));

    positionErrorX_m = ...
        vehicleX_m(sampleIndex) ...
        - projectedX_m(sampleIndex);

    positionErrorY_m = ...
        vehicleY_m(sampleIndex) ...
        - projectedY_m(sampleIndex);

    lateralError_m(sampleIndex) = ...
        -positionErrorX_m ...
        * sin(projectedYaw_rad(sampleIndex)) ...
        + positionErrorY_m ...
        * cos(projectedYaw_rad(sampleIndex));

    rawHeadingError_rad = ...
        vehicleYaw_rad(sampleIndex) ...
        - projectedYaw_rad(sampleIndex);

    headingError_rad(sampleIndex) = atan2( ...
        sin(rawHeadingError_rad), ...
        cos(rawHeadingError_rad));
end

%% Compute longitudinal-speed tracking error

speedError_mps = ...
    vehicleSpeed_mps - projectedSpeed_mps;

%% Construct the monitor result

monitor = struct();

monitor.time_s = time_s;
monitor.reference_station_m = referenceStation_m;
monitor.reference_segment_index = referenceSegmentIndex;

monitor.reference_x_m = projectedX_m;
monitor.reference_y_m = projectedY_m;
monitor.reference_yaw_rad = projectedYaw_rad;
monitor.reference_speed_mps = projectedSpeed_mps;

monitor.vehicle_yaw_rad = vehicleYaw_rad;

monitor.ev_mps = speedError_mps;
monitor.ey_m = lateralError_m;
monitor.epsi_rad = headingError_rad;

end


function value = toColumn(value)
%TOCOLUMN Convert logged or reference data to a double column vector.

value = reshape( ...
    squeeze(double(value)), ...
    [], ...
    1);

end