function row = createDelaySweepRow( ...
    scenarioName, ...
    environmentName, ...
    delay_s, ...
    results, ...
    options)
%CREATEDELAYSWEEPROW Convert one Phase 1 run into one table row.

arguments
    scenarioName (1,1) string
    environmentName (1,1) string
    delay_s (1,1) double {mustBeNonnegative}
    results (1,1) struct = struct()

    options.Completed (1,1) logical = true
    options.ErrorIdentifier (1,1) string = ""
    options.ErrorMessage (1,1) string = ""
end

% Defaults for a failed or incomplete simulation.
finalTime_s = NaN;

speedRMSE_mps = NaN;
speedPeak_mps = NaN;

lateralRMSE_m = NaN;
lateralPeak_m = NaN;

headingRMSE_rad = NaN;
headingPeak_rad = NaN;

violationSamples = NaN;
violationEvents = NaN;
violationDuration_s = NaN;

if options.Completed
    tracking = results.tracking_metrics;
    constraints = results.constraint_metrics;

    finalTime_s = results.time_s(end);

    speedRMSE_mps = tracking.speed_rmse_mps;
    speedPeak_mps = tracking.speed_peak_mps;

    lateralRMSE_m = tracking.lateral_rmse_m;
    lateralPeak_m = tracking.lateral_peak_m;

    headingRMSE_rad = tracking.heading_rmse_rad;
    headingPeak_rad = tracking.heading_peak_rad;

    violationSamples = constraints.any_sample_count;
    violationEvents = constraints.event_count;
    violationDuration_s = constraints.duration_s;
end

variableNames = { ...
    'scenario_name', ...
    'environment_name', ...
    'delay_s', ...
    'delay_ms', ...
    'simulation_completed', ...
    'final_time_s', ...
    'speed_rmse_mps', ...
    'speed_peak_mps', ...
    'lateral_rmse_m', ...
    'lateral_peak_m', ...
    'heading_rmse_rad', ...
    'heading_peak_rad', ...
    'constraint_violation_samples', ...
    'constraint_violation_events', ...
    'constraint_violation_duration_s', ...
    'error_identifier', ...
    'error_message'};

row = table( ...
    scenarioName, ...
    environmentName, ...
    delay_s, ...
    delay_s * 1e3, ...
    options.Completed, ...
    finalTime_s, ...
    speedRMSE_mps, ...
    speedPeak_mps, ...
    lateralRMSE_m, ...
    lateralPeak_m, ...
    headingRMSE_rad, ...
    headingPeak_rad, ...
    violationSamples, ...
    violationEvents, ...
    violationDuration_s, ...
    options.ErrorIdentifier, ...
    options.ErrorMessage, ...
    'VariableNames', variableNames);
end