function validation = validateActuationDelay( ...
    commandTime_s, ...
    commandValue, ...
    appliedTime_s, ...
    appliedValue, ...
    delay_s, ...
    options)
%VALIDATEACTUATIONDELAY Verify:
%   u_applied(t) = u_command(t - delay)

arguments
    commandTime_s (:,1) double
    commandValue (:,1) double
    appliedTime_s (:,1) double
    appliedValue (:,1) double
    delay_s (1,1) double {mustBeNonnegative}

    options.InitialValue (1,1) double = 0
    options.SignalName (1,1) string = "Actuation command"
    options.MakePlot (1,1) logical = true
end

assert( ...
    numel(commandTime_s) == numel(commandValue), ...
    "Command time and data sizes do not match.");

assert( ...
    numel(appliedTime_s) == numel(appliedValue), ...
    "Applied time and data sizes do not match.");

assert(all(isfinite( ...
    [ ...
    commandTime_s; ...
    commandValue; ...
    appliedTime_s; ...
    appliedValue ...
    ])), ...
    "Actuation telemetry contains NaN or Inf.");

%% Remove repeated command timestamps

[commandTime_s, uniqueIndices] = ...
    unique(commandTime_s, "last");

commandValue = commandValue(uniqueIndices);

%% Calculate expected delayed command

delayedQueryTime_s = ...
    appliedTime_s - delay_s;

expectedAppliedValue = ...
    options.InitialValue * ...
    ones(size(appliedTime_s));

validSamples = ...
    delayedQueryTime_s >= commandTime_s(1) & ...
    delayedQueryTime_s <= commandTime_s(end);

expectedAppliedValue(validSamples) = ...
    interp1( ...
        commandTime_s, ...
        commandValue, ...
        delayedQueryTime_s(validSamples), ...
        "previous");

%% Calculate delay residual

delayResidual = ...
    appliedValue - expectedAppliedValue;

evaluatedResidual = ...
    delayResidual(validSamples);

validation = struct();

validation.requested_delay_s = delay_s;
validation.requested_delay_ms = 1e3 * delay_s;

validation.sample_count = nnz(validSamples);

validation.residual_rms = sqrt( ...
    mean(evaluatedResidual.^2));

validation.residual_peak = max( ...
    abs(evaluatedResidual));

validation.expected_applied_value = ...
    expectedAppliedValue;

validation.residual = delayResidual;

fprintf("\nActuation-delay validation: %s\n", ...
    options.SignalName);

fprintf("Requested delay: %.3f ms\n", ...
    validation.requested_delay_ms);

fprintf("Evaluated samples: %d\n", ...
    validation.sample_count);

fprintf("Residual RMS: %.9g\n", ...
    validation.residual_rms);

fprintf("Residual peak: %.9g\n", ...
    validation.residual_peak);

%% Plot verification

if options.MakePlot

    validation.figure = figure( ...
        Name=options.SignalName + " delay validation", ...
        Color="white");

    layout = tiledlayout( ...
        validation.figure, ...
        3, ...
        1, ...
        TileSpacing="compact", ...
        Padding="compact");

    nexttile(layout);

    plot( ...
        commandTime_s + delay_s, ...
        commandValue, ...
        "--", ...
        LineWidth=1.2, ...
        DisplayName="Command shifted by \tau");

    hold on;

    plot( ...
        appliedTime_s, ...
        appliedValue, ...
        LineWidth=1.1, ...
        DisplayName="Applied to plant");

    hold off;
    grid on;
    ylabel("Command");
    legend(Location="best");
    title(options.SignalName);

    nexttile(layout);

    plot( ...
        appliedTime_s, ...
        expectedAppliedValue, ...
        "--", ...
        LineWidth=1.2, ...
        DisplayName="Expected");

    hold on;

    plot( ...
        appliedTime_s, ...
        appliedValue, ...
        LineWidth=1.1, ...
        DisplayName="Measured");

    hold off;
    grid on;
    ylabel("Command");
    legend(Location="best");
    title("Expected and measured applied commands");

    nexttile(layout);

    plot( ...
        appliedTime_s, ...
        delayResidual, ...
        LineWidth=1);

    grid on;
    xlabel("Time (s)");
    ylabel("Residual");
    title( ...
        sprintf( ...
            "Residual: RMS %.3g, peak %.3g", ...
            validation.residual_rms, ...
            validation.residual_peak));
end

end