projectRoot = string( ...
    matlab.project.currentProject().RootFolder);

scenarioName = "aggressive_maneuver";
environmentName = "low_friction_road";
sample_period = "10";

fixedFile = fullfile( ...
    projectRoot, ...
    "phase4", ...
    "results", ...
    "performance_map_runs", ...
    scenarioName, ...
    environmentName, ...
    "sample_time_0" + sample_period + "_ms", ...
    "fixed_mode_run.mat");


supervisorFile = fullfile( ...
    projectRoot, ...
    "phase4", ...
    "results", ...
    "lookup_supervisor", ...
    scenarioName, ...
    environmentName, ...
    "simulation_output.mat");

outputFile = fullfile( ...
    projectRoot, ...
    "phase4", ...
    "results", ...
    "lookup_supervisor", ...
    scenarioName, ...
    environmentName, ...
    "phase4_lookup_supervisor_demo.png");

[demoFigure, demoMetrics] = plot_phase4_demo( ...
    fixedFile, ...
    supervisorFile, ...
    TrackingMetric="lateral", ...
    TimeWindow_s=[NaN, NaN], ...
    FixedLabel="Fixed "+ sample_period +" ms", ...
    SupervisorLabel="Lookup-map supervisor", ...
    Title="Fixed "+ sample_period +" ms vs. Lookup-Map Supervisor", ...
    SaveFile=outputFile);

disp(demoMetrics);