projectRoot = string( ...
    matlab.project.currentProject().RootFolder);

scenarioName = "aggressive_maneuver";
environmentName = "dry_road";
timeWindow_s = [NaN, NaN];

resultFile = fullfile( ...
    projectRoot, ...
    "phase4", ...
    "results", ...
    "lookup_supervisor", ...
    scenarioName, ...
    environmentName, ...
    "simulation_output.mat");

assert(isfile(resultFile), ...
    "Phase 4 result file does not exist:\n%s", resultFile);

savedData = load(resultFile, "runArtifact");
runArtifact = savedData.runArtifact;

assert(isfield(runArtifact, "candidateCost"), ...
    ["The result does not contain runArtifact.candidateCost. " ...
     "Rerun the Phase 4 simulation with candidate_cost logged."]);

outputFile = fullfile( ...
    fileparts(resultFile), ...
    "phase4_candidate_cost_comparison.png");

plotTitle = sprintf( ...
    "Candidate Costs: %s | %s", ...
    strrep(scenarioName, "_", " "), ...
    strrep(environmentName, "_", " "));

[costFigure, costTable] = ...
    plot_phase4_candidate_cost_comparison( ...
        runArtifact.candidateCost, ...
        SelectedMode=runArtifact.mode, ...
        TimeWindow_s=timeWindow_s, ...
        Title=plotTitle, ...
        SaveFile=outputFile);

fprintf("Saved candidate-cost plot:\n%s\n", outputFile);
