function figureHandle = plot_actuation_delay_test(resultsSource)
%PLOT_ACTUATION_DELAY_TEST Plot saved actuation-delay validation data.

if isstruct(resultsSource)
    data = resultsSource;
else
    resultsSource = string(resultsSource);
    assert(isfile(resultsSource), ...
        "Delay-test result file does not exist: %s", resultsSource);
    stored = load(resultsSource, "delayTestData");
    assert(isfield(stored, "delayTestData"), ...
        "Result file does not contain delayTestData.");
    data = stored.delayTestData;
end

figureHandle = figure;
stairs( ...
    data.commandBefore.Time, ...
    data.commandBefore.Data, ...
    LineWidth=1.5, ...
    DisplayName="Command before delay");
hold on;
stairs( ...
    data.commandAfter.Time, ...
    data.commandAfter.Data, ...
    "--", ...
    LineWidth=1.5, ...
    DisplayName="Command after delay");
grid on;
xlabel("Time (s)");
ylabel("Command");
title("Actuation-delay validation");
legend(Location="best");

end
