function [summaryTable, sweepFigure] = run_constant_delay_sweep(options)
%RUN_CONSTANT_DELAY_SWEEP Run one or more constant-delay experiments.
%
% UpdateSummary=false returns rows for the requested runs without reading,
% writing, or plotting the stored sweep summary. UpdateSummary=true loads
% the stored summary, replaces only matching scenario/environment/delay
% rows, checkpoints it after each run, and regenerates the summary plot.

arguments
    options.ScenarioNames (1,:) string ...
        = [sdv.enum.ScenarioName.urban_profile, ...
        sdv.enum.ScenarioName.aggressive_maneuver, ...
        sdv.enum.ScenarioName.highway_cruise]
    options.EnvironmentNames (1,:) string ...
        = [sdv.enum.EnvironmentName.dry_road, ...
        sdv.enum.EnvironmentName.low_friction_road]
    options.Delay_ms (1,:) double {mustBeNonnegative} = 0:5:100
    options.UpdateSummary (1,1) logical = true
    options.SaveRunResults (1,1) logical = true
    options.SaveRunFigures (1,1) logical = true
    options.ShowRunFigures (1,1) logical = false
end

configuration = build_phase0_configuration( ...
    options.ScenarioNames(1));

controllerName = sdv.config.controllerName( ...
    configuration.controller);

if options.UpdateSummary
    summaryTable = loadStoredSummary(controllerName);
else
    summaryTable = table();
end

for delay_ms = options.Delay_ms

    delay_s = delay_ms * 1e-3;

    for scenarioName = options.ScenarioNames
        % for log file
        fprintf( ...
            "\nScenario: %s, delay: %.1f ms\n", ...
            scenarioName, ...
            delay_ms);
        for environmentName = options.EnvironmentNames

            try
                % as usual run files which run simulink from here
                [results, ~] = run_phase1_baseline( ...
                    scenarioName, ...
                    environmentName, ...
                    delay_s, ...
                    SaveResults=options.SaveRunResults, ...
                    SaveFigures=options.SaveRunFigures, ...
                    ShowFigures=options.ShowRunFigures);

                newRow = sdv.metrics.createDelaySweepRow( ...
                    scenarioName, ...
                    environmentName, ...
                    delay_s, ...
                    results);

            catch simulationError
                % error will be saved in log files
                warning( ...
                    "SDV:DelaySweepRunFailed", ...
                    "Scenario %s failed at %.1f ms:\n%s", ...
                    scenarioName, ...
                    delay_ms, ...
                    simulationError.message);

                newRow = sdv.metrics.createDelaySweepRow( ...
                    scenarioName, ...
                    environmentName, ...
                    delay_s, ...
                    struct(), ...
                    Completed=false, ...
                    ErrorIdentifier=string( ...
                    simulationError.identifier), ...
                    ErrorMessage=string( ...
                    simulationError.message));
            end
            summaryTable = upsertRow(summaryTable, newRow);

            summaryTable = sortrows( ...
                summaryTable, ...
                ["scenario_name", "environment_name", "delay_ms"]);

            if options.UpdateSummary
                % Checkpoint after every simulation without changing
                % unrelated rows already stored in the summary.
                sdv.io.saveDelaySweepSummary( ...
                    summaryTable, ...
                    controllerName);
            end
        end
    end
end

sweepFigure = gobjects(0);

if ~options.UpdateSummary
    return;
end

%% Plot the complete updated summary.
sweepFigure = plotDelaySweepMetrics(summaryTable);

projectRoot = string( ...
    matlab.project.currentProject().RootFolder);

figureFolder = fullfile( ...
    projectRoot, ...
    "phase1", ...
    "figures", ...
    controllerName, ...
    "constant_delay_sweep" ...
    );

sdv.io.exportFigure( ...
    sweepFigure, ...
    figureFolder, ...
    "constant_delay_metrics");

end

function summaryTable = loadStoredSummary(controllerName)
% Load the existing summary when row-level updates are enabled.

projectRoot = string( ...
    matlab.project.currentProject().RootFolder);

summaryFile = fullfile( ...
    projectRoot, ...
    "phase1", ...
    "results", ...
    controllerName, ...
    "constant_delay_sweep", ...
    "constant_delay_summary.mat");

summaryTable = table();

if ~isfile(summaryFile)
    return;
end

stored = load(summaryFile, "summaryTable");

assert(isfield(stored, "summaryTable") && istable(stored.summaryTable), ...
    "Stored constant-delay summary does not contain a valid summaryTable.");

summaryTable = stored.summaryTable;

end

function summaryTable = upsertRow(summaryTable, newRow)
% Replace one matching case or append it when it is not yet stored.

if isempty(summaryTable)
    summaryTable = newRow;
    return;
end

matchingRow = ...
    string(summaryTable.scenario_name) == string(newRow.scenario_name(1)) & ...
    string(summaryTable.environment_name) == string(newRow.environment_name(1)) & ...
    summaryTable.delay_ms == newRow.delay_ms(1);

summaryTable(matchingRow, :) = [];
summaryTable = [summaryTable; newRow];

end

function figureHandle = plotDelaySweepMetrics(summaryTable)
% Plot constant-delay metrics after the complete sweep finishes.

completedTable = summaryTable( ...
    summaryTable.simulation_completed, :);

assert(~isempty(completedTable), ...
    "No completed simulations are available for plotting.");

% Optional: use degrees in the report figure.
completedTable.heading_rmse_deg = ...
    rad2deg(completedTable.heading_rmse_rad);

figureHandle = figure( ...
    Name="Phase 1.1 constant-delay sweep", ...
    Color="white");

layout = tiledlayout( ...
    figureHandle, ...
    3, ...
    1, ...
    TileSpacing="compact", ...
    Padding="compact");

nexttile(layout);
plotMetric(completedTable, "lateral_rmse_m");
ylabel("Lateral RMSE (m)");
title("Lateral Tracking Error");
grid on;

nexttile(layout);
plotMetric(completedTable, "heading_rmse_deg");
ylabel("Heading RMSE (deg)");
title("Heading Tracking Error");
grid on;

nexttile(layout);
plotMetric(completedTable, ...
    "constraint_violation_samples");
ylabel("Number of violating samples");
title("Total Constraint-Violating Samples");
grid on;

xlabel(layout, ...
    "Constant actuation delay, \tau (ms)");

title(layout, ...
    "Phase 1.1: Performance versus Constant Delay");

end
function plotMetric(summaryTable, variableName)
% Plot one sweep metric for every scenario/environment combination.

hold on;

scenarioNames = unique( ...
    summaryTable.scenario_name, ...
    "stable");

environmentNames = unique( ...
    summaryTable.environment_name, ...
    "stable");

colors = lines(numel(scenarioNames));
styles = enumeration("sdv.enum.plotStyle");

for scenarioIndex = 1:numel(scenarioNames)

    scenarioName = scenarioNames(scenarioIndex);

    for environmentIndex = 1:numel(environmentNames)

        environmentName = ...
            environmentNames(environmentIndex);

        selectedRows = ...
            summaryTable.scenario_name == scenarioName & ...
            summaryTable.environment_name == environmentName;

        if ~any(selectedRows)
            continue;
        end

        selectedTable = sortrows( ...
            summaryTable(selectedRows, :), ...
            "delay_ms");

        styleIndex = mod( ...
            environmentIndex - 1, ...
            numel(styles)) + 1;

        plot( ...
            selectedTable.delay_ms, ...
            selectedTable.(variableName), ...
            styles(styleIndex).LineSpec, ...
            Color=colors(scenarioIndex, :), ...
            LineWidth=1.4, ...
            MarkerSize=5, ...
            DisplayName=replace( ...
            scenarioName + " / " + environmentName, ...
            "_", " "));
    end
end

hold off;
grid on;
legend(Location="best");

end
