function [summaryTable, sweepFigure] = ...
    run_random_delay_sweep(options)
%RUN_RANDOM_DELAY_SWEEP Run reproducible Phase 1.2 Monte Carlo trials.
%
% Each trial uses an independent, uniformly distributed actuation-delay
% profile in [0, MaximumDelay_ms]. The delay is updated at the controller
% sample period and the same profile is applied to torque and steering.

arguments
    options.ScenarioNames (1,:) string = ...
        ["urban_profile", "aggressive_maneuver", "highway_cruise"]
    options.EnvironmentNames (1,:) string = "dry_road"
    options.MaximumDelay_ms (1,:) double ...
        {mustBeNonnegative} = [10, 25, 50, 75, 100]
    options.TrialsPerLevel (1,1) double ...
        {mustBeInteger, mustBePositive} = 20
    options.BaseSeed (1,1) double ...
        {mustBeInteger, mustBeNonnegative} = 1000
    options.SaveTrialResults (1,1) logical = true
    options.ShowFigure (1,1) logical = true
end

startup_project;

projectRoot = string( ...
    matlab.project.currentProject().RootFolder);

firstConfiguration = build_phase0_configuration( ...
    options.ScenarioNames(1));

controller = firstConfiguration.controller;
controllerName = sdv.config.controllerName(controller);
randomDelayMode = controller.DELAY_MODE_RANDOM;

maximumConfiguredDelay_ms = ...
    1e3 * controller.maximumRandomDelay_s;

assert(all(options.MaximumDelay_ms <= maximumConfiguredDelay_ms), ...
    "MaximumDelay_ms cannot exceed the configured limit of %.3f ms.", ...
    maximumConfiguredDelay_ms);

summaryTable = table();
runNumber = 0;

for environmentName = options.EnvironmentNames
    for maximumDelay_ms = options.MaximumDelay_ms
        maximumDelay_s = maximumDelay_ms * 1e-3;

        for scenarioName = options.ScenarioNames
            scenarioConfiguration = ...
                build_phase0_configuration(scenarioName);

            sampleTime_s = ...
                scenarioConfiguration.controller.Ts_s;
            stopTime_s = ...
                scenarioConfiguration.simulation.stop_time_s;

            for trialIndex = 1:options.TrialsPerLevel
                runNumber = runNumber + 1;
                randomSeed = options.BaseSeed + runNumber - 1;

                delayProfile = ...
                    sdv.timing.generate_random_delay_profile( ...
                        stopTime_s, ...
                        sampleTime_s, ...
                        maximumDelay_s, ...
                        randomSeed);

                randomDelayProfile = delayProfile.timeseries;

                delayData_s = randomDelayProfile.Data(:);

                fprintf( ...
                    ['\nScenario: %s, environment: %s, ' ...
                    'maximum delay: %.1f ms, trial: %d/%d, seed: %d\n'], ...
                    char(scenarioName), ...
                    char(environmentName), ...
                    maximumDelay_ms, ...
                    trialIndex, ...
                    options.TrialsPerLevel, ...
                    randomSeed);
                try
                    [results, config] = run_phase1_baseline( ...
                        scenarioName, ...
                        environmentName, ...
                        0, ...
                        DelayMode=randomDelayMode, ...
                        RandomDelayProfile=randomDelayProfile, ...
                        RandomSeed=randomSeed, ...
                        SaveResults=false, ...
                        SaveFigures=false, ...
                        ShowFigures=false);

                    newRow = createRandomDelayRow( ...
                        scenarioName, ...
                        environmentName, ...
                        maximumDelay_s, ...
                        trialIndex, ...
                        randomSeed, ...
                        delayData_s, ...
                        results);

                    if options.SaveTrialResults
                        saveTrialResult( ...
                            projectRoot, ...
                            controllerName, ...
                            scenarioName, ...
                            environmentName, ...
                            maximumDelay_ms, ...
                            trialIndex, ...
                            randomSeed, ...
                            results, ...
                            config, ...
                            randomDelayProfile);
                    end

                catch simulationError
                    warning( ...
                        "SDV:RandomDelayRunFailed", ...
                        ["Scenario %s failed for maximum delay %.1f ms, " ...
                        "trial %d, seed %d:\n%s"], ...
                        scenarioName, ...
                        maximumDelay_ms, ...
                        trialIndex, ...
                        randomSeed, ...
                        simulationError.message);

                    newRow = createRandomDelayRow( ...
                        scenarioName, ...
                        environmentName, ...
                        maximumDelay_s, ...
                        trialIndex, ...
                        randomSeed, ...
                        delayData_s, ...
                        struct(), ...
                        Completed=false, ...
                        ErrorIdentifier=string( ...
                            simulationError.identifier), ...
                        ErrorMessage=string( ...
                            simulationError.message));
                end

                if isempty(summaryTable)
                    summaryTable = newRow;
                else
                    summaryTable = [summaryTable; newRow];
                end

                summaryTable = sortrows( ...
                    summaryTable, ...
                    ["environment_name", "scenario_name", ...
                    "maximum_delay_ms", "trial_index"]);

                saveRandomDelaySummary( ...
                    summaryTable, ...
                    projectRoot, ...
                    controllerName);
            end
        end
    end
end

sweepFigure = plotRandomDelayMetrics(summaryTable);

figureFolder = fullfile( ...
    projectRoot, ...
    "phase1", ...
    "figures", ...
    controllerName, ...
    "random_delay_sweep");

sdv.io.exportFigure( ...
    sweepFigure, ...
    figureFolder, ...
    "random_delay_monte_carlo_metrics");

if ~options.ShowFigure
    close(sweepFigure);
end

end

function row = createRandomDelayRow( ...
    scenarioName, environmentName, maximumDelay_s, ...
    trialIndex, randomSeed, delayData_s, results, options)
%CREATERANDOMDELAYROW Convert one Monte Carlo trial into one table row.

arguments
    scenarioName (1,1) string
    environmentName (1,1) string
    maximumDelay_s (1,1) double {mustBeNonnegative}
    trialIndex (1,1) double
    randomSeed (1,1) double
    delayData_s (:,1) double
    results (1,1) struct
    options.Completed (1,1) logical = true
    options.ErrorIdentifier (1,1) string = ""
    options.ErrorMessage (1,1) string = ""
end

row = sdv.metrics.createDelaySweepRow( ...
    scenarioName, ...
    environmentName, ...
    maximumDelay_s, ...
    results, ...
    Completed=options.Completed, ...
    ErrorIdentifier=options.ErrorIdentifier, ...
    ErrorMessage=options.ErrorMessage);

row = renamevars( ...
    row, ...
    ["delay_s", "delay_ms"], ...
    ["maximum_delay_s", "maximum_delay_ms"]);

row.trial_index = trialIndex;
row.random_seed = randomSeed;
row.delay_distribution = "uniform";
row.realized_delay_mean_ms = mean(delayData_s) * 1e3;
row.realized_delay_std_ms = std(delayData_s) * 1e3;
sortedDelay_s = sort(delayData_s);
percentileIndex = max( ...
    1, ceil(0.95 * numel(sortedDelay_s)));
row.realized_delay_p95_ms = ...
    sortedDelay_s(percentileIndex) * 1e3;
row.realized_delay_max_ms = max(delayData_s) * 1e3;

row.delay_validation_passed = false;
row.torque_delay_residual_rmse_Nm = NaN;
row.torque_delay_residual_max_Nm = NaN;
row.steering_delay_residual_rmse_rad = NaN;
row.steering_delay_residual_max_rad = NaN;

if options.Completed && ...
        isfield(results, "delay_validation") && ...
        results.delay_validation.available

    validation = results.delay_validation;
    row.delay_validation_passed = validation.passed;
    row.torque_delay_residual_rmse_Nm = ...
        validation.torque.rmse;
    row.torque_delay_residual_max_Nm = ...
        validation.torque.maximum_absolute;
    row.steering_delay_residual_rmse_rad = ...
        validation.steering.rmse;
    row.steering_delay_residual_max_rad = ...
        validation.steering.maximum_absolute;
end

row = movevars( ...
    row, ...
    ["trial_index", "random_seed", "delay_distribution", ...
    "realized_delay_mean_ms", "realized_delay_std_ms", ...
    "realized_delay_p95_ms", "realized_delay_max_ms", ...
    "delay_validation_passed", ...
    "torque_delay_residual_rmse_Nm", ...
    "torque_delay_residual_max_Nm", ...
    "steering_delay_residual_rmse_rad", ...
    "steering_delay_residual_max_rad"], ...
    After="maximum_delay_ms");

end

function saveRandomDelaySummary( ...
    summaryTable, projectRoot, controllerName)
%SAVERANDOMDELAYSUMMARY Checkpoint the Monte Carlo table.

resultsFolder = fullfile( ...
    projectRoot, ...
    "phase1", ...
    "results", ...
    controllerName, ...
    "random_delay_sweep");

if ~isfolder(resultsFolder)
    mkdir(resultsFolder);
end

save( ...
    fullfile(resultsFolder, "random_delay_summary.mat"), ...
    "summaryTable");

writetable( ...
    summaryTable, ...
    fullfile(resultsFolder, "random_delay_summary.csv"));

end

function saveTrialResult( ...
    projectRoot, controllerName, scenarioName, environmentName, ...
    maximumDelay_ms, trialIndex, randomSeed, ...
    results, config, randomDelayProfile)
%SAVETRIALRESULT Save one trial under a collision-free filename.

maximumDelayText = replace( ...
    string(sprintf("%g", maximumDelay_ms)), ".", "p");

trialFolder = fullfile( ...
    projectRoot, ...
    "phase1", ...
    "results", ...
    controllerName, ...
    "random_delay_sweep", ...
    environmentName, ...
    scenarioName, ...
    "maximum_delay_" + maximumDelayText + "_ms");

if ~isfolder(trialFolder)
    mkdir(trialFolder);
end

fileName = sprintf( ...
    "trial_%03d_seed_%d.mat", ...
    trialIndex, ...
    randomSeed);

save( ...
    fullfile(trialFolder, fileName), ...
    "results", ...
    "config", ...
    "randomDelayProfile");

end

function figureHandle = plotRandomDelayMetrics(summaryTable)
%PLOTRANDOMDELAYMETRICS Plot Monte Carlo mean and standard deviation.

figureHandle = figure( ...
    Name="Phase 1.2 random-delay Monte Carlo sweep", ...
    Color="white");

layout = tiledlayout( ...
    figureHandle, 2, 2, ...
    TileSpacing="compact", ...
    Padding="compact");

plotMetric(layout, summaryTable, ...
    "lateral_rmse_m", "Lateral RMSE (m)", ...
    "Lateral tracking RMS");

plotMetric(layout, summaryTable, ...
    "heading_rmse_rad", "Heading RMSE (rad)", ...
    "Heading tracking RMS");

plotMetric(layout, summaryTable, ...
    "speed_rmse_mps", "Speed RMSE (m/s)", ...
    "Longitudinal tracking RMS");

plotMetric(layout, summaryTable, ...
    "constraint_violation_samples", "Violating samples", ...
    "Constraint-violation count");

xlabel(layout, "Maximum random actuation delay (ms)");
title(layout, ...
    "Phase 1.2: Monte Carlo Metrics versus Random-Delay Bound");

end

function plotMetric( ...
    layout, summaryTable, variableName, yLabelText, titleText)

nexttile(layout);
hold on;

completedTable = summaryTable( ...
    summaryTable.simulation_completed, :);

environmentNames = unique( ...
    completedTable.environment_name, "stable");
scenarioNames = unique( ...
    completedTable.scenario_name, "stable");

for environmentName = environmentNames.'
    for scenarioName = scenarioNames.'
        selected = ...
            completedTable.environment_name == environmentName & ...
            completedTable.scenario_name == scenarioName;

        selectedTable = completedTable(selected, :);

        if isempty(selectedTable)
            continue;
        end

        delayLevels_ms = unique( ...
            selectedTable.maximum_delay_ms);
        metricMean = zeros(size(delayLevels_ms));
        metricStd = zeros(size(delayLevels_ms));

        for index = 1:numel(delayLevels_ms)
            levelSelected = ...
                selectedTable.maximum_delay_ms == ...
                delayLevels_ms(index);
            values = selectedTable.(variableName)(levelSelected);
            metricMean(index) = mean(values, "omitnan");
            metricStd(index) = std(values, "omitnan");
        end

        errorbar( ...
            delayLevels_ms, ...
            metricMean, ...
            metricStd, ...
            "-o", ...
            LineWidth=1.3, ...
            MarkerSize=5, ...
            DisplayName=replace( ...
                scenarioName + " / " + environmentName, ...
                "_", " "));
    end
end

hold off;
grid on;
ylabel(yLabelText);
title(titleText);
legend(Location="best");

end
