function [summaryTable, validation] = ...
    run_sampling_jitter_step_convergence(options)
%RUN_SAMPLING_JITTER_STEP_CONVERGENCE Check fixed-step sensitivity.

arguments
    options.ScenarioName (1,1) string = "highway_cruise"
    options.EnvironmentName (1,1) string = "dry_road"
    options.JitterBound_ms (1,1) double ...
        {mustBeNonnegative} = 5
    options.RandomSeed (1,1) double ...
        {mustBeInteger, mustBeNonnegative} = 1
    options.SimulationSteps_s (1,:) double ...
        {mustBePositive} = [0.001, 0.0005, 0.00025]
    options.MaximumSpeedRmseChange_mps (1,1) double ...
        {mustBeNonnegative} = 0.05
    options.MaximumLateralRmseChange_m (1,1) double ...
        {mustBeNonnegative} = 0.01
    options.MaximumHeadingRmseChange_rad (1,1) double ...
        {mustBeNonnegative} = deg2rad(0.1)
    options.AssertConverged (1,1) logical = true
end

startup_project;

simulationSteps_s = sort(options.SimulationSteps_s, "descend");
summaryTable = table();

for simulationStep_s = simulationSteps_s
    fprintf("\nFixed-step convergence run: h = %.4f ms\n", ...
        1e3*simulationStep_s);

    [results, ~] = run_sampling_jitter_case( ...
        options.ScenarioName, ...
        options.EnvironmentName, ...
        options.JitterBound_ms, ...
        options.RandomSeed, ...
        simulationStep_s, ...
        SaveResults=false, ...
        SaveFigures=false, ...
        ShowFigures=false);

    row = table( ...
        simulationStep_s, ...
        results.tracking_metrics.speed_rmse_mps, ...
        results.tracking_metrics.lateral_rmse_m, ...
        results.tracking_metrics.heading_rmse_rad, ...
        results.execution_validation.maximum_timing_error_s, ...
        height(results.controller_execution_log), ...
        mean(results.controller_execution_log.SolveTime_s), ...
        VariableNames=[ ...
            "SimulationStep_s"
            "SpeedRmse_mps"
            "LateralRmse_m"
            "HeadingRmse_rad"
            "MaximumTimingError_s"
            "ExecutionCount"
            "MeanSolveTime_s"]);

    summaryTable = [summaryTable; row]; %#ok<AGROW>
end

summaryTable = sortrows(summaryTable, "SimulationStep_s", "descend");

assert(height(summaryTable) >= 2, ...
    "At least two simulation steps are required for convergence.");

medium = summaryTable(end-1,:);
fine = summaryTable(end,:);

validation = struct();
validation.speed_rmse_change_mps = abs( ...
    medium.SpeedRmse_mps - fine.SpeedRmse_mps);
validation.lateral_rmse_change_m = abs( ...
    medium.LateralRmse_m - fine.LateralRmse_m);
validation.heading_rmse_change_rad = abs( ...
    medium.HeadingRmse_rad - fine.HeadingRmse_rad);
validation.execution_count_change = abs( ...
    medium.ExecutionCount - fine.ExecutionCount);
validation.passed = ...
    validation.speed_rmse_change_mps <= ...
        options.MaximumSpeedRmseChange_mps && ...
    validation.lateral_rmse_change_m <= ...
        options.MaximumLateralRmseChange_m && ...
    validation.heading_rmse_change_rad <= ...
        options.MaximumHeadingRmseChange_rad;

disp(summaryTable);
fprintf("\nMedium-to-fine fixed-step changes:\n");
fprintf("Speed RMSE:   %.6f m/s\n", ...
    validation.speed_rmse_change_mps);
fprintf("Lateral RMSE: %.6f m\n", ...
    validation.lateral_rmse_change_m);
fprintf("Heading RMSE: %.6f deg\n", ...
    rad2deg(validation.heading_rmse_change_rad));

if options.AssertConverged
    assert(validation.passed, ...
        "Phase 1.3 metrics did not converge under step refinement.");
end

fprintf("Step 11 passed: fixed-step convergence verified.\n");

end
