function [results, config] = ...
    run_highway_cruise_phase1(environmentName, actuationDelay_s)

arguments
    environmentName (1,1) string = "dry_road"
    actuationDelay_s (1,1) double ...
    {mustBeNonnegative} = 0
end

[results, config] = run_phase1_baseline( ...
    "highway_cruise", ...
    environmentName, ...
    actuationDelay_s ...
);

if config.controller.controller_backend == ...
        config.controller.BACKEND_ACADOS

    disp(results.solve_time_metrics.summary_table);
end

end