function [results, config, timingData] = run_phase1_case( ...
    timingMode, scenarioName, environmentName, options)
%RUN_PHASE1_CASE Run one Phase 1 timing experiment.
%
% timingMode:
%   "constant_delay"  - fixed actuator delay
%   "random_delay"    - reproducible uniform actuator delay
%   "sampling_jitter" - triggered controller execution

arguments
    timingMode (1,1) string {mustBeMember(timingMode, ...
        ["constant_delay", "random_delay", "sampling_jitter"])}
    scenarioName (1,1) string
    environmentName (1,1) string = "dry_road"

    options.Delay_ms (1,1) double {mustBeNonnegative} = 0
    options.JitterBound_ms (1,1) double {mustBeNonnegative} = 0
    options.RandomSeed (1,1) double ...
        {mustBeInteger, mustBeNonnegative} = 1
    options.SimulationStep_s (1,1) double {mustBePositive} = 0.0005
    options.SaveResults (1,1) logical = true
end

startup_project;
timingData = [];

switch timingMode
    case "constant_delay"
        [results, config] = run_phase1_baseline( ...
            scenarioName, environmentName, options.Delay_ms*1e-3, ...
            DelayMode=1, ...
            SaveResults=options.SaveResults);

    case "random_delay"
        scenarioConfig = build_phase0_configuration(scenarioName);
        controller = scenarioConfig.controller;
        maximumDelay_s = options.Delay_ms*1e-3;

        assert(maximumDelay_s <= controller.maximumRandomDelay_s, ...
            "Delay_ms exceeds the configured maximum of %.1f ms.", ...
            1e3*controller.maximumRandomDelay_s);

        timingData = sdv.timing.generate_random_delay_profile( ...
            scenarioConfig.simulation.stop_time_s, ...
            controller.Ts_s, ...
            maximumDelay_s, ...
            options.RandomSeed);

        [results, config] = run_phase1_baseline( ...
            scenarioName, environmentName, 0, ...
            DelayMode=controller.DELAY_MODE_RANDOM, ...
            RandomDelayProfile=timingData.timeseries, ...
            RandomSeed=options.RandomSeed, ...
            SaveResults=options.SaveResults);

    case "sampling_jitter"
        [results, config, timingData] = run_sampling_jitter_case( ...
            scenarioName, ...
            environmentName, ...
            options.JitterBound_ms, ...
            options.RandomSeed, ...
            options.SimulationStep_s, ...
            SaveResults=options.SaveResults);
end

end
