function [results, config, jitterEventTable, caseSummary] = ...
    run_sampling_jitter_case( ...
        scenarioName, ...
        environmentName, ...
        jitterBound_ms, ...
        randomSeed, ...
        simulationStep_s, ...
        options)
%RUN_SAMPLING_JITTER_CASE Run one Phase 1.3 sampling-jitter experiment.

arguments
    scenarioName (1,1) string
    environmentName (1,1) string = "dry_road"
    jitterBound_ms (1,1) double ...
        {mustBeNonnegative} = 0
    randomSeed (1,1) double ...
        {mustBeInteger, mustBeNonnegative} = 1
    simulationStep_s (1,1) double ...
        {mustBePositive} = 0.0005

    options.SaveResults (1,1) logical = true
    options.SaveFigures (1,1) logical = true
    options.ShowFigures (1,1) logical = true
end

startup_project;

configuration = build_phase0_configuration(scenarioName);

assert( ...
    jitterBound_ms * 1e-3 < configuration.controller.Ts_s, ...
    "Jitter bound must be smaller than the nominal controller period.");

minimumInterval_s = ...
    configuration.controller.Ts_s - jitterBound_ms*1e-3;
assert(minimumInterval_s > 2*simulationStep_s, ...
    "The minimum controller interval must exceed the two-step trigger pulse.");

stepsPerNominalPeriod = ...
    configuration.controller.Ts_s/simulationStep_s;
assert(abs(stepsPerNominalPeriod - round(stepsPerNominalPeriod)) ...
        <= 100*eps(max(1,stepsPerNominalPeriod)), ...
    "Controller Ts must be an integer multiple of the simulation step.");

runConfig = sdv.config.createRun( ...
    "phase1_trigger", ...
    scenarioName, ...
    environmentName, ...
    ActuationDelay_s=0, ...
    SaveResults=options.SaveResults, ...
    SaveFigures=options.SaveFigures, ...
    ShowFigures=options.ShowFigures);

runConfig.jitter = struct( ...
    "bound_ms", jitterBound_ms, ...
    "random_seed", randomSeed, ...
    "simulation_step_s", simulationStep_s);

runner = sdv.ExperimentRunner(runConfig);
[results, config] = runner.run();

jitterEventTable = results.jitter_event_table;

caseSummary = table( ...
    scenarioName, ...
    environmentName, ...
    jitterBound_ms, ...
    randomSeed, ...
    simulationStep_s, ...
    results.jitter_validation.execution_count, ...
    results.tracking_metrics.speed_rmse_mps, ...
    results.tracking_metrics.lateral_rmse_m, ...
    results.tracking_metrics.heading_rmse_rad, ...
    results.jitter_validation.deadline_miss_count, ...
    VariableNames=[ ...
        "ScenarioName"
        "EnvironmentName"
        "JitterBound_ms"
        "RandomSeed"
        "SimulationStep_s"
        "ExecutionCount"
        "SpeedRmse_mps"
        "LateralRmse_m"
        "HeadingRmse_rad"
        "DeadlineMissCount"]);

fprintf( ...
    "Phase 1.3 single case complete: %s, %s, J = %.3f ms, seed = %d.\n", ...
    scenarioName, environmentName, jitterBound_ms, randomSeed);

end
