function [results, config, resultsFile] = run_phase1_baseline( ...
    scenarioName, ...
    environmentName, ...
    actuationDelay_s, ...
    options)
%RUN_PHASE1_BASELINE Run one Phase 1 experiment.

arguments
    scenarioName (1,1) string
    environmentName (1,1) string = "dry_road"
    actuationDelay_s (1,1) double ...
        {mustBeNonnegative} = 0

    options.SaveResults (1,1) logical = true
    options.DelayMode (1,1) double ...
        {mustBeMember(options.DelayMode, [1, 2])} = 1
    options.RandomDelayProfile = []
    options.RandomSeed (1,1) double = NaN
end

% startup_project;

% setup all the requirement for simulation to run
runConfig = sdv.config.createRun( ...
    "phase1", ... %% to run particular SIMULINK model, phase0_baseline, phase1_baseline
    scenarioName, ...
    environmentName, ...
    ActuationDelay_s=actuationDelay_s, ...
    DelayMode=options.DelayMode, ...
    RandomDelayProfile=options.RandomDelayProfile, ...
    RandomSeed=options.RandomSeed, ...
    SaveResults=options.SaveResults);

% pass the requirements or configuration to class to create object to run
% simulation
runner = sdv.ExperimentRunner(runConfig);

[results, config, resultsFile] = runner.run();

fprintf("Relevant plot file:\n%s\n", fullfile( ...
    matlab.project.currentProject().RootFolder, ...
    "phase1", "plots", "plot_phase1_baseline.m"));

if strlength(resultsFile) > 0
    fprintf("Plot input artifact:\n%s\n", resultsFile);
end

end
