function summaryTable = run_constant_delay_sweep(options)
%RUN_CONSTANT_DELAY_SWEEP Run one or more constant-delay experiments.
%
% UpdateSummary=false returns rows for the requested runs without reading,
% writing the stored sweep summary. UpdateSummary=true loads
% the stored summary, replaces only matching scenario/environment/delay
% rows, and checkpoints it after each run. Plotting is performed offline.

arguments
    options.ScenarioNames (1,:) string ...
        = [sdv.enum.ScenarioName.urban_profile, ...
        sdv.enum.ScenarioName.aggressive_maneuver, ...
        sdv.enum.ScenarioName.highway_cruise]
    options.EnvironmentNames (1,:) string ...
        = [sdv.enum.EnvironmentName.dry_road, ...
        sdv.enum.EnvironmentName.low_friction_road]
    options.Delay_ms (1,:) double {mustBeNonnegative} = 0:5:100
    options.UpdateSummary (1,1) logical = true
    options.SaveRunResults (1,1) logical = true
end

configuration = build_phase0_configuration( ...
    options.ScenarioNames(1));

controllerName = sdv.config.controllerName( ...
    configuration.controller);

if options.UpdateSummary
    summaryTable = loadStoredSummary(controllerName);
else
    summaryTable = table();
end

for delay_ms = options.Delay_ms

    delay_s = delay_ms * 1e-3;

    for scenarioName = options.ScenarioNames
        % for log file
        fprintf( ...
            "\nScenario: %s, delay: %.1f ms\n", ...
            scenarioName, ...
            delay_ms);
        for environmentName = options.EnvironmentNames

            try
                % as usual run files which run simulink from here
                [results, ~] = run_phase1_baseline( ...
                    scenarioName, ...
                    environmentName, ...
                    delay_s, ...
                    SaveResults=options.SaveRunResults);

                newRow = sdv.metrics.createDelaySweepRow( ...
                    scenarioName, ...
                    environmentName, ...
                    delay_s, ...
                    results);

            catch simulationError
                % error will be saved in log files
                warning( ...
                    "SDV:DelaySweepRunFailed", ...
                    "Scenario %s failed at %.1f ms:\n%s", ...
                    scenarioName, ...
                    delay_ms, ...
                    simulationError.message);

                newRow = sdv.metrics.createDelaySweepRow( ...
                    scenarioName, ...
                    environmentName, ...
                    delay_s, ...
                    struct(), ...
                    Completed=false, ...
                    ErrorIdentifier=string( ...
                    simulationError.identifier), ...
                    ErrorMessage=string( ...
                    simulationError.message));
            end
            summaryTable = upsertRow(summaryTable, newRow);

            summaryTable = sortrows( ...
                summaryTable, ...
                ["scenario_name", "environment_name", "delay_ms"]);

            if options.UpdateSummary
                % Checkpoint after every simulation without changing
                % unrelated rows already stored in the summary.
                sdv.io.saveDelaySweepSummary( ...
                    summaryTable, ...
                    controllerName);
            end
        end
    end
end

projectRoot = string( ...
    matlab.project.currentProject().RootFolder);

fprintf("Relevant plot file:\n%s\n", fullfile( ...
    projectRoot, "phase1", "plots", ...
    "plot_constant_delay_sweep.m"));

end

function summaryTable = loadStoredSummary(controllerName)
% Load the existing summary when row-level updates are enabled.

projectRoot = string( ...
    matlab.project.currentProject().RootFolder);

summaryFile = fullfile( ...
    projectRoot, ...
    "phase1", ...
    "results", ...
    controllerName, ...
    "constant_delay_sweep", ...
    "constant_delay_summary.mat");

summaryTable = table();

if ~isfile(summaryFile)
    return;
end

stored = load(summaryFile, "summaryTable");

assert(isfield(stored, "summaryTable") && istable(stored.summaryTable), ...
    "Stored constant-delay summary does not contain a valid summaryTable.");

summaryTable = stored.summaryTable;

end

function summaryTable = upsertRow(summaryTable, newRow)
% Replace one matching case or append it when it is not yet stored.

if isempty(summaryTable)
    summaryTable = newRow;
    return;
end

matchingRow = ...
    string(summaryTable.scenario_name) == string(newRow.scenario_name(1)) & ...
    string(summaryTable.environment_name) == string(newRow.environment_name(1)) & ...
    summaryTable.delay_ms == newRow.delay_ms(1);

summaryTable(matchingRow, :) = [];
summaryTable = [summaryTable; newRow];

end
