function [summaryTable, sweepFigure] = ...
    run_random_delay_sweep(options)
%RUN_RANDOM_DELAY_SWEEP Run reproducible Phase 1.2 Monte Carlo trials.
%
% Each trial uses an independent, uniformly distributed actuation-delay
% profile in [0, MaximumDelay_ms]. The delay is updated at the controller
% sample period and the same profile is applied to torque and steering.
% UpdateSummary=false returns only the requested trial rows and does not
% read, write, plot, or export the persistent Monte Carlo summary.
% UpdateSummary=true loads the stored summary, replaces matching trial
% rows, checkpoints after every trial, and regenerates the sweep figure.

arguments
    options.ScenarioNames (1,:) string = [ ...
        sdv.enum.ScenarioName.urban_profile, ...
        % sdv.enum.ScenarioName.aggressive_maneuver, ...
        % sdv.enum.ScenarioName.highway_cruise
        ]

    options.EnvironmentNames (1,:) string = [ ...
        sdv.enum.EnvironmentName.dry_road, ...
        sdv.enum.EnvironmentName.low_friction_road]

    options.MaximumDelay_ms (1,:) double ...
        {mustBeNonnegative} = [10, 30, 50, 70, 90, 100, 120, 130, 150, 170, 180, 200]
    options.TrialsPerLevel (1,1) double ...
        {mustBeInteger, mustBePositive} = 20
    options.BaseSeed (1,1) double ...
        {mustBeInteger, mustBeNonnegative} = 1000
    options.SaveTrialResults (1,1) logical = true
    options.ShowFigure (1,1) logical = true
    options.UpdateSummary (1,1) logical = true
end

% startup_project;

numberOfRuns = numel(options.ScenarioNames) * numel(options.EnvironmentNames) * numel(options.MaximumDelay_ms) * options.TrialsPerLevel;

fprintf("Expected runs: %d\n", numberOfRuns);

projectRoot = string( ...
    matlab.project.currentProject().RootFolder);

firstConfiguration = build_phase0_configuration( ...
    options.ScenarioNames(1));

controller = firstConfiguration.controller;
controllerName = sdv.config.controllerName(controller);
randomDelayMode = controller.DELAY_MODE_RANDOM;

maximumConfiguredDelay_ms = ...
    1e3 * controller.maximumRandomDelay_s;

assert(all(options.MaximumDelay_ms <= maximumConfiguredDelay_ms), ...
    "MaximumDelay_ms cannot exceed the configured limit of %.3f ms.", ...
    maximumConfiguredDelay_ms);


if options.UpdateSummary
    summaryTable = loadStoredRandomDelaySummary( ...
        projectRoot, controllerName);
else
    summaryTable = table();
end


r = 0;

for environmentName = options.EnvironmentNames
    for maximumDelay_ms = options.MaximumDelay_ms
        maximumDelay_s = maximumDelay_ms * 1e-3;

        for scenarioName = options.ScenarioNames
            scenarioConfiguration = ...
                build_phase0_configuration(scenarioName);

            sampleTime_s = ...
                scenarioConfiguration.controller.Ts_s;
            stopTime_s = ...
                scenarioConfiguration.simulation.stop_time_s;

            for trialIndex = 1:options.TrialsPerLevel
                r = r + 1;
                fprintf( ...
                    "\nRun %d/%d: %s, %s, D = %.1f ms, seed = %d\n", ...
                    r, ...
                    numberOfRuns, ...
                    scenarioName, ...
                    environmentName, ...
                    maximumDelay_ms, ...
                    trialIndex);

                randomSeed = options.BaseSeed + trialIndex - 1;

                delayProfile = ...
                    sdv.timing.generate_random_delay_profile( ...
                        stopTime_s, ...
                        sampleTime_s, ...
                        maximumDelay_s, ...
                        randomSeed);

                randomDelayProfile = delayProfile.timeseries;

                delayData_s = randomDelayProfile.Data(:);

                fprintf( ...
                    ['\nScenario: %s, environment: %s, ' ...
                    'maximum delay: %.1f ms, trial: %d/%d, seed: %d\n'], ...
                    char(scenarioName), ...
                    char(environmentName), ...
                    maximumDelay_ms, ...
                    trialIndex, ...
                    options.TrialsPerLevel, ...
                    randomSeed);
                try
                    [results, config] = run_phase1_baseline( ...
                        scenarioName, ...
                        environmentName, ...
                        0, ...
                        DelayMode=randomDelayMode, ...
                        RandomDelayProfile=randomDelayProfile, ...
                        RandomSeed=randomSeed, ...
                        SaveResults=options.SaveTrialResults, ...
                        SaveFigures=false, ...
                        ShowFigures=false);

                    newRow = createRandomDelayRow( ...
                        scenarioName, ...
                        environmentName, ...
                        maximumDelay_s, ...
                        trialIndex, ...
                        randomSeed, ...
                        delayData_s, ...
                        results);

                    if options.SaveTrialResults
                        saveTrialResult( ...
                            projectRoot, ...
                            controllerName, ...
                            scenarioName, ...
                            environmentName, ...
                            maximumDelay_ms, ...
                            trialIndex, ...
                            randomSeed, ...
                            results, ...
                            config, ...
                            randomDelayProfile);
                    end

                catch simulationError
                    warning( ...
                        "SDV:RandomDelayRunFailed", ...
                        ["Scenario %s failed for maximum delay %.1f ms, " ...
                        "trial %d, seed %d:\n%s"], ...
                        scenarioName, ...
                        maximumDelay_ms, ...
                        trialIndex, ...
                        randomSeed, ...
                        simulationError.message);

                    newRow = createRandomDelayRow( ...
                        scenarioName, ...
                        environmentName, ...
                        maximumDelay_s, ...
                        trialIndex, ...
                        randomSeed, ...
                        delayData_s, ...
                        struct(), ...
                        Completed=false, ...
                        ErrorIdentifier=string( ...
                            simulationError.identifier), ...
                        ErrorMessage=string( ...
                            simulationError.message));
                end

                if isempty(summaryTable)
                    summaryTable = newRow;
                else
                    summaryTable = removeExistingCase( ...
                        summaryTable, ...
                        scenarioName, ...
                        environmentName, ...
                        maximumDelay_ms, ...
                        trialIndex);
                    summaryTable = [summaryTable; newRow];
                end
                summaryTable = sortrows( ...
                    summaryTable, ...
                    ["environment_name", "scenario_name", ...
                    "maximum_delay_ms", "trial_index"]);
                
                if options.UpdateSummary
                    saveRandomDelaySummary( ...
                        summaryTable, ...
                        projectRoot, ...
                        controllerName);
                end
            end
        end
    end
end

sweepFigure = gobjects(0);

if ~options.UpdateSummary
    return;
end

figureVisibility = "off";
if options.ShowFigure
    figureVisibility = "on";
end

sweepFigure = sdv.plot.randomDelaySweepMetrics( ...
    summaryTable, ...
    FigureTitle="Phase 1.2: Monte Carlo Metrics versus Random-Delay Bound", ...
    Visible=figureVisibility);

figureFolder = fullfile( ...
    projectRoot, ...
    "phase1", ...
    "figures", ...
    controllerName, ...
    "random_delay_sweep");

sdv.io.exportFigure( ...
    sweepFigure, ...
    figureFolder, ...
    "random_delay_monte_carlo_metrics");

if ~options.ShowFigure
    close(sweepFigure);
end

end

function row = createRandomDelayRow( ...
    scenarioName, environmentName, maximumDelay_s, ...
    trialIndex, randomSeed, delayData_s, results, options)
%CREATERANDOMDELAYROW Convert one Monte Carlo trial into one table row.

arguments
    scenarioName (1,1) string
    environmentName (1,1) string
    maximumDelay_s (1,1) double {mustBeNonnegative}
    trialIndex (1,1) double
    randomSeed (1,1) double
    delayData_s (:,1) double
    results (1,1) struct
    options.Completed (1,1) logical = true
    options.ErrorIdentifier (1,1) string = ""
    options.ErrorMessage (1,1) string = ""
end

row = sdv.metrics.createDelaySweepRow( ...
    scenarioName, ...
    environmentName, ...
    maximumDelay_s, ...
    results, ...
    Completed=options.Completed, ...
    ErrorIdentifier=options.ErrorIdentifier, ...
    ErrorMessage=options.ErrorMessage);

row = renamevars( ...
    row, ...
    ["delay_s", "delay_ms"], ...
    ["maximum_delay_s", "maximum_delay_ms"]);

row.trial_index = trialIndex;
row.random_seed = randomSeed;
row.delay_distribution = "uniform";
row.realized_delay_mean_ms = mean(delayData_s) * 1e3;
row.realized_delay_std_ms = std(delayData_s) * 1e3;
sortedDelay_s = sort(delayData_s);
percentileIndex = max( ...
    1, ceil(0.95 * numel(sortedDelay_s)));
row.realized_delay_p95_ms = ...
    sortedDelay_s(percentileIndex) * 1e3;
row.realized_delay_max_ms = max(delayData_s) * 1e3;

row.delay_validation_passed = false;
row.torque_delay_residual_rmse_Nm = NaN;
row.torque_delay_residual_max_Nm = NaN;
row.steering_delay_residual_rmse_deg = NaN;
row.steering_delay_residual_max_deg = NaN;

if options.Completed && ...
        isfield(results, "delay_validation") && ...
        results.delay_validation.available

    validation = results.delay_validation;
    row.delay_validation_passed = validation.passed;
    row.torque_delay_residual_rmse_Nm = ...
        validation.torque.rmse;
    row.torque_delay_residual_max_Nm = ...
        validation.torque.maximum_absolute;
    row.steering_delay_residual_rmse_deg = ...
        validation.steering.rmse;
    row.steering_delay_residual_max_deg = ...
        validation.steering.maximum_absolute;
end

row = movevars( ...
    row, ...
    ["trial_index", "random_seed", "delay_distribution", ...
    "realized_delay_mean_ms", "realized_delay_std_ms", ...
    "realized_delay_p95_ms", "realized_delay_max_ms", ...
    "delay_validation_passed", ...
    "torque_delay_residual_rmse_Nm", ...
    "torque_delay_residual_max_Nm", ...
    "steering_delay_residual_rmse_deg", ...
    "steering_delay_residual_max_deg"], ...
    After="maximum_delay_ms");

end

function saveRandomDelaySummary( ...
    summaryTable, projectRoot, controllerName)
%SAVERANDOMDELAYSUMMARY Checkpoint the Monte Carlo table.

resultsFolder = fullfile( ...
    projectRoot, ...
    "phase1", ...
    "results", ...
    controllerName, ...
    "random_delay_sweep");

if ~isfolder(resultsFolder)
    mkdir(resultsFolder);
end

save( ...
    fullfile(resultsFolder, "random_delay_summary.mat"), ...
    "summaryTable");
writetable( ...
    summaryTable, ...
    fullfile(resultsFolder, "random_delay_summary.csv"));

end

function saveTrialResult( ...
    projectRoot, controllerName, scenarioName, environmentName, ...
    maximumDelay_ms, trialIndex, randomSeed, ...
    results, config, randomDelayProfile)
%SAVETRIALRESULT Save one trial under a collision-free filename.

maximumDelayText = replace( ...
    string(sprintf("%g", maximumDelay_ms)), ".", "p");

trialFolder = fullfile( ...
    projectRoot, ...
    "phase1", ...
    "results", ...
    controllerName, ...
    "random_delay_sweep", ...
    environmentName, ...
    scenarioName, ...
    "maximum_delay_" + maximumDelayText + "_ms");

if ~isfolder(trialFolder)
    mkdir(trialFolder);
end

fileName = sprintf( ...
    "trial_%03d_seed_%d.mat", ...
    trialIndex, ...
    randomSeed);

save( ...
    fullfile(trialFolder, fileName), ...
    "results", ...
    "config", ...
    "randomDelayProfile");

end

function tableData = removeExistingCase( ...
    tableData, ...
    scenario, ...
    environment, ...
    maximum_delay_ms, ...
    trial_index)

if isempty(tableData)
    return;
end

matching = ...
    tableData.scenario_name == scenario ...
    & tableData.environment_name == environment ...
    & abs(tableData.maximum_delay_ms - maximum_delay_ms) < 1e-9 ...
    & tableData.trial_index == trial_index;

tableData(matching,:) = [];

end

function summaryTable = loadStoredRandomDelaySummary( ...
    projectRoot, controllerName)
% Load the persistent summary only when updates are explicitly enabled.

summaryFile = fullfile( ...
    projectRoot, ...
    "phase1", ...
    "results", ...
    controllerName, ...
    "random_delay_sweep", ...
    "random_delay_summary.mat");

summaryTable = table();

if ~isfile(summaryFile)
    return;
end

stored = load(summaryFile, "summaryTable");

assert(isfield(stored, "summaryTable") && istable(stored.summaryTable), ...
    "Stored random-delay summary does not contain a valid summaryTable.");

summaryTable = stored.summaryTable;

end
