projectRoot = string( ...
    matlab.project.currentProject().RootFolder);

scenarioNames = [
    "urban_profile"
    "highway_cruise"
    "aggressive_maneuver"
    ];

environmentNames = [
    "dry_road"
    "low_friction_road"
    ];

numberOfCases = ...
    numel(scenarioNames) * numel(environmentNames);

phase0Files = strings(numberOfCases, 1);
phase1Files = strings(numberOfCases, 1);
caseLabels = strings(numberOfCases, 1);

caseIndex = 0;

for scenarioName = scenarioNames.'
    for environmentName = environmentNames.'

        caseIndex = caseIndex + 1;

        phase0Files(caseIndex) = fullfile( ...
            projectRoot, ...
            "phase0", ...
            "results", ...
            "ACADOS_MPC", ...
            scenarioName, ...
            environmentName, ...
            scenarioName + "_results.mat");

        phase1Files(caseIndex) = fullfile( ...
            projectRoot, ...
            "phase1", ...
            "results", ...
            "ACADOS_MPC", ...
            "actuation_delay_200_ms", ...
            scenarioName, ...
            environmentName, ...
            scenarioName + "_results.mat");

        caseLabels(caseIndex) = replace( ...
            scenarioName + " / " + environmentName, ...
            "_", ...
            " ");
    end
end

[comparisonFigure, comparisonTable] = ...
    sdv.plot.compareTrackingEquivalence( ...
    phase0Files, ...
    phase1Files, ...
    ReferenceLabel="Phase 0", ...
    CandidateLabel="Phase 1.1, 0 ms", ...
    CaseLabels=caseLabels, ...
    FigureTitle="Phase 0 versus Zero-Delay Phase 1.1");

disp(comparisonTable);