function [figureHandle, sourceTable] = ...
    run_plot_constant_delay_tracking_errors( ...
    scenarioName, environmentName, options)
%RUN_PLOT_CONSTANT_DELAY_TRACKING_ERRORS Plot available delay histories.

arguments
    scenarioName (1,1) string = ...
        sdv.enum.ScenarioName.aggressive_maneuver
    environmentName (1,1) string = ...
        sdv.enum.EnvironmentName.dry_road
    options.Delay_ms (1,:) double {mustBeNonnegative} = 0:5:200
    options.SaveFigure (1,1) logical = true
    options.ShowFigure (1,1) logical = true
    options.ShowConstraints (1,1) logical = true
    options.HighlightViolations (1,1) logical = true
    options.LateralLimits_m (1,2) double = [NaN, NaN]
    options.HeadingLimits_deg (1,2) double = [NaN, NaN]
    options.LegendColumns (1,1) double ...
        {mustBeInteger, mustBeNonnegative} = 0
    options.XLimits_s (1,2) double = [NaN, NaN]
end

startup_project;

projectRoot = string( ...
    matlab.project.currentProject().RootFolder);

configuration = build_phase0_configuration(scenarioName);
controllerName = sdv.config.controllerName( ...
    configuration.controller);

[lateralLimits_m, headingLimits_deg] = resolveLimits( ...
    configuration.controller, ...
    options.ShowConstraints, ...
    options.LateralLimits_m, ...
    options.HeadingLimits_deg);

timeSeries_s = cell(0,1);
lateralErrorSeries_m = cell(0,1);
headingErrorSeries_deg = cell(0,1);
legendLabels = strings(0,1);
availableDelay_ms = zeros(0,1);
sourceFiles = strings(0,1);
missingDelay_ms = zeros(0,1);

for delay_ms = options.Delay_ms
    delayText = replace( ...
        string(sprintf("%g", delay_ms)), ".", "p");

    sourceFile = fullfile( ...
        projectRoot, ...
        "phase1", ...
        "results", ...
        controllerName, ...
        "actuation_delay_" + delayText + "_ms", ...
        scenarioName, ...
        environmentName, ...
        scenarioName + "_results.mat");

    if ~isfile(sourceFile)
        missingDelay_ms(end+1,1) = delay_ms; %#ok<AGROW>
        continue;
    end

    savedData = load(sourceFile, "results");
    assert(isfield(savedData, "results"), ...
        "File does not contain results: %s", sourceFile);

    results = savedData.results;
    requiredFields = ["time_s", "ey_m", "epsi_rad"];
    missingFields = setdiff( ...
        requiredFields, string(fieldnames(results)));

    assert(isempty(missingFields), ...
        "Result file %s is missing: %s", ...
        sourceFile, strjoin(missingFields, ", "));

    timeSeries_s{end+1,1} = results.time_s(:); %#ok<AGROW>
    lateralErrorSeries_m{end+1,1} = results.ey_m(:); %#ok<AGROW>
    headingErrorSeries_deg{end+1,1} = ...
        rad2deg(results.epsi_rad(:)); %#ok<AGROW>
    legendLabels(end+1,1) = ...
        string(sprintf("%g ms", delay_ms)); %#ok<AGROW>
    availableDelay_ms(end+1,1) = delay_ms; %#ok<AGROW>
    sourceFiles(end+1,1) = sourceFile; %#ok<AGROW>
end

assert(~isempty(timeSeries_s), ...
    "No requested constant-delay result files were found.");

if ~isempty(missingDelay_ms)
    fprintf( ...
        "Skipped %d unavailable delay cases: %s ms\n", ...
        numel(missingDelay_ms), ...
        strjoin(string(missingDelay_ms.'), ", "));
end

figureTitle = "Constant-delay tracking errors for 0:5:150ms: " + ...
    replace(scenarioName, "_", " ") + " / " + ...
    replace(environmentName, "_", " ");

visibility = "off";
if options.ShowFigure
    visibility = "on";
end

figureHandle = sdv.plot.trackingErrorOverlay( ...
    timeSeries_s, ...
    lateralErrorSeries_m, ...
    headingErrorSeries_deg, ...
    legendLabels, ...
    FigureTitle=figureTitle, ...
    HeadingUnit="deg", ...
    LateralLimits_m=lateralLimits_m, ...
    HeadingLimits=headingLimits_deg, ...
    HighlightViolations=options.HighlightViolations, ...
    LegendColumns=options.LegendColumns, ...
    XLimits_s=options.XLimits_s, ...
    Visible=visibility);

sourceTable = table( ...
    availableDelay_ms, sourceFiles, ...
    VariableNames=["delay_ms", "results_file"]);

if options.SaveFigure
    figureFolder = fullfile( ...
        projectRoot, ...
        "phase1", ...
        "figures", ...
        controllerName, ...
        "constant_delay_sweep");

    baseName = scenarioName + "_" + environmentName + ...
        "_tracking_error_overlay";

    sdv.io.exportFigure( ...
        figureHandle, figureFolder, baseName);
end

end

function [lateralLimits_m, headingLimits_deg] = resolveLimits( ...
    controller, showConstraints, manualLateralLimits_m, ...
    manualHeadingLimits_deg)

if ~showConstraints
    lateralLimits_m = [NaN, NaN];
    headingLimits_deg = [NaN, NaN];
    return;
end

lateralLimits_m = manualLateralLimits_m;
if all(isnan(lateralLimits_m))
    lateralLimits_m = [ ...
        controller.minimumState(4), ...
        controller.maximumState(4)];
else
    assert(all(isfinite(lateralLimits_m)), ...
        "LateralLimits_m must contain two finite values or [NaN, NaN].");
end

headingLimits_deg = manualHeadingLimits_deg;
if all(isnan(headingLimits_deg))
    headingLimits_deg = rad2deg([ ...
        controller.minimumState(5), ...
        controller.maximumState(5)]);
else
    assert(all(isfinite(headingLimits_deg)), ...
        "HeadingLimits_deg must contain two finite values or [NaN, NaN].");
end

assert(lateralLimits_m(2) > lateralLimits_m(1), ...
    "LateralLimits_m must be [lower, upper].");
assert(headingLimits_deg(2) > headingLimits_deg(1), ...
    "HeadingLimits_deg must be [lower, upper].");

end
