function [sweepSummary, sweepStatistics] = ...
    run_sampling_jitter_monte_carlo( ...
    scenarioNames, environmentNames, jitterBounds_ms, options)
%RUN_SAMPLING_JITTER_MONTE_CARLO  Sampling-jitter sweep (concise).
%
% UpdateSummary=false runs isolated cases without reading or writing the
% stored sweep summary. UpdateSummary=true loads the existing checkpoint
% and replaces only matching scenario/environment/jitter/seed rows.
arguments
    scenarioNames (1,:) string = [ ...
        sdv.enum.ScenarioName.urban_profile, ...
        sdv.enum.ScenarioName.aggressive_maneuver, ...
        sdv.enum.ScenarioName.highway_cruise
        ]

    environmentNames (1,:) string = [ ...
        sdv.enum.EnvironmentName.dry_road, ...
        sdv.enum.EnvironmentName.low_friction_road]

    jitterBounds_ms (1,:) double = [0 2 4 5 6 7 8]
    options.RandomSeeds (1,:) double ...
        {mustBeInteger, mustBePositive} = 1:20
    options.SimulationStep_s (1,1) double ...
        {mustBePositive} = 0.0005
    options.UpdateSummary (1,1) logical = true
    options.SaveRunResults (1,1) logical = true
end

randomSeeds = options.RandomSeeds;
simulationStep_s = options.SimulationStep_s;

numberOfRuns = ...
    numel(scenarioNames) * ...
    numel(environmentNames) * ...
    (1 + ...
    (numel(jitterBounds_ms) - 1) * numel(randomSeeds));

configuration = ...
    build_phase0_configuration("highway_cruise");

controllerName = ...
    sdv.config.controllerName(configuration.controller);

projectRoot = string( ...
    matlab.project.currentProject().RootFolder);

summaryFolder = fullfile( ...
    projectRoot, "phase1", "results", ...
    controllerName, "sampling_jitter", "sweep");

logFolder = fullfile( ...
    projectRoot, "phase1", "logs");

checkpointFile = fullfile( ...
    summaryFolder, "sweep_summary_checkpoint.mat");

csvFile = fullfile( ...
    summaryFolder, "sweep_summary.csv");

logFile = "";
if options.UpdateSummary
    if ~isfolder(summaryFolder)
        mkdir(summaryFolder);
    end
    if ~isfolder(logFolder)
        mkdir(logFolder);
    end

    timestamp = string(datetime( ...
        "now", Format="yyyyMMdd_HHmmss"));
    logFile = fullfile( ...
        logFolder, ...
        "sampling_jitter_sweep_" + timestamp + ".txt");

    diary(logFile);
    diary on;
    diaryCleanup = onCleanup(@() diary("off"));
end

fprintf("\n========================================\n");
fprintf("Phase 1.3 sampling-jitter sweep\n");
fprintf("========================================\n");
fprintf("Scenarios: %s\n", strjoin(scenarioNames, ", "));
fprintf("Environments: %s\n", ...
    strjoin(environmentNames, ", "));
fprintf("Jitter bounds: %s ms\n", ...
    strjoin(string(jitterBounds_ms), ", "));
fprintf("Nonzero-jitter seeds: %d to %d\n", ...
    randomSeeds(1), randomSeeds(end));
fprintf("Simulation step: %.3f ms\n", ...
    1e3*simulationStep_s);
fprintf("Expected runs: %d\n", numberOfRuns);
if strlength(logFile) > 0
    fprintf("Log: %s\n", logFile);
else
    fprintf("Persistent summary update: disabled\n");
end
fprintf("========================================\n\n");

if options.UpdateSummary
    sweepSummary = loadStoredSummary(checkpointFile);
else
    sweepSummary = table();
end
runNumber = 0;


for environmentName = environmentNames

    for scenarioName = scenarioNames

        for jitterBound_ms = jitterBounds_ms

            if jitterBound_ms == 0
                seedsForBatch = 1;
            else
                seedsForBatch = randomSeeds;
            end

            for randomSeed = seedsForBatch

                runNumber = runNumber + 1;

                fprintf( ...
                    "\nRun %d/%d: %s, %s, J = %.1f ms, seed = %d\n", ...
                    runNumber, ...
                    numberOfRuns, ...
                    scenarioName, ...
                    environmentName, ...
                    jitterBound_ms, ...
                    randomSeed);
    
                try
                    [results, ~, ~, caseSummary] = ...
                        run_sampling_jitter_case( ...
                            scenarioName, ...
                            environmentName, ...
                            jitterBound_ms, ...
                            randomSeed, ...
                            simulationStep_s, ...
                            SaveResults=options.SaveRunResults);
    
                    tracking = results.tracking_metrics;
                    constraints = results.constraint_metrics;
                    validation = results.jitter_validation;
                    executionLog = results.controller_execution_log;
    
                    rawStatus = executionLog.SolverStatus(:);
                    solveTime_ms = ...
                        1e3*executionLog.SolveTime_s(:);
    
                    caseSummary.Completed = true;
                    caseSummary.SpeedPeak_mps = ...
                        tracking.speed_peak_mps;
                    caseSummary.LateralPeak_m = ...
                        tracking.lateral_peak_m;
                    caseSummary.HeadingRmse_deg = ...
                        tracking.heading_rmse_deg;
                    caseSummary.HeadingPeak_deg = ...
                        tracking.heading_peak_deg;
    
                    caseSummary.ConstraintViolationSamples = ...
                        constraints.any_sample_count;
                    caseSummary.ConstraintEventCount = ...
                        constraints.event_count;
                    caseSummary.ConstraintDuration_s = ...
                        constraints.duration_s;
    
                    % Preserve raw acados statuses without remapping.
                    caseSummary.RawStatus0Count = nnz(rawStatus == 0);
                    caseSummary.RawStatus2Count = nnz(rawStatus == 2);
                    caseSummary.RawStatus4Count = nnz(rawStatus == 4);
                    caseSummary.OtherStatusCount = ...
                        nnz(~ismember(rawStatus, [0 2 4]));
    
                    caseSummary.SolveTimeP95_ms = ...
                        samplePercentile(solveTime_ms, 0.95);
    
                    caseSummary.MaximumActualJitter_ms = ...
                        1e3*validation.maximum_abs_actual_jitter_s;
    
                    caseSummary.ErrorMessage = "";
    
                catch simulationError
                    warning( ...
                        "sweep run failed: %s", ...
                        simulationError.message);
    
                    caseSummary = createFailedRow( ...
                        scenarioName, ...
                        environmentName, ...
                        jitterBound_ms, ...
                        randomSeed, ...
                        simulationStep_s, ...
                        string(simulationError.message));
                end

                sweepSummary = upsertCase(sweepSummary, caseSummary);

                if options.UpdateSummary
                    % Checkpoint after every completed or failed case.
                    save( ...
                        checkpointFile, ...
                        "sweepSummary", ...
                        "scenarioNames", ...
                        "environmentNames", ...
                        "jitterBounds_ms", ...
                        "randomSeeds", ...
                        "simulationStep_s");
                    writetable(sweepSummary, csvFile);
                end
    
                clear results caseSummary

            end
        end
    end
end

sweepSummary = sortrows( ...
    sweepSummary, ...
    [ ...
        "EnvironmentName", ...
        "ScenarioName", ...
        "JitterBound_ms", ...
        "RandomSeed" ...
    ]);

sweepStatistics = table();

if any(sweepSummary.Completed)
    sweepStatistics = ...
        summarizeSamplingJitterSweep(sweepSummary);
end

statisticsCsvFile = fullfile( ...
    summaryFolder, ...
    "sweep_statistics.csv");

statisticsMatFile = fullfile( ...
    summaryFolder, ...
    "sweep_statistics.mat");

if options.UpdateSummary
    if ~isempty(sweepStatistics)
        writetable(sweepStatistics, statisticsCsvFile);
    end

    save( ...
        statisticsMatFile, ...
        "sweepStatistics", ...
        "sweepSummary", ...
        "scenarioNames", ...
        "environmentNames", ...
        "jitterBounds_ms", ...
        "randomSeeds", ...
        "simulationStep_s");

    save( ...
        checkpointFile, ...
        "sweepSummary", ...
        "scenarioNames", ...
        "environmentNames", ...
        "jitterBounds_ms", ...
        "randomSeeds", ...
        "simulationStep_s");
    writetable(sweepSummary, csvFile);
end

fprintf("\n========================================\n");
fprintf("sweep completed\n");
fprintf("Successful runs: %d/%d\n", ...
    nnz(sweepSummary.Completed), height(sweepSummary));
if options.UpdateSummary
    fprintf("Summary: %s\n", csvFile);
else
    fprintf("Persistent summary was not modified.\n");
end
fprintf("Relevant plot file: %s\n", fullfile( ...
    projectRoot, "phase1", "plots", ...
    "plot_sampling_jitter_monte_carlo.m"));
fprintf("========================================\n");

end


function summary = loadStoredSummary(checkpointFile)
%LOADSTOREDSUMMARY Load the existing checkpoint without changing it.

summary = table();
if ~isfile(checkpointFile)
    return;
end

stored = load(checkpointFile, "sweepSummary");
assert(isfield(stored, "sweepSummary") && istable(stored.sweepSummary), ...
    "Stored jitter checkpoint does not contain a valid sweepSummary.");
summary = stored.sweepSummary;

end


function summary = upsertCase(summary, row)
%UPSERTCASE Replace one matching case or append it when absent.

if isempty(summary)
    summary = row;
    return;
end

matching = ...
    string(summary.ScenarioName) == string(row.ScenarioName(1)) & ...
    string(summary.EnvironmentName) == string(row.EnvironmentName(1)) & ...
    summary.JitterBound_ms == row.JitterBound_ms(1) & ...
    summary.RandomSeed == row.RandomSeed(1);

summary(matching,:) = [];
summary = [summary; row];

end


function row = createFailedRow( ...
    scenarioName, environmentName, jitterBound_ms, ...
    randomSeed, simulationStep_s, errorMessage)

nanValue = NaN;

row = table( ...
    scenarioName, environmentName, jitterBound_ms, ...
    randomSeed, simulationStep_s, ...
    nanValue, nanValue, nanValue, nanValue, nanValue, ...
    false, ...
    nanValue, nanValue, nanValue, nanValue, ...
    nanValue, nanValue, nanValue, ...
    nanValue, nanValue, nanValue, nanValue, ...
    nanValue, nanValue, errorMessage, ...
    VariableNames=[ ...
        "ScenarioName", ...
        "EnvironmentName", ...
        "JitterBound_ms", ...
        "RandomSeed", ...
        "SimulationStep_s", ...
        "ExecutionCount", ...
        "SpeedRmse_mps", ...
        "LateralRmse_m", ...
        "HeadingRmse_rad", ...
        "DeadlineMissCount", ...
        "Completed", ...
        "SpeedPeak_mps", ...
        "LateralPeak_m", ...
        "HeadingRmse_deg", ...
        "HeadingPeak_deg", ...
        "ConstraintViolationSamples", ...
        "ConstraintEventCount", ...
        "ConstraintDuration_s", ...
        "RawStatus0Count", ...
        "RawStatus2Count", ...
        "RawStatus4Count", ...
        "OtherStatusCount", ...
        "SolveTimeP95_ms", ...
        "MaximumActualJitter_ms", ...
        "ErrorMessage"]);
end


function value = samplePercentile(data, probability)

data = sort(data(isfinite(data)));

if isempty(data)
    value = NaN;
    return;
end

index = max(1, ceil(probability*numel(data)));
value = data(index);

end

function statistics = ...
    summarizeSamplingJitterSweep(summary)
%SUMMARIZESAMPLINGJITTERSWEEP
% Calculate statistics across random seeds for every scenario,
% environment, and jitter bound.

validRows = summary(summary.Completed, :);

assert(~isempty(validRows), ...
    "No completed sampling-jitter simulations are available.");

groupVariables = [
    "ScenarioName"
    "EnvironmentName"
    "JitterBound_ms"
    ];

statistics = unique( ...
    validRows(:, groupVariables), ...
    "rows", ...
    "stable");

metrics = [
    "SpeedRmse_mps"
    "SpeedPeak_mps"
    "LateralRmse_m"
    "LateralPeak_m"
    "HeadingRmse_deg"
    "HeadingPeak_deg"
    "ConstraintViolationSamples"
    "ConstraintEventCount"
    "ConstraintDuration_s"
    "RawStatus0Count"
    "RawStatus2Count"
    "RawStatus4Count"
    "OtherStatusCount"
    "DeadlineMissCount"
    "SolveTimeP95_ms"
    "MaximumActualJitter_ms"
    ];

numberOfGroups = height(statistics);

statistics.SampleCount = ...
    zeros(numberOfGroups, 1);

for groupIndex = 1:numberOfGroups

    selected = ...
        validRows.ScenarioName == ...
            statistics.ScenarioName(groupIndex) & ...
        validRows.EnvironmentName == ...
            statistics.EnvironmentName(groupIndex) & ...
        validRows.JitterBound_ms == ...
            statistics.JitterBound_ms(groupIndex);

    statistics.SampleCount(groupIndex) = nnz(selected);
end

for metricName = metrics.'

    meanValues = nan(numberOfGroups, 1);
    standardDeviationValues = nan(numberOfGroups, 1);
    medianValues = nan(numberOfGroups, 1);
    percentile95Values = nan(numberOfGroups, 1);

    for groupIndex = 1:numberOfGroups

        selected = ...
            validRows.ScenarioName == ...
                statistics.ScenarioName(groupIndex) & ...
            validRows.EnvironmentName == ...
                statistics.EnvironmentName(groupIndex) & ...
            validRows.JitterBound_ms == ...
                statistics.JitterBound_ms(groupIndex);

        values = ...
            validRows.(metricName)(selected);

        values = values(isfinite(values));

        if isempty(values)
            continue;
        end

        meanValues(groupIndex) = ...
            mean(values);

        standardDeviationValues(groupIndex) = ...
            std(values);

        medianValues(groupIndex) = ...
            median(values);

        percentile95Values(groupIndex) = ...
            samplePercentile(values, 0.95);
    end

    statistics.(metricName + "_Mean") = ...
        meanValues;

    statistics.(metricName + "_Std") = ...
        standardDeviationValues;

    statistics.(metricName + "_Median") = ...
        medianValues;

    statistics.(metricName + "_P95") = ...
        percentile95Values;
end

statistics = sortrows( ...
    statistics, ...
    [ ...
    "EnvironmentName", ...
    "ScenarioName", ...
    "JitterBound_ms" ...
    ]);

end
