function [results, config] = ...
    run_aggressive_maneuver_phase1(environmentName, actuationDelay_s)

arguments
    environmentName (1,1) string = "dry_road"
    actuationDelay_s (1,1) double ...
        {mustBeNonnegative} = 0
end

[results, config] = run_phase1_baseline( ...
    "aggressive_maneuver", ...
    environmentName, ...
    actuationDelay_s ...
);

if config.controller.controller_backend == ...
        config.controller.BACKEND_ACADOS

    disp(results.solve_time_metrics.summary_table);
end

end