function [results, config] = run_phase1_baseline( ...
    scenarioName, ...
    environmentName, ...
    actuationDelay_s ...
    )

arguments
    scenarioName (1,1) string
    environmentName (1,1) string = "dry_road"
    actuationDelay_s (1,1) double ...
    {mustBeNonnegative} = 0
end

startup_project;
rng(0, "twister");

modelName = "phase1_baseline";

%% Build complete run configuration

%config remain same for all phase
config = build_phase0_configuration(scenarioName);

vehicleParams = config.vehicle;
controllerParams = config.controller;
simulationParams = config.simulation;
adaptiveModelParams = config.adaptiveModel;

%% for Plant simulink model
UT = legacy_plant_parameters( ...
    vehicleParams, ...
    simulationParams);

% Required by MPC_backend_acados
acadosSettings = acados_ocp_parameters(controllerParams);
acados_nominal_input = acadosSettings.nominal_input;
acados_nominal_input = reshape(acados_nominal_input, 2, 1); % acados nominal input

track_ref_table = config.scenario.lookup_table;
scenario_stop_table = config.scenario.stop_event_table;
final_track_index = size(track_ref_table, 1);

%% Configure environment

environmentName = lower(environmentName);

simulationStopTime_s = ...
    simulationParams.stop_time_s;

environment = load_env_profile( ...
    environmentName, ...
    simulationStopTime_s, ...
    FrictionDropTime_s=10);

roadFrictionProfile = ...
    environment.road_friction_profile;

% Save plain metadata without the live timeseries object.
config.environment = rmfield( ...
    environment, ...
    'road_friction_profile');

%% Configure selected controller backend

switch controllerParams.controller_backend

    case controllerParams.BACKEND_ACADOS
        disp("Running acados controller... ")
        % error("ACADOS backend is not implemented yet.");

    case controllerParams.BACKEND_MATLAB
        error("Fixed linear MATLAB MPC backend is not implemented yet.");

    case controllerParams.BACKEND_ADAPTIVE

        [Ad0, Bmv0, Emd0] = ...
            linearize_prediction_model(vehicleParams, simulationParams, controllerParams);

        mpc_adaptive = configure_baseline_mpc( ...
            Ad0, Bmv0, Emd0, controllerParams);

    otherwise
        error( ...
            "Unknown controller backend ID: %d", ...
            controllerParams.controller_backend);
end

%% Create one SimulationInput object

simInput = Simulink.SimulationInput(modelName);

simInput = simInput.setVariable( ...
    "vehicleParams", vehicleParams);

simInput = simInput.setVariable( ...
    "controllerParams", controllerParams);

simInput = simInput.setVariable( ...
    "simulationParams", simulationParams);

simInput = simInput.setVariable( ...
    "adaptiveModelParams", adaptiveModelParams);

simInput = simInput.setVariable( ...
    "track_ref_table", track_ref_table);

simInput = simInput.setVariable( ...
    "scenario_stop_table", scenario_stop_table);
simInput = simInput.setVariable( ...
    "final_track_index", ...
    final_track_index);
simInput = simInput.setVariable( ...
    "actuationDelay_s", ...
    actuationDelay_s);

simInput = simInput.setVariable("UT", UT);

simInput = simInput.setVariable( ...
    "acados_nominal_input", ...
    acados_nominal_input);

if controllerParams.controller_backend == ...
        controllerParams.BACKEND_ADAPTIVE

    simInput = simInput.setVariable( ...
        "mpc_adaptive", mpc_adaptive);
end

simInput = simInput.setModelParameter( ...
    StopTime=string(simulationParams.stop_time_s), ...
    ReturnWorkspaceOutputs="on", ...
    SignalInfNanChecking="error");

simInput = simInput.setVariable( ...
    "roadFrictionProfile", ...
    roadFrictionProfile);

%% Run simulation

simulationOutput = sim(simInput);

%% Validate logging

assert(isprop(simulationOutput, "logsout") || ...
    any(simulationOutput.who == "logsout"), ...
    "Simulation did not return logsout.");

logs = simulationOutput.logsout;

requiredSignals = [ ...
    "vx_meas"
    "vx_ref"
    "ax_meas"
    "x_pos"
    "y_pos"
    "torque_opt"
    "steering_angle_opt"
    "yaw_rate_meas"
    "ey_m"
    "epsi_rad"
    "solve_status"
    "solve_time"
    "road_friction_mu"
    ];

availableSignals = string(logs.getElementNames);

missingSignals = setdiff(requiredSignals, availableSignals);

assert(isempty(missingSignals), ...
    "Missing logged signals: %s", ...
    strjoin(missingSignals, ", "));

%% Extract results

solveTimeAvailable = ...
    controllerParams.controller_backend == ...
    controllerParams.BACKEND_ACADOS;

%for right now use results that is used in phase0. change later
results = extract_phase0_baseline_results( ...
    logs, ...
    solveTimeAvailable);

%% add reproducibility metadata
results.metadata.scenario_name = scenarioName;
results.metadata.matlab_version = string(version);
results.metadata.generated_at_utc = ...
    datetime("now", TimeZone="UTC");
results.metadata.controller_backend = ...
    controllerParams.controller_backend;
results.metadata.scenario_schema_version = ...
    config.scenario.schema_version;
results.metadata.environment_name = ...
    environmentName;
results.metadata.environment_schema_version = ...
    environment.schema_version;

results.metadata.environment_event_type = ...
    environment.event_type;

results.metadata.environment_event_time_s = ...
    environment.event_time_s;

%% Save deterministic deliverable

actuationDelay_s_str = "actuationDelay_s_" + string(actuationDelay_s) + "_ms";
projectRoot = string(matlab.project.currentProject().RootFolder);
resultsFolder = fullfile(projectRoot, "phase1", "results", ...
    controllerName(controllerParams), ...
    actuationDelay_s_str, ...
    scenarioName, ...
    environmentName ...
    );
figuresFolder = fullfile(projectRoot, "phase1", "figures", ...
    controllerName(controllerParams), ...
    actuationDelay_s_str, ...
    scenarioName, ...
    environmentName ...
    );

if ~isfolder(resultsFolder)
    mkdir(resultsFolder);
end

if ~isfolder(figuresFolder)
    mkdir(figuresFolder);
end

resultsFile = fullfile( ...
    resultsFolder, scenarioName + "_results.mat");

%use the plot same as phase0. if required change create new file
figureHandle = plot_phase0_results( ...
    results, config.scenario, environmentName);

% Generate tracking-error plots and metrics. same as phase0.
[errorFigureHandle, results.tracking_metrics] = ...
    plot_phase0_tracking_errors( ...
    results, ...
    config.scenario, ...
    environmentName, ...
    controllerParams);

figureFile = fullfile( ...
    figuresFolder, scenarioName + "_closed_loop_results.png");

print(figureHandle, figureFile, "-dpng", "-r200");
savefig( ...
    figureHandle, ...
    fullfile(figuresFolder, scenarioName + "_closed_loop_results.fig"));

%------------------
if solveTimeAvailable
    %solve time is same as phase0.
    [solveTimeFigureHandle, ...
        results.solve_time_metrics] = ...
        plot_phase0_solve_time( ...
        results, ...
        config.scenario, ...
        environmentName, ...
        simulationParams.Ts_s);
    
    %
    [solveTimeTelemetryFigureHandle, ...
        results.solve_time_tele_metrics] = ...
        plot_solve_time_telemetry( ...
        results, ...
        string(config.scenario.name), ...
        environmentName, ...
        simulationParams.Ts_s);

    solveTimeFigureFile = fullfile( ...
        figuresFolder, ...
        scenarioName + "_solve_time_histogram.png");

    print( ...
        solveTimeFigureHandle, ...
        solveTimeFigureFile, ...
        "-dpng", ...
        "-r200");

    savefig( ...
        solveTimeFigureHandle, ...
        fullfile( ...
        figuresFolder, ...
        scenarioName + "_solve_time_histogram.fig"));

    solveTimeTeleFigureFile = fullfile( ...
        figuresFolder, ...
        scenarioName + "_solve_time_telemetry.png");

    print( ...
        solveTimeTelemetryFigureHandle, ...
        solveTimeTeleFigureFile, ...
        "-dpng", ...
        "-r200");

    savefig( ...
        solveTimeTelemetryFigureHandle, ...
        fullfile( ...
        figuresFolder, ...
        scenarioName + "_solve_time_telemetry.fig"));

else

    results.solve_time_metrics = struct( ...
        "available", false);

    results.solve_time_tele_metrics = struct( ...
        "available", false);

end

%------------------
errorFigureFile = fullfile( ...
    figuresFolder, scenarioName + "_tracking_errors.png");

print(errorFigureHandle, errorFigureFile, "-dpng", "-r200");

savefig( ...
    errorFigureHandle, ...
    fullfile( ...
        figuresFolder, ...
        scenarioName + "_tracking_errors.fig"));

save(resultsFile, "results", "config");

end









function controller_name = controllerName(controllerParams)
% Return a readable controller name from controllerParams.controller_backend

switch controllerParams.controller_backend
    case controllerParams.BACKEND_ACADOS
        controller_name = "ACADOS_MPC";
    case controllerParams.BACKEND_MATLAB
        controller_name = "MATLAB_MPC";
    case controllerParams.BACKEND_ADAPTIVE
        controller_name = "ADAPTIVE_MPC";
    otherwise
        error( ...
            "Unknown controller backend ID: %d", ...
            controllerParams.controller_backend);
end
end
