startup_project;

projectRoot = string( ...
    matlab.project.currentProject().RootFolder);

outputFile = fullfile( ...
    projectRoot, ...
    "phase1", ...
    "results", ...
    "ACADOS_MPC", ...
    "solve_time_boxplot_ts_10ms.png");

resultFile = fullfile( ...
    projectRoot, ...
    "phase1", ...
    "results", ...
    "ACADOS_MPC", ...
    "actuation_delay_0_ms" ...
    );

[solveTimeFigure, solveTimeSummary] = sdv.plot.solve_time_box_plot( ...
    ResultsRoot = resultFile, ...
    Deadline_ms = 10, ...
    SaveFile = outputFile, ...
    ShowFigure = true);


disp(solveTimeSummary);