function [summaryTable, sweepFigure] = ...
    run_constant_delay_sweep(options)
%RUN_CONSTANT_DELAY_SWEEP Run Phase 1.1 constant-delay experiments.

arguments
    options.ScenarioNames (1,:) string = ...
        ["urban_profile", "aggressive_maneuver"]

    options.EnvironmentName (1,1) string = "dry_road"

    options.Delay_ms (1,:) double ...
        {mustBeNonnegative} = 0:5:100
end

startup_project;

configuration = build_phase0_configuration( ...
    options.ScenarioNames(1));

controllerName = sdv.config.controllerName( ...
    configuration.controller);

summaryTable = table();

for delay_ms = options.Delay_ms

    delay_s = delay_ms * 1e-3;

    for scenarioName = options.ScenarioNames

        fprintf( ...
            "\nScenario: %s, delay: %.1f ms\n", ...
            scenarioName, ...
            delay_ms);

        try
            [results, ~] = run_phase1_baseline( ...
                scenarioName, ...
                options.EnvironmentName, ...
                delay_s, ...
                SaveResults=true, ...
                SaveFigures=false, ...
                ShowFigures=false);

            newRow = sdv.metrics.createDelaySweepRow( ...
                scenarioName, ...
                options.EnvironmentName, ...
                delay_s, ...
                results);

        catch simulationError
            warning( ...
                "SDV:DelaySweepRunFailed", ...
                "Scenario %s failed at %.1f ms:\n%s", ...
                scenarioName, ...
                delay_ms, ...
                simulationError.message);

            newRow = sdv.metrics.createDelaySweepRow( ...
                scenarioName, ...
                options.EnvironmentName, ...
                delay_s, ...
                struct(), ...
                Completed=false, ...
                ErrorIdentifier=string( ...
                    simulationError.identifier), ...
                ErrorMessage=string( ...
                    simulationError.message));
        end

        if isempty(summaryTable)
            summaryTable = newRow;
        else
            summaryTable = [summaryTable; newRow];
        end

        summaryTable = sortrows( ...
            summaryTable, ...
            ["scenario_name", "delay_ms"]);

        % Checkpoint after every simulation.
        sdv.io.saveDelaySweepSummary( ...
            summaryTable, ...
            controllerName, ...
            options.EnvironmentName);
    end
end

sweepFigure = plotDelaySweepMetrics(summaryTable);

projectRoot = string( ...
    matlab.project.currentProject().RootFolder);

figureFolder = fullfile( ...
    projectRoot, ...
    "phase1", ...
    "figures", ...
    controllerName, ...
    "constant_delay_sweep", ...
    options.EnvironmentName);

sdv.io.exportFigure( ...
    sweepFigure, ...
    figureFolder, ...
    "constant_delay_metrics");

end

function figureHandle = plotDelaySweepMetrics(summaryTable)
%PLOTDELAYSWEEPMETRICS Plot per-run metrics against delay tau.

figureHandle = figure( ...
    Name="Phase 1.1 constant-delay sweep", ...
    Color="white");

layout = tiledlayout( ...
    figureHandle, ...
    2, ...
    2, ...
    TileSpacing="compact", ...
    Padding="compact");

scenarioNames = unique( ...
    summaryTable.scenario_name, ...
    "stable");

nexttile(layout);
plotMetric( ...
    summaryTable, scenarioNames, ...
    "lateral_rmse_m");
ylabel("Lateral RMSE (m)");
title("Lateral tracking RMS");
legend(Location="best");
grid on;

nexttile(layout);
plotMetric( ...
    summaryTable, scenarioNames, ...
    "lateral_peak_m");
ylabel("Peak |e_y| (m)");
title("Peak lateral error");
grid on;

nexttile(layout);
plotMetric( ...
    summaryTable, scenarioNames, ...
    "speed_rmse_mps");
ylabel("Speed RMSE (m/s)");
title("Longitudinal tracking RMS");
grid on;

nexttile(layout);
plotMetric( ...
    summaryTable, scenarioNames, ...
    "constraint_violation_samples");
ylabel("Violating samples");
title("Constraint-violation count");
grid on;

xlabel(layout, "Constant actuation delay, \tau (ms)");
title(layout, "Phase 1.1: Metrics versus Constant Delay");

end

function plotMetric(summaryTable, scenarioNames, variableName)

hold on;

for scenarioName = scenarioNames.'

    selectedRows = ...
        summaryTable.scenario_name == scenarioName;

    scenarioTable = sortrows( ...
        summaryTable(selectedRows,:), ...
        "delay_ms");

    plot( ...
        scenarioTable.delay_ms, ...
        scenarioTable.(variableName), ...
        "-o", ...
        LineWidth=1.4, ...
        MarkerSize=5, ...
        DisplayName=replace( ...
            scenarioName, "_", " "));
end

hold off;

end