%% Phase 1.3 trigger-generator validation

stopTime_s = 2;
nominalSampleTime_s = 0.010;
jitterBound_s = 0.005;
simulationStep_s = 0.0005;
randomSeed = 1;

[controllerTrigger, eventTable] = ...
    generate_sampling_jitter_trigger( ...
        stopTime_s, ...
        nominalSampleTime_s, ...
        jitterBound_s, ...
        simulationStep_s, ...
        randomSeed);

timeTolerance_s = ...
    20 * eps(max(1, stopTime_s));

%% Initial event

assert(eventTable.RequestedTime_s(1) == 0, ...
    "The first requested trigger must occur at t = 0.");
assert(eventTable.AppliedTime_s(1) == 0, ...
    "The first applied trigger must occur at t = 0.");
assert(isnan(eventTable.RequestedInterval_s(1)), ...
    "The initial event must not have a preceding interval.");
assert(isnan(eventTable.AppliedJitter_s(1)), ...
    "The initial event must not be assigned jitter.");

%% Event sequence

assert(all(diff(eventTable.RequestedTime_s) > 0), ...
    "Requested trigger times must be strictly increasing.");
assert(all(diff(eventTable.AppliedTime_s) > 0), ...
    "Applied trigger times must be strictly increasing.");

assert(all( ...
    abs(eventTable.RequestedJitter_s(2:end)) ...
    <= jitterBound_s + timeTolerance_s), ...
    "Requested jitter exceeded its configured bound.");

assert(all( ...
    abs(eventTable.QuantizationError_s) ...
    <= simulationStep_s/2 + timeTolerance_s), ...
    "Trigger quantization error exceeded half a simulation step.");

%% Trigger pulses

triggerData = controllerTrigger.Data(:);
numberOfRisingEdges = nnz(diff([0; triggerData]) == 1);

assert(numberOfRisingEdges == height(eventTable), ...
    "Rising-edge count does not match the event table.");

for eventNumber = 1:height(eventTable)
    eventIndex = round( ...
        eventTable.AppliedTime_s(eventNumber) ...
        / simulationStep_s) + 1;

    assert(all(triggerData(eventIndex:eventIndex+1) == 1), ...
        "Every trigger pulse must remain high for two steps.");
    assert(triggerData(eventIndex+2) == 0, ...
        "Every trigger pulse must return low after two steps.");
end

%% Zero-jitter schedule

[~, zeroJitterTable] = ...
    generate_sampling_jitter_trigger( ...
        stopTime_s, ...
        nominalSampleTime_s, ...
        0, ...
        simulationStep_s, ...
        randomSeed);

expectedPeriodicTimes_s = ...
    (0:nominalSampleTime_s:stopTime_s).';
expectedPeriodicTimes_s = ...
    expectedPeriodicTimes_s( ...
        expectedPeriodicTimes_s < stopTime_s);

assert( ...
    numel(expectedPeriodicTimes_s) == ...
    height(zeroJitterTable), ...
    "The zero-jitter event count is incorrect.");

assert(all( ...
    abs( ...
        zeroJitterTable.AppliedTime_s ...
        - expectedPeriodicTimes_s) ...
    <= timeTolerance_s), ...
    "J = 0 did not produce an exactly periodic schedule.");

%% Display

disp(eventTable(1:min(10,height(eventTable)),:));

figure(Name="Phase 1.3 trigger validation", Color="white");
stairs( ...
    controllerTrigger.Time, ...
    controllerTrigger.Data, ...
    LineWidth=1.2);

grid on;
xlim([0 0.1]);
xlabel("Time (s)");
ylabel("Trigger");
title("Script-Generated Controller Trigger");

fprintf( ...
    "Step 1 passed: %d events, including t = 0.\n", ...
    height(eventTable));
