function timingReport = ...
    validate_phase1_3_timing_configuration(simulationStep_s)
%VALIDATE_PHASE1_3_TIMING_CONFIGURATION Check Phase 1.3 timing setup.

arguments
    simulationStep_s (1,1) double ...
        {mustBePositive} = 0.0005
end

startup_project;

configuration = ...
    build_phase0_configuration("highway_cruise");

controllerSampleTime_s = ...
    configuration.controller.Ts_s;

assert(simulationStep_s < controllerSampleTime_s, ...
    "Simulation step must be smaller than the controller period.");

stepsPerNominalPeriod = ...
    controllerSampleTime_s / simulationStep_s;

integerTolerance = ...
    100 * eps(max(1, stepsPerNominalPeriod));

assert( ...
    abs( ...
        stepsPerNominalPeriod ...
        - round(stepsPerNominalPeriod)) ...
    <= integerTolerance, ...
    "The nominal controller period must be an integer multiple " + ...
    "of the fixed simulation step.");

modelNames = [ ...
    "phase1_baseline_sampling_jitter"
    "ControllerWrapperJitter"
    "PlantWrapper"
    "MPC_backend_main"
    ];

modelWasLoaded = false(size(modelNames));

for modelIndex = 1:numel(modelNames)
    modelWasLoaded(modelIndex) = ...
        bdIsLoaded(modelNames(modelIndex));
    load_system(modelNames(modelIndex));
end

cleanupModels = onCleanup(@() ...
    closeNewlyLoadedModels(modelNames, modelWasLoaded));

solverTypes = strings(size(modelNames));
fixedSteps = strings(size(modelNames));

for modelIndex = 1:numel(modelNames)
    solverTypes(modelIndex) = string(get_param( ...
        modelNames(modelIndex), "SolverType"));
    fixedSteps(modelIndex) = string(get_param( ...
        modelNames(modelIndex), "FixedStep"));
end

assert(all(solverTypes == "Fixed-step"), ...
    "Every active Phase 1.3 model must use a fixed-step solver.");

timingReport = table( ...
    modelNames, ...
    solverTypes, ...
    fixedSteps, ...
    VariableNames=[ ...
        "Model", ...
        "SolverType", ...
        "SavedFixedStep"]);

%% Verify the nominal acados prediction-model timing

acadosSettings = ...
    acados_ocp_parameters(configuration.controller);

timeTolerance_s = ...
    100 * eps(max(1, controllerSampleTime_s));

assert( ...
    abs( ...
        acadosSettings.sample_time_s ...
        - controllerSampleTime_s) ...
    <= timeTolerance_s, ...
    "acados prediction-model sample time differs from controller Ts.");

%% Verify inherited timing in the generated acados S-function

projectRoot = string( ...
    matlab.project.currentProject().RootFolder);

sFunctionSource = fullfile( ...
    projectRoot, ...
    "build", ...
    "acados", ...
    "sdv_dynamic_bicycle", ...
    "acados_solver_sfunction_sdv_dynamic_bicycle.c");

assert(isfile(sFunctionSource), ...
    "Generated acados S-function source was not found: %s", ...
    sFunctionSource);

sourceText = string(fileread(sFunctionSource));

assert(contains(sourceText, "#define SAMPLINGTIME -1"), ...
    "Generated acados S-function must inherit its sample time.");

assert(contains( ...
        sourceText, ...
        "USE_DEFAULT_FOR_DISCRETE_INHERITANCE"), ...
    "Generated acados S-function is missing its model-reference " + ...
    "sample-time inheritance rule.");

fprintf("\nPhase 1.3 timing validation passed.\n");
fprintf( ...
    "Simulation step:             %.4f ms\n", ...
    1e3 * simulationStep_s);
fprintf( ...
    "Nominal controller period:   %.4f ms\n", ...
    1e3 * controllerSampleTime_s);
fprintf( ...
    "Steps per nominal period:    %d\n", ...
    round(stepsPerNominalPeriod));
fprintf( ...
    "acados prediction period:    %.4f ms\n", ...
    1e3 * acadosSettings.sample_time_s);

disp(timingReport);

% Keep the cleanup object alive until function exit.
clear cleanupModels;

end

function closeNewlyLoadedModels(modelNames, modelWasLoaded)
%CLOSENEWLYLOADEDMODELS Restore the caller's loaded-model state.

for modelIndex = numel(modelNames):-1:1
    if ~modelWasLoaded(modelIndex) && ...
            bdIsLoaded(modelNames(modelIndex))
        close_system(modelNames(modelIndex), 0);
    end
end

end
