function [results, config] = ...
    validate_sampling_jitter_five_ms_case( ...
        scenarioName, environmentName, randomSeed, simulationStep_s)
%VALIDATE_SAMPLING_JITTER_FIVE_MS_CASE Run the Step 10 smoke test.

arguments
    scenarioName (1,1) string = "highway_cruise"
    environmentName (1,1) string = "dry_road"
    randomSeed (1,1) double ...
        {mustBeInteger, mustBeNonnegative} = 1
    simulationStep_s (1,1) double ...
        {mustBePositive} = 0.0005
end

[results, config] = run_sampling_jitter_case( ...
    scenarioName, environmentName, 5, randomSeed, simulationStep_s, ...
    SaveResults=false, ...
    SaveFigures=false, ...
    ShowFigures=false);

assert(results.jitter_validation.passed, ...
    "The J = 5 ms Phase 1.3 smoke test failed.");

fprintf("Step 10 passed: J = 5 ms single-case validation succeeded.\n");

end
