function figures = ...
    plot_phase3_comparison( ...
        comparisonTable, ...
        options)

arguments
    comparisonTable table
    options.SaveFigures (1,1) logical = true
end

completed = comparisonTable( ...
    comparisonTable.Status == "completed", :);

assert( ...
    ~isempty(completed), ...
    "No completed Phase 3 cases are available.");

scenarioNames = unique( ...
    completed.Scenario, ...
    "stable");

figures = gobjects( ...
    numel(scenarioNames), ...
    1);

for scenarioIndex = 1:numel(scenarioNames)

    scenarioName = ...
        scenarioNames(scenarioIndex);

    scenarioRows = completed( ...
        completed.Scenario == scenarioName, :);

    figures(scenarioIndex) = figure( ...
        Name="Phase 3 comparison — " + scenarioName, ...
        Color="white", ...
        Position=[70 50 1400 820]);

    layout = tiledlayout( ...
        figures(scenarioIndex), ...
        2, ...
        3, ...
        TileSpacing="compact", ...
        Padding="compact");

    plotMetric( ...
        nexttile(layout), ...
        scenarioRows, ...
        "ControlCpuUtilization_pct", ...
        "Control CPU demand (%)");

    plotMetric( ...
        nexttile(layout), ...
        scenarioRows, ...
        "LoadP95Response_ms", ...
        "LoadTask P95 response (ms)");

    plotMetric( ...
        nexttile(layout), ...
        scenarioRows, ...
        "LoadDeadlineMissPercent", ...
        "LoadTask deadline misses (%)");

    plotMetric( ...
        nexttile(layout), ...
        scenarioRows, ...
        "SpeedRMS_mps", ...
        "Speed RMS error (m/s)");

    plotMetric( ...
        nexttile(layout), ...
        scenarioRows, ...
        "LateralRMS_m", ...
        "Lateral RMS error (m)");

    plotMetric( ...
        nexttile(layout), ...
        scenarioRows, ...
        "HeadingRMS_deg", ...
        "Heading RMS error (deg)");

    title( ...
        layout, ...
        "Fixed-Rate versus Variable-Rate Control — " ...
        + cleanLabel(scenarioName));

    if options.SaveFigures

        projectRoot = string( ...
            matlab.project.currentProject().RootFolder);

        figureFolder = fullfile( ...
            projectRoot, ...
            "phase3", ...
            "figures", ...
            "comparison");

        if ~isfolder(figureFolder)
            mkdir(figureFolder);
        end

        exportgraphics( ...
            figures(scenarioIndex), ...
            fullfile( ...
                figureFolder, ...
                scenarioName + "_comparison.png"), ...
            Resolution=200);
    end
end

end


function plotMetric( ...
    axisHandle, ...
    tableData, ...
    variableName, ...
    yLabel)

environmentNames = unique( ...
    tableData.Environment, ...
    "stable");

policyNames = unique( ...
    tableData.Policy, ...
    "stable");

colors = lines(numel(environmentNames));

hold(axisHandle, "on");

for environmentIndex = 1:numel(environmentNames)

    for policyIndex = 1:numel(policyNames)

        environmentName = ...
            environmentNames(environmentIndex);

        policyName = ...
            policyNames(policyIndex);

        rows = tableData( ...
            tableData.Environment == environmentName ...
            & tableData.Policy == policyName, :);

        rows = sortrows( ...
            rows, ...
            "LoadExecution_ms");

        if isempty(rows)
            continue;
        end

        if policyName == "variable_rate"
            lineStyle = "-";
            marker = "o";
        else
            lineStyle = "--";
            marker = "s";
        end

        plot( ...
            axisHandle, ...
            rows.LoadExecution_ms, ...
            rows.(variableName), ...
            LineStyle=lineStyle, ...
            Marker=marker, ...
            Color=colors(environmentIndex,:), ...
            LineWidth=1.4, ...
            MarkerSize=6, ...
            DisplayName= ...
                cleanLabel(environmentName) ...
                + " | " ...
                + cleanLabel(policyName));
    end
end

hold(axisHandle, "off");

grid(axisHandle, "on");
xlabel(axisHandle, "LoadTask execution time (ms)");
ylabel(axisHandle, yLabel);
legend(axisHandle, Location="best");

end


function label = cleanLabel(value)

label = replace(string(value), "_", " ");

end