function figureHandle = ...
    plot_phase3_scenario_tags( ...
        taggedScenario, ...
        options)
%PLOT_PHASE3_SCENARIO_TAGS
% Visualize the Phase 3 offline demand tags for one scenario.

arguments
    taggedScenario (1,1) struct
    options.ExportFolder (1,1) string = ""
    options.Visible (1,1) logical = true
end

tagTable = taggedScenario.demand_table;
parameters = taggedScenario.parameters;

scenarioName = string( ...
    taggedScenario.scenario_name);

%% Validate required columns

requiredVariables = [
    "time_s"
    "xReference_m"
    "yReference_m"
    "curvatureReference_1pm"
    "speedReference_mps"
    "previewKappa_1pm"
    "previewDeltaSpeed_mps"
    "rawMode"
    "dwellMode"
    "sampleTime_s"
    ];

availableVariables = string( ...
    tagTable.Properties.VariableNames);

missingVariables = setdiff( ...
    requiredVariables, ...
    availableVariables);

assert(isempty(missingVariables), ...
    "Missing demand-table variables: %s", ...
    strjoin(missingVariables, ", "));

%% Extract data

time_s = tagTable.time_s;

xReference_m = tagTable.xReference_m;
yReference_m = tagTable.yReference_m;

curvature_1pm = ...
    tagTable.curvatureReference_1pm;

speedReference_mps = ...
    tagTable.speedReference_mps;

previewCurvature_1pm = ...
    tagTable.previewKappa_1pm;

previewSpeedChange_mps = ...
    tagTable.previewDeltaSpeed_mps;

rawMode = double(tagTable.rawMode);
dwellMode = double(tagTable.dwellMode);

sampleTime_ms = ...
    1e3 * tagTable.sampleTime_s;

%% Mode colors

modeColors = [
    0.00 0.45 0.74   % LOW: deep blue
    0.95 0.60 0.05   % MEDIUM: amber
    0.80 0.10 0.20   % HIGH: crimson
    ];

%% Create figure

visibility = "on";

if ~options.Visible
    visibility = "off";
end

figureHandle = figure( ...
    Name="Phase 3 demand tags: " + scenarioName, ...
    Color="w", ...
    Visible=visibility);

layout = tiledlayout( ...
    figureHandle, ...
    2, ...
    2, ...
    TileSpacing="compact", ...
    Padding="compact");

title( ...
    layout, ...
    "Phase 3 Offline Demand Tags: " ...
    + replace(scenarioName, "_", " "));

%% 1. Reference trajectory colored by mode

trajectoryAxes = nexttile(layout, 1);

plot( ...
    trajectoryAxes, ...
    xReference_m, ...
    yReference_m, ...
    "-", ...
    Color=[0.75 0.75 0.75], ...
    LineWidth=1.0, ...
    DisplayName="Reference path");

hold(trajectoryAxes, "on");

scatter( ...
    trajectoryAxes, ...
    xReference_m, ...
    yReference_m, ...
    18, ...
    dwellMode, ...
    "filled", ...
    DisplayName="Demand tag");

plot( ...
    trajectoryAxes, ...
    xReference_m(1), ...
    yReference_m(1), ...
    "ko", ...
    MarkerFaceColor="g", ...
    MarkerSize=7, ...
    DisplayName="Start");

plot( ...
    trajectoryAxes, ...
    xReference_m(end), ...
    yReference_m(end), ...
    "ko", ...
    MarkerFaceColor="r", ...
    MarkerSize=7, ...
    DisplayName="End");

hold(trajectoryAxes, "off");

axis(trajectoryAxes, "equal");
grid(trajectoryAxes, "on");

xlabel(trajectoryAxes, "X position (m)");
ylabel(trajectoryAxes, "Y position (m)");
title(trajectoryAxes, "Reference Trajectory and Demand Mode");

colormap(trajectoryAxes, modeColors);
clim(trajectoryAxes, [0.5 3.5]);

colorScale = colorbar(trajectoryAxes);
colorScale.Ticks = [1 2 3];
colorScale.TickLabels = [
    "LOW — 50 ms"
    "MEDIUM — 20 ms"
    "HIGH — 10 ms"
    ];

%% 2. Curvature tagging feature

curvatureAxes = nexttile(layout, 2);

plot( ...
    curvatureAxes, ...
    time_s, ...
    abs(curvature_1pm), ...
    Color=[0.55 0.55 0.55], ...
    LineWidth=1.0, ...
    DisplayName="|\kappa_{ref}|");

hold(curvatureAxes, "on");

plot( ...
    curvatureAxes, ...
    time_s, ...
    previewCurvature_1pm, ...
    "b-", ...
    LineWidth=1.4, ...
    DisplayName="Preview maximum");

yline( ...
    curvatureAxes, ...
    parameters.kappa_low_1pm, ...
    "--", ...
    Color=modeColors(2,:), ...
    LineWidth=1.3, ...
    DisplayName="\kappa_{low}");

yline( ...
    curvatureAxes, ...
    parameters.kappa_high_1pm, ...
    "--", ...
    Color=modeColors(3,:), ...
    LineWidth=1.3, ...
    DisplayName="\kappa_{high}");

hold(curvatureAxes, "off");

grid(curvatureAxes, "on");

xlabel(curvatureAxes, "Reference time (s)");
ylabel(curvatureAxes, "Curvature magnitude (1/m)");
title(curvatureAxes, "Curvature Demand Feature");
legend(curvatureAxes, Location="best");

%% 3. Speed-change tagging feature

speedAxes = nexttile(layout, 3);

yyaxis(speedAxes, "left");

plot( ...
    speedAxes, ...
    time_s, ...
    speedReference_mps, ...
    "b-", ...
    LineWidth=1.3, ...
    DisplayName="Reference speed");

ylabel(speedAxes, "Reference speed (m/s)");

yyaxis(speedAxes, "right");

plot( ...
    speedAxes, ...
    time_s, ...
    previewSpeedChange_mps, ...
    Color=[0.45 0.15 0.75], ...
    LineWidth=1.3, ...
    DisplayName="Preview \Deltav");

hold(speedAxes, "on");

yline( ...
    speedAxes, ...
    parameters.delta_speed_low_mps, ...
    "--", ...
    Color=modeColors(2,:), ...
    LineWidth=1.3, ...
    DisplayName="\Deltav_{low}");

yline( ...
    speedAxes, ...
    parameters.delta_speed_high_mps, ...
    "--", ...
    Color=modeColors(3,:), ...
    LineWidth=1.3, ...
    DisplayName="\Deltav_{high}");

hold(speedAxes, "off");

ylabel(speedAxes, "Preview speed change (m/s)");
xlabel(speedAxes, "Reference time (s)");
title(speedAxes, "Speed-Change Demand Feature");

grid(speedAxes, "on");
legend(speedAxes, Location="best");

%% 4. Raw tag, dwell-filtered tag and selected period

modeAxes = nexttile(layout, 4);

yyaxis(modeAxes, "left");

stairs( ...
    modeAxes, ...
    time_s, ...
    rawMode, ...
    "--", ...
    Color=[0.55 0.55 0.55], ...
    LineWidth=1.0, ...
    DisplayName="Raw mode");

hold(modeAxes, "on");

stairs( ...
    modeAxes, ...
    time_s, ...
    dwellMode, ...
    "k-", ...
    LineWidth=1.6, ...
    DisplayName="Dwell-filtered mode");

hold(modeAxes, "off");

ylim(modeAxes, [0.5 3.5]);
yticks(modeAxes, [1 2 3]);
yticklabels(modeAxes, ["LOW", "MEDIUM", "HIGH"]);

ylabel(modeAxes, "Demand mode");

yyaxis(modeAxes, "right");

stairs( ...
    modeAxes, ...
    time_s, ...
    sampleTime_ms, ...
    Color=[0.10 0.45 0.85], ...
    LineWidth=1.2, ...
    DisplayName="Controller period");

ylim(modeAxes, [0 55]);

ylabel(modeAxes, "Selected period (ms)");
xlabel(modeAxes, "Reference time (s)");
title(modeAxes, "Demand Mode and Controller Period");

grid(modeAxes, "on");
legend(modeAxes, Location="best");

%% Enforce white axes

allAxes = findall( ...
    figureHandle, ...
    Type="axes");

set( ...
    allAxes, ...
    Color="w", ...
    XColor="k", ...
    YColor="k");

%% Optional export

if strlength(options.ExportFolder) > 0

    if ~isfolder(options.ExportFolder)
        mkdir(options.ExportFolder);
    end

    fileBase = ...
        scenarioName + "_phase3_demand_tags";

    exportgraphics( ...
        figureHandle, ...
        fullfile( ...
            options.ExportFolder, ...
            fileBase + ".png"), ...
        Resolution=300);

    savefig( ...
        figureHandle, ...
        fullfile( ...
            options.ExportFolder, ...
            fileBase + ".fig"));
end

end