function [figureHandle, metrics] = plot_phase3_demo( ...
    fixedSource, ...
    supervisorSource, ...
    options)
%PLOT_PHASE3_DEMO Phase 3 fixed-rate versus naive-supervisor demo.
%
% Panels:
%   1. X and Y path references with supervisor Ts-mode bands
%   2. Observed CPU utilization for both runs
%   3. Lateral and heading errors for both runs

arguments
    fixedSource
    supervisorSource

    options.TrackingMetric (1,1) string ...
        {mustBeMember(options.TrackingMetric, ...
        ["lateral", "heading"])} = "lateral"

    options.TimeWindow_s (1,2) double = [NaN, NaN]

    options.FixedLabel (1,1) string = "Fixed 10 ms"
    options.SupervisorLabel (1,1) string = "Naive supervisor"
    options.Title (1,1) string = "Phase 3 Demo Experiment"

    options.FixedColor (1,3) double = [0.00, 0.45, 0.74]
    options.SupervisorColor (1,3) double = [0.85, 0.33, 0.10]

    options.LineWidth (1,1) double {mustBePositive} = 1.5
    options.Visible (1,1) logical = true

    options.ReferenceXColumn (1,1) double = 2
    options.ReferenceYColumn (1,1) double = 3

    options.SaveFile (1,1) string = ""
    options.ExportResolution (1,1) double = 300
end

fixedArtifact = loadRunArtifact(fixedSource);
supervisorArtifact = loadRunArtifact(supervisorSource);

validateArtifact(fixedArtifact, "fixed run");
validateArtifact(supervisorArtifact, "supervisor run");

%% Common time window

fixedTime = double(fixedArtifact.results.time_s(:));
supervisorTime = double(supervisorArtifact.results.time_s(:));

timeWindow = [
    max(fixedTime(1), supervisorTime(1)), ...
    min(fixedTime(end), supervisorTime(end))
    ];

if all(isfinite(options.TimeWindow_s))
    timeWindow(1) = max(timeWindow(1), options.TimeWindow_s(1));
    timeWindow(2) = min(timeWindow(2), options.TimeWindow_s(2));
elseif any(isfinite(options.TimeWindow_s))
    error( ...
        "SDV:InvalidTimeWindow", ...
        "TimeWindow_s must be [NaN NaN] or two finite values.");
end

assert( ...
    timeWindow(2) > timeWindow(1), ...
    "The two runs do not share a valid time window.");

%% Time-aligned reference path

[referenceTime, referenceX, referenceY] = ...
    timeAlignedPathReference( ...
        supervisorArtifact, ...
        timeWindow, ...
        options.ReferenceXColumn, ...
        options.ReferenceYColumn);

%% Observed CPU utilization

[fixedCpuTime, fixedCpu] = ...
    observedCpuTrace(fixedArtifact, timeWindow);

[supervisorCpuTime, supervisorCpu] = ...
    observedCpuTrace(supervisorArtifact, timeWindow);

fixedMeanUtilization = finiteMean(fixedCpu);
supervisorMeanUtilization = finiteMean(supervisorCpu);

utilizationReduction = relativeChange( ...
    fixedMeanUtilization, ...
    supervisorMeanUtilization, ...
    "reduction");

%% Lateral error

[fixedLateralTime, fixedLateralError] = windowSignal( ...
    fixedArtifact.results.time_s, ...
    fixedArtifact.results.ey_m, ...
    timeWindow);

[supervisorLateralTime, supervisorLateralError] = ...
    windowSignal( ...
        supervisorArtifact.results.time_s, ...
        supervisorArtifact.results.ey_m, ...
        timeWindow);

fixedLateralRms = finiteRms(fixedLateralError);
supervisorLateralRms = finiteRms(supervisorLateralError);

lateralRmsDegradation = relativeChange( ...
    fixedLateralRms, ...
    supervisorLateralRms, ...
    "increase");

%% Heading error

[fixedHeadingTime, fixedHeadingError] = windowSignal( ...
    fixedArtifact.results.time_s, ...
    rad2deg(fixedArtifact.results.epsi_rad), ...
    timeWindow);

[supervisorHeadingTime, supervisorHeadingError] = ...
    windowSignal( ...
        supervisorArtifact.results.time_s, ...
        rad2deg(supervisorArtifact.results.epsi_rad), ...
        timeWindow);

fixedHeadingRms = finiteRms(fixedHeadingError);
supervisorHeadingRms = finiteRms(supervisorHeadingError);

headingRmsDegradation = relativeChange( ...
    fixedHeadingRms, ...
    supervisorHeadingRms, ...
    "increase");

%% Select the headline tracking metric

switch options.TrackingMetric
    case "lateral"
        headlineTrackingName = "Lateral-error";
        headlineTrackingDegradation = lateralRmsDegradation;

    case "heading"
        headlineTrackingName = "Heading-error";
        headlineTrackingDegradation = headingRmsDegradation;
end

%% Summary table

metrics = table( ...
    fixedMeanUtilization, ...
    supervisorMeanUtilization, ...
    utilizationReduction, ...
    fixedLateralRms, ...
    supervisorLateralRms, ...
    lateralRmsDegradation, ...
    fixedHeadingRms, ...
    supervisorHeadingRms, ...
    headingRmsDegradation, ...
    VariableNames =[ ...
        "FixedMeanCpuUtilization_pct", ...
        "SupervisorMeanCpuUtilization_pct", ...
        "AverageUtilizationReduction_pct", ...
        "FixedLateralRms_m", ...
        "SupervisorLateralRms_m", ...
        "LateralRmsDegradation_pct", ...
        "FixedHeadingRms_deg", ...
        "SupervisorHeadingRms_deg", ...
        "HeadingRmsDegradation_pct" ...
        ]);

headline = sprintf( ...
    "Average utilization reduction: %.1f%% | " + ...
    "%s RMS degradation: %.1f%%", ...
    utilizationReduction, ...
    headlineTrackingName, ...
    headlineTrackingDegradation);

%% Create figure

if options.Visible
    figureVisibility = "on";
else
    figureVisibility = "off";
end

figureHandle = figure( ...
    Name=options.Title, ...
    Color="white", ...
    Visible=figureVisibility);

layout = tiledlayout( ...
    figureHandle, ...
    3, ...
    1, ...
    TileSpacing="compact", ...
    Padding="compact");

title( ...
    layout, ...
    sprintf("%s\n%s", options.Title, headline), ...
    Interpreter="none", ...
    FontWeight="bold");

%% Panel 1: X/Y path reference and Ts mode

pathAxes = nexttile(layout);
hold(pathAxes, "on");

yyaxis(pathAxes, "left");

xReferenceLine = plot( ...
    pathAxes, ...
    referenceTime, ...
    referenceX, ...
    Color=[0.10, 0.10, 0.10], ...
    LineStyle="-.", ...
    LineWidth=1.7, ...
    DisplayName="X reference");

ylabel(pathAxes, "X reference (m)");

yyaxis(pathAxes, "right");

yReferenceLine = plot( ...
    pathAxes, ...
    referenceTime, ...
    referenceY, ...
    Color=[0.30, 0.30, 0.30], ...
    LineStyle="--", ...
    LineWidth=1.7, ...
    DisplayName="Y reference");

ylabel(pathAxes, "Y reference (m)");

yyaxis(pathAxes, "left");

drawModeBands( ...
    pathAxes, ...
    supervisorArtifact.mode, ...
    timeWindow);

title( ...
    pathAxes, ...
    "Reference Path and Supervisor Sampling Mode " + ...
    "(blue: 50 ms, amber: 20 ms, red: 10 ms)");

grid(pathAxes, "on");
box(pathAxes, "on");
xlim(pathAxes, timeWindow);

legend( ...
    pathAxes, ...
    [xReferenceLine, yReferenceLine], ...
    Location="best", ...
    Interpreter="none");

%% Panel 2: lateral and heading errors

errorAxes = nexttile(layout);
hold(errorAxes, "on");

yyaxis(errorAxes, "left");

fixedLateralLine = plot( ...
    errorAxes, ...
    fixedLateralTime, ...
    fixedLateralError, ...
    Color=options.FixedColor, ...
    LineStyle="-", ...
    LineWidth=options.LineWidth, ...
    DisplayName=options.FixedLabel + " lateral");

supervisorLateralLine = plot( ...
    errorAxes, ...
    supervisorLateralTime, ...
    supervisorLateralError, ...
    Color=options.SupervisorColor, ...
    LineStyle="-", ...
    LineWidth=options.LineWidth, ...
    DisplayName=options.SupervisorLabel + " lateral");

ylabel(errorAxes, "Lateral error, e_y (m)");

yyaxis(errorAxes, "right");

fixedHeadingLine = plot( ...
    errorAxes, ...
    fixedHeadingTime, ...
    fixedHeadingError, ...
    Color=options.FixedColor, ...
    LineStyle="--", ...
    LineWidth=options.LineWidth, ...
    DisplayName=options.FixedLabel + " heading");

supervisorHeadingLine = plot( ...
    errorAxes, ...
    supervisorHeadingTime, ...
    supervisorHeadingError, ...
    Color=options.SupervisorColor, ...
    LineStyle="--", ...
    LineWidth=options.LineWidth, ...
    DisplayName=options.SupervisorLabel + " heading");

ylabel(errorAxes, "Heading error, e_\psi (deg)");
xlabel(errorAxes, "Time (s)");

title( ...
    errorAxes, ...
    sprintf( ...
    "Lateral RMS: %.4g / %.4g m | " + ...
    "Heading RMS: %.4g / %.4g deg " + ...
    "(Fixed/Supervisor)", ...
    fixedLateralRms, ...
    supervisorLateralRms, ...
    fixedHeadingRms, ...
    supervisorHeadingRms));

grid(errorAxes, "on");
box(errorAxes, "on");
xlim(errorAxes, timeWindow);

legend( ...
    errorAxes, ...
    [ ...
    fixedLateralLine, ...
    supervisorLateralLine, ...
    fixedHeadingLine, ...
    supervisorHeadingLine], ...
    Location="best", ...
    NumColumns=2, ...
    Interpreter="none");

%% Panel 3: observed CPU utilization

cpuAxes = nexttile(layout);
hold(cpuAxes, "on");

stairs( ...
    cpuAxes, ...
    fixedCpuTime, ...
    fixedCpu, ...
    Color=options.FixedColor, ...
    LineWidth=options.LineWidth, ...
    DisplayName=options.FixedLabel);

stairs( ...
    cpuAxes, ...
    supervisorCpuTime, ...
    supervisorCpu, ...
    Color=options.SupervisorColor, ...
    LineWidth=options.LineWidth, ...
    DisplayName=options.SupervisorLabel);

yline( ...
    cpuAxes, ...
    100, ...
    "k:", ...
    LineWidth=1.2, ...
    HandleVisibility="off");

ylabel(cpuAxes, "Observed CPU utilization (%)");

title( ...
    cpuAxes, ...
    sprintf( ...
        "CPU Utilization: Fixed %.1f%%, Supervisor %.1f%%", ...
        fixedMeanUtilization, ...
        supervisorMeanUtilization));

grid(cpuAxes, "on");
box(cpuAxes, "on");
xlim(cpuAxes, timeWindow);
legend(cpuAxes, Location="best", Interpreter="none");

linkaxes([pathAxes, cpuAxes, errorAxes], "x");

%% Export

if strlength(options.SaveFile) > 0
    outputFolder = string(fileparts(options.SaveFile));

    if strlength(outputFolder) > 0 && ~isfolder(outputFolder)
        mkdir(outputFolder);
    end

    exportgraphics( ...
        figureHandle, ...
        options.SaveFile, ...
        Resolution=options.ExportResolution);
end

disp(metrics);

end


function artifact = loadRunArtifact(source)

if ischar(source) || (isstring(source) && isscalar(source))
    sourceFile = string(source);

    assert(isfile(sourceFile), ...
        "Run-artifact file does not exist: %s", sourceFile);

    loadedData = load(sourceFile);

    assert(isfield(loadedData, "runArtifact"), ...
        "File does not contain runArtifact: %s", sourceFile);

    artifact = loadedData.runArtifact;

elseif isstruct(source) && isfield(source, "runArtifact")
    artifact = source.runArtifact;

elseif isstruct(source) && isfield(source, "results")
    artifact = source;

else
    error( ...
        "SDV:InvalidRunArtifact", ...
        "Input must be a runArtifact or MAT-file path.");
end

end


function validateArtifact(artifact, runName)

requiredArtifactFields = [
    "results"
    "reference"
    "mode"
    "controlJobs"
    "observedCpuUtilization"
    ];

assert( ...
    all(isfield(artifact, requiredArtifactFields)), ...
    "%s artifact is missing required fields.", ...
    runName);

requiredResultFields = [
    "time_s"
    "x_pos_m"
    "y_pos_m"
    "ey_m"
    "epsi_rad"
    ];

assert( ...
    all(isfield(artifact.results, requiredResultFields)), ...
    "%s results are missing required signals.", ...
    runName);

end


function [time, referenceX, referenceY] = ...
    timeAlignedPathReference( ...
        artifact, ...
        timeWindow, ...
        xColumn, ...
        yColumn)

results = artifact.results;

rawTime = double(results.time_s(:));
actualX = double(results.x_pos_m(:));
actualY = double(results.y_pos_m(:));

numberOfSamples = min( ...
    [numel(rawTime), numel(actualX), numel(actualY)]);

rawTime = rawTime(1:numberOfSamples);
actualX = actualX(1:numberOfSamples);
actualY = actualY(1:numberOfSamples);

valid = ...
    isfinite(rawTime) & ...
    isfinite(actualX) & ...
    isfinite(actualY) & ...
    rawTime >= timeWindow(1) & ...
    rawTime <= timeWindow(2);

time = rawTime(valid);
actualX = actualX(valid);
actualY = actualY(valid);

% Use explicitly logged reference coordinates when available.
if isfield(results, "x_ref_m") && isfield(results, "y_ref_m")
    rawReferenceX = double(results.x_ref_m(:));
    rawReferenceY = double(results.y_ref_m(:));

    rawReferenceX = rawReferenceX(1:numberOfSamples);
    rawReferenceY = rawReferenceY(1:numberOfSamples);

    referenceX = rawReferenceX(valid);
    referenceY = rawReferenceY(valid);
    return;
end

% Otherwise obtain the closest path-reference point for every sample.
referenceTable = artifact.reference;

if istable(referenceTable)
    referenceTable = table2array(referenceTable);
end

referenceTable = double(referenceTable);

assert( ...
    size(referenceTable, 2) >= max(xColumn, yColumn), ...
    "Reference table does not contain the configured X/Y columns.");

pathX = referenceTable(:, xColumn);
pathY = referenceTable(:, yColumn);

validReference = isfinite(pathX) & isfinite(pathY);
pathX = pathX(validReference);
pathY = pathY(validReference);

referenceX = zeros(size(time));
referenceY = zeros(size(time));

for sampleIndex = 1:numel(time)
    distanceSquared = ...
        (pathX - actualX(sampleIndex)).^2 + ...
        (pathY - actualY(sampleIndex)).^2;

    [~, nearestIndex] = min(distanceSquared);

    referenceX(sampleIndex) = pathX(nearestIndex);
    referenceY(sampleIndex) = pathY(nearestIndex);
end

end


function [time, utilization] = ...
    observedCpuTrace(artifact, timeWindow)

jobs = artifact.controlJobs;

assert( ...
    all(ismember( ...
    ["ReleaseTime_s", "ObservedCpuUtilization"], ...
    string(jobs.Properties.VariableNames))), ...
    "controlJobs must contain ReleaseTime_s and " + ...
    "ObservedCpuUtilization.");

time = double(jobs.ReleaseTime_s(:));

controlUtilization = ...
    100 * double(jobs.ObservedCpuUtilization(:));

observedSummary = artifact.observedCpuUtilization;

nonControlUtilization = ...
    double(observedSummary.Total_pct) - ...
    double(observedSummary.Control_pct);

utilization = ...
    controlUtilization + nonControlUtilization;

valid = ...
    isfinite(time) & ...
    isfinite(utilization) & ...
    time >= timeWindow(1) & ...
    time <= timeWindow(2);

time = time(valid);
utilization = utilization(valid);

[time, order] = sort(time);
utilization = utilization(order);

end


function drawModeBands(axesHandle, modeSignal, timeWindow)

if ~isstruct(modeSignal) || ...
        ~all(isfield(modeSignal, ["Time_s", "Data"]))
    return;
end

modeTime = double(modeSignal.Time_s(:));
modeData = round(double(modeSignal.Data(:)));

valid = isfinite(modeTime) & isfinite(modeData);
modeTime = modeTime(valid);
modeData = modeData(valid);

if isempty(modeTime)
    return;
end

[modeTime, uniqueIndices] = unique(modeTime, "last");
modeData = modeData(uniqueIndices);

changeTimes = modeTime([true; diff(modeData) ~= 0]);

boundaries = [
    timeWindow(1)
    changeTimes( ...
        changeTimes > timeWindow(1) & ...
        changeTimes < timeWindow(2))
    timeWindow(2)
    ];

modeColors = [
    0.18, 0.19, 0.23   % Low demand:    Ts = 50 ms
    0.95, 0.55, 0.00   % Medium demand: Ts = 20 ms
    0.78, 0.08, 0.10   % High demand:   Ts = 10 ms
    ];

yLimits = ylim(axesHandle);
bandHandles = gobjects(0);

for intervalIndex = 1:(numel(boundaries) - 1)
    startTime = boundaries(intervalIndex);
    endTime = boundaries(intervalIndex + 1);

    activeMode = interp1( ...
        modeTime, ...
        modeData, ...
        startTime, ...
        "previous", ...
        "extrap");

    activeMode = min(max(round(activeMode), 1), 3);

    bandHandles(end + 1) = patch( ... %#ok<AGROW>
        axesHandle, ...
        [startTime, endTime, endTime, startTime], ...
        [yLimits(1), yLimits(1), yLimits(2), yLimits(2)], ...
        modeColors(activeMode, :), ...
        FaceAlpha=0.20, ...
        EdgeColor="none", ...
        HandleVisibility="off");
end

% Do not call uistack here. With yyaxis, the left- and right-axis graphics
% share an Axes object but use different rulers, and uistack can fail while
% trying to reorder that mixed child list. The low FaceAlpha keeps the
% bands readable without obscuring the reference traces.

end


function [time, data] = windowSignal( ...
    rawTime, ...
    rawData, ...
    timeWindow)

rawTime = double(rawTime(:));
rawData = double(rawData(:));

numberOfSamples = min(numel(rawTime), numel(rawData));

rawTime = rawTime(1:numberOfSamples);
rawData = rawData(1:numberOfSamples);

valid = ...
    isfinite(rawTime) & ...
    isfinite(rawData) & ...
    rawTime >= timeWindow(1) & ...
    rawTime <= timeWindow(2);

time = rawTime(valid);
data = rawData(valid);

end


function value = finiteMean(data)

data = double(data(:));
data = data(isfinite(data));

if isempty(data)
    value = NaN;
else
    value = mean(data);
end

end


function value = finiteRms(data)

data = double(data(:));
data = data(isfinite(data));

if isempty(data)
    value = NaN;
else
    value = sqrt(mean(data.^2));
end

end


function percentage = relativeChange( ...
    referenceValue, ...
    newValue, ...
    calculationType)

if ~isfinite(referenceValue) || abs(referenceValue) < eps
    percentage = NaN;
    return;
end

switch calculationType
    case "reduction"
        percentage = ...
            100 * (referenceValue - newValue) / referenceValue;

    case "increase"
        percentage = ...
            100 * (newValue - referenceValue) / referenceValue;
end

end
