function mapRows = ...
    create_phase4_performance_map_rows( ...
        runArtifact, options)
%CREATE_PHASE4_PERFORMANCE_MAP_ROWS Extract sliding-window map rows.

arguments
    runArtifact (1,1) struct
    options.PredictionHorizon_s (1,1) double ...
        {mustBePositive} = 1.0
    options.RowStride_s (1,1) double ...
        {mustBePositive} = 0.050
end

requiredFields = [
    "scenarioName"
    "environmentName"
    "fixedSampleTime_s"
    "fixedModeId"
    "controlInput"
    "controlJobs"
    "reference"
    "results"
    ];

missingFields = setdiff( ...
    requiredFields, string(fieldnames(runArtifact)));

assert(isempty(missingFields), ...
    "Run artifact is missing fields: %s", ...
    strjoin(missingFields, ", "));

time_s = double(runArtifact.controlInput.Time_s(:));
controlInput = double(runArtifact.controlInput.Data);

assert(size(controlInput, 1) == numel(time_s), ...
    "controlInput time and data lengths do not match.");

assert(size(controlInput, 2) >= 6, ...
    "controlInput must contain [vx, vy, yaw rate, X, Y, yaw].");

[time_s, uniqueIndices] = unique(time_s, "stable");
controlInput = controlInput(uniqueIndices, :);

trackReferenceTable = double(runArtifact.reference);

assert(size(trackReferenceTable, 2) >= 7, ...
    "Reference table must contain seven columns.");

vx_mps = controlInput(:, 1);
vy_mps = controlInput(:, 2);
yawRate_radps = controlInput(:, 3);
x_m = controlInput(:, 4);
y_m = controlInput(:, 5);
yaw_rad = controlInput(:, 6);

[trackIndex, ey_m, epsi_rad] = ...
    computePathErrors( ...
        x_m, y_m, yaw_rad, trackReferenceTable);

lastAnchorTime_s = ...
    time_s(end) - options.PredictionHorizon_s;

assert(lastAnchorTime_s >= time_s(1), ...
    "Run is shorter than the prediction horizon.");

anchorTime_s = ( ...
    time_s(1):options.RowStride_s:lastAnchorTime_s).';

numberOfAnchors = numel(anchorTime_s);

featureData = nan(numberOfAnchors, 7);
outcomeData = nan(numberOfAnchors, 6);
windowEndTime_s = ...
    anchorTime_s + options.PredictionHorizon_s;
validRow = false(numberOfAnchors, 1);

controlJobs = runArtifact.controlJobs;
solveStatusTime_s = ...
    double(runArtifact.results.solve_status_time_s(:));
solveStatus = ...
    double(runArtifact.results.solve_status(:));

for anchorIndex = 1:numberOfAnchors

    currentTime_s = anchorTime_s(anchorIndex);
    currentSample = find( ...
        time_s >= currentTime_s, 1, "first");

    futureWindow = ...
        time_s >= currentTime_s ...
        & time_s <= windowEndTime_s(anchorIndex);

    if nnz(futureWindow) < 2
        continue;
    end

    responseWindow = ...
        controlJobs.ReleaseTime_s >= currentTime_s ...
        & controlJobs.ReleaseTime_s ...
            <= windowEndTime_s(anchorIndex);

    responseTime_s = double( ...
        controlJobs.ResponseTime_s(responseWindow));

    responseTime_s = responseTime_s( ...
        isfinite(responseTime_s));

    if isempty(responseTime_s)
        continue;
    end

    curvaturePreview = computeCurvaturePreview( ...
        vx_mps(currentSample), ...
        trackIndex(currentSample), ...
        trackReferenceTable);

    curvatureRms_1pm = sqrt( ...
        mean(curvaturePreview.^2));

    curvatureMaximum_1pm = ...
        max(abs(curvaturePreview));

    featureData(anchorIndex, :) = [
        abs(ey_m(currentSample))
        abs(epsi_rad(currentSample))
        vx_mps(currentSample)
        abs(vy_mps(currentSample))
        abs(yawRate_radps(currentSample))
        curvatureRms_1pm
        curvatureMaximum_1pm
        ].';

    statusWindow = ...
        solveStatusTime_s >= currentTime_s ...
        & solveStatusTime_s ...
            <= windowEndTime_s(anchorIndex);

    solverFailure = any( ...
        solveStatus(statusWindow) ~= 0);

    outcomeData(anchorIndex, :) = [
        rootMeanSquare(ey_m(futureWindow))
        rootMeanSquare(epsi_rad(futureWindow))
        max(abs(ey_m(futureWindow)))
        max(abs(epsi_rad(futureWindow)))
        empiricalPercentile(responseTime_s, 95)
        double(solverFailure)
        ].';

    validRow(anchorIndex) = ...
        all(isfinite(featureData(anchorIndex, :))) ...
        && all(isfinite(outcomeData(anchorIndex, :)));
end

featureData = featureData(validRow, :);
outcomeData = outcomeData(validRow, :);
anchorTime_s = anchorTime_s(validRow);
windowEndTime_s = windowEndTime_s(validRow);

numberOfRows = nnz(validRow);

mapRows = table( ...
    repmat(string(runArtifact.scenarioName), numberOfRows, 1), ...
    repmat(string(runArtifact.environmentName), numberOfRows, 1), ...
    repmat(double(runArtifact.fixedModeId), numberOfRows, 1), ...
    repmat(runArtifact.fixedSampleTime_s, numberOfRows, 1), ...
    anchorTime_s, ...
    windowEndTime_s, ...
    featureData(:, 1), ...
    featureData(:, 2), ...
    featureData(:, 3), ...
    featureData(:, 4), ...
    featureData(:, 5), ...
    featureData(:, 6), ...
    featureData(:, 7), ...
    outcomeData(:, 1), ...
    outcomeData(:, 2), ...
    outcomeData(:, 3), ...
    outcomeData(:, 4), ...
    outcomeData(:, 5), ...
    outcomeData(:, 6), ...
    repmat(string(runArtifact.runFile), numberOfRows, 1), ...
    VariableNames=[ ...
        "Scenario", ...
        "Environment", ...
        "ModeId", ...
        "CandidateSampleTime_s", ...
        "SourceTime_s", ...
        "WindowEndTime_s", ...
        "AbsLateralError_m", ...
        "AbsHeadingError_rad", ...
        "LongitudinalSpeed_mps", ...
        "AbsLateralSpeed_mps", ...
        "AbsYawRate_radps", ...
        "CurvatureRms_1pm", ...
        "CurvatureMaximum_1pm", ...
        "LateralRms_m", ...
        "HeadingRms_rad", ...
        "LateralPeak_m", ...
        "HeadingPeak_rad", ...
        "ResponseP95_s", ...
        "SolverFailure", ...
        "SourceRunFile"]);

end


function [trackIndex, ey_m, epsi_rad] = ...
    computePathErrors(x_m, y_m, yaw_rad, reference)

numberOfSamples = numel(x_m);
numberOfTrackPoints = size(reference, 1);

trackIndex = ones(numberOfSamples, 1);
ey_m = zeros(numberOfSamples, 1);
epsi_rad = zeros(numberOfSamples, 1);

previousIndex = 1;

for sampleIndex = 1:numberOfSamples

    firstIndex = max(1, previousIndex - 5);
    lastIndex = min( ...
        numberOfTrackPoints, previousIndex + 200);

    candidateIndices = (firstIndex:lastIndex).';

    distanceSquared = ...
        (reference(candidateIndices, 2) - x_m(sampleIndex)).^2 ...
        + (reference(candidateIndices, 3) - y_m(sampleIndex)).^2;

    [~, localIndex] = min(distanceSquared);
    currentIndex = candidateIndices(localIndex);
    currentIndex = max(currentIndex, previousIndex);

    deltaX_m = ...
        x_m(sampleIndex) - reference(currentIndex, 2);
    deltaY_m = ...
        y_m(sampleIndex) - reference(currentIndex, 3);
    referenceYaw_rad = reference(currentIndex, 4);

    ey_m(sampleIndex) = ...
        -deltaX_m*sin(referenceYaw_rad) ...
        + deltaY_m*cos(referenceYaw_rad);

    epsi_rad(sampleIndex) = atan2( ...
        sin(yaw_rad(sampleIndex) - referenceYaw_rad), ...
        cos(yaw_rad(sampleIndex) - referenceYaw_rad));

    trackIndex(sampleIndex) = currentIndex;
    previousIndex = currentIndex;
end

end


function curvaturePreview = ...
    computeCurvaturePreview(vx_mps, trackIndex, reference)

numberOfIntervals = 100;
previewStep_s = 0.01;
curvaturePreview = zeros(numberOfIntervals + 1, 1);

numberOfTrackPoints = size(reference, 1);
currentIndex = min(max(round(trackIndex), 1), numberOfTrackPoints);
predictedStation_m = reference(currentIndex, 1);
previewSpeed_mps = max(vx_mps, 0);

curvaturePreview(1) = reference(currentIndex, 5);

for previewIndex = 2:(numberOfIntervals + 1)
    predictedStation_m = ...
        predictedStation_m ...
        + previewSpeed_mps*previewStep_s;

    while currentIndex < numberOfTrackPoints ...
            && reference(currentIndex, 1) < predictedStation_m
        currentIndex = currentIndex + 1;
    end

    curvaturePreview(previewIndex) = ...
        reference(currentIndex, 5);
end

end


function value = rootMeanSquare(data)

data = double(data(:));
data = data(isfinite(data));
value = sqrt(mean(data.^2));

end


function value = empiricalPercentile(data, percentile)

data = sort(double(data(:)));
data = data(isfinite(data));

sampleIndex = max( ...
    1, ceil((percentile/100)*numel(data)));

value = data(sampleIndex);

end
