function [performanceMap, mapFile] = ...
    load_phase4_performance_map( ...
        scenarioName, environmentName)
%LOAD_PHASE4_PERFORMANCE_MAP Load and validate one runtime map.

arguments
    scenarioName (1,1) string
    environmentName (1,1) string
end

projectRoot = string( ...
    matlab.project.currentProject().RootFolder);

mapFile = fullfile( ...
    projectRoot, ...
    "phase4", ...
    "data", ...
    "performance_maps", ...
    scenarioName, ...
    environmentName, ...
    "performance_map.mat");

assert(isfile(mapFile), ...
    "Performance map does not exist:\n%s", mapFile);

savedData = load(mapFile, "performanceMap");

assert(isfield(savedData, "performanceMap"), ...
    "performanceMap is missing from:\n%s", mapFile);

performanceMap = savedData.performanceMap;

requiredFields = [
    "mapX"
    "mapY"
    "mapSampleTimes_s"
    "normalizationMean"
    "normalizationScale"
    "rawMinimum"
    "rawMaximum"
    "safetyMargins"
    "maximumNearestDistance"
    "candidateSampleTimes_s"
    "meanControlExecutionTime_s"
    "p95ControlExecutionTime_s"
    ];

missingFields = setdiff( ...
    requiredFields, string(fieldnames(performanceMap)));

assert(isempty(missingFields), ...
    "Performance map is missing fields: %s", ...
    strjoin(missingFields, ", "));

assert(size(performanceMap.mapX, 2) == 7, ...
    "Performance-map input must contain seven features.");

assert(size(performanceMap.mapY, 2) == 6, ...
    "Performance-map output must contain six outcomes.");

assert(size(performanceMap.mapX, 1) == ...
        size(performanceMap.mapY, 1), ...
    "mapX and mapY row counts do not match.");

assert(size(performanceMap.mapX, 1) == ...
        numel(performanceMap.mapSampleTimes_s), ...
    "Map sample-time count does not match the map rows.");

expectedSampleTimes_s = [0.010];

% assert(isequal( ...
%         sort(double(performanceMap.candidateSampleTimes_s(:))), ...
%         sort(expectedSampleTimes_s)), ...
%     "Performance map must contain the 50, 20, and 10 ms modes.");

for candidateIndex = 1:numel(expectedSampleTimes_s)
    sampleTime_s = expectedSampleTimes_s(candidateIndex);
    modeRows = abs( ...
        double(performanceMap.mapSampleTimes_s(:)) ...
        - sampleTime_s) < 1e-12;

    assert(any(modeRows), ...
        "Performance map has no observations for the %.0f ms mode.", ...
        1e3*sampleTime_s);
end

assert(isequal(size(performanceMap.rawMinimum), [3, 7]) ...
        && isequal(size(performanceMap.rawMaximum), [3, 7]) ...
        && isequal(size(performanceMap.maximumNearestDistance), [3, 1]), ...
    "Performance-map coverage arrays must represent all three modes.");

end
