function [figureHandle, statistics] = ...
    plotSamplingJitterSummary(sweepSummary, options)
%PLOTSAMPLINGJITTERSUMMARY Plot Phase 1.3 jitter-sweep results.
%
% Default panels:
%   lateral_rmse
%   heading_rmse
%   constraint_counts
%   deadline_misses

arguments
    sweepSummary table

    options.Panels (1,:) string = [ ...
        "lateral_rmse", ...
        "heading_rmse", ...
        "constraint_counts", ...
        "deadline_misses"]

    options.IncludeScenarios (1,:) string = ...
        string.empty(1,0)

    options.IncludeEnvironments (1,:) string = ...
        string.empty(1,0)

    options.SigmaMultiplier (1,1) double ...
        {mustBeNonnegative} = 1

    options.ShowLegend (1,1) logical = true

    options.FigureTitle (1,1) string = ...
        "Phase 1.3: Sampling-Jitter Sensitivity"
end

%% Validate requested panels

supportedPanels = [
    "lateral_rmse"
    "heading_rmse"
    "constraint_counts"
    "deadline_misses"
    "solve_time_p95"
    "actual_jitter"
    "raw_status_failures"
    ];

unknownPanels = setdiff( ...
    options.Panels, ...
    supportedPanels);

assert(isempty(unknownPanels), ...
    "Unsupported panel(s): %s", ...
    strjoin(unknownPanels, ", "));

%% Determine required summary variables

metricVariables = strings(0,1);

for panelName = options.Panels

    switch panelName

        case "lateral_rmse"
            metricVariables(end+1) = ...
                "LateralRmse_m";

        case "heading_rmse"
            metricVariables(end+1) = ...
                "HeadingRmse_deg";

        case "constraint_counts"
            metricVariables(end+1:end+2) = [
                "ConstraintViolationSamples"
                "ConstraintEventCount"
                ];

        case "deadline_misses"
            metricVariables(end+1) = ...
                "DeadlineMissCount";

        case "solve_time_p95"
            metricVariables(end+1) = ...
                "SolveTimeP95_ms";

        case "actual_jitter"
            metricVariables(end+1) = ...
                "MaximumActualJitter_ms";

        case "raw_status_failures"
            metricVariables(end+1) = ...
                "NonzeroStatusCount";
    end
end

metricVariables = unique(metricVariables, "stable");
metricVariables = metricVariables(:);

metricColumns = setdiff( ...
    metricVariables, ...
    "NonzeroStatusCount", ...
    "stable");

requiredColumns = [
    "ScenarioName"
    "EnvironmentName"
    "JitterBound_ms"
    "Completed"
    ];

if ismember("raw_status_failures", options.Panels)
    requiredColumns = [
        requiredColumns
        "RawStatus2Count"
        "RawStatus4Count"
        "OtherStatusCount"
        ];
end

requiredColumns = unique( ...
    [requiredColumns(:); metricColumns(:)], ...
    "stable");


tableColumns = string( ...
    sweepSummary.Properties.VariableNames);

missingColumns = setdiff( ...
    requiredColumns, ...
    tableColumns);

assert(isempty(missingColumns), ...
    "Missing sweep-summary column(s): %s", ...
    strjoin(missingColumns, ", "));

%% Keep completed simulations

plotTable = sweepSummary( ...
    sweepSummary.Completed, :);

assert(~isempty(plotTable), ...
    "No completed simulations are available.");

plotTable.ScenarioName = ...
    string(plotTable.ScenarioName);

plotTable.EnvironmentName = ...
    string(plotTable.EnvironmentName);

%% Add combined raw-status failure count if requested

if ismember("raw_status_failures", options.Panels)

    plotTable.NonzeroStatusCount = ...
        plotTable.RawStatus2Count + ...
        plotTable.RawStatus4Count + ...
        plotTable.OtherStatusCount;
end

%% Apply scenario filter

if ~isempty(options.IncludeScenarios)

    requestedScenarios = ...
        string(options.IncludeScenarios);

    availableScenarios = unique( ...
        plotTable.ScenarioName);

    unknownScenarios = setdiff( ...
        requestedScenarios, ...
        availableScenarios);

    assert(isempty(unknownScenarios), ...
        "Unknown scenario(s): %s", ...
        strjoin(unknownScenarios, ", "));

    plotTable = plotTable( ...
        ismember( ...
            plotTable.ScenarioName, ...
            requestedScenarios), ...
        :);
end

%% Apply environment filter

if ~isempty(options.IncludeEnvironments)

    requestedEnvironments = ...
        string(options.IncludeEnvironments);

    availableEnvironments = unique( ...
        plotTable.EnvironmentName);

    unknownEnvironments = setdiff( ...
        requestedEnvironments, ...
        availableEnvironments);

    assert(isempty(unknownEnvironments), ...
        "Unknown environment(s): %s", ...
        strjoin(unknownEnvironments, ", "));

    plotTable = plotTable( ...
        ismember( ...
            plotTable.EnvironmentName, ...
            requestedEnvironments), ...
        :);
end

assert(~isempty(plotTable), ...
    "No simulations remain after filtering.");

%% Calculate Monte Carlo statistics
%
% Each group is:
% scenario + environment + jitter bound

[groupIndex, ...
 scenarioName, ...
 environmentName, ...
 jitterBound_ms] = findgroups( ...
    plotTable.ScenarioName, ...
    plotTable.EnvironmentName, ...
    plotTable.JitterBound_ms);

statistics = table( ...
    scenarioName, ...
    environmentName, ...
    jitterBound_ms, ...
    VariableNames=[ ...
        "ScenarioName", ...
        "EnvironmentName", ...
        "JitterBound_ms"]);

statistics.TrialCount = splitapply( ...
    @numel, ...
    plotTable.JitterBound_ms, ...
    groupIndex);

for metricName = metricVariables.'

    values = plotTable.(metricName);

    statistics.(metricName + "_Mean") = ...
        splitapply( ...
            @finiteMean, ...
            values, ...
            groupIndex);

    statistics.(metricName + "_Std") = ...
        splitapply( ...
            @finiteStandardDeviation, ...
            values, ...
            groupIndex);
end

statistics = sortrows( ...
    statistics, ...
    ["ScenarioName", ...
     "EnvironmentName", ...
     "JitterBound_ms"]);

%% Create figure

numberOfPanels = numel(options.Panels);
numberOfColumns = min(2, numberOfPanels);
numberOfRows = ceil( ...
    numberOfPanels / numberOfColumns);

figureHandle = figure( ...
    Name="Sampling-jitter sweep summary", ...
    Color="white");

layout = tiledlayout( ...
    figureHandle, ...
    numberOfRows, ...
    numberOfColumns, ...
    TileSpacing="compact", ...
    Padding="compact");

title(layout, options.FigureTitle);

xlabel( ...
    layout, ...
    "Sampling-jitter bound, J (ms)");

%% Define scenario/environment series

seriesTable = unique( ...
    statistics(:, [ ...
        "ScenarioName", ...
        "EnvironmentName"]), ...
    "rows", ...
    "stable");

seriesColors = lines( ...
    height(seriesTable));

%% Plot requested panels

for panelName = options.Panels

    switch panelName

        case "lateral_rmse"

            plotMetricPanel( ...
                layout, ...
                statistics, ...
                seriesTable, ...
                seriesColors, ...
                "LateralRmse_m", ...
                "Lateral RMSE (m)", ...
                "Lateral Tracking RMS", ...
                options);

        case "heading_rmse"

            plotMetricPanel( ...
                layout, ...
                statistics, ...
                seriesTable, ...
                seriesColors, ...
                "HeadingRmse_deg", ...
                "Heading RMSE (deg)", ...
                "Heading Tracking RMS", ...
                options);

        case "constraint_counts"

            plotConstraintPanel( ...
                layout, ...
                statistics, ...
                seriesTable, ...
                seriesColors, ...
                options);

        case "deadline_misses"

            plotMetricPanel( ...
                layout, ...
                statistics, ...
                seriesTable, ...
                seriesColors, ...
                "DeadlineMissCount", ...
                "Deadline-miss count", ...
                "Controller Deadline Misses", ...
                options);

        case "solve_time_p95"

            plotMetricPanel( ...
                layout, ...
                statistics, ...
                seriesTable, ...
                seriesColors, ...
                "SolveTimeP95_ms", ...
                "Solve-time P95 (ms)", ...
                "Controller Solve Time", ...
                options);

        case "actual_jitter"

            plotMetricPanel( ...
                layout, ...
                statistics, ...
                seriesTable, ...
                seriesColors, ...
                "MaximumActualJitter_ms", ...
                "Maximum actual jitter (ms)", ...
                "Realized Sampling Jitter", ...
                options);

        case "raw_status_failures"

            plotMetricPanel( ...
                layout, ...
                statistics, ...
                seriesTable, ...
                seriesColors, ...
                "NonzeroStatusCount", ...
                "Nonzero raw-status count", ...
                "Raw acados Solver Failures", ...
                options);
    end
end

end


function plotMetricPanel( ...
    layout, statistics, ...
    seriesTable, seriesColors, ...
    metricName, yLabelText, titleText, options)

axesHandle = nexttile(layout);
hold(axesHandle, "on");

for seriesIndex = 1:height(seriesTable)

    selected = ...
        statistics.ScenarioName == ...
            seriesTable.ScenarioName(seriesIndex) & ...
        statistics.EnvironmentName == ...
            seriesTable.EnvironmentName(seriesIndex);

    seriesData = sortrows( ...
        statistics(selected,:), ...
        "JitterBound_ms");

    x = seriesData.JitterBound_ms;
    meanValue = ...
        seriesData.(metricName + "_Mean");
    standardDeviation = ...
        seriesData.(metricName + "_Std");

    valid = ...
        isfinite(x) & ...
        isfinite(meanValue) & ...
        isfinite(standardDeviation);

    x = x(valid);
    meanValue = meanValue(valid);
    standardDeviation = ...
        standardDeviation(valid);

    if isempty(x)
        continue;
    end

    lowerBand = max( ...
        0, ...
        meanValue - ...
        options.SigmaMultiplier .* ...
        standardDeviation);

    upperBand = ...
        meanValue + ...
        options.SigmaMultiplier .* ...
        standardDeviation;

    seriesColor = ...
        seriesColors(seriesIndex,:);

    if numel(x) > 1

        fill( ...
            axesHandle, ...
            [x; flipud(x)], ...
            [lowerBand; flipud(upperBand)], ...
            seriesColor, ...
            FaceAlpha=0.15, ...
            EdgeColor="none", ...
            HandleVisibility="off");
    end

    plot( ...
        axesHandle, ...
        x, ...
        meanValue, ...
        "-o", ...
        Color=seriesColor, ...
        MarkerFaceColor=seriesColor, ...
        LineWidth=1.5, ...
        MarkerSize=5, ...
        DisplayName=createDisplayName( ...
            seriesTable, seriesIndex));
end

hold(axesHandle, "off");
grid(axesHandle, "on");
box(axesHandle, "on");

ylabel(axesHandle, yLabelText);
title(axesHandle, titleText);

if options.ShowLegend
    legend( ...
        axesHandle, ...
        Location="best", ...
        Interpreter="none");
end

end


function plotConstraintPanel( ...
    layout, statistics, ...
    seriesTable, seriesColors, options)

axesHandle = nexttile(layout);

yyaxis(axesHandle, "left");
hold(axesHandle, "on");

yyaxis(axesHandle, "right");
hold(axesHandle, "on");

for seriesIndex = 1:height(seriesTable)

    selected = ...
        statistics.ScenarioName == ...
            seriesTable.ScenarioName(seriesIndex) & ...
        statistics.EnvironmentName == ...
            seriesTable.EnvironmentName(seriesIndex);

    seriesData = sortrows( ...
        statistics(selected,:), ...
        "JitterBound_ms");

    x = seriesData.JitterBound_ms;
    seriesColor = ...
        seriesColors(seriesIndex,:);

    displayName = createDisplayName( ...
        seriesTable, seriesIndex);

    %% Violating samples

    sampleMean = ...
        seriesData.ConstraintViolationSamples_Mean;

    sampleStd = ...
        seriesData.ConstraintViolationSamples_Std;

    validSamples = ...
        isfinite(x) & ...
        isfinite(sampleMean) & ...
        isfinite(sampleStd);

    if any(validSamples)

        yyaxis(axesHandle, "left");

        lowerError = min( ...
            sampleStd(validSamples), ...
            sampleMean(validSamples));

        errorbar( ...
            axesHandle, ...
            x(validSamples), ...
            sampleMean(validSamples), ...
            lowerError, ...
            sampleStd(validSamples), ...
            "-o", ...
            Color=seriesColor, ...
            MarkerFaceColor=seriesColor, ...
            LineWidth=1.4, ...
            DisplayName= ...
                displayName + " / samples");
    end

    %% Violation events

    eventMean = ...
        seriesData.ConstraintEventCount_Mean;

    eventStd = ...
        seriesData.ConstraintEventCount_Std;

    validEvents = ...
        isfinite(x) & ...
        isfinite(eventMean) & ...
        isfinite(eventStd);

    if any(validEvents)

        yyaxis(axesHandle, "right");

        lowerError = min( ...
            eventStd(validEvents), ...
            eventMean(validEvents));

        errorbar( ...
            axesHandle, ...
            x(validEvents), ...
            eventMean(validEvents), ...
            lowerError, ...
            eventStd(validEvents), ...
            "--s", ...
            Color=seriesColor, ...
            LineWidth=1.4, ...
            DisplayName= ...
                displayName + " / events");
    end
end

yyaxis(axesHandle, "left");
ylabel(axesHandle, "Violating samples");

yyaxis(axesHandle, "right");
ylabel(axesHandle, "Violation events");

grid(axesHandle, "on");
box(axesHandle, "on");

title( ...
    axesHandle, ...
    "Constraint-Violating Samples and Events");

if options.ShowLegend
    legend( ...
        axesHandle, ...
        Location="best", ...
        Interpreter="none");
end

end


function value = finiteMean(samples)

samples = samples(isfinite(samples));

if isempty(samples)
    value = NaN;
else
    value = mean(samples);
end

end


function value = finiteStandardDeviation(samples)

samples = samples(isfinite(samples));

if isempty(samples)
    value = NaN;
elseif isscalar(samples)
    value = 0;
else
    value = std(samples, 0);
end

end


function displayName = ...
    createDisplayName(seriesTable, seriesIndex)

displayName = replace( ...
    seriesTable.ScenarioName(seriesIndex) + ...
    " / " + ...
    seriesTable.EnvironmentName(seriesIndex), ...
    "_", ...
    " ");

end