function [figureHandle, summaryTable] = ...
    plot_solve_time_box_plot(options)
%PLOT_PHASE0_SOLVE_TIME_BOXPLOT Compare acados solve-time distributions.
%
% Example:
  % [figureHandle, summaryTable] = ...
  %     plot_solve_time_box_plot( ...
  %         Deadline_ms=10, ...
  %         SaveFile="phase0_solve_time_boxplot.png");

arguments
    options.ResultsRoot (1,1) string = ""
    options.ScenarioNames (1,:) string = [ ...
        "urban_profile", ...
        "highway_cruise", ...
        "aggressive_maneuver"]
    options.EnvironmentNames (1,:) string = [ ...
        "dry_road", ...
        "low_friction_road"]
    options.Deadline_ms (1,1) double = 10
    options.SaveFile (1,1) string = ""
    options.ShowFigure (1,1) logical = true
end

%% Results location

if strlength(options.ResultsRoot) == 0

    projectRoot = string( ...
        matlab.project.currentProject().RootFolder);

    resultsRoot = fullfile( ...
        projectRoot, ...
        "phase0", ...
        "results", ...
        "ACADOS_MPC");
else
    resultsRoot = options.ResultsRoot;
end

numberOfScenarios = numel(options.ScenarioNames);
numberOfEnvironments = numel(options.EnvironmentNames);
numberOfGroups = ...
    numberOfScenarios*numberOfEnvironments;

solveTimeGroups_ms = cell(numberOfGroups, 1);
groupLabels = strings(numberOfGroups, 1);
groupEnvironments = strings(numberOfGroups, 1);

summaryRecords = repmat(struct( ...
    Scenario="", ...
    Environment="", ...
    Samples=0, ...
    Mean_ms=NaN, ...
    Median_ms=NaN, ...
    P95_ms=NaN, ...
    Maximum_ms=NaN, ...
    DeadlineMissPercent=NaN), ...
    numberOfGroups, ...
    1);

%% Load all six datasets

groupIndex = 0;

for scenarioIndex = 1:numberOfScenarios

    scenarioName = ...
        options.ScenarioNames(scenarioIndex);

    for environmentIndex = 1:numberOfEnvironments

        environmentName = ...
            options.EnvironmentNames(environmentIndex);

        groupIndex = groupIndex + 1;

        resultsFile = fullfile( ...
            resultsRoot, ...
            scenarioName, ...
            environmentName, ...
            scenarioName + "_results.mat");

        assert(isfile(resultsFile), ...
            "Phase 0 result file not found: %s", ...
            resultsFile);

        savedData = load(resultsFile);
        results = findResultsStructure( ...
            savedData, ...
            resultsFile);

        assert(isfield(results, "solve_time_s"), ...
            "solve_time_s is missing from %s.", ...
            resultsFile);

        solveTime_ms = ...
            1e3*double(results.solve_time_s(:));

        % Remove initialization, invalid and unavailable samples.
        validSample = ...
            isfinite(solveTime_ms) ...
            & solveTime_ms > 0;

        solveTime_ms = solveTime_ms(validSample);

        assert(~isempty(solveTime_ms), ...
            "No valid solve-time samples found in %s.", ...
            resultsFile);

        solveTimeGroups_ms{groupIndex} = ...
            solveTime_ms;

        groupLabels(groupIndex) = ...
            prettyName(scenarioName) ...
            + " / " ...
            + prettyName(environmentName);

        groupEnvironments(groupIndex) = ...
            environmentName;

        summaryRecords(groupIndex).Scenario = ...
            scenarioName;

        summaryRecords(groupIndex).Environment = ...
            environmentName;

        summaryRecords(groupIndex).Samples = ...
            numel(solveTime_ms);

        summaryRecords(groupIndex).Mean_ms = ...
            mean(solveTime_ms);

        summaryRecords(groupIndex).Median_ms = ...
            median(solveTime_ms);

        summaryRecords(groupIndex).P95_ms = ...
            empiricalPercentile(solveTime_ms, 95);

        summaryRecords(groupIndex).Maximum_ms = ...
            max(solveTime_ms);

        summaryRecords(groupIndex).DeadlineMissPercent = ...
            100*mean( ...
                solveTime_ms > options.Deadline_ms);
    end
end

summaryTable = struct2table(summaryRecords);

%% Plot

if options.ShowFigure
    figureVisibility = "on";
else
    figureVisibility = "off";
end

figureHandle = figure( ...
    "Color", "white", ...
    "Visible", figureVisibility, ...
    "Name", "solve-time comparison for " + options.Deadline_ms + "ms sampling time");

axesHandle = axes( ...
    figureHandle, ...
    "Color", "white");

hold(axesHandle, "on");
grid(axesHandle, "on");
box(axesHandle, "on");

environmentColors = [
    0.00 0.45 0.74  % Dry road
    0.85 0.33 0.10  % Low-friction road
    ];

for index = 1:numberOfGroups

    environmentIndex = find( ...
        options.EnvironmentNames ...
        == groupEnvironments(index), ...
        1);

    values_ms = solveTimeGroups_ms{index};

    boxchart( ...
        axesHandle, ...
        repmat(index, size(values_ms)), ...
        values_ms, ...
        "BoxFaceColor", ...
        environmentColors(environmentIndex,:), ...
        "MarkerStyle", ".", ...
        "MarkerSize", 10, ...
        "JitterOutliers", "on", ...
        "BoxWidth", 0.55);
end

deadlineLine = yline( ...
    axesHandle, ...
    options.Deadline_ms, ...
    "--", ...
    sprintf("Deadline: %.1f ms", ...
        options.Deadline_ms), ...
    "Color", [0.75 0.10 0.10], ...
    "LineWidth", 1.5, ...
    "LabelHorizontalAlignment", "left");

deadlineLine.HandleVisibility = "off";

xlim(axesHandle, ...
    [0.5, numberOfGroups + 0.5]);

xticks(axesHandle, ...
    1:numberOfGroups);

xticklabels(axesHandle, ...
    groupLabels);

xtickangle(axesHandle, 25);

ylabel(axesHandle, ...
    "Solve time (ms)");

title(axesHandle, ...
    "Solve-Time Distributions");

subtitle(axesHandle, ...
    "Boxes: interquartile range; center lines: median");

% Legend proxies for the two environments.
dryLegend = plot( ...
    axesHandle, ...
    NaN, NaN, ...
    "s", ...
    "MarkerFaceColor", environmentColors(1,:), ...
    "MarkerEdgeColor", environmentColors(1,:), ...
    "DisplayName", "Dry road");

lowFrictionLegend = plot( ...
    axesHandle, ...
    NaN, NaN, ...
    "s", ...
    "MarkerFaceColor", environmentColors(2,:), ...
    "MarkerEdgeColor", environmentColors(2,:), ...
    "DisplayName", "Low-friction road");

legend( ...
    axesHandle, ...
    [dryLegend, lowFrictionLegend], ...
    "Location", "best");

%% Optional export

if strlength(options.SaveFile) > 0

    outputFolder = fileparts(options.SaveFile);

    if strlength(outputFolder) > 0 && ...
            ~isfolder(outputFolder)
        mkdir(outputFolder);
    end

    exportgraphics( ...
        figureHandle, ...
        options.SaveFile, ...
        "Resolution", 300);
end

end


function results = ...
    findResultsStructure(savedData, resultsFile)

if isfield(savedData, "results")
    results = savedData.results;
    return;
end

if isfield(savedData, "runArtifact") && ...
        isfield(savedData.runArtifact, "results")
    results = savedData.runArtifact.results;
    return;
end

variableNames = fieldnames(savedData);

for index = 1:numel(variableNames)

    candidate = savedData.(variableNames{index});

    if isstruct(candidate) && ...
            isfield(candidate, "solve_time_s")
        results = candidate;
        return;
    end
end

error( ...
    "No results structure containing solve_time_s found in %s.", ...
    resultsFile);

end


function outputName = prettyName(inputName)

outputName = replace(inputName, "_", " ");

end


function value = ...
    empiricalPercentile(samples, percentile)

samples = sort(samples(:));

sampleIndex = max( ...
    1, ...
    ceil((percentile/100)*numel(samples)));

value = samples(sampleIndex);

end


