classdef ExperimentRunner
    %EXPERIMENTRUNNER Run, analyze, plot, and save one SDV experiment.
    %
    % This class is an orchestration boundary only. It never enters the
    % Simulink workspace; models receive the existing numeric structures.

    properties (SetAccess = private)
        RunConfig (1,1) struct
    end

    methods
        function obj = ExperimentRunner(runConfig)
            obj.RunConfig = validateRunConfig(runConfig);
        end

        function [results, config] = run(obj)
            rng(0, "twister");

            runConfig = obj.RunConfig;
            config = build_phase0_configuration( ...
                runConfig.scenario_name);

            vehicleParams = config.vehicle;
            controllerParams = config.controller;
            simulationParams = config.simulation;
            adaptiveModelParams = config.adaptiveModel;

            % Make direct scenario runners reproducible in a clean MATLAB
            % session, including adding the generated acados S-function.
            check_runtime_requirements(controllerParams); % can be removed since done in main.m file
            
            % UT variable is used by Original PLant model (DON'T CHANGE)
            UT = legacy_plant_parameters( ...
                vehicleParams, simulationParams);
            % acados solver settings for optimization. If you want to
            % change the constraints, qp solver, tolerance, min/max itr,
            % integration method.
            % WARNINGS: if you change any settings, you have to REBUILD IT
            % and change the S-function in SIMULINK.
            acadosSettings = ...
                acados_ocp_parameters(controllerParams);
            acadosNominalInput = reshape( ...
                acadosSettings.nominal_input, 2, 1);

            trackReferenceTable = config.scenario.lookup_table; % track profile
            scenarioStopTable = config.scenario.stop_event_table; % stop_event: vel., dwell time, position
            finalTrackIndex = size(trackReferenceTable, 1);

            [environment, roadFrictionProfile] = ...
                configureEnvironment( ...
                    runConfig.environment_name, ...
                    simulationParams.stop_time_s);

            config.environment = rmfield( ...
                environment, "road_friction_profile");
            config.run = runConfig;
            % initialize all the variables required by SIMULINK AND
            % CONTROLLER
            backendVariables = configureController( ...
                vehicleParams, ...
                controllerParams, ...
                simulationParams);
            % create the input required by SIMULINK
            simInput = createSimulationInput( ...
                runConfig, ...
                vehicleParams, ...
                controllerParams, ...
                simulationParams, ...
                adaptiveModelParams, ...
                trackReferenceTable, ...
                scenarioStopTable, ...
                finalTrackIndex, ...
                UT, ...
                acadosNominalInput, ...
                roadFrictionProfile, ...
                backendVariables);

            simulationOutput = sim(simInput);
            logs = validateLogging(simulationOutput);

            solveTimeAvailable = ...
                controllerParams.controller_backend == ...
                controllerParams.BACKEND_ACADOS;

            results = sdv.results.extractBaseline( ...
                logs, solveTimeAvailable);

            results = addMetadata( ...
                results, config, environment, runConfig);

            [results, figures] = analyzeAndPlot( ...
                results, config, runConfig, solveTimeAvailable);

            results.constraint_metrics = ...
                sdv.metrics.computeConstraintViolations( ...
                    results, ...
                    controllerParams, ...
                    simulationParams.Ts_s);

            saveArtifacts(results, config, figures, runConfig);

            if ~runConfig.output.show_figures
                closeValidFigures(figures);
            end
        end
    end
end

% check the field required to run the simulation
function runConfig = validateRunConfig(runConfig)
%VALIDATERUNCONFIG Validate the public runner contract.

requiredFields = [ ...
    "schema_version"
    "phase_name"
    "model_name"
    "scenario_name"
    "environment_name"
    "actuation_delay_s"
    "output"
    ];

missingFields = setdiff( ...
    requiredFields, string(fieldnames(runConfig)));

assert(isempty(missingFields), ...
    "Missing run-configuration fields: %s", ...
    strjoin(missingFields, ", "));

assert(any(runConfig.phase_name == ["phase0", "phase1"]), ...
    "Unsupported experiment phase: %s", ...
    runConfig.phase_name);

end

function [environment, roadFrictionProfile] = ...
    configureEnvironment(environmentName, stopTime_s)
%CONFIGUREENVIRONMENT Load environment metadata and live input data.
%FrictionDropTime_s is used only for switching the friction from lower to
%higher. But we are not using it from phase1.
environment = load_env_profile( ...
    lower(environmentName), ...
    stopTime_s, ...
    FrictionDropTime_s=10);
% friction profile remain same constant value for all time. Unless u'r
% changing it.
roadFrictionProfile = environment.road_friction_profile;

end

function backendVariables = configureController( ...
    vehicleParams, controllerParams, simulationParams)
%CONFIGURECONTROLLER Prepare backend-specific MATLAB variables.

backendVariables = struct();

switch controllerParams.controller_backend
    case controllerParams.BACKEND_ACADOS
        disp("Running acados controller... ");

    case controllerParams.BACKEND_MATLAB
        error( ...
            "Fixed linear MATLAB MPC backend is not implemented yet.");

    case controllerParams.BACKEND_ADAPTIVE
        [Ad0, Bmv0, Emd0] = ...
            linearize_prediction_model( ...
                vehicleParams, ...
                simulationParams, ...
                controllerParams);

        backendVariables.mpc_adaptive = ...
            configure_baseline_mpc( ...
                Ad0, Bmv0, Emd0, controllerParams);

    otherwise
        error( ...
            "Unknown controller backend ID: %d", ...
            controllerParams.controller_backend);
end

end

function simInput = createSimulationInput( ...
    runConfig, ...
    vehicleParams, ...
    controllerParams, ...
    simulationParams, ...
    adaptiveModelParams, ...
    trackReferenceTable, ...
    scenarioStopTable, ...
    finalTrackIndex, ...
    UT, ...
    acadosNominalInput, ...
    roadFrictionProfile, ...
    backendVariables)
%CREATESIMULATIONINPUT Build one deterministic SimulationInput object.

simInput = Simulink.SimulationInput(runConfig.model_name);

simInput = simInput.setVariable("vehicleParams", vehicleParams);
simInput = simInput.setVariable("controllerParams", controllerParams);
simInput = simInput.setVariable("simulationParams", simulationParams);
simInput = simInput.setVariable( ...
    "adaptiveModelParams", adaptiveModelParams);
simInput = simInput.setVariable( ...
    "track_ref_table", trackReferenceTable);
simInput = simInput.setVariable( ...
    "scenario_stop_table", scenarioStopTable);
simInput = simInput.setVariable( ...
    "final_track_index", finalTrackIndex); % track end: stop the simulation
simInput = simInput.setVariable("UT", UT);
simInput = simInput.setVariable( ...
    "acados_nominal_input", acadosNominalInput);
simInput = simInput.setVariable( ...
    "roadFrictionProfile", roadFrictionProfile); % disturbance in -> PLANT model

if runConfig.phase_name == "phase1"
    simInput = simInput.setVariable( ...
        "actuationDelay_s", runConfig.actuation_delay_s);
end

if isfield(backendVariables, "mpc_adaptive")
    simInput = simInput.setVariable( ...
        "mpc_adaptive", backendVariables.mpc_adaptive);
end

simInput = simInput.setModelParameter( ...
    StopTime=string(simulationParams.stop_time_s), ...
    ReturnWorkspaceOutputs="on", ...
    SignalInfNanChecking="error");

end

function logs = validateLogging(simulationOutput)
%VALIDATELOGGING Check the stable simulation logging contract.

assert(isprop(simulationOutput, "logsout") || ...
    any(simulationOutput.who == "logsout"), ...
    "Simulation did not return logsout.");

logs = simulationOutput.logsout;

requiredSignals = [ ...
    "vx_meas"
    "vx_ref"
    "ax_meas"
    "x_pos"
    "y_pos"
    "torque_opt"
    "applied_torque"
    "steering_angle_opt"
    "applied_steering_angle"
    "yaw_rate_meas"
    "ey_m"
    "epsi_rad"
    "solve_status"
    "solve_time"
    "cpu_time_sim"
    "cpu_time_qp"
    "cpu_time_lin"
    "road_friction_mu"
    ];

availableSignals = string(logs.getElementNames);
missingSignals = setdiff(requiredSignals, availableSignals);

assert(isempty(missingSignals), ...
    "Missing logged signals: %s", ...
    strjoin(missingSignals, ", "));

end

function results = addMetadata( ...
    results, config, environment, runConfig)
%ADDMETADATA Add reproducibility and experiment metadata.

results.metadata.scenario_name = runConfig.scenario_name;
results.metadata.matlab_version = string(version);
results.metadata.generated_at_utc = ...
    datetime("now", TimeZone="UTC");
results.metadata.controller_backend = ...
    config.controller.controller_backend;
results.metadata.scenario_schema_version = ...
    config.scenario.schema_version;
results.metadata.environment_name = runConfig.environment_name;
results.metadata.environment_schema_version = ...
    environment.schema_version;
results.metadata.environment_event_type = environment.event_type;
results.metadata.environment_event_time_s = environment.event_time_s;
results.metadata.phase_name = runConfig.phase_name;
results.metadata.model_name = runConfig.model_name;
results.metadata.actuation_delay_s = runConfig.actuation_delay_s;



end

function [results, figures] = analyzeAndPlot( ...
    results, config, runConfig, solveTimeAvailable)
%ANALYZEANDPLOT Run reusable analysis and create standard figures.

figures = struct();
figures.closed_loop = sdv.plot.closedLoop( ...
    results, config.scenario, runConfig.environment_name, ...
    runConfig.actuation_delay_s);

[figures.tracking_errors, results.tracking_metrics] = ...
    sdv.plot.trackingErrors( ...
        results, ...
        config.scenario, ...
        runConfig.environment_name, ...
        config.controller, ...
        runConfig.actuation_delay_s);

if solveTimeAvailable
    [figures.solve_time_histogram, ...
        results.solve_time_metrics] = ...
        sdv.plot.solveTimeHistogram( ...
            results, ...
            config.scenario, ...
            runConfig.environment_name, ...
            config.simulation.Ts_s, ...
            runConfig.actuation_delay_s);

    [figures.solve_time_telemetry, ...
        results.solve_time_tele_metrics] = ...
        sdv.plot.solveTimeTelemetry( ...
            results, ...
            string(config.scenario.name), ...
            runConfig.environment_name, ...
            config.simulation.Ts_s, ...
            runConfig.actuation_delay_s);
else
    results.solve_time_metrics = struct("available", false);
    results.solve_time_tele_metrics = struct("available", false);
end

end

function saveArtifacts(results, config, figures, runConfig)
%SAVEARTIFACTS Save standardized results and figures when requested.

if ~runConfig.output.save_results && ...
        ~runConfig.output.save_figures
    return;
end

projectRoot = string( ...
    matlab.project.currentProject().RootFolder);
controllerName = sdv.config.controllerName(config.controller);

folders = sdv.io.createOutputFolders( ...
    projectRoot, runConfig, controllerName);

if runConfig.output.save_figures
    if runConfig.phase_name == "phase0"
        closedLoopName = runConfig.scenario_name + "_tracking";
    else
        closedLoopName = ...
            runConfig.scenario_name + "_closed_loop_results";
    end

    sdv.io.exportFigure( ...
        figures.closed_loop, folders.figures, closedLoopName);
    sdv.io.exportFigure( ...
        figures.tracking_errors, ...
        folders.figures, ...
        runConfig.scenario_name + "_tracking_errors");

    if isfield(figures, "solve_time_histogram")
        sdv.io.exportFigure( ...
            figures.solve_time_histogram, ...
            folders.figures, ...
            runConfig.scenario_name + "_solve_time_histogram");
        sdv.io.exportFigure( ...
            figures.solve_time_telemetry, ...
            folders.figures, ...
            runConfig.scenario_name + "_solve_time_telemetry");
    end
end

if runConfig.output.save_results
    resultsFile = fullfile( ...
        folders.results, ...
        runConfig.scenario_name + "_results.mat");
    save(resultsFile, "results", "config");
end

end

function closeValidFigures(figures)
%CLOSEVALIDFIGURES Close every figure created by one experiment.

names = fieldnames(figures);

for index = 1:numel(names)
    figureHandle = figures.(names{index});

    if isgraphics(figureHandle, "figure")
        close(figureHandle);
    end
end

end
