%% Box-plot comparison of constant and random delay in the knee region

startup_project;

projectRoot = string(matlab.project.currentProject().RootFolder);
scenarioName = "aggressive_maneuver";
meanDelayLevels_ms = (105:5:135).';

numberOfLevels = numel(meanDelayLevels_ms);
lateralSamples = cell(2*numberOfLevels,1);
headingSamples = cell(2*numberOfLevels,1);
delayValues_ms = repelem(meanDelayLevels_ms,2);
groupNames = repmat(["Constant delay"; "Random delay"], numberOfLevels,1);

for index = 1:numberOfLevels
    meanDelay_ms = meanDelayLevels_ms(index);

    constantFile = fullfile( ...
        projectRoot, "phase1", "results", "ACADOS_MPC", ...
        "actuation_delay_" + meanDelay_ms + "_ms", ...
        scenarioName, "low_friction_road", ...
        scenarioName + "_results.mat");

    randomFile = fullfile( ...
        projectRoot, "phase1", "results", "ACADOS_MPC", ...
        "random_delay_sweep", "low_friction_road", scenarioName, ...
        "maximum_delay_" + 2*meanDelay_ms + "_ms", ...
        "trial_001_seed_1000.mat");

    assert(isfile(constantFile), "Missing file: %s", constantFile);
    assert(isfile(randomFile), "Missing file: %s", randomFile);

    constantData = load(constantFile, "results");
    randomData = load(randomFile, "results");
    constantIndex = 2*index - 1;
    randomIndex = 2*index;

    lateralSamples{constantIndex} = abs(constantData.results.ey_m(:));
    lateralSamples{randomIndex} = abs(randomData.results.ey_m(:));
    headingSamples{constantIndex} = ...
        abs(rad2deg(constantData.results.epsi_rad(:)));
    headingSamples{randomIndex} = ...
        abs(rad2deg(randomData.results.epsi_rad(:)));
end

figureHandle = figure( ...
    Name="Constant versus random knee-delay comparison", ...
    Color="white");
layout = tiledlayout(figureHandle, 2, 1, ...
    TileSpacing="compact", Padding="compact");

lateralStatistics = sdv.plot.delayMetricBoxPlot( ...
    nexttile(layout), lateralSamples, delayValues_ms, groupNames, ...
    Title="Absolute lateral-error distribution", ...
    YLabel="|e_y| (m)", ...
    Colors=[0.15, 0.45, 0.80; 0.85, 0.35, 0.20]);

headingStatistics = sdv.plot.delayMetricBoxPlot( ...
    nexttile(layout), headingSamples, delayValues_ms, groupNames, ...
    Title="Absolute heading-error distribution", ...
    YLabel="|e_\psi| (deg)", ...
    Colors=[0.15, 0.45, 0.80; 0.85, 0.35, 0.20]);

title(layout, ...
    "Constant delay versus U(0, 2\tau) random delay: trial 1, seed 1000");

disp(lateralStatistics);
disp(headingStatistics);
