%% Plot trial 1, seed 1000 across available random-delay levels

startup_project;

scenarioName = "aggressive_maneuver";
environmentName = "low_friction_road";
requestedDelay_ms = 0:10:270;
trialFileName = "trial_001_seed_1000.mat";

projectRoot = string(matlab.project.currentProject().RootFolder);
configuration = build_phase0_configuration(scenarioName);
controllerName = sdv.config.controllerName(configuration.controller);

resultsRoot = fullfile( ...
    projectRoot, "phase1", "results", controllerName, ...
    "random_delay_sweep", environmentName, scenarioName);

timeSeries_s = cell(0,1);
lateralErrorSeries_m = cell(0,1);
headingErrorSeries_deg = cell(0,1);
legendLabels = strings(0,1);
availableDelay_ms = zeros(0,1);
sourceFiles = strings(0,1);

for maximumDelay_ms = requestedDelay_ms
    delayText = replace(string(sprintf("%g", maximumDelay_ms)), ".", "p");
    sourceFile = fullfile( ...
        resultsRoot, ...
        "maximum_delay_" + delayText + "_ms", ...
        trialFileName);

    if ~isfile(sourceFile)
        continue;
    end

    savedData = load(sourceFile, "results");
    assert(isfield(savedData, "results"), ...
        "File does not contain results: %s", sourceFile);

    results = savedData.results;
    requiredFields = ["time_s", "ey_m", "epsi_rad"];
    missingFields = setdiff(requiredFields, string(fieldnames(results)));
    assert(isempty(missingFields), ...
        "Result file %s is missing: %s", ...
        sourceFile, strjoin(missingFields, ", "));

    timeSeries_s{end+1,1} = results.time_s(:); %#ok<SAGROW>
    lateralErrorSeries_m{end+1,1} = results.ey_m(:); %#ok<SAGROW>
    headingErrorSeries_deg{end+1,1} = ...
        rad2deg(results.epsi_rad(:)); %#ok<SAGROW>
    legendLabels(end+1,1) = ...
        string(sprintf("%g ms", maximumDelay_ms/2)); %#ok<SAGROW>
    availableDelay_ms(end+1,1) = maximumDelay_ms; %#ok<SAGROW>
    sourceFiles(end+1,1) = sourceFile; %#ok<SAGROW>
end

assert(~isempty(timeSeries_s), ...
    "No trial 1, seed 1000 results were found from 0 to 270 ms.");

controller = configuration.controller;
lateralLimits_m = [controller.minimumState(4), controller.maximumState(4)];
headingLimits_deg = rad2deg([ ...
    controller.minimumState(5), controller.maximumState(5)]);

figureHandle = sdv.plot.trackingErrorOverlay( ...
    timeSeries_s, ...
    lateralErrorSeries_m, ...
    headingErrorSeries_deg, ...
    legendLabels, ...
    FigureTitle="Random-delay tracking errors: aggressive maneuver / low friction road", ...
    HeadingUnit="deg", ...
    LateralLimits_m=lateralLimits_m, ...
    HeadingLimits=headingLimits_deg, ...
    HighlightViolations=true, ...
    Visible="on");

sourceTable = table( ...
    availableDelay_ms, sourceFiles, ...
    VariableNames=["maximum_delay_ms", "results_file"]);

figureFolder = fullfile( ...
    projectRoot, "phase1", "figures", controllerName, ...
    "random_delay_sweep");

sdv.io.exportFigure( ...
    figureHandle, figureFolder, ...
    "aggressive_maneuver_low_friction_trial_001_tracking_errors");
