[figureHandle, jitterData, sourceTable] = ...
    run_plot_sampling_jitter_seed_comparison( ...
    8, ...          % Jitter bound, ms [7, 8]
    11, ...         % Failing seed [11]
    [0, 0.05]);      % Time window, s [10, 11]