[caseSummary, statistics, figureHandle] = ...
    run_sampling_jitter_monte_carlo( ...
    "highway_cruise", ...
    "dry_road", ...
    8, ... % jitterBound_ms = 7 & 8
    RandomSeeds=11, ... %% 11
    UpdateSummary=false, ...
    SaveRunResults=true, ...
    SaveRunFigures=false, ...
    ShowRunFigures=true, ...
    ShowSweepFigure=false);