%% after reproducing the same results, it successfully able to converge and find the 
%solution
[caseSummary, statistics] = ...
    run_sampling_jitter_monte_carlo( ...
        "aggressive_maneuver", ...
        "dry_road", ...
        2, ... % jitterBound_ms
        RandomSeeds=2, ...
        UpdateSummary=false, ...
        SaveRunResults=false);
