%% it will plot all the aggresive maneuver tracking error sweep from where
% tracking starts to degrade
% since from analysis we found that aggressive-maneuver with low-friction
% road is what going to get affected
% [210, 220, 230, 240, 250, 250, 260, 270]/2 = mean delay

%% RUN IF YOU WANT TO GENERATE DATA ONLY, FOR PLOT FROM THE DATA
% RUN run_plot_rand_delay_agg_track_err_sweep.m
[summaryTable, sweepFigure] = run_random_delay_sweep( ...
    ScenarioNames= "aggressive_maneuver", ...
    EnvironmentNames="low_friction_road", ...
    MaximumDelay_ms=[220, 230, 240, 250, 250, 260], ...
    TrialsPerLevel=1, ...
    BaseSeed=1000, ...
    UpdateSummary=false, ...
    SaveTrialResults=true, ...
    ShowFigure=true);