function render_file( ...
    in_file, out_file, json_fullfile, template_glob)
%RENDER_FILE Windows-compatible renderer for acados v0.5.4.

t_renderer_location = get_tera();

acados_root_dir = getenv('ACADOS_INSTALL_DIR');

if nargin < 4

    acados_template_folder = fullfile( ...
        acados_root_dir, ...
        'interfaces', ...
        'acados_template', ...
        'acados_template', ...
        'c_templates_tera');

    [template_path, template_name, template_extension] = ...
        fileparts(in_file);

    template_glob = fullfile( ...
        acados_template_folder, ...
        template_path, ...
        '**', ...
        '*');

    in_file = [template_name, template_extension];
end

% Required compatibility correction for t_renderer on Windows.
if ispc
    template_glob = strrep(template_glob, '\', '/');
end

command = sprintf( ...
    '"%s" "%s" "%s" "%s" "%s"', ...
    t_renderer_location, ...
    template_glob, ...
    in_file, ...
    json_fullfile, ...
    out_file);

[status, result] = system(command);

if status ~= 0
    error( ...
        'SDV:AcadosTemplateRenderingFailed', ...
        ['Rendering %s failed.\n' ...
        'Command:\n%s\n' ...
        'Renderer output:\n%s'], ...
        in_file, ...
        command, ...
        result);
end

if contains(result, 'Error')
    error( ...
        'SDV:AcadosTemplateRenderingFailed', ...
        ['Rendering %s reported an error.\n' ...
        'Renderer output:\n%s'], ...
        in_file, ...
        result);
end

end